Partial_14Dec2021/force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Feedback__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Feedback__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ringing - No Response</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Feedback Given</fullName>
                <default>true</default>
                <label>Feedback Given</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/TestTaskCreatelogacall.cls
@isTest
Public class TestTaskCreatelogacall
{
Static testMethod void testlogaCall()
      {
      Test.StartTest();
      Account a6=new Account();
      a6.Name='Task Account';
      a6.Contact_Number_Mobile__c='9898969694';
      insert a6;
      
      Feedback__c  f0=new Feedback__c ();
      f0.Name='Feedback Test task';
      f0.Account__c=a6.Id;
      f0.Date__c=System.Today();
      f0.Status__c='Wrong Number';
      insert f0;
      
      Task tk=new Task();
      //tk.OwnerId=f0.CreatedById;
      tk.WhatId =f0.Account__c;
      tk.ActivityDate=f0.Date__c;
      tk.Subject= 'Feedback Status - Wrong Number';
      insert tk;
      
      Test.StopTest();
      }
}