Partial_14Dec2021/force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Feedback__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Feedback__c/fields/Call_Center_Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Call_Center_Person_Name__c</fullName>
    <label>Call Center Person Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Call Center Executive 1</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 2</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 3</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 4</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 5</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 6</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 7</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 8</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 9</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 10</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 11</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 12</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 13</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 14</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 15</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 16</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 17</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 18</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 19</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 20</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 21</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Feedback__c/fields/Feedback_Master__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feedback Master</label>
    <referenceTo>Feedback_Master__c</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Feedback__c/fields/Overall_Satisfaction__c.field-meta.xml
<CustomField>
    <fullName>Overall_Satisfaction__c</fullName>
    <label>Overall Satisfaction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Excellent</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Fair</fullName>
            </value>
            <value>
                <fullName>Poor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Feedback__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ringing - No Response</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Feedback Given</fullName>
                <default>true</default>
                <label>Feedback Given</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Feedback__c/fields/Status_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Status_Remarks__c</fullName>
    <label>Status Remarks</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Feedback_Line_Item__c/Feedback_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Feedback Line Item</label>
    <nameField>
        <displayFormat>FL-{0000}</displayFormat>
        <label>Feedback Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Feedback_Line_Item__c/fields/Feedback__c.field-meta.xml
<CustomField>
    <fullName>Feedback__c</fullName>
    <label>Feedback</label>
    <referenceTo>Feedback__c</referenceTo>
    <relationshipLabel>Feedback Line Items</relationshipLabel>
    <relationshipName>Feedback_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Feedback_Master__c/Feedback_Master__c.object-meta.xml
<CustomObject>
    <label>Feedback Master</label>
    <nameField>
        <label>Feedback Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedback Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Feedback_Master__c/fields/Applicable_State__c.field-meta.xml
<CustomField>
    <fullName>Applicable_State__c</fullName>
    <label>Applicable State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Pondicherry</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Feedback_Master_Line_Item__c/Feedback_Master_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Feedback Master Line Item</label>
    <nameField>
        <displayFormat>FM-{0000}</displayFormat>
        <label>Feedback Master Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback Master Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Feedback_Master_Line_Item__c/fields/Feedback_Master__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Master__c</fullName>
    <label>Feedback Master</label>
    <referenceTo>Feedback_Master__c</referenceTo>
    <relationshipLabel>Feedback Master Line Items</relationshipLabel>
    <relationshipName>Feedback_Master_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/feedback.cls
public class feedback
{
public List<Feedback_Master__c> fb{get;set;}
public List<Feedback_Master__c> AllcheckedFm{get;set;}
public Boolean showexisting{get;set;}
public Boolean showFM{get;set;}
Public Feedback__c f{get;set;}
Public Feedback__c fo{get;set;}
Public Feedback__c fcc{get;set;}
Public List<Feedback__c> CreateFBS{get;set;}
Public Id aId;
Public Account a{get;set;}

public List<Feedback_Line_Item__c> li{get;set;}
       public feedback(ApexPages.StandardController controller) 
       {
       try
       {
       CreateFBS=new List<Feedback__c>();
                 aId=ApexPages.CurrentPage().getParameters().get('id');
                  a=[Select id,Name,State__c FROM Account WHERE id=:aid LIMIT 1];
                   AllcheckedFm= new List<Feedback_Master__c>();
                   
                   fb=[SELECT id,Name,Active__c,Checkbox__c,Applicable_State__c FROM Feedback_Master__c WHERE  Applicable_State__c includes (:a.State__c)
                    AND Active__c=True order by CreatedDate desc];
                   fo=new Feedback__c();   
                 f=new Feedback__c();    
                 showFM = False;
       }
       
       catch(Exception e)
       {
       }
       }
       
       public pageReference Add()
       {
       try
       {
       if(f.status__c!='Feedback Given')
       {
       f.Account__c=aId;
       insert f;
       }
       }
       catch(Exception e)
              {
       }
       pageReference p5=new pageReference('/'+aid);
       p5.setRedirect(true);
       return p5;
       
      
       }
       
     public Void Next()
    {
    try
        {
        List<Feedback_Master__c> dummy=new List<Feedback_Master__c >();
       
        if(f.Status__c=='Feedback Given')
        {
        for(Feedback_Master__c e:fb)
        {
            if(e.Checkbox__c==true)
         {
         dummy.add(e);
         }
        }
            if(dummy.size()==1)
         {
            for(Feedback_Master__c fb1:dummy)
            {
     
             showFM = True;
        
            System.Debug('------->>>FM Name'+fb1.Name);
            
                Feedback__c newFB = new Feedback__c(Account__c=aid);
                  newFB.Name=fb1.Name;
                  newFB.Feedback_Master__c=fb1.id;
                  newFB.Status__c=f.Status__c;
                  newFB.Call_Center_Person_Name__c=f.Call_Center_Person_Name__c;
                  newFB.Status_Remarks__c=f.Status_Remarks__c;
                  newFB.Date__c=f.Date__c;
                  
                CreateFBS.add(newFB);
                Feedback_Master__c checkedFm = [SELECT id,Name,Active__c,Applicable_State__c,Remarks__c,Checkbox__c,(SELECT id,Name,Display_Order__c,Question__c,Answer__c,Feedback_Master__c FROM Feedback_Master_Line_Items__r ORDER By Display_Order__c ASC) FROM Feedback_Master__c WHERE id =:fb1.id];
                
               System.Debug('@@@@@------->>>LinItemsSize'+checkedFm.Feedback_Master_Line_Items__r.Size());
                AllcheckedFm.add(checkedFm);
                
                
                System.Debug('------->>>Size'+AllcheckedFm.Size());
            }
            insert CreateFBS;
            
        }
        else
        {
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Select Any 1 Questionnaire'));
        
        }
           
        }
        if(f.Status__c!='Feedback Given')
        {
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Other Than "Feedback Given" Feedback Line Items shouldnot be created so  click on ADD button  to create Feedbacks Only'));
        
        }
        
        }
        
        catch(exception e)
        {
            ApexPages.addMessages(e);
        }
    
    }
     public PageReference Saveall()
    {
    try
        {
        Set<Id> FB_Ids = new Set<Id>();
        Map<Id,Feedback__c> MapFBs = new Map<Id,Feedback__c>();
        for(Feedback__c each:CreateFBS)
        {
            FB_Ids.add(each.id);
            each.Overall_Satisfaction__c=fo.Overall_Satisfaction__c;
            update each;
        }
        List<Feedback__c> AllFBs=[SELECT id,Name,Feedback_Master__c FROM Feedback__c WHERE id IN: FB_Ids];
       
        if(!AllFBs.isEmpty())
        {
        
            for(Feedback__c each1:CreateFBS)
            {
            
                MapFBs.put(each1.Feedback_Master__c,each1);
            }
        }
        List<Feedback_Line_Item__c> fmli =new List<Feedback_Line_Item__c>();
        
        for(Feedback_Master__c m:AllcheckedFm)
        {
         for(Feedback_Master_Line_Item__c e:m.Feedback_Master_Line_Items__r)
        {
            if(MapFBs.get(e.Feedback_Master__c)!=Null)
            {
                Feedback_Line_Item__c fd=new Feedback_Line_Item__c();
                fd.Feedback__c=MapFBs.get(e.Feedback_Master__c).Id;
                fd.Question__c=e.Question__c;
                fd.Answer__c=e.Answer__c;
                fd.Display_Order__c=e.Display_Order__c;
                fmli.add(fd);
                System.Debug('#######Size'+fmli);
            }
            
        }
        System.Debug('123#######Size'+fmli.Size());
        
        }
insert fmli;
pageReference p1=new PageReference('/'+aid);
    p1.SetRedirect(true);
    return p1;      
        }
        catch(exception e)
        {
            ApexPages.addMessages(e);
        }
        return null;
    }
    public pageReference Cancel()
    {
    pageReference p2=new PageReference('/'+aid);
    p2.setRedirect(true);
    return p2;
    }
   }