Partial_14Dec2021/force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Feedback__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Feedback__c/fields/Feedback_Master__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feedback Master</label>
    <referenceTo>Feedback_Master__c</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Feedback__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ringing - No Response</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Feedback Given</fullName>
                <default>true</default>
                <label>Feedback Given</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Feedback_Line_Item__c/Feedback_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Feedback Line Item</label>
    <nameField>
        <displayFormat>FL-{0000}</displayFormat>
        <label>Feedback Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Feedback_Line_Item__c/fields/Feedback__c.field-meta.xml
<CustomField>
    <fullName>Feedback__c</fullName>
    <label>Feedback</label>
    <referenceTo>Feedback__c</referenceTo>
    <relationshipLabel>Feedback Line Items</relationshipLabel>
    <relationshipName>Feedback_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Feedback_Master__c/Feedback_Master__c.object-meta.xml
<CustomObject>
    <label>Feedback Master</label>
    <nameField>
        <label>Feedback Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedback Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Feedback_Master__c/fields/Applicable_State__c.field-meta.xml
<CustomField>
    <fullName>Applicable_State__c</fullName>
    <label>Applicable State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Pondicherry</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Feedback_Master_Line_Item__c/Feedback_Master_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Feedback Master Line Item</label>
    <nameField>
        <displayFormat>FM-{0000}</displayFormat>
        <label>Feedback Master Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback Master Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Feedback_Master_Line_Item__c/fields/Feedback_Master__c.field-meta.xml
<CustomField>
    <fullName>Feedback_Master__c</fullName>
    <label>Feedback Master</label>
    <referenceTo>Feedback_Master__c</referenceTo>
    <relationshipLabel>Feedback Master Line Items</relationshipLabel>
    <relationshipName>Feedback_Master_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/Testfeedback.cls
@isTest
Public Class Testfeedback
{
Static testMethod void testfeedback()
      {
     
      Account a5=new Account();
      a5.Name='Test Feedback Class';
      a5.State__c='Tamil Nadu';
      a5.Mobile_No_Status__c='Invalid';
      a5.Contact_Number_Mobile__c='9874563218';
      insert a5;
     
      Feedback_Master__c fm1=new Feedback_Master__c();
      fm1.Name='Feedback Master Test 1';
      fm1.Active__c=true;
      fm1.Applicable_State__c='Tamil Nadu';
      fm1.Checkbox__c = True;
      insert fm1; 
      
     
      Feedback_Master_Line_Item__c fmli1=new Feedback_Master_Line_Item__c();
      fmli1.Feedback_Master__c=fm1.Id;
      fmli1.Display_Order__c=1;
      fmli1.Answer__c='test Answer';
      fmli1.Question__c='How is Post sales support?';
      insert fmli1;
      
      
      
      Feedback__c f10=new Feedback__c();
      f10.Name='Feedback Class';
      f10.Account__c=a5.Id;
      f10.Status__c='Feedback Given';
      f10.Date__c=System.Today();
      f10.Feedback_Master__c = fm1.id;
      insert f10;
      
    
      
      Feedback_Line_Item__c fli1=new Feedback_Line_Item__c();
      fli1.Feedback__c=f10.Id;
      fli1.Display_Order__c=fmli1.Display_Order__c;
      fli1.Answer__c=fmli1.Answer__c;
      fli1.Question__c=fmli1.Question__c;
      insert fli1;
       
        
         PageReference pageRef = Page.Feedback;
         Test.setCurrentPage(pageRef);
         pageRef.setredirect(true);
         pageRef.getParameters().put('id',a5.Id);
    
        
        feedback fdb = new feedback(new ApexPages.StandardController(a5));
       
        fdb.f.Status__c='Feedback Given';
        fdb.Next();
        fdb.f.Status__c='';
        fdb.Next();
        fdb.Add();
        fdb.Saveall();
        fdb.Cancel();
   
        
      }
      }