Partial_14Dec2021/force-app/main/default/objects/Projects__c/Projects__c.object-meta.xml
<CustomObject>
    <label>Projects(O)</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects(O)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Supply_Detail__c/Supply_Detail__c.object-meta.xml
<CustomObject>
    <label>Order and Supply Details</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order and Supply Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Supply_Detail__c/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <label>Projects</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Supply_Details1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Supply_Detail__c/fields/Supply_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Supply_Quantity__c</fullName>
    <label>Supply Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/Addsupplydetail.cls
public class Addsupplydetail
{
    public boolean message{get;set;}
    public string pageid{get;set;}
    public account acc{get;set;}
    public Supply_Detail__c supplyid{get;set;}
    public Addsupplydetail(ApexPages.StandardController controller) {
    try{
        pageid= apexpages.currentpage().getparameters().get('id');
        acc= [select id,name,Total_Order_Quantity__c,Total_Supply_Value__c,(select id,Projects__c from Supply_Details1__r order by name asc Limit 1 ) from account where id=:pageid];
        supplyList = new list<Supply_Detail__c>();
        supplyid = acc.Supply_Details1__r[0];
        message=false;
        }
        catch(exception e)
        {
        }
    }
    
    
    public PageReference savesupplydetail() {
        list<Supply_Detail__c > slist = new   list<Supply_Detail__c >();
        Double supplyqty=0;
        try
        {
            for(Supply_Detail__c s:supplyList)
            {
                supplyqty+=s.Supply_Quantity__c;  
                slist.add(s);    
            }
            if( supplyqty > acc.Total_Order_Quantity__c-acc.Total_Supply_Value__c)
            {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Supply Quantity should not be greater than order quantity'));
                return null;
            }
            else if(supplyqty < acc.Total_Order_Quantity__c-acc.Total_Supply_Value__c || supplyqty == acc.Total_Order_Quantity__c-acc.Total_Supply_Value__c)
            {
                insert slist;
                pagereference pg = new pagereference('/'+pageid);
                return pg;
            }
            
            pagereference pg = new pagereference('/'+pageid);
            return pg;
        }
        
        Catch(Exception e)
        {
            return null;
        } 
    } 
    public PageReference cancelsupplydetail() {
        
        pagereference pf = new pagereference('/'+pageid);
        return pf;
    }
    
    public  List<Supply_Detail__c> supplyList {get;set;}
    public List<Supply_Detail__c> supplyAddList {get;set;}
    //public String ordervalue {get;set;}   
    
    public Addsupplydetail()
    {
        
        
    }
    public void AddRow()
    {
        try
        {
            supplyList.add(new Supply_Detail__c(projects__C=pageid));
        }
        Catch(Exception e)
        {
            System.Debug(e);
        }   
    }  
}