Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/Tour_Plan1__c.object-meta.xml
<CustomObject>
    <label>Tour Plans</label>
    <nameField>
        <label>Tour Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Tour_Program__c.field-meta.xml
<CustomField>
    <fullName>Tour_Program__c</fullName>
    <label>Tour Program</label>
    <referenceTo>Tour_Program__c</referenceTo>
    <relationshipLabel>Tour Plans</relationshipLabel>
    <relationshipName>Tour_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/Tour_Program__c.object-meta.xml
<CustomObject>
    <label>Tour Program</label>
    <nameField>
        <label>Tour Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/TestUpdateIncomeClass.cls
@isTest


    Public Class TestUpdateIncomeClass
    {
    
    Static TestMethod Void UpdateIncomeClass()
    {
     Test.StartTest();
    
       Tour_Program__c tr=new Tour_Program__c();
            tr.From_Date__c=date.newinstance(2014, 3, 1);
             tr.To_Date__c=date.newinstance(2014, 3, 15);
       insert tr;
       
       List<Tour_Plan1__c > TourPlan=new List<Tour_Plan1__c >();
       
       Tour_Plan1__c tp=new Tour_Plan1__c();
       tp.Name='Tour Palan';
       tp.Tour_Program__c=tr.id;
       
       insert tp;
       update tp;
       
       TourPlan.add(tp);
       update TourPlan;
       
       Test.StopTest();
       
       
        PageReference pageRef = Page.TLTourPlan;
          Test.setCurrentPage(pageRef);
          pageRef.setredirect(true);
          pageRef.getParameters().put('id',tr.id);
          
        UpdateIncomeClass npm = new UpdateIncomeClass (new ApexPages.StandardController(tr)); 
        npm.Autorun();
        npm.getplans1();
        npm.GetID();
        npm.UpdateRecords();        
       }
    }