Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/Tour_Plan1__c.object-meta.xml
<CustomObject>
    <label>Tour Plans</label>
    <nameField>
        <label>Tour Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Tour_Program__c.field-meta.xml
<CustomField>
    <fullName>Tour_Program__c</fullName>
    <label>Tour Program</label>
    <referenceTo>Tour_Program__c</referenceTo>
    <relationshipLabel>Tour Plans</relationshipLabel>
    <relationshipName>Tour_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/Tour_Program__c.object-meta.xml
<CustomObject>
    <label>Tour Program</label>
    <nameField>
        <label>Tour Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/TestDisplayTourPlansClass.cls
@isTest
Public Class TestDisplayTourPlansClass 
{
    Static TestMethod Void DisplayTourPlansClass()
    {
        Test.StartTest();
            
            Tour_Program__c tpg=new Tour_Program__c();
              tpg.From_Date__c=date.newinstance(2010,1,1);  
              tpg.To_Date__c=date.newinstance(2010,1,15);
            insert tpg;
            
            Tour_Plan1__c tp=new Tour_Plan1__c();
              tp.Name='sssss';
              tp.Tour_Program__c=tpg.id;
            insert tp;
            
            PageReference pageRef = Page.DisplayTourPlans;
              Test.setCurrentPage(pageRef);
              pageRef.setredirect(true);
              pageRef .getParameters().put('id',tpg.id);
              
            DisplayTourPlansClass t= new DisplayTourPlansClass(new ApexPages.StandardController(tpg));   
        Test.StopTest();
    } 
}