Partial_14Dec2021/force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Claim__c/fields/Plumber_Scheme__c.field-meta.xml
<CustomField>
    <fullName>Plumber_Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plumber Scheme</label>
    <referenceTo>Plumber_Scheme_Relation__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Plumber_Scheme_Relation__c/Plumber_Scheme_Relation__c.object-meta.xml
<CustomObject>
    <label>Plumber Scheme</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Plumber Scheme Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plumber Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Plumber_Scheme_Relation__c/fields/Plumber__c.field-meta.xml
<CustomField>
    <fullName>Plumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plumber</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plumber Schemes</relationshipLabel>
    <relationshipName>Schemes</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/CheckClaim.cls
/* 
* Name      : CheckClaim
* Purpose   : This class is used as an utility to check Claim is valid.
* Company   : DGenX Technologies
* Author    : Dushyant
*/
public class CheckClaim {
    public class PlumberInput {
        @InvocableVariable
        public String plumberId;
        @InvocableVariable
        public String claimId;
    }
    public class PlumberOutput {
        @InvocableVariable
        public String status;
    }
    @InvocableMethod(label='Check Claim Status')
    public static List<PlumberOutput> getClaimStatus(List<PlumberInput> plumberInputs){
        List<PlumberOutput> plumberOutputList = new List<PlumberOutput>();
        List<Claim__c> claimList = new List<Claim__c>();
        PlumberOutput pOutput = new PlumberOutput();
        claimList = [SELECT Id FROM Claim__c WHERE Plumber_Scheme__r.Plumber__c =:plumberInputs[0].plumberId AND Name =:plumberInputs[0].claimId];
        if(claimList.size() >0)
            pOutput.status = 'Valid';
        else
            pOutput.status = 'InValid';
        
        plumberOutputList.add(pOutput);
        RETURN plumberOutputList;
    }
}