Partial_14Dec2021/force-app/main/default/objects/Claim__c/Claim__c.object-meta.xml
<CustomObject>
    <label>Claim</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Claim Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Claim__c/fields/Plumber_Scheme__c.field-meta.xml
<CustomField>
    <fullName>Plumber_Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plumber Scheme</label>
    <referenceTo>Plumber_Scheme_Relation__c</referenceTo>
    <relationshipLabel>Claims</relationshipLabel>
    <relationshipName>Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Claim__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Plumber_Scheme_Relation__c/Plumber_Scheme_Relation__c.object-meta.xml
<CustomObject>
    <label>Plumber Scheme</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Plumber Scheme Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plumber Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Plumber_Scheme_Relation__c/fields/Plumber__c.field-meta.xml
<CustomField>
    <fullName>Plumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plumber</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plumber Schemes</relationshipLabel>
    <relationshipName>Schemes</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Plumber_Scheme_Relation__c/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheme</label>
    <referenceTo>Sales_scheme__c</referenceTo>
    <relationshipLabel>Registered Plumbers</relationshipLabel>
    <relationshipName>Registered_Plumber</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Sales_scheme__c/Sales_scheme__c.object-meta.xml
<CustomObject>
    <label>Sales scheme</label>
    <nameField>
        <label>Scheme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/FetchSchemeDetails.cls
/* 
* Name      : FetchSchemeDetails
* Purpose   : This class is used as an utility to fetch all claims done by any plumber.
* Company   : DGenX Technologies
* Author    : Dushyant
*/
public class FetchSchemeDetails {
    public class PlumberInput {
        @InvocableVariable
        public String plumberId;
        @InvocableVariable
        public String schemeId;
    }
    public class PlumberOutput {
        @InvocableVariable
        public String claimDetails;
        @InvocableVariable
        public String schemeId;
    }
    @InvocableMethod(label='Fetch Claim Details')
    public static List<PlumberOutput> getClaimDetails(List<PlumberInput> plumberInputs){
        List<PlumberOutput> plumberOutputList = new List<PlumberOutput>();
        List<Claim__c> claimList = new List<Claim__c>();
        PlumberOutput pOutput = new PlumberOutput();
        Integer counter = 1;
        pOutput.claimDetails = '';
        claimList = [SELECT Id,Name,Status__c,Capacity__c FROM Claim__c WHERE Plumber_Scheme__r.Plumber__c =:plumberInputs[0].plumberId AND Plumber_Scheme__r.Scheme__r.Is_active__c = true];
        for(Claim__c cliamObj : claimList){
            pOutput.claimDetails += counter+'. Claim Id: '+cliamObj.Name+', Capacity: '+cliamObj.Capacity__c+', Status: '+cliamObj.Status__c+'\n';
            counter++;
        }
        if(pOutput.claimDetails == '')
            pOutput.claimDetails = 'No Claim Details Found!';
        pOutput.schemeId = plumberInputs[0].schemeId;
        
        plumberOutputList.add(pOutput);
        RETURN plumberOutputList;
    }
}