Partial_14Dec2021/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Raised</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Service_Charge__c/Service_Charge__c.object-meta.xml
<CustomObject>
    <label>Service Charge</label>
    <nameField>
        <displayFormat>SERCH-{000000}</displayFormat>
        <label>Service  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Service_Charge__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Service Charges</relationshipLabel>
    <relationshipName>Service_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Service_Charge__c/fields/Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Location_Name__c</fullName>
    <label>Location Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Service_Charge__c/fields/Plumber__c.field-meta.xml
<CustomField>
    <fullName>Plumber__c</fullName>
    <label>Plumber</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Service_Charge__c/fields/Service_Charge_Amount__c.field-meta.xml
<CustomField>
    <fullName>Service_Charge_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Service Charge Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Service_Charge__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Created&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Raised</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Service_Charge__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Service Charges</relationshipLabel>
    <relationshipName>Service_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/LCC_CreateInvoice.cls
public without sharing class LCC_CreateInvoice {
    public class ServiceChargeWrapper{
        @AuraEnabled
        public Service_Charge__c sc;
        @AuraEnabled
        public Boolean check;
    }
    public class Datawarp{
        @auraEnabled
        public List<Service_Charge__c> sclist;
        @auraEnabled
        public String total;
        @auraEnabled
        public String totalserviceCharges;
         @auraEnabled
        public String FixedCharges;
        @auraEnabled
        public id accountid;
    }
    @auraEnabled
    public static Datawarp getsreciveCharges(string scids){
        System.debug('Id is'+scids);
        Type idArrType = Type.forName('List<string>');
    	List<string> wrapperList = (List<string>) JSON.deserialize(scids, idArrType);
        //List<id> listids=new List<id>();
        Datawarp da=new Datawarp();
        Map<id,user> usermap=new Map<id,user>();
        //listids=scids.split(',');
        //Set<id> idset=new Set<id>();
        //idset.addAll(listids);
        List<Service_Charge__c> shlist=new List<Service_Charge__c>();
        shlist=[Select id,Name,Status__c,Service_Charge_Amount__c,work_order__r.ownerid from Service_Charge__c where id=:wrapperList  ];
        if(!shlist.isEmpty()){     
           usermap=new Map<id,user>([Select id,contactid,contact.accountId,contact.account.Service_Fixed_Payment__c from user where id =:shlist[0].work_order__r.ownerid]);
        }
        System.debug('usermap is'+usermap);
        Decimal total=0;
        if(!shlist.isEmpty()){
            for(Service_Charge__c sc:shlist){
                total +=sc.Service_Charge_Amount__c; 
            }
        }
        da.totalserviceCharges=String.valueOf(total);
        if(!usermap.isEmpty()){
            if( usermap.values()[0].contact.account.Service_Fixed_Payment__c!=null)
            total =total + usermap.values()[0].contact.account.Service_Fixed_Payment__c;
            da.FixedCharges=String.valueOf(usermap.values()[0].contact.account.Service_Fixed_Payment__c);
            da.accountid=usermap.values()[0].contact.accountId;
        }
        
         
        da.total=String.valueOf(total);
        da.sclist=shlist;
        System.debug('shlist*******'+shlist);
        return da;
    }
     @auraEnabled
    public static String updatesreciveCharges(string invid,List<Service_Charge__c> sclist){
          if(!sclist.isEmpty()){
            for(Service_Charge__c sc:sclist){
                sc.put('Invoice__c',invid); 
                sc.put('status__c','Raised');
            }
            update sclist;
        }
        System.debug('invalid is'+invid);
        return invid;
    }
    
    @AuraEnabled
    public static List<ServiceChargeWrapper> getServiceCharges(){
        List<ServiceChargeWrapper> scwlist = new List<ServiceChargeWrapper>();
        Id currentUserId = UserInfo.getUserId();
        //added by Haritha
        
          Integer month = Date.Today().Month();
          Integer year = Date.Today().Year();
          system.debug('****month-->'+month);
          system.debug('****year-->'+year);
          Datetime currentMonthDate = Datetime.newInstanceGmt(year, month, 7);
          system.debug('****currentMonthDate-->'+currentMonthDate);
          if(month == 1){
             month = 12;
             year -= 1;
            }
       else{
           month -= 1;
            }
         
        Datetime PreviousMonthDate = Datetime.newInstanceGmt(year, month , 8);
        
        system.debug('****nextMonthDate-->'+PreviousMonthDate);       
        
        //Code end
        for(Service_Charge__c src : [Select Id,Name, Customer_Name__c ,Location_Name__c, Plumber__c , Service_Charge_Amount__c  from Service_Charge__c where Invoice__c = null and OwnerId =: currentUserId ]){
            ServiceChargeWrapper scw = new ServiceChargeWrapper();
            scw.check = false;
            scw.sc = src;
            scwlist.add(scw);
        }
        return scwlist;
    }
}