Partial_14Dec2021/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Raised</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/InvoiceTriggerHandler.cls
public class InvoiceTriggerHandler {
    public static void beforeUpdate(Map<id,Invoice__c> newmap,Map<id,Invoice__c> oldmap){
        Map<id,Invoice__c> invMspUnderpro=new Map<id,Invoice__c>();
        for(Invoice__c inv:newMap.values()){
            if(inv.Status__c=='Raised' && oldMap.get(inv.id).Status__c!='Raised'){
             invMspUnderpro.put(inv.id,inv);   
            }
        }
        if(!invMspUnderpro.isEmpty()){
            System.debug('validation');
            InvoiceTriggerHelper.validateattachment(invMspUnderpro);
        }
    }
     public static void afterUpdate(Map<id,Invoice__c> newmap,Map<id,Invoice__c> oldmap){
        Map<id,Invoice__c> invMspUnderpro=new Map<id,Invoice__c>();
        for(Invoice__c inv:newMap.values()){
            if(inv.Status__c=='Raised' && oldMap.get(inv.id).Status__c!='Raised'){
             invMspUnderpro.put(inv.id,inv);   
            }
        }
        if(!invMspUnderpro.isEmpty()){
            System.debug('send email');
             InvoiceTriggerHelper.sendEmailToPaymnetteam(invMspUnderpro);
        }
    }
}