Partial_14Dec2021/force-app/main/default/objects/New_Order__c/New_Order__c.object-meta.xml
<CustomObject>
    <description>This is the custom Order Object that is used to store all the records that are generated after offer. This object is used after the revamp structure.</description>
    <label>New Order</label>
    <nameField>
        <displayFormat>Order-{0000}</displayFormat>
        <label>Unique Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/New_Order__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>New Orders</relationshipLabel>
    <relationshipName>New_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Supply__c/Supply__c.object-meta.xml
<CustomObject>
    <label>Supply</label>
    <nameField>
        <displayFormat>Supply-{00000000}</displayFormat>
        <label>Supply Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Supply__c/fields/New_Order__c.field-meta.xml
<CustomField>
    <fullName>New_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To be refered to after the project modifications/ revamp</description>
    <label>New Order</label>
    <referenceTo>New_Order__c</referenceTo>
    <relationshipLabel>Supplies</relationshipLabel>
    <relationshipName>Supplies</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Supply__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Supplies</relationshipLabel>
    <relationshipName>Supplies</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/SupplyLineItem__c.object-meta.xml
<CustomObject>
    <label>SupplyLineItem</label>
    <nameField>
        <displayFormat>SupplyItem-{0000000000}</displayFormat>
        <label>SupplyLineItem Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SupplyLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SupplyLineItems</relationshipLabel>
    <relationshipName>SupplyLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/ORC_Markup__c.field-meta.xml
<CustomField>
    <fullName>ORC_Markup__c</fullName>
    <label>ORC/Markup</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/ORC_Status__c.field-meta.xml
<CustomField>
    <fullName>ORC_Status__c</fullName>
    <label>ORC Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Order Received</fullName>
            </value>
            <value>
                <fullName>Part Received</fullName>
            </value>
            <value>
                <fullName>Order Lost</fullName>
            </value>
            <value>
                <fullName>Order Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Order_Value__c.field-meta.xml
<CustomField>
    <fullName>Order_Value__c</fullName>
    <label>Supply Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/OrderLineItem__c.field-meta.xml
<CustomField>
    <fullName>OrderLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>SupplyLineItems</relationshipLabel>
    <relationshipName>SupplyLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100% advance with PO</fullName>
            </value>
            <value>
                <fullName>20% advance &amp; Balance against Delivery</fullName>
            </value>
            <value>
                <fullName>30 days after delivery</fullName>
            </value>
            <value>
                <fullName>45 days after delivery</fullName>
            </value>
            <value>
                <fullName>60 days after delivery</fullName>
            </value>
            <value>
                <fullName>90 days after delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>SupplyLineItems</relationshipLabel>
    <relationshipName>SupplyLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Product_name__c.field-meta.xml
<CustomField>
    <fullName>Product_name__c</fullName>
    <description>name of the product. In use after project revamp structure</description>
    <label>Product name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>SupplyLineItems</relationshipLabel>
    <relationshipName>SupplyLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Supply_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Supply_End_Date__c</fullName>
    <label>Supply End Date</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Supply_Status__c.field-meta.xml
<CustomField>
    <fullName>Supply_Status__c</fullName>
    <label>Supply Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fully Received</fullName>
            </value>
            <value>
                <fullName>Part Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/SupplyDetails__c.field-meta.xml
<CustomField>
    <fullName>SupplyDetails__c</fullName>
    <label>Supply</label>
    <referenceTo>Supply__c</referenceTo>
    <relationshipLabel>SupplyLineItems</relationshipLabel>
    <relationshipName>SupplyLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Boxes</fullName>
            </value>
            <value>
                <fullName>Mtrs</fullName>
            </value>
            <value>
                <fullName>No.&apos;s</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/SupplyEditSectionController.cls
/*******************XXX**********************************

Created By      :Subhajit Ghosh
Created Date    :11-05-2019
Modified Date   :
Version         :1.0
Description     :Controller of SupplyEditSectionVF page, Edit the supply on click of edit button

test            :SupplyEditSectionTest
********************XXX***********************************/
public class SupplyEditSectionController {
    
     public String oppProId {get;set;}
    public String applType {get;set;}
   
   // public Opportunity oppTc {get; set;}
    public Opportunity opp;
   
   // public List<Order> parentOrderList;
    public List<SupplyLineItem__c> SupplyItemList;
    public List<Supply__c> parentSupplyRecord;
    public List<SupplyLineItem__c> supplyLineItemsList;
    public List<SupplyWrapperClass>SupplyItemWrapperList;
   // public Boolean saveOrder {get;set;}
    public Boolean saveSupply {get;set;}

    
    public String delID {get;set;}
 
    
     public SupplyEditSectionController(ApexPages.StandardController stdController) {
         SupplyItemWrapperList=new List<SupplyWrapperClass>();
         supplyLineItemsList=new List<SupplyLineItem__c>();
        SupplyItemList=new List<SupplyLineItem__c>();
         oppProId = Apexpages.currentPage().getParameters().get('id');   
        applType = Apexpages.currentPage().getParameters().get('applType'); 
         system.debug('oppProId--'+oppProId);
         system.debug('applType--'+applType);
     }
    
    public PageReference savePage() {   

        PageReference pf = new PageReference('/'+oppProId);
        try{
            
          if(applType == 'supplyType' && SupplyItemWrapperList.size() > 0) {
                List<SupplyLineItem__c> supplyLineItemList = new List<SupplyLineItem__c>();
                for(SupplyWrapperClass tempObject : SupplyItemWrapperList) {
                    SupplyLineItem__c supplyItemObject  = new SupplyLineItem__c();
                    supplyItemObject = tempObject.SupplyLineItemInstance;
                    supplyLineItemList.add(supplyItemObject);
                } 
               Update supplyLineItemList;
               return pf;
        }
        }
            catch(exception e){
                system.debug('eroror occured at line number----'+e.getLineNumber() );
                 return pf;
            }

        return pf;           
       
       
    }
    
      public list<SupplyWrapperClass> getSupplyListPro() {

        SupplyItemWrapperList = new List<SupplyWrapperClass>();
        supplyLineItemsList = new List<SupplyLineItem__c>([SELECT Id, Distributor_Name__c, Distributor_Name__r.name,OrderLineItem__c, Product_name__c, 
                                                           Product__r.Name, Quantity__c, Unit__c, Order_Value__c, Invoice_Date__c, Payment_Terms__c,
                                                           Supply_Status__c, ORC_Markup__c, ORC_Status__c,SupplyDetails__r.New_Order__r.Name 
                                                           from SupplyLineItem__c WHERE Project__c=:oppProId  ORDER BY SupplyDetails__r.New_Order__r.Name ASC]); //WHERE SupplyDetails__c = : parentSupplyRecord[0].Id
        
      system.debug('supplyLineItemsList--'+supplyLineItemsList);
          for (SupplyLineItem__c  tempSupplyItem : supplyLineItemsList) {

            SupplyWrapperClass supplyWrpObj = new SupplyWrapperClass();
            supplyWrpObj.SupplyLineItemInstance = tempSupplyItem;
            
            /*supplyWrpObj.SupplyLineItemInstance.Product__c = tempSupplyItem.Product__c;
            //supplyWrpObj.SupplyLineItemInstance.Quantity__c = tempSupplyItem.Quantity__c;
           // supplyWrpObj.SupplyLineItemInstance.Unit__c = tempSupplyItem.Unit__c;
            supplyWrpObj.SupplyLineItemInstance.Order_Value__c = tempSupplyItem.Order_Value__c;
            supplyWrpObj.SupplyLineItemInstance.Invoice_Date__c = tempSupplyItem.Invoice_Date__c;
            supplyWrpObj.SupplyLineItemInstance.Payment_Terms__c = tempSupplyItem.Payment_Terms__c;
            supplyWrpObj.SupplyLineItemInstance.Supply_Status__c = tempSupplyItem.Supply_Status__c;*/
            
            //supplyWrpObj.SupplyLineItemInstance.Supply_End_Date__c = tempOrderItem.EndDate;
            supplyWrpObj.productName = tempSupplyItem.Product_name__c;
            SupplyItemWrapperList.add(supplyWrpObj);
        }
        system.debug('supplyLineItemsList:: ' + supplyLineItemsList);
        return SupplyItemWrapperList;        
    }

    public class SupplyWrapperClass {    
        
        public SupplyLineItem__c SupplyLineItemInstance {get; set;} 
        public String productName {get; set;}
        
        public SupplyWrapperClass() {
            SupplyLineItemInstance = new SupplyLineItem__c();
            productName = '';
        }   
    }

   /* public void deleteRow() {

        String delId = Apexpages.currentPage().getParameters().get('delId');
        if(delId.length() != 0){

            OpportunityLineItem delOLI= [SELECT id from OpportunityLineItem where id=:delId];
            //system.debug('*******delId********'+delId);
            if(delOLI != null) {

               delete delOLI;
            }
            
        }
    }*/

    public void deleteData() {

        String emptyDataId = Apexpages.currentPage().getParameters().get('emptyDataId');
        //System.debug('@@@@@@@@@'+emptyDataId);
        //OpportunityLineItem delOLI;
        try{            
            
           if(applType == 'supplyType') {

                SupplyLineItem__c deleteRecord = new SupplyLineItem__c();
                deleteRecord.Id = emptyDataId;
                delete deleteRecord;
                /*delOLI.Supply_Quantity__c       = null;
                delOLI.Invoice_Value__c         = null;
                delOLI.Invoice_Date__c          = null;
                delOLI.Supply_Check__c          = false;*/
            
            }  
            
           /* else if if(applType == 'orderLost'){
                delOLI.Order_Loss_Check__c = false;
            }*/
           // update delOLI;
           
            
        }catch(Exception e) {
             system.debug('error at line number--'+e.getLineNumber() );
             system.debug('error at line number--'+e.getMessage() );
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, e.getMessage()));  
        }
     
    }

}