Partial_14Dec2021/force-app/main/default/objects/sales_accrual__c/sales_accrual__c.object-meta.xml
<CustomObject>
    <label>Sales Accrual</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Sales Accrual Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Accrual</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/sales_accrual__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.is_active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Accrual (Account)</relationshipLabel>
    <relationshipName>Sales_Accrual</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/sales_accrual__c/fields/Bill_amount__c.field-meta.xml
<CustomField>
    <fullName>Bill_amount__c</fullName>
    <label>Bill amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/sales_accrual__c/fields/Bill_Image__c.field-meta.xml
<CustomField>
    <fullName>Bill_Image__c</fullName>
    <label>Bill Image</label>
    <type>Url</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/sales_accrual__c/fields/Bonus_point__c.field-meta.xml
<CustomField>
    <fullName>Bonus_point__c</fullName>
    <formula>IF ( post_bonus_point__c &gt; 0, post_bonus_point__c,  pre_bonus_point__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bonus point</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/sales_accrual__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Accrual</relationshipLabel>
    <relationshipName>Sales_Accrual_dealer</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/sales_accrual__c/fields/Enterprise_points__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_points__c</fullName>
    <formula>IF(post_enterprise_point__c &gt; 0, post_enterprise_point__c, Pre_enterprise_point__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Enterprise points</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/sales_accrual__c/fields/scheme_point__c.field-meta.xml
<CustomField>
    <fullName>scheme_point__c</fullName>
    <label>Scheme point</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/sales_accrual__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Sales Accrual</relationshipLabel>
    <relationshipName>Sales_Accrual_Transaction</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TN-{000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/TransactionEscalation.cls
public class TransactionEscalation{
    public static void toSendEmail(String transId){
        if(transId != null && transId != ''){
            list<Messaging.SingleEmailMessage> mailList= new list<Messaging.SingleEmailMessage>();
            List<Transaction__c> transList = new List<Transaction__c>();
            List<User> ownerUserList = new List<User>();
            List<String> toAddressses = new List<String>();
            List<String> ccAddressses = new List<String>();            
            
            transList = [SELECT Id,Name,OwnerId,Owner.Name,Owner.Email,CreatedDate,(SELECT Id,Name,Bill_amount__c,Account__r.Name,Dealer__r.Name,Enterprise_points__c,Bonus_point__c,scheme_point__c,Bill_Image__c FROM Sales_Accrual_Transaction__r) FROM Transaction__c WHERE Id =:transId];
            ownerUserList = [SELECT Id,Name,Manager.Name,Manager.Email FROM User WHERE Id =:transList[0].OwnerId];
            toAddressses.add(ownerUserList[0].Manager.Email);
            ccAddressses.add(transList[0].Owner.Email);
            toAddressses.add('shantanu.vaidya@ashirvad.com');
            toAddressses.add('deepika@caritorsolutions.in');
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setSubject('Experts\' Club: Bill verification is pending for more than 2 days.');
            mail.setHtmlBody('<html><body>Hi '+ownerUserList[0].Manager.Name+',<br><br>'+
                             'Bills uploaded through the Experts\' Club App are pending for Mr. '+transList[0].Owner.Name+'\'s approval for more than 2 days in SFDC.<br>'+
                             'Kindly request Mr. '+transList[0].Owner.Name+' to verify approve/reject the pending bills at the earliest. Please find below the transaction details:<br><br>'+
                             'TGM Name: '+transList[0].Owner.Name+'<br>'+
                             +'Sales Accrual Name: '+transList[0].Sales_Accrual_Transaction__r[0].Name+'<br>'+
                             +'Transaction ID: '+transList[0].Name+'<br>'+
                             +'Transaction Amount: '+transList[0].Sales_Accrual_Transaction__r[0].Bill_amount__c+'<br>'+
                             +'Plumber Name: '+transList[0].Sales_Accrual_Transaction__r[0].Account__r.Name+'<br>'+
                             +'Dealer Name: '+transList[0].Sales_Accrual_Transaction__r[0].Dealer__r.Name+'<br>'+
                             +'Enterprise points: '+transList[0].Sales_Accrual_Transaction__r[0].Enterprise_points__c+'<br>'+
                             +'Bonus point: '+transList[0].Sales_Accrual_Transaction__r[0].Bonus_point__c+'<br>'+
                             +'Created Date: '+transList[0].CreatedDate+'<br><br>'+
                             +'Regards,<br>SFDC Support<br></html></body>');
            mail.setToAddresses(toAddressses);
            mail.setCcAddresses(ccAddressses);
            mail.setSenderDisplayName(transList[0].Owner.Name);
            mailList.add(mail);
            
            if(!mailList.isEmpty()){
                Messaging.SendEmail(mailList);
            }
        }
    }
}