Partial_14Dec2021/force-app/main/default/objects/AP_Taluk_Master__c/AP_Taluk_Master__c.object-meta.xml
<CustomObject>
    <label>APPL Taluk Master</label>
    <nameField>
        <label>Taluk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taluk Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Taluk_Master__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adilabad</fullName>
            </value>
            <value>
                <fullName>Ahmedabad</fullName>
            </value>
            <value>
                <fullName>Allahabad</fullName>
            </value>
            <value>
                <fullName>Amaravathi</fullName>
            </value>
            <value>
                <fullName>Ambikapur</fullName>
            </value>
            <value>
                <fullName>Amritsar</fullName>
            </value>
            <value>
                <fullName>Anantpur</fullName>
            </value>
            <value>
                <fullName>Andaman &amp; Nicobar</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Baroda</fullName>
            </value>
            <value>
                <fullName>Bathinda</fullName>
            </value>
            <value>
                <fullName>Belgaum</fullName>
            </value>
            <value>
                <fullName>Bhandara</fullName>
            </value>
            <value>
                <fullName>Bhopal</fullName>
            </value>
            <value>
                <fullName>Bijapur</fullName>
            </value>
            <value>
                <fullName>Bikaner</fullName>
            </value>
            <value>
                <fullName>Bilaspur</fullName>
            </value>
            <value>
                <fullName>Blr Zone</fullName>
            </value>
            <value>
                <fullName>Central Bihar</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Coimbatore</fullName>
            </value>
            <value>
                <fullName>Cuddapah</fullName>
            </value>
            <value>
                <fullName>Delhi-Ncr</fullName>
            </value>
            <value>
                <fullName>DL-NORTH-WEST</fullName>
            </value>
            <value>
                <fullName>DL-SOUTH-CENTRAL</fullName>
            </value>
            <value>
                <fullName>Durg</fullName>
            </value>
            <value>
                <fullName>Faridabad DL</fullName>
            </value>
            <value>
                <fullName>Ghaziabad</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Taluk_Master__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Andaman &amp; Nicobar</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/Influencer__c.object-meta.xml
<CustomObject>
    <label>Influencer</label>
    <nameField>
        <displayFormat>INF-{0000}</displayFormat>
        <label>Influencer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Influencer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual Contacts</value>
        </filterItems>
        <filterItems>
            <field>Account.Party_Type__c</field>
            <operation>equals</operation>
            <value>Architect, Contractor, Plumbing Contractor, Project Manager, Purchase Manager, Site Engineer, Project Owner/Developer, Plumbing Consultant, Consultant</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Influencer</relationshipLabel>
    <relationshipName>Influencer</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Firm_Name__c.field-meta.xml
<CustomField>
    <fullName>Firm_Name__c</fullName>
    <formula>Account__r.Firm_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm Name</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Influencer_Type__c.field-meta.xml
<CustomField>
    <fullName>Influencer_Type__c</fullName>
    <label>Influencer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Plumber</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Project Owner/Developer/Builder</fullName>
            </value>
            <value>
                <fullName>Purchase Manager</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Site Engineer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Plumbing Consultant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Influencer</relationshipLabel>
    <relationshipName>Influencer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Update_of_Last_Visit__c.field-meta.xml
<CustomField>
    <fullName>Update_of_Last_Visit__c</fullName>
    <label>Update of Last Visit</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer_types__c/Influencer_types__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting contains a list of all the Influencer Types</description>
    <label>Influencer types</label>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Project_Tracker__c/Project_Tracker__c.object-meta.xml
<CustomObject>
    <label>Project Tracker</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Project Tracker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Project_Tracker__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Tracker</relationshipLabel>
    <relationshipName>Project_Tracker</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Project_Tracker_Questions__c/Project_Tracker_Questions__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting contains all the project tracker questions</description>
    <label>Project Tracker Questions</label>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/AP_NewRetailProjectEntry.cls
global with sharing class AP_NewRetailProjectEntry {

    public Opportunity opportunityRecord {get;set;}
    public list<Influencer__c> influencerList {get;set;}
    public list<wrapperInfluencer> wrapInfuList {get;set;}
    public list<Project_Tracker__c> trackerList {get;set;}
    public String recordTypeId {get;set;}
    public AP_Taluk_Master__c brandingTaluk{get;set;}    
    String returnURL;


    public class myException extends Exception {
        
    }


    public AP_NewRetailProjectEntry(ApexPages.StandardController controller) {
        this.opportunityRecord = new Opportunity();
        this.influencerList = new list<Influencer__c>();
        this.trackerList = new list<Project_Tracker__c>();
        this.wrapInfuList   = new list<wrapperInfluencer>();
        recordTypeId  = [select id from RecordType where SobjectType = 'Account' AND Name ='Individual Contacts'].id;
        returnURL = ApexPages.CurrentPage().getParameters().get('retURL');

        
        Map<String, Influencer_types__c> nameToCstmSettingMap = Influencer_types__c.getAll();
        
        for(String type : nameToCstmSettingMap.keySet()){
            Influencer__c inf = new Influencer__c();
            inf.Influencer_Type__c = nameToCstmSettingMap.get(type).Type__c;
            wrapperInfluencer wInfu = new wrapperInfluencer();
            wInfu.influ = inf;           
            wrapInfuList.add(wInfu);
        }
       
        Map<String, Project_Tracker_Questions__c> trackerNameToCstmSettingMap = Project_Tracker_Questions__c.getAll();
        
        for(String trackerName : trackerNameToCstmSettingMap.keySet()){
            Project_Tracker__c tracker = new Project_Tracker__c();
            tracker.Question__c = trackerNameToCstmSettingMap.get(trackerName).Question__c;
            trackerList.add(tracker);
        }
    }

    /*********** On Save ***********/
    public PageReference saveProject(){
        set<Id> accIds = new set<Id>();
        set<Id> conIds = new set<Id>();
        set<String> updateVisit = new set<String>();
        Savepoint sp = Database.setSavepoint();
        try{

            insert opportunityRecord;

            list<Influencer__c> influencerNewList = new List<Influencer__c>();
            for(wrapperInfluencer wrap:wrapInfuList){

                influencerNewList.add(wrap.influ);
            }
            
            list<Influencer__c> influencerToInsertList = new List<Influencer__c>();
            for(Influencer__c inf:influencerNewList){
                inf.Opportunity__c = opportunityRecord.Id;
                if(inf.Account__c != null){
                    accIds.add(inf.Account__c);
                    
                }
               
                if(inf.Update_of_Last_Visit__c != null){
                    updateVisit.add(inf.Update_of_Last_Visit__c);
                }
                influencerToInsertList.add(inf);
            }
            
            if(accIds.size() == 0 && updateVisit.size() == 0) {
                
                ApexPages.Message theMessage = new ApexPages.Message(ApexPages.Severity.ERROR,'Please fill details of alteast one influencer');
                ApexPages.addMessage(theMessage);
                throw new myException('Please fill details of alteast one influencer');
                return null;
            }
            else {
                insert influencerToInsertList;
            }
            list<Project_Tracker__c> projectTrackerToInsertList = new List<Project_Tracker__c>();
            for(Project_Tracker__c tracker:trackerList){
                tracker.Opportunity__c = opportunityRecord.Id;
                projectTrackerToInsertList.add(tracker);
            }
            insert projectTrackerToInsertList;
          
     
            PageReference pf = new PageReference('/'+opportunityRecord.Id);
            pf.setRedirect(true);
            return pf;
        }
        catch(Exception e){
            opportunityRecord = opportunityRecord.clone(false,false);
            Database.rollback(sp);
            ApexPages.addMessages(e);
            return NULL;
        }

    }


/******** On Cancel *********/

    public PageReference cancel(){
        PageReference pfc = new PageReference('/006/o');
        pfc.setRedirect(true);
        return pfc;
       

    }

    public class wrapperInfluencer {
        public Influencer__c influ {get;set;}
        public String firmName {get;set;}

        public wrapperInfluencer() {
            firmName = '';
        }

    }

    @RemoteAction
    global static String getAccountInfo(String accName){
    
        Account acc;
        //if(accName.size()>0) {

            acc = [SELECT id,Firm_Name__c,Name FROM Account WHERE Name=:accName limit 1];

            return acc.Firm_Name__c;
        
    }

    public PageReference calRender (){
       
        return null;
    }
    public void projectCategoryVal(){
  opportunityRecord.Category__c='';
  
  
 if(Apexpages.currentPage().getParameters().get('firstParam')+''!='null' && Apexpages.currentPage().getParameters().get('firstParam')+''!='' ){
     
             opportunityRecord.Approximate_Project_Value__c=Apexpages.currentPage().getParameters().get('firstParam');
   
    if(opportunityRecord.Approximate_Project_Value__c == 'Rs.0 – Rs.5Lakhs'){
           opportunityRecord.Category__c='Low End';
           }
    else if (opportunityRecord.Approximate_Project_Value__c == 'Rs.5Lakhs – Rs.20Lakhs' ){   
           opportunityRecord.Category__c='Mid End';

        }
        else if (opportunityRecord.Approximate_Project_Value__c == 'Rs.20Lakhs and Above'){
        opportunityRecord.Category__c='High End';
        }
       }
   
  }        
    public void getTalukDetails(){
 system.debug('inside gettaluk');
 
  if(opportunityRecord.taluk__c <> null ){
  
  brandingTaluk = [select Name, Cluster__c, District__c, State__c from AP_Taluk_Master__c where id =:opportunityRecord.taluk__c];
    system.debug('gettaluk'+brandingTaluk);
      opportunityRecord.State__c =brandingTaluk.State__c;
      opportunityRecord.District__c = brandingTaluk.District__c;
      opportunityRecord.Cluster__c = brandingTaluk.Cluster__c;
 }
 
 else{
    opportunityRecord.State__c ='';
      opportunityRecord.District__c = '';
      opportunityRecord.Cluster__c ='';
  }
  
}
}