Partial_14Dec2021/force-app/main/default/objects/AP_Taluk_Master__c/AP_Taluk_Master__c.object-meta.xml
<CustomObject>
    <label>APPL Taluk Master</label>
    <nameField>
        <label>Taluk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taluk Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Taluk_Master__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adilabad</fullName>
            </value>
            <value>
                <fullName>Ahmedabad</fullName>
            </value>
            <value>
                <fullName>Allahabad</fullName>
            </value>
            <value>
                <fullName>Amaravathi</fullName>
            </value>
            <value>
                <fullName>Ambikapur</fullName>
            </value>
            <value>
                <fullName>Amritsar</fullName>
            </value>
            <value>
                <fullName>Anantpur</fullName>
            </value>
            <value>
                <fullName>Andaman &amp; Nicobar</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Baroda</fullName>
            </value>
            <value>
                <fullName>Bathinda</fullName>
            </value>
            <value>
                <fullName>Belgaum</fullName>
            </value>
            <value>
                <fullName>Bhandara</fullName>
            </value>
            <value>
                <fullName>Bhopal</fullName>
            </value>
            <value>
                <fullName>Bijapur</fullName>
            </value>
            <value>
                <fullName>Bikaner</fullName>
            </value>
            <value>
                <fullName>Bilaspur</fullName>
            </value>
            <value>
                <fullName>Blr Zone</fullName>
            </value>
            <value>
                <fullName>Central Bihar</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Coimbatore</fullName>
            </value>
            <value>
                <fullName>Cuddapah</fullName>
            </value>
            <value>
                <fullName>Delhi-Ncr</fullName>
            </value>
            <value>
                <fullName>DL-NORTH-WEST</fullName>
            </value>
            <value>
                <fullName>DL-SOUTH-CENTRAL</fullName>
            </value>
            <value>
                <fullName>Durg</fullName>
            </value>
            <value>
                <fullName>Faridabad DL</fullName>
            </value>
            <value>
                <fullName>Ghaziabad</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Hubli</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Taluk_Master__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>East</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Taluk_Master__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Andaman &amp; Nicobar</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Taluk_Master__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Taluk_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/Branding_Request__c.object-meta.xml
<CustomObject>
    <label>Branding Request</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Branding Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branding Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Branding_Manager__c.field-meta.xml
<CustomField>
    <fullName>Branding_Manager__c</fullName>
    <formula>$User.ManagerBranding__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branding Manager</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <description>Cluster from the page selected from Branding request.</description>
    <label>Cluster</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Details</label>
    <referenceTo>Vendor_Details__c</referenceTo>
    <relationshipLabel>Branding Requests</relationshipLabel>
    <relationshipName>Branding_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Vendor_Details__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Details</label>
    <referenceTo>Vendor_Details__c</referenceTo>
    <relationshipLabel>Branding Requests (Vendor Details)</relationshipLabel>
    <relationshipName>Branding_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Vertical_type__c.field-meta.xml
<CustomField>
    <fullName>Vertical_type__c</fullName>
    <formula>TEXT( CreatedBy.Vertical_Type__c )</formula>
    <label>Vertical type</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/User_Taluk_Master_Junction__c/User_Taluk_Master_Junction__c.object-meta.xml
<CustomObject>
    <label>APPL User Taluk Master Junction</label>
    <nameField>
        <label>User Taluk Master Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Taluk Master Junctions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/User_Taluk_Master_Junction__c/fields/AP_Taluk_Master__c.field-meta.xml
<CustomField>
    <fullName>AP_Taluk_Master__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>AP Taluk Master</label>
    <referenceTo>AP_Taluk_Master__c</referenceTo>
    <relationshipLabel>User Taluk Master Junctions</relationshipLabel>
    <relationshipName>User_Taluk_Master_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/User_Taluk_Master_Junction__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <formula>Text(AP_Taluk_Master__r.Cluster__c)</formula>
    <label>Cluster</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/User_Taluk_Master_Junction__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Text(AP_Taluk_Master__r.District__c)</formula>
    <label>District</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/User_Taluk_Master_Junction__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>Text(AP_Taluk_Master__r.Region__c )</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/User_Taluk_Master_Junction__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>Text(AP_Taluk_Master__r.State__c)</formula>
    <label>State</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/User_Taluk_Master_Junction__c/fields/Unique_filed__c.field-meta.xml
<CustomField>
    <fullName>Unique_filed__c</fullName>
    <label>Unique filed</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/User_Taluk_Master_Junction__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Taluk_Master_Junctions</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/Vendor_Details__c.object-meta.xml
<CustomObject>
    <label>Vendor Details</label>
    <nameField>
        <label>Vendor Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/fields/Board_4X2__c.field-meta.xml
<CustomField>
    <fullName>Board_4X2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Board_4X2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/fields/Board_6X3__c.field-meta.xml
<CustomField>
    <fullName>Board_6X3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Board_6X3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/fields/Board_8X3__c.field-meta.xml
<CustomField>
    <fullName>Board_8X3__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Board_8X3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/fields/Board_8X4__c.field-meta.xml
<CustomField>
    <fullName>Board_8X4__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Board_8X4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/Test_BandhanController.cls
@isTest(seeAllData=false)
private class Test_BandhanController{
    @testSetup
    public static void setup(){
       User HBUser=new User();
        HBUser.ProfileId=[SELECT Id FROM Profile WHERE Name =: 'Head Branding'].Id;
        HBUser.LastName='userHB';
        HBUser.Email='userhb@hb.com';
        HBUser.Username='userhb@hb.com'+ System.currentTimeMillis();
        HBUser.CompanyName='Test';
        HBUser.TimeZoneSidKey='Asia/Kolkata';
        HBUser.Title='title';
        HBUser.Alias='aliasss';
        HBUser.EmailEncodingKey='UTF-8';
        HBUser.LanguageLocaleKey='en_US';
        HBUser.LocaleSidKey='en_IN';
        HBUser.IsActive=true;
        insert HBUser;
        
        
        User RBMUser=new User();
        RBMUser.ProfileId=[SELECT Id FROM Profile WHERE Name =: 'Regional Branding Manager'].Id;
        RBMUser.LastName='userRBM';
        RBMUser.Email='userrbm@rbm.com';
        RBMUser.Username='userrbm@bdm.com'+ System.currentTimeMillis();
        RBMUser.CompanyName='Test';
        RBMUser.TimeZoneSidKey='Asia/Kolkata';
        RBMUser.Title='title';
        RBMUser.Alias='aliasss';
        RBMUser.EmailEncodingKey='UTF-8';
        RBMUser.LanguageLocaleKey='en_US';
        RBMUser.LocaleSidKey='en_IN';
        RBMUser.IsActive=true;
        insert RBMUser;
        
        
        
        
        
        
        User BDMUser=new User();
        BDMUser.ProfileId=[SELECT Id FROM Profile WHERE Name =: 'BD'].Id;
        BDMUser.LastName='userBdm';
        BDMUser.Email='userbdm@bdm.com';
        BDMUser.Username='userBdm@bdm.com'+ System.currentTimeMillis();
        BDMUser.CompanyName='Test';
        BDMUser.TimeZoneSidKey='Asia/Kolkata';
        BDMUser.Title='title';
        BDMUser.Alias='aliasss';
        BDMUser.EmailEncodingKey='UTF-8';
        BDMUser.LanguageLocaleKey='en_US';
        BDMUser.LocaleSidKey='en_IN';
        BDMUser.Branding_Manager__c=HBUser.Id;                   //Head Branding 
        BDMUser.Branding_Team_Member__c=RBMUser.Id;               //RBM
        BDMUser.Vertical_Type__c='Column';
        BDMUser.IsActive=true;

        insert BDMUser;
        
        
        
        
        User VUser=new User();
        VUser.ProfileId=[SELECT Id FROM Profile WHERE Name =: 'Vendor Partner'].Id;
        VUser.LastName='userVen';
        VUser.Email='userven@ven.com';
        VUser.Username='userven@ven.com'+ System.currentTimeMillis();
        VUser.CompanyName='Test';
        VUser.TimeZoneSidKey='Asia/Kolkata';
        VUser.Title='title';
        VUser.Alias='aliasss';
        VUser.EmailEncodingKey='UTF-8';
        VUser.LanguageLocaleKey='en_US';
        VUser.LocaleSidKey='en_IN';
        VUser.Branding_Manager__c=HBUser.Id;                   //Head Branding 
        VUser.Branding_Team_Member__c=RBMUser.Id;
        VUser.IsActive=true; 
        insert VUser; 
        
        AP_Taluk_Master__c TalukMaster=new AP_Taluk_Master__c();
        TalukMaster.Name='TalukMaster';
        TalukMaster.Region__c='South';
        TalukMaster.State__c='Karnataka';
        TalukMaster.District__c='Karwar';
        TalukMaster.Cluster__c='Hubli';
        insert TalukMaster;
        
        
        
        User_Taluk_Master_Junction__c usrTalukJunction=new User_Taluk_Master_Junction__c();
        usrTalukJunction.Name='Junction1';
        usrTalukJunction.AP_Taluk_Master__c=TalukMaster.Id;
        usrTalukJunction.Unique_filed__c='abcsd';
        usrTalukJunction.User__c=BDMUser.Id;
        insert usrTalukJunction;
        
        Vendor_Details__c venDetail=new Vendor_Details__c();
        venDetail.Board_4X2__c=40;
        venDetail.Board_6X3__c=10;
        venDetail.Board_8X3__c=20;
        venDetail.Board_8X4__c=30;
        venDetail.Primary_Vendor__c=true;
        venDetail.Vendor__c=VUser.Id;
        venDetail.Vendor_Code__c='sssss';
        venDetail.Vendor_Cluster__c='HUBLI';
        insert venDetail;
       
        Account acc1=new Account();
        acc1.RecordTypeId=[select id from RecordType where name='Dealer'].Id;
        acc1.Name='testAccount';
        acc1.Contact_Name__c='asdfghjkl';
        acc1.Contact_Number_Mobile__c='9876543210';
        acc1.Contact_Number_Phone__c='9876543210';
        acc1.Website='';
        acc1.ownerId=BDMUser.id;
        acc1.APPL_Taluk__c  =usrTalukJunction.Id;
        acc1.Bandhan_Cutsomer__c=true;
        insert acc1;
        
        
        Account acc2=new Account();
        acc2.RecordTypeId=[select id from RecordType where name='Dealer'].Id;
        acc2.Name='testAccount2';
        acc2.Contact_Name__c='asddfgfghjkl';
        acc2.Contact_Number_Mobile__c='9876533210';
        acc2.Contact_Number_Phone__c='9872543210';
        acc2.Website='';  
        acc2.APPL_Taluk__c  =usrTalukJunction.Id;
        acc2.ownerId=BDMUser.id;
        acc2.Bandhan_Cutsomer__c=true;
        insert acc2;
    }
    
    testmethod static void test1(){
        PageReference ref = new PageReference('/apex/BhandhanPage');
        Test.setCurrentPage(ref); 
        List<Account> ac=[select id,APPL_Taluk__c,APPL_Taluk__r.Cluster__c   from account];
        
        ApexPages.currentPage().getParameters().put('id',ac[0].id);
        
        BandhanController brdObject=new BandhanController();
        List<Branding_Request__c> brdLst=BandhanController.collectStoredBranding();
        Account acclst=BandhanController.collectAccount(ac[0].id);
        boolean zu= BandhanController.changeAddress(ac[0].id,'gfgfg','fghgfhfg','fghfghfg','fghgfh','123456');
        
        
        BandhanController.BrandWrap bw=new BandhanController.BrandWrap();          
            bw.Id='';
            bw.Shop=ac[0].Id;
            bw.BrandType='Standard';
            bw.MediaType='4x2';
            bw.MediaChild='';
            bw.Language='Hindi';
            bw.Cluster='Hubli';
            //bw.OwnerId=
            bw.mediabol=true;
            bw.mchildbol=false;
            bw.updbol=false;
            System.debug(bw);
            
            
           
            
            List<BandhanController.BrandWrap> bwList=new List<BandhanController.BrandWrap>();
            bwList.add(bw);
           
            
            String answer=BandhanController.saveReloaded(bwList,false,'');
            System.debug(answer);
            answer=BandhanController.updateReloaded(bwList,false,'');
            System.debug(answer);
    }
    
    
    testmethod static void test2(){
        PageReference ref = new PageReference('/apex/BhandhanPage');
        Test.setCurrentPage(ref); 
        List<Account> ac=[select id,APPL_Taluk__c,APPL_Taluk__r.Cluster__c   from account];
        
        ApexPages.currentPage().getParameters().put('id',ac[0].id);
        
        BandhanController brdObject=new BandhanController();
        List<Branding_Request__c> brdLst=BandhanController.collectStoredBranding();
        Account acclst=BandhanController.collectAccount(ac[0].id);
        boolean zu= BandhanController.changeAddress(ac[0].id,'gfgfg','fghgfhfg','fghfghfg','fghgfh','123456');
        
        
        BandhanController.BrandWrap bw=new BandhanController.BrandWrap();          
            bw.Id='';
            bw.Shop=ac[0].Id;
            bw.BrandType='Standard';
            bw.MediaType='4x2';
            bw.MediaChild='';
            bw.Language='Hindi';
            bw.Cluster='Hubli';
            //bw.OwnerId=
            bw.mediabol=true;
            bw.mchildbol=false;
            bw.updbol=false;
            System.debug(bw);
            
            
           
            
            List<BandhanController.BrandWrap> bwList=new List<BandhanController.BrandWrap>();
            bwList.add(bw);
           
            
            String answer=BandhanController.updateReloaded(bwList,false,'');
            System.debug(answer);
    }
}