Partial_14Dec2021/force-app/main/default/objects/AP_Taluk_Master__c/AP_Taluk_Master__c.object-meta.xml
<CustomObject>
    <label>APPL Taluk Master</label>
    <nameField>
        <label>Taluk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taluk Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Taluk_Master__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adilabad</fullName>
            </value>
            <value>
                <fullName>Ahmedabad</fullName>
            </value>
            <value>
                <fullName>Allahabad</fullName>
            </value>
            <value>
                <fullName>Amaravathi</fullName>
            </value>
            <value>
                <fullName>Ambikapur</fullName>
            </value>
            <value>
                <fullName>Amritsar</fullName>
            </value>
            <value>
                <fullName>Anantpur</fullName>
            </value>
            <value>
                <fullName>Andaman &amp; Nicobar</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Baroda</fullName>
            </value>
            <value>
                <fullName>Bathinda</fullName>
            </value>
            <value>
                <fullName>Belgaum</fullName>
            </value>
            <value>
                <fullName>Bhandara</fullName>
            </value>
            <value>
                <fullName>Bhopal</fullName>
            </value>
            <value>
                <fullName>Bijapur</fullName>
            </value>
            <value>
                <fullName>Bikaner</fullName>
            </value>
            <value>
                <fullName>Bilaspur</fullName>
            </value>
            <value>
                <fullName>Blr Zone</fullName>
            </value>
            <value>
                <fullName>Central Bihar</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Coimbatore</fullName>
            </value>
            <value>
                <fullName>Cuddapah</fullName>
            </value>
            <value>
                <fullName>Delhi-Ncr</fullName>
            </value>
            <value>
                <fullName>DL-NORTH-WEST</fullName>
            </value>
            <value>
                <fullName>DL-SOUTH-CENTRAL</fullName>
            </value>
            <value>
                <fullName>Durg</fullName>
            </value>
            <value>
                <fullName>Faridabad DL</fullName>
            </value>
            <value>
                <fullName>Ghaziabad</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Taluk_Master__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Region__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Andaman &amp; Nicobar</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/Influencer__c.object-meta.xml
<CustomObject>
    <label>Influencer</label>
    <nameField>
        <displayFormat>INF-{0000}</displayFormat>
        <label>Influencer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Influencer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual Contacts</value>
        </filterItems>
        <filterItems>
            <field>Account.Party_Type__c</field>
            <operation>equals</operation>
            <value>Architect, Contractor, Plumbing Contractor, Project Manager, Purchase Manager, Site Engineer, Project Owner/Developer, Plumbing Consultant, Consultant</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Influencer</relationshipLabel>
    <relationshipName>Influencer</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Firm_Name__c.field-meta.xml
<CustomField>
    <fullName>Firm_Name__c</fullName>
    <formula>Account__r.Firm_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm Name</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Influencer_Type__c.field-meta.xml
<CustomField>
    <fullName>Influencer_Type__c</fullName>
    <label>Influencer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Plumber</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Project Owner/Developer/Builder</fullName>
            </value>
            <value>
                <fullName>Purchase Manager</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Site Engineer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Plumbing Consultant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Influencer</relationshipLabel>
    <relationshipName>Influencer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Update_of_Last_Visit__c.field-meta.xml
<CustomField>
    <fullName>Update_of_Last_Visit__c</fullName>
    <label>Update of Last Visit</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer_types__c/Influencer_types__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting contains a list of all the Influencer Types</description>
    <label>Influencer types</label>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Project_Tracker__c/Project_Tracker__c.object-meta.xml
<CustomObject>
    <label>Project Tracker</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Project Tracker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Project_Tracker__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Tracker</relationshipLabel>
    <relationshipName>Project_Tracker</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Project_Tracker__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Project_Tracker_Questions__c/Project_Tracker_Questions__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting contains all the project tracker questions</description>
    <label>Project Tracker Questions</label>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/Test_CaptureProjectDetails.cls
/*******************XXX**********************************

Created By      :Mohd.Numaan Ahmed
Created Date    :29-Jan-2015
Modified Date   :
Version         :1.0
Description     :Test class for CaptureProjectDetails class

********************XXX***********************************/
@isTest(seeAllData=false)
private class Test_CaptureProjectDetails {
    
    

    @isTest static void test_method_one() {
    
    
      Influencer_types__c  infCustom = new Influencer_types__c();
        infCustom.Type__c='Site Engineer';
        infCustom.Name='Type 1';
      
       
        //infCustom.
        insert infCustom;
    
    
    String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Account' and Name = 'Key Accounts'].Id;
    Account acc = new Account();
    acc.Name='testAcc';
    acc.Contact_Number_Mobile__c = '9765433318';
    acc.recordTypeId = strRecordTypeId;
    acc.Firm_Name__c = 'et';
    insert acc;
    
     AP_Taluk_Master__c  ap = new  AP_Taluk_Master__c ();
     ap.name='Bangalore';
     ap.Cluster__c='qweqwe';
     ap.District__c='bangalore';
     ap.State__c = 'karnataka';
     insert ap;
    
    
      Opportunity opp = new Opportunity();
      opp.Name='TestClass';
      opp.StageName = 'Designing';
      opp.CloseDate =date.TODAY()+10;
      opp.Approximate_Project_Value__c='Rs.0 – Rs.5Lakhs';
      
      opp.Project_Type__c='Commercial';
      opp.No_of_Bathrooms__c = 12;
     
      opp.Project_By__c=acc.Id;
      opp.Special_Pricing_Request_Approval__c='Submitted';
      opp.Taluk__c=ap.Id;
      insert opp;
      
        Influencer__c inf = new Influencer__c();
     
       // inf.Influencer_Type__c='Site Architect';
        inf.Account__c=acc.Id;
        inf.Update_of_Last_Visit__c='trtr';
     inf.Opportunity__c = opp.Id;
        insert inf;
      
    Project_Tracker__c pro = new Project_Tracker__c();  
    pro.Question__c='wewqeqe';
     pro.Response__c='yes';
       pro.Opportunity__c = opp.Id;
               insert pro; 
   
    

    Project_Tracker_Questions__c   projectCustom = new Project_Tracker_Questions__c();
        projectCustom.Question__c='All Product range approved';
        projectCustom.Name='Question 1';
        insert projectCustom;
       
     

            Test.startTest();
               Apexpages.currentPage().getParameters().put('Id',null);
            Apexpages.currentPage().getParameters().put('firstParam','Rs.0 – Rs.5Lakhs');
               ApexPages.StandardController sc = new ApexPages.StandardController(opp );
               CaptureProjectDetails oppController = new CaptureProjectDetails(sc);
              // CaptureProjectDetails.wrapperInfluencer win = new CaptureProjectDetails.wrapperInfluencer();
    
                    //     win.influ=inf;
                      //   oppController.wrapInfuList.add(win);
                         
                         
                         // win.influ.Account__c=acc.id;
                         //  win.influ.Influencer_Type__c='Site Architect';
                           
                         //  win.influ.Update_of_Last_Visit__c='qweq';
                     // opp.No_of_Bathrooms__c = 1;     
                        
             oppController.saveProject();
               CaptureProjectDetails.getAccountInfo('testAcc');
               oppController.projectCategoryVal();
               Apexpages.currentPage().getParameters().put('firstParam','Rs.5Lakhs – Rs.20Lakhs');
               oppController.projectCategoryVal();
               Apexpages.currentPage().getParameters().put('firstParam','Rs.20Lakhs and Above');
               oppController.calRender();
               oppController.cancel();
               oppController.projectCategoryVal();
               oppController.getTalukDetails();
             
               oppController.saveProject();
               oppController.getTalukDetails();
               oppController.opportunityRecord.taluk__c = ap.id ;
               oppController.getTalukDetails();
               oppController.getRequestInformation(opp.id);
              oppController.saveProject();
        		oppController.runQuery();
         
            Test.stopTest();
            
       
    }
    
   
    
}