Partial_14Dec2021/force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/City__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/Influencer__c.object-meta.xml
<CustomObject>
    <label>Influencer</label>
    <nameField>
        <displayFormat>INF-{0000}</displayFormat>
        <label>Influencer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Influencer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual Contacts</value>
        </filterItems>
        <filterItems>
            <field>Account.Party_Type__c</field>
            <operation>equals</operation>
            <value>Architect, Contractor, Plumbing Contractor, Project Manager, Purchase Manager, Site Engineer, Project Owner/Developer, Plumbing Consultant, Consultant</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Influencer</relationshipLabel>
    <relationshipName>Influencer</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Firm_Name__c.field-meta.xml
<CustomField>
    <fullName>Firm_Name__c</fullName>
    <formula>Account__r.Firm_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm Name</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Inf_Order__c.field-meta.xml
<CustomField>
    <fullName>Inf_Order__c</fullName>
    <description>This field will store the order of influencer.</description>
    <label>Inf Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Influencer_Type__c.field-meta.xml
<CustomField>
    <fullName>Influencer_Type__c</fullName>
    <label>Influencer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Plumber</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Project Owner/Developer/Builder</fullName>
            </value>
            <value>
                <fullName>Purchase Manager</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Site Engineer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Plumbing Consultant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Influencer</relationshipLabel>
    <relationshipName>Influencer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Labour Contractor</fullName>
            </value>
            <value>
                <fullName>In House</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Update_of_Last_Visit__c.field-meta.xml
<CustomField>
    <fullName>Update_of_Last_Visit__c</fullName>
    <label>Update of Last Visit</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/MassEditInfulencers.cls
/*******************XXX**********************************

Created By      :Mohd.Numaan Ahmed
Created Date    :29-Dec-2014
Modified Date   :
Version         :1.0
Description     :

********************XXX***********************************/
public class MassEditInfulencers {

    public String projectId {get;set;} 
    public List<Influencer__c> influencerList {get;set;}
    public String recordTypeId {get;set;}
    
    public MassEditInfulencers(){

        projectId = ApexPages.currentPage().getParameters().get('ProjectId');
        influencerList = new List<Influencer__c>();
        influencerList = [SELECT Id, Account__c,Account__r.Name ,Account__r.Firm_Name__c, Influencer_Type__c, Last_Visit_Date__c, Update_of_Last_Visit__c,Inf_Order__c,Source__c FROM Influencer__c WHERE Opportunity__c = :projectId ORDER by Inf_Order__c];
        recordTypeId  = [select id from RecordType where SobjectType = 'Account' AND Name ='Individual Contacts'].id;
    }

    public void updateInfluencers(){

        try{
            
            update influencerList;
        }
        catch(exception e){

            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, e.getMessage()));

        }
    }
    
    
    public PageReference cancel(){

        PageReference pf = new PageReference('/'+projectId);
        return pf;
    }
       // the query string entered by the user
    public String orderQuery {get; set;}
    // the matchin>g accounts
    public List<Account> orderAccounts {get; set;}
    
     // executes the search
    public void runOrderQuery()
    {   
        System.debug('coming inside');
        if(orderQuery != null) {
            orderQuery = orderQuery .trim();
        }
        
        String nameCond = '%'+orderQuery +'%';
        String cond = orderQuery +'%';
        orderAccounts  = new List<Account>();
        List<Account> searchResults= New List<Account>([SELECT Id,Name, Primary_Contact_Person_Name__c, Party_type__c, Contact_Number_Mobile__c, State__c, District__c, City__c, Status__c, Street_Address__c, Ramco_ID__c  FROM Account WHERE  (Name LIKE :nameCond OR City__c LIKE :cond OR District__c LIKE :cond OR Contact_Number_Mobile__c LIKE :cond ) limit 999]);
        
        orderAccounts.addAll(searchResults);
        System.debug('coming inside runQuery ' +orderAccounts);
        
    }
 
    
    }