Partial_14Dec2021/force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/City__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Promotion No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer(o)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Distributor_Dealer__c.Type__c</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Distributor_Dealer__c</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Gifts_given__c.field-meta.xml
<CustomField>
    <fullName>Gifts_given__c</fullName>
    <label>Gifts given</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>caps</fullName>
            </value>
            <value>
                <fullName>carrybags</fullName>
            </value>
            <value>
                <fullName>keychains</fullName>
            </value>
            <value>
                <fullName>lunchboxes</fullName>
            </value>
            <value>
                <fullName>measuring tapes</fullName>
            </value>
            <value>
                <fullName>pens</fullName>
            </value>
            <value>
                <fullName>pigeon kitchen sets</fullName>
            </value>
            <value>
                <fullName>stationary kits</fullName>
            </value>
            <value>
                <fullName>table tops</fullName>
            </value>
            <value>
                <fullName>Tools Kit</fullName>
            </value>
            <value>
                <fullName>Torches</fullName>
            </value>
            <value>
                <fullName>t-shirts</fullName>
            </value>
            <value>
                <fullName>umbrellas</fullName>
            </value>
            <value>
                <fullName>wallets</fullName>
            </value>
            <value>
                <fullName>wind cheaters</fullName>
            </value>
            <value>
                <fullName>wrist watches</fullName>
            </value>
            <value>
                <fullName>No gifts given</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhatisgarh</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Pondicherry</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttaranchal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Total_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Total_Expenses__c</fullName>
    <label>Total Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Total_no_of_attendees__c.field-meta.xml
<CustomField>
    <fullName>Total_no_of_attendees__c</fullName>
    <label>No. of members attended</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Architects / Engineers / Consultants Factory Visit</fullName>
            </value>
            <value>
                <fullName>Architects Meets</fullName>
            </value>
            <value>
                <fullName>Boarers Meets</fullName>
            </value>
            <value>
                <fullName>Builders Meets</fullName>
            </value>
            <value>
                <fullName>Column Dealer / Distributor Meets</fullName>
            </value>
            <value>
                <fullName>Column Distributors / Dealers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Column DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Engineers Meets</fullName>
            </value>
            <value>
                <fullName>Exhibition / Agri Fairs</fullName>
            </value>
            <value>
                <fullName>Exhibition / Construction Fairs</fullName>
            </value>
            <value>
                <fullName>Group Activity</fullName>
            </value>
            <value>
                <fullName>Inshop Boarers Meets</fullName>
            </value>
            <value>
                <fullName>Inshop Mechanic Meets</fullName>
            </value>
            <value>
                <fullName>Inshop Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Jeep Campaign</fullName>
            </value>
            <value>
                <fullName>Mechanics Factory Visit</fullName>
            </value>
            <value>
                <fullName>Mega Farmer Meets</fullName>
            </value>
            <value>
                <fullName>Mega Mechanic Meets</fullName>
            </value>
            <value>
                <fullName>Mega Plumbers Meets</fullName>
            </value>
            <value>
                <fullName>Mini Farmer Meet</fullName>
            </value>
            <value>
                <fullName>Naaka Meets</fullName>
            </value>
            <value>
                <fullName>Onsite Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Plumbers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealer / Distributor Meets</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealers Factory Visits</fullName>
            </value>
            <value>
                <fullName>Plumbing DSM Meet/Training</fullName>
            </value>
            <value>
                <fullName>Product Presentation</fullName>
            </value>
            <value>
                <fullName>Projects DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Shandy Shows</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/Promotion_Member__c.object-meta.xml
<CustomObject>
    <label>Promotion Member</label>
    <nameField>
        <displayFormat>PM-{YY}-{MM}-{DD}-{00}</displayFormat>
        <label>Promotion Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Promotion_Members1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Distributor_Dealer__c.Type__c</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Distributor_Dealer__c</referenceTo>
    <relationshipLabel>Promotion Members</relationshipLabel>
    <relationshipName>Promotion_Members1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>Used in related list Accounts</description>
    <formula>Text(Promotions2__r.District__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Party_type__c.field-meta.xml
<CustomField>
    <fullName>Party_type__c</fullName>
    <formula>TEXT(Account__r.Party_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Party type</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Promotions2__c.field-meta.xml
<CustomField>
    <fullName>Promotions2__c</fullName>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipName>Promotion_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT( Promotions2__r.State__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/APPL_NEW_PROMOTION_CTRL.cls
/*--++----------------------------------------------------------------------
||        Author      : BABA
||
||        Purpose     : Creating Promotion and adding Promotion members to it.
If member is not there, then Create Account.
||                  
||        Modified By : 02/07/2015 / Baba
|| 
||        Reason      : Code beautification/Review and made code to follow the best practices. 
||
++----------------------------------------------------------------------- */
global class APPL_NEW_PROMOTION_CTRL {
    
    //Varibles
    public Promotion__c newpromotion {get;set;}
    public Boolean showPromotion  {get;set;}
    public boolean showAddMemberPanel {get;set;}
    public List<string> productList {get; set;}
    public String accRecTypeId {get;set;}
    public String dealerRtId {get;set;}
    public String directDealerId {get;set;}
    public String distrubutorId {get;set;}
    public String promotionName {get;set;}
    public boolean validationCheck {get; set;}
    public Boolean showMemberSaveBtn {get;set;}
    public Boolean showPromotionSaveBtn {get;set;}
    public List<Account> proAccounts {get;set;}
    public Map<String,Account> proAccountMap {get;set;}
    public List<String> giftsGiven {get;set;}
    public list<RecordType> accountRecordTypes = new List<RecordType>();
    public String accToRemove{get;set;}
    public String accToRefresh{get;set;}
    public Boolean validationRequired{get;set;}
    public Boolean disabled{get; set;}
    
    //Constructor showPromotion
    public APPL_NEW_PROMOTION_CTRL() {
        showMemberSaveBtn = true;
        showPromotionSaveBtn = true;
        promotionName = '';
        validationCheck = false;
        newpromotion = new Promotion__c();
        showPromotion = true;
        proAccounts = new List<Account>();
        productList = new List<String>();
        proAccountMap = new Map<String,Account>();
        giftsGiven = new List<String>();
        validationRequired =false;
        disabled=true;
        //Getting Products of Travel Dynamic
        Schema.DescribeFieldResult productsResult = Account.Products__c.getDescribe();
        List<Schema.PicklistEntry> pro = productsResult.getPicklistValues();
        for( Schema.PicklistEntry f : pro)
        {
            productList.add(f.getValue());
        } 

        Schema.DescribeFieldResult giftGivenResult =Promotion__c.Gifts_given__c.getDescribe();
        List<Schema.PicklistEntry> gifts = giftGivenResult.getPicklistValues();
        for( Schema.PicklistEntry g : gifts)
        {
            giftsGiven.add(g.getValue());
        } 
        //Get the Account Record Types
        accountRecordTypes = [SELECT DeveloperName,Id,Name FROM RecordType WHERE SobjectType = 'Account'];
        
        for(RecordType rt:accountRecordTypes){
            
            if(rt.DeveloperName == 'Dealer'){
                dealerRtId = rt.id;
            }else if(rt.DeveloperName == 'Direct_Dealer'){
                directDealerId = rt.id;
            }else if(rt.DeveloperName == 'Distributor'){
                distrubutorId = rt.id;
            }else if(rt.DeveloperName == 'Individual_Contacts'){
                accRecTypeId = rt.id;//individaul contacts
            }
        }
    }
    
    public PageReference addMember(){
        system.debug('No. Of Members ='+newpromotion.Total_no_of_attendees__c);
        proAccounts.add(new Account());
        proAccountMap.putAll(proAccounts);
        return null;
    }
    //Create
    public PageReference CreatePromotion(){
        showPromotion = false;

        try{
            if(newpromotion.Type__c != null &&
               newpromotion.Total_Expenses__c != null &&
               newpromotion.Total_no_of_attendees__c != null &&
               newpromotion.State__c != null
              ){
                  system.debug('newpromotion '+newpromotion);
                  insert newpromotion;
                  system.debug('newpromotion'+newpromotion.id);  
                  showPromotion = false;
                  promotionName = [Select Name from Promotion__c where id =:newpromotion.id].Name;
                  
              }else{
                  system.debug('All Fields are not Entered');
              }
            showPromotionSaveBtn = false;
            Apexpages.addMessage(new ApexPages.message(Apexpages.severity.Confirm,'Promotion saved Succesfully'));   
        }catch(exception ex){ 
            system.debug('Ex '+ex);
            showPromotionSaveBtn = true;
            Apexpages.addMessage(new ApexPages.message(Apexpages.severity.Error,ex.getMessage()));
        }
        return null;
    }
    
    public PageReference CancelToPromo(){
        showPromotion = true;
        return null;
    }
    
    public void ShowMembers(){
        showAddMemberPanel = true;
        try{
            for(Integer i=0; i<newpromotion.Total_no_of_attendees__c;i++)
                proAccounts.add(new Account());
        }catch(exception ex){
            system.debug(ex);
            Apexpages.addMessage(new ApexPages.message(Apexpages.severity.Error,ex.getMessage()));
        }   
        
    }
    
    /*  Search Customer based on the Name. */
    @RemoteAction
    global static list<Account> getCustomer( string cusMob) {
        list<account> accList = new list<Account>();
        try {
            
            accList = [SELECT Id,Name,recordTypeId,Contact_Number_Mobile__c FROM Account WHERE Contact_Number_Mobile__c LIKE :cusMob+'%'];
            System.debug(accList);
        } catch(Exception e) {
            system.debug(e.getMessage());
        }
        return accList;
    }
    
    //Action Fucntion proAccounts
    public PageReference getAccoutRow(){
        
        String tempRow = String.valueOf(ApexPages.currentPage().getParameters().get('rowIndex'));
        String mobileNumber = String.valueOf(ApexPages.currentPage().getParameters().get('cusMobile'));
        Integer rowNumber = Integer.valueOf(tempRow);
        List<Account> accList = new List<Account>();
        accList = [Select RecordTypeId,Id, Name, Dealer__c, Account__c, Contact_Number_Mobile__c,Visit_Type__c, Firm_Name__c,State__c, District__c, City__c,Contact_Number_Phone__c,
                   Status__c, PIN_Code__c,Party_Type__c, Primary_Contact_Person_Name__c, Products__c,Street_Address__c 
                   from Account where Contact_Number_Mobile__c =:mobileNumber];
       
        if( !accList.isEmpty() && accList.size() > 0){
            proAccounts.set(rowNumber-1, accList.get(0));
        }else{
            proAccounts.set(rowNumber-1, new Account(Contact_Number_Mobile__c =mobileNumber ));
        }
        return null;
    }
    
    
    //Save Functionality
    public PageReference SavePromotionMembers(){
        validationRequired = true;
         
        List<Promotion_Member__c> pmsList = new List<Promotion_Member__c>();
        try{
            if(newpromotion.Id != null){
                system.debug('Save Account Members'+proAccounts);
                
                for(Account acc : proAccounts){
                    acc.System_Flag__c = true;
                   
                    if(acc.RecordTypeId == null){
                        if(newpromotion.Type__c == 'Dealer'){
                            acc.recordtypeId = dealerRtId;
                        }else{
                            acc.recordtypeId = accRecTypeId;
                        } 
                    }
                }
                
                upsert proAccounts;
                
                for(Account acc : proAccounts){
                    
                    Promotion_Member__c pms = new Promotion_Member__c();
                    pms.Account__c = acc.Id;
                    pms.Promotions2__c = newpromotion.Id;
                    
                    pmsList.add(pms);
                }   
                
                if(!pmsList.isEmpty()){
                    insert pmsList;
                }
                
            }
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Confirm,'Promotion Members Added Succesfully'));
            validationCheck = true;
            showMemberSaveBtn = false;
             disabled=false;
        }catch(exception ex){
            system.debug('exception'+ex);
            validationCheck = false;
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,ex.getMessage()));
            showMemberSaveBtn = true;
            disabled=true;
            return null;
        } 
        return null;
    }
    
    //Cancel
    public PageReference CanelPromotion(){
        newpromotion = new Promotion__c();
        return null;
    }
    
    //Delete Entry
    public PageReference DeleteEntry(){
    validationRequired = false;
   
    system.debug('proAccounts::'+proAccounts);
    //String tempRow = String.valueOf(ApexPages.currentPage().getParameters().get('rowIndex'));
   // String mobileNumber = String.valueOf(ApexPages.currentPage().getParameters().get('cusMobile'));
    Integer rowNumber = Integer.valueOf(accToRemove);
    system.debug('rowNumber:::'+ rowNumber );
    proAccounts.remove(rowNumber - 1);
    
    return null;
    }
    
    //Refresh Entry
    public PageReference RefreshEntry(){
    
         Integer rowNumber = Integer.valueOf(accToRemove);
        if(accToRefresh != ''){
        List<Account> accList = new List<Account>();
        accList = [Select RecordTypeId,Id, Name, Dealer__c, Account__c, Contact_Number_Mobile__c,Visit_Type__c, Firm_Name__c,State__c, District__c, City__c,Contact_Number_Phone__c, Status__c,
                   PIN_Code__c,Party_Type__c, Primary_Contact_Person_Name__c, Products__c,Street_Address__c from Account where Contact_Number_Mobile__c =:accToRefresh];
       
        if( !accList.isEmpty() && accList.size() > 0){
            proAccounts.set(rowNumber-1, accList.get(0));
        }else{
            proAccounts.set(rowNumber-1, new Account(Contact_Number_Mobile__c =accToRefresh));
        }
        }
        return null;
    }
}