Partial_14Dec2021/force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/City__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Promotion No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer(o)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Distributor_Dealer__c.Type__c</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Distributor_Dealer__c</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhatisgarh</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Pondicherry</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttaranchal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Architects / Engineers / Consultants Factory Visit</fullName>
            </value>
            <value>
                <fullName>Architects Meets</fullName>
            </value>
            <value>
                <fullName>Boarers Meets</fullName>
            </value>
            <value>
                <fullName>Builders Meets</fullName>
            </value>
            <value>
                <fullName>Column Dealer / Distributor Meets</fullName>
            </value>
            <value>
                <fullName>Column Distributors / Dealers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Column DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Engineers Meets</fullName>
            </value>
            <value>
                <fullName>Exhibition / Agri Fairs</fullName>
            </value>
            <value>
                <fullName>Exhibition / Construction Fairs</fullName>
            </value>
            <value>
                <fullName>Group Activity</fullName>
            </value>
            <value>
                <fullName>Inshop Boarers Meets</fullName>
            </value>
            <value>
                <fullName>Inshop Mechanic Meets</fullName>
            </value>
            <value>
                <fullName>Inshop Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Jeep Campaign</fullName>
            </value>
            <value>
                <fullName>Mechanics Factory Visit</fullName>
            </value>
            <value>
                <fullName>Mega Farmer Meets</fullName>
            </value>
            <value>
                <fullName>Mega Mechanic Meets</fullName>
            </value>
            <value>
                <fullName>Mega Plumbers Meets</fullName>
            </value>
            <value>
                <fullName>Mini Farmer Meet</fullName>
            </value>
            <value>
                <fullName>Naaka Meets</fullName>
            </value>
            <value>
                <fullName>Onsite Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Plumbers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealer / Distributor Meets</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealers Factory Visits</fullName>
            </value>
            <value>
                <fullName>Plumbing DSM Meet/Training</fullName>
            </value>
            <value>
                <fullName>Product Presentation</fullName>
            </value>
            <value>
                <fullName>Projects DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Shandy Shows</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/Promotion_Member__c.object-meta.xml
<CustomObject>
    <label>Promotion Member</label>
    <nameField>
        <displayFormat>PM-{YY}-{MM}-{DD}-{00}</displayFormat>
        <label>Promotion Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Promotion_Members1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <formula>IF( ISBLANK(Contacts__c), Account__r.Contact_Number_Mobile__c, Contacts__r.Mobile__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Number</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Distributor_Dealer__c.Type__c</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Distributor_Dealer__c</referenceTo>
    <relationshipLabel>Promotion Members</relationshipLabel>
    <relationshipName>Promotion_Members1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <description>Used in related list Accounts</description>
    <formula>Text(Promotions2__r.District__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Party_type__c.field-meta.xml
<CustomField>
    <fullName>Party_type__c</fullName>
    <formula>TEXT(Account__r.Party_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Party type</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Promotions2__c.field-meta.xml
<CustomField>
    <fullName>Promotions2__c</fullName>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipName>Promotion_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>TEXT( Promotions2__r.State__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Type1__c.field-meta.xml
<CustomField>
    <fullName>Type1__c</fullName>
    <label>Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/SearchandCreateMembers.cls
public class SearchandCreateMembers {

    Public Id prmId; 
    public Promotion__c prm{get;set;}
    
    //Integer count= 0;
    Public Boolean showmsg{get;set;}
    public integer num{ get; set; }
    
    public List<Account> MobileNumbers;
    public List<Account> existingAccountList;
    public List<Account> newAccountList;
    public List<Account> combinedAccountList;
    Public Map<String,Promotion_Member__c> MapMobiles;

    public SearchandCreateMembers(ApexPages.StandardController controller) {
        prmId=ApexPages.CurrentPage().getParameters().get('id');
        MapMobiles = new Map<String,Promotion_Member__c>();
        if(prmId!=null)
            prm=[SELECT id,Name,Type__c,(SELECT id,Name,Contact_Number__c FROM Promotion_Members__r) FROM Promotion__c WHERE id=:prmId];
            if(!prm.Promotion_Members__r.isEmpty())
            {
                for(Promotion_Member__c pm : prm.Promotion_Members__r)
                {
                    if(pm.Contact_Number__c!=Null)
                    {
                        MapMobiles.put(pm.Contact_Number__c,pm);
                    }
                }
            }
    
        
    }
    
     public Void add_rows() {
     
        if(MobileNumbers==null){
            MobileNumbers = new List<Account>();
        }
        
        for(integer i=0;i<num ;i++){           
            MobileNumbers.add(new Account()); 
        } 
    }
    
    
    public List<Account> getMobileNumbers() {
        return MobileNumbers;
    }
    
    public List<Account> getCombinedAccountList() {
        return combinedAccountList;
    }
    
     public List<Account> getExistingAccountList() {
        return existingAccountList;
    }


     public List<Account> getNewAccountList() {
        return newAccountList;
    }
    /**
    public SearchandCreateMembers() {
        if(MobileNumbers==null){
            MobileNumbers = new List<Account>();
        }
        
        MobileNumbers.add(new Account());
        MobileNumbers.add(new Account());
    }**/
    
    public PageReference searchMobileNumber(){
    try
    {
        boolean errorFlag = false;
        set<String> mobileNumberset = new set<String>();
        for(Account eachMob: MobileNumbers){
            String phoneNumber = eachMob.Contact_Number_Mobile__c;
            Pattern isnumbers = Pattern.Compile('^[0-9]+$');
            if(eachMob.Contact_Number_Mobile__c!=null && eachMob.Contact_Number_Mobile__c.trim()!='' ){
                Matcher MobileMatch = isnumbers.matcher(phoneNumber);
                if(!MobileMatch.Matches() || phoneNumber.length()!=10){
                     //System.debug('@@@@@@@@@@@@Match Match@@@@@@@@@@@@'+MobileMatch );
                     //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Correct the below errors'));
                     eachMob.Contact_Number_Mobile__c.addError('Please enter valid 10 digit number');
                     errorFlag = true;
                }else {
                    mobileNumberset.add(eachMob.Contact_Number_Mobile__c);
                }
            }else{
                eachMob.Contact_Number_Mobile__c.addError('Please enter valid 10 digit number');
                errorFlag = true;
            }
        }
        if(errorFlag )return null;
        existingAccountList = [Select Id, Name, Dealer__c, Account__c, Contact_Number_Mobile__c, 
                                      Visit_Type__c, Firm_Name__c, State__c, District__c, City__c, 
                                      Contact_Number_Phone__c, Status__c, PIN_Code__c,Party_Type__c, Primary_Contact_Person_Name__c, Products__c,Street_Address__c
                                      from Account where Contact_Number_Mobile__c in : mobileNumberset];
        
        set<String> existingMobileNumberset =  new set<string>();
        for(Account eachExistAcct : existingAccountList ){
            existingMobileNumberset.add(eachExistAcct.Contact_Number_Mobile__c);
        }
        newAccountList = new List<Account>();
        for(Account eachMob: MobileNumbers){
          if(eachMob.Contact_Number_Mobile__c!=null && eachMob.Contact_Number_Mobile__c.trim()!='' )
          {
            if(!existingMobileNumberset.contains(eachMob.Contact_Number_Mobile__c)){
                newAccountList.add(eachMob);
            }}
        }
        combinedAccountList = new List<Account>();
        combinedAccountList.addall(existingAccountList );
        combinedAccountList.addall(newAccountList);
        
        
        
        PageReference p=new PageReference('/apex/createMembers');
        return p;
        }
        catch(exception e)
        {return null;}
        
    }
    
    public PageReference saveMembers(){
       try
       {
        for(Account eachAccount: existingAccountList ){
            System.debug('**** DK .. Mobile = '+eachAccount.Contact_Number_Mobile__c +' Email = ');
        }
        
        for(Account eachAccount: newAccountList){
            System.debug('**** DK .. Mobile = '+eachAccount.Contact_Number_Mobile__c +' Email = ');
        }
        
        for(Account eachAccount: combinedAccountList){
            System.debug('**** DK .. Mobile = '+eachAccount.Contact_Number_Mobile__c +' Email = ');
        }
        
        for(Account each12 : newAccountList){
      
       if(each12.PIN_Code__c!=null && each12.PIN_Code__c.length()!=6)
       {
        each12.PIN_Code__c.addError('Please enter valid 6 digit number');
        return null;
        } 
            }
            Insert newAccountList;
        //update existingAccountList ;
       
        
        //upsert combinedAccountList;
        List<Promotion_Member__c> promotionMemberList = new List<Promotion_Member__c>(); 
        
        List<String> dupemobile=new List<String>();
        for(Account each : combinedAccountList){
       
        if(MapMobiles.Containskey(each.Contact_Number_Mobile__c))
            {
            dupemobile.add(each.Contact_Number_Mobile__c);
            }
           
        }
        if(!dupemobile.IsEmpty())
        {
        String error='';
        for(String S:dupemobile)
        {
        error=error+','+S;
        }
        ApexPages.addmessage(new Apexpages.message(apexpages.Severity.Error,'Already Promotion Members created with this Mobile Number'+error));
        return null;
        }
        if(dupemobile.IsEmpty()==True)
        {
            for(Account each : combinedAccountList)
            {
             promotionMemberList.add(new Promotion_Member__c(Promotions2__c=prm.id,Type1__c=prm.Type__c,Account__c=each.id));
            }
        }
        insert promotionMemberList;
        
        PageReference p = new PageReference('/'+ApexPages.CurrentPage().getParameters().get('id'));
        return p;
       }
        catch(exception e)
        {ApexPages.addMessages(e);} 
        return null;
    }
    


}