Partial_14Dec2021/force-app/main/default/objects/Answer_Option__c/Answer_Option__c.object-meta.xml
<CustomObject>
    <label>Answer Option</label>
    <nameField>
        <displayFormat>Answer Option-{0000}</displayFormat>
        <label>Answer Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Answer_Option__c/fields/Custom_Question__c.field-meta.xml
<CustomField>
    <fullName>Custom_Question__c</fullName>
    <description>Is us used to capture custom question dependent questions value.</description>
    <label>Custom Question</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Answer_Option__c/fields/Custom_Value__c.field-meta.xml
<CustomField>
    <fullName>Custom_Value__c</fullName>
    <description>It is used to capture custom questions value.</description>
    <label>Custom Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Answer_Option__c/fields/Other_Top_Brand__c.field-meta.xml
<CustomField>
    <fullName>Other_Top_Brand__c</fullName>
    <description>This will capture rating of top brand(other than Ashirvad).</description>
    <label>Other Top Brand</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Answer_Option__c/fields/Survey_Details__c.field-meta.xml
<CustomField>
    <fullName>Survey_Details__c</fullName>
    <description>It is used to capture Question Id from Survey Details(Parent) object.</description>
    <label>Survey Details</label>
    <referenceTo>Survey_Details__c</referenceTo>
    <relationshipLabel>Answer Options</relationshipLabel>
    <relationshipName>Answer_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Master_Questions__c/Master_Questions__c.object-meta.xml
<CustomObject>
    <description>It is used to capture questions value, data type of questions</description>
    <label>Master Questions</label>
    <nameField>
        <label>Master Questions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Master_Questions__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify question is mandatory or not</description>
    <inlineHelpText>If this checkbox is checked then this question will be mandatory on NPS feedback page else won&apos;t.</inlineHelpText>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Master_Questions__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <label>Options</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Master_Questions__c/fields/Question_Name__c.field-meta.xml
<CustomField>
    <fullName>Question_Name__c</fullName>
    <description>Used to store name of question</description>
    <inlineHelpText>It will display question on the NPS feedback page.</inlineHelpText>
    <label>Question Name</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Master_Questions__c/fields/Question_Order__c.field-meta.xml
<CustomField>
    <fullName>Question_Order__c</fullName>
    <description>It is used to get questions according to sequence in soql query.</description>
    <inlineHelpText>Questions will display on NPS feedback page according to Question Order value.</inlineHelpText>
    <label>Question Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Master_Questions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to Identify question is activate or not</description>
    <inlineHelpText>If status is checked then this question will appear on feedback page else it won&apos;t.</inlineHelpText>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Master_Questions__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Used to define data type for question in lightning component.</description>
    <inlineHelpText>If Type is pick-list then enter comma separated value in Options field.
If Type is Text/Text-Area/Number then enter &apos;null&apos; as a value in Options field.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>TextArea</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Multiselect</fullName>
                <isActive>false</isActive>
                <label>Multiselect</label>
            </value>
            <value>
                <fullName>Radio</fullName>
                <isActive>false</isActive>
                <label>Radio</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/NPS__c/NPS__c.object-meta.xml
<CustomObject>
    <label>NPS</label>
    <nameField>
        <displayFormat>NPS-{0000}</displayFormat>
        <label>NPS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/NPS__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NPS</relationshipLabel>
    <relationshipName>NPS</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/NPS__c/fields/First_Brand__c.field-meta.xml
<CustomField>
    <fullName>First_Brand__c</fullName>
    <label>First Brand</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/NPS__c/fields/First_Brand_Rating__c.field-meta.xml
<CustomField>
    <fullName>First_Brand_Rating__c</fullName>
    <label>First Brand Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/NPS__c/fields/NPSType__c.field-meta.xml
<CustomField>
    <fullName>NPSType__c</fullName>
    <label>NPSType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/NPS__c/fields/Rating_Capture_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Capture_Date__c</fullName>
    <description>Whenever rating for top brand is captured this field will capture value of current time.</description>
    <label>Rating Capture Date</label>
    <type>DateTime</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/NPS__c/fields/Second_Brand__c.field-meta.xml
<CustomField>
    <fullName>Second_Brand__c</fullName>
    <label>Second Brand</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/NPS__c/fields/Second_Brand_Rating__c.field-meta.xml
<CustomField>
    <fullName>Second_Brand_Rating__c</fullName>
    <label>Second Brand Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/NPS__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Onhold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/NPS__c/fields/Third_Brand__c.field-meta.xml
<CustomField>
    <fullName>Third_Brand__c</fullName>
    <label>Third Brand</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/NPS__c/fields/Third_Brand_Rating__c.field-meta.xml
<CustomField>
    <fullName>Third_Brand_Rating__c</fullName>
    <label>Third Brand Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/NPS__c/fields/Top_Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Top_Brand_Name__c</fullName>
    <description>capture the selected top brand name from nps feedback form.</description>
    <label>Top Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/NPS__c/fields/Top_Brand_Rating__c.field-meta.xml
<CustomField>
    <fullName>Top_Brand_Rating__c</fullName>
    <description>capture the selected top brand rating from nps feedback form.</description>
    <label>Top Brand Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Survey_Details__c/Survey_Details__c.object-meta.xml
<CustomObject>
    <description>Used to capture response of survey.</description>
    <label>Survey Details</label>
    <nameField>
        <displayFormat>Survey Details-{0000}</displayFormat>
        <label>Survey Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Survey_Details__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Survey Details</relationshipLabel>
    <relationshipName>Survey_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Survey_Details__c/fields/Master_Questions__c.field-meta.xml
<CustomField>
    <fullName>Master_Questions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Questions</label>
    <referenceTo>Master_Questions__c</referenceTo>
    <relationshipLabel>Survey Details</relationshipLabel>
    <relationshipName>Survey_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Survey_Details__c/fields/NPS__c.field-meta.xml
<CustomField>
    <fullName>NPS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NPS</label>
    <referenceTo>NPS__c</referenceTo>
    <relationshipLabel>Survey Details</relationshipLabel>
    <relationshipName>Survey_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Survey_Details__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>Used to capture response from feedback form</description>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/NpsFeedbackController.cls
public with sharing class NpsFeedbackController {
    
    @AuraEnabled(cacheable=true)
    public static List<QuestionWrapper> fetchQuestions(String accountId) {
        System.debug('accountId **** ' + accountId);
        Account accountList;
        Id npsRecordId;
        List<NPS__c> npsRecordList = new List<NPS__c>();
        if(accountId != null) {
            accountList = [SELECT Id, Party_Type__c FROM Account WHERE Id =: accountId LIMIT 1];
            npsRecordList = [SELECT Id FROM NPS__c WHERE Account__c =: accountId AND Account__c != null Order By CreatedDate Desc LIMIT 1];
            if (npsRecordList.size() > 0) {
                npsRecordId = npsRecordList[0].Id;
            }
        }
        
        List<QuestionWrapper> wrapQuestionList = new List<QuestionWrapper>();
        List<Master_Questions__c> masterQuestionList = new List<Master_Questions__c>([SELECT Id, Question_Name__c, Type__c, Options__c,
                                                                                        Status__c, Mandatory__c, Question_Order__c
                                                                                        FROM Master_Questions__c WHERE Status__c = true 
                                                                                        ORDER BY Question_Order__c ASC]);

        System.debug('masterQuestionList ' + masterQuestionList);
        for(Master_Questions__c mQues : masterQuestionList) {
            if(accountList != null && 
                (accountList.Party_Type__c == Label.Dealer_Label || accountList.Party_Type__c == Label.Plumber_Label)
                && npsRecordId != null) {
                String quesName = mQues.Question_Name__c;
                quesName = quesName.replace(Label.Question_Modify, accountList.Party_Type__c); // replace @@@@ in the question with PArty type of Account.
                wrapQuestionList.add(new QuestionWrapper(mQues.Id, 
                                                            quesName, 
                                                            mQues.Status__c, 
                                                            mQues.Options__c, 
                                                            mQues.Type__c, '',
                                                            mQues.Question_Order__c, 
                                                            mQues.Mandatory__c,
                                                            npsRecordId));
            }
        }
        System.debug('wrapQuestionList **** ' + wrapQuestionList);
        return wrapQuestionList;
    }

    @AuraEnabled
    public static void saveSurveyDetailsMethod(List<Survey_Details__c> surveyDetailList, String surveyDetailChildList,
                                                String selectedTopBrandName, Decimal selectedTopBrandRating, 
                                                String accountId, String selectedFeedbackStatus, String lookupValueWithLabel) {
        try {
            System.debug('lookupValueWithLabel ' + lookupValueWithLabel);
            System.debug('selectedTopBrandName ' + selectedTopBrandName + ' --- ' + selectedTopBrandRating + ' ---- ' + accountId);
            List<Answer_Option__c> answerOptionListToInsert = new List<Answer_Option__c>();
            Map<Id, Id> serveyDetailMap = new Map<Id, Id>();
            if(surveyDetailList.size() > 0) {

                if (surveyDetailList.size() > 0) {
                    System.debug('surveyDetailList before insert ' + surveyDetailList);
                    Insert surveyDetailList; // Insert Survey details which has response of master questions
                }
                System.debug('surveyDetailList after insert ' + surveyDetailList);
                for (Survey_Details__c serDetail : surveyDetailList) {
                    serveyDetailMap.put(serDetail.Master_Questions__c, serDetail.Id); // storing Survey details Id on each question id to insert child record(Answer option)
                }

                List<Object> lookupValueWithLabelList = (List<Object>) JSON.deserializeUntyped(lookupValueWithLabel);
                Map<String, String> lookupMap = new Map<String, String>();
                for (Object iterateObjList : lookupValueWithLabelList) {
                    if(iterateObjList != null) {
                        Map<String, Object> surveyDetailMap = (Map<String, Object>) iterateObjList;
                        List<String> keyValue = new List<String>(surveyDetailMap.keySet());
                        lookupMap.put(keyValue[0], JSON.serialize(surveyDetailMap.get(keyValue[0]))); // Map to hold rating as key and brand name as value 
                    }
                }
                System.debug('qwewwe final lookupMap ' + lookupMap);
                
                
                List<Object> surveyDetailObj = (List<Object>) JSON.deserializeUntyped(surveyDetailChildList);
                for (Object iterateObjList : surveyDetailObj) {
                    if(iterateObjList != null) {
                        Map<String, Object> surveyDetailMap = (Map<String, Object>) iterateObjList;
                        
                        System.debug('fdsfdsf' + surveyDetailMap.get('Response__c'));
                        if ((String) surveyDetailMap.get('Type') == 'Custom' && (String) surveyDetailMap.get('Options') == '001' && surveyDetailMap.get('Response__c') != null) {
                            List<Object> responseList = (List<object>) surveyDetailMap.get('Response__c');

                            for (Object obj : responseList) {
                                ResponseWrapper wrpInstace = (ResponseWrapper)JSON.deserializeStrict(JSON.serialize(obj), ResponseWrapper.class); // map response list values with wrapper class attributes
                                Answer_Option__c ansOption = new Answer_Option__c();
                                ansOption.Survey_Details__c = serveyDetailMap.get((String)surveyDetailMap.get('Master_Questions__c'));
                                ansOption.Custom_Question__c = '';
                                ansOption.Custom_Value__c = wrpInstace.Name;
                                ansOption.Other_Top_Brand__c = '';
                                answerOptionListToInsert.add(ansOption);
                            }
                            
                        }

                        if ((String) surveyDetailMap.get('Type') == 'Custom' && (String) surveyDetailMap.get('Options') == '002' && surveyDetailMap.get('Response__c') != null) {
                            List<Object> responseList = (List<object>) surveyDetailMap.get('Response__c');

                            for (Object obj : responseList) {
                                ResponseWrapper wrpInstace = (ResponseWrapper)JSON.deserializeStrict(JSON.serialize(obj), ResponseWrapper.class);
                                Answer_Option__c ansOption = new Answer_Option__c();
                                ansOption.Survey_Details__c = serveyDetailMap.get((String)surveyDetailMap.get('Master_Questions__c'));
                                ansOption.Custom_Question__c = lookupMap.get(wrpInstace.value).remove('\"'); // removing double quote from selected brand name
                                ansOption.Custom_Value__c = wrpInstace.value;
                                ansOption.Other_Top_Brand__c = '';
                                answerOptionListToInsert.add(ansOption);
                            }
                            
                        }

                        if ((String) surveyDetailMap.get('Type') == 'Custom' && (String) surveyDetailMap.get('Options') == '003' && surveyDetailMap.get('Response__c') != null) {
                            List<Object> responseList = (List<object>) surveyDetailMap.get('Response__c');

                            for (Object obj : responseList) {
                                ResponseWrapper wrpInstace = (ResponseWrapper)JSON.deserializeStrict(JSON.serialize(obj), ResponseWrapper.class);
                                Answer_Option__c ansOption = new Answer_Option__c();
                                ansOption.Survey_Details__c = serveyDetailMap.get((String)surveyDetailMap.get('Master_Questions__c'));
                                ansOption.Custom_Question__c = wrpInstace.label;
                                ansOption.Custom_Value__c = wrpInstace.subQuesRating;
                                ansOption.Other_Top_Brand__c = wrpInstace.subQuesTopBrandRating;
                                answerOptionListToInsert.add(ansOption);
                            }

                        }

                        if ((String) surveyDetailMap.get('Type') == 'Custom' && (String) surveyDetailMap.get('Options') == '004' && surveyDetailMap.get('Response__c') != null) {
                            List<Object> responseList = (List<object>) surveyDetailMap.get('Response__c');

                            for (Object obj : responseList) {
                                ResponseWrapper wrpInstace = (ResponseWrapper)JSON.deserializeStrict(JSON.serialize(obj), ResponseWrapper.class);
                                Answer_Option__c ansOption = new Answer_Option__c();
                                ansOption.Survey_Details__c = serveyDetailMap.get((String)surveyDetailMap.get('Master_Questions__c'));
                                ansOption.Custom_Question__c = '';
                                ansOption.Custom_Value__c = wrpInstace.value;
                                ansOption.Other_Top_Brand__c = '';
                                answerOptionListToInsert.add(ansOption);
                            }
                            
                        }
                    }
                }
                System.debug('1111 ' + answerOptionListToInsert);
                
                if (answerOptionListToInsert.size() > 0) {
                    Insert answerOptionListToInsert;
                }
                /* Logic to insert NPS record and update account record */
                if (selectedTopBrandName != null && selectedTopBrandRating != null &&
                         accountId != null && selectedFeedbackStatus != null) {
                    
                    Account acc = new Account();
                    acc.Id = accountId;
                    acc.Rating_Capture_Date__c = System.now();

                    if (acc != null) {
                        Update acc;
                    }

                    List<NPS__c> npsListToUpdate = new List<NPS__c>();
                    for (NPS__c nps : [SELECT Id, Top_Brand_Name__c, Top_Brand_Rating__c, Rating_Capture_Date__c, Status__c FROM NPS__c 
                            WHERE Account__c =: accountId Order By CreatedDate Desc LIMIT 1]) {
                        NPS__c npsIns = new NPS__c();
                        npsIns.Id = nps.Id;
                        npsIns.Top_Brand_Name__c = selectedTopBrandName;
                        npsIns.Top_Brand_Rating__c = selectedTopBrandRating;
                        npsIns.Rating_Capture_Date__c = System.now();
                        npsIns.Status__c = selectedFeedbackStatus;
                        if(selectedTopBrandRating >= 1 && selectedTopBrandRating <= 6) {
                            npsIns.NPSType__c = Label.Demotors;
                        } else if(selectedTopBrandRating >= 7 && selectedTopBrandRating <= 8) {
                            npsIns.NPSType__c = Label.Passive;
                        } else if(selectedTopBrandRating >= 9 && selectedTopBrandRating <= 10){
                            npsIns.NPSType__c = Label.Promotors;
                        } else {
                            npsIns.NPSType__c = '';
                        }
                        Integer i = 0;
                        for (String str : lookupMap.keySet()) {
                            if (i == 0) {
                                npsIns.First_Brand__c = lookupMap.get(str).remove('\"');
                                npsIns.First_Brand_Rating__c = Decimal.valueOf(str);
                            }
                            if (i == 1) {
                                npsIns.Second_Brand__c = lookupMap.get(str).remove('\"');
                                npsIns.Second_Brand_Rating__c = Decimal.valueOf(str);
                            }
                            if (i == 2) {
                                npsIns.Third_Brand__c = lookupMap.get(str).remove('\"');
                                npsIns.Third_Brand_Rating__c = Decimal.valueOf(str);
                            }
                            i++;
                        }
                        npsListToUpdate.add(npsIns);
                    }
                    System.debug('npsListToUpdate ' + npsListToUpdate);
                    if (npsListToUpdate.size() > 0) {
                        Update npsListToUpdate;
                    }
                    
                }
            }
            
        } catch(Exception ex) {
            System.debug('wrapQuestionList **** ' + ex);
            throw new AuraHandledException(ex.getMessage());
        }
        
    }

    public class QuestionWrapper {
        
        
        @AuraEnabled
        public Id recordId;

        @AuraEnabled
        public Id npsId;

        @AuraEnabled
        public String QuestionName;

        @AuraEnabled
        public Boolean Status;

        @AuraEnabled
        public String Options;

        @AuraEnabled
        public String Type;

        @AuraEnabled
        public object Response;

        @AuraEnabled
        public Decimal questionOrder;

        @AuraEnabled
        public Boolean mandatory;

        public QuestionWrapper() {

        }
        public QuestionWrapper(Id recordId,
                                String QuestionName, 
                                Boolean Status, 
                                String Options, 
                                String Type, 
                                object Response, 
                                Decimal questionOrder,
                                Boolean mandatory,
                                Id npsId) {
            this.recordId = recordId;
            this.QuestionName = QuestionName;
            this.Status = Status;
            this.Options = Options;
            this.Type = Type;
            this.Response = Response;
            this.questionOrder = questionOrder;
            this.mandatory = mandatory;
            this.npsId = npsId;
        }
    }
    public class ResponseWrapper {
        public String Id;
        public String Name;
        public String value;
        public String label;
        public String subQuesRating;
        public String subQuesTopBrandRating;
    }
}