Partial_14Dec2021/force-app/main/default/objects/Bandhan_Orders__c/Bandhan_Orders__c.object-meta.xml
<CustomObject>
    <description>For  the Account with Bandhan checked. And in order to show product names as column name, fields are created with product name</description>
    <label>Bandhan Order</label>
    <nameField>
        <displayFormat>BO - {000000}</displayFormat>
        <label>Bandhan Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bandhan Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Bandhan_Orders__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bandhan Orders</relationshipLabel>
    <relationshipName>Bandhan_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Bandhan_Orders__c/fields/Cart_Status__c.field-meta.xml
<CustomField>
    <fullName>Cart_Status__c</fullName>
    <label>Cart Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Given</fullName>
            </value>
            <value>
                <fullName>No order given</fullName>
            </value>
            <value>
                <fullName>Call later</fullName>
            </value>
            <value>
                <fullName>Invalid/Wrong Number</fullName>
            </value>
            <value>
                <fullName>RNR/Busy/Call Divert</fullName>
            </value>
            <value>
                <fullName>Not dealing with ashirvad</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Bandhan_Orders__c/fields/Month_of_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>Month_of_CreatedDate__c</fullName>
    <formula>MONTH( DATEVALUE( CreatedDate ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month of CreatedDate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Bandhan_Orders__c/fields/Year_of_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>Year_of_CreatedDate__c</fullName>
    <formula>YEAR( DATEVALUE( CreatedDate ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year of CreatedDate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/BandhanOrderCls.cls
/*******************************************************************************
 * Developer : Srilakshmi K.U
 * Description : Apex controller for button Bandhan Orders on account layout
********************************************************************************/
public class BandhanOrderCls {
	@AuraEnabled   
    public static Map<String, Object> getBandhanOrdRec(id recordId){
        Map<String, Object> res = new Map<String, Object>();
        list<Bandhan_Orders__c> bord = new list<Bandhan_Orders__c>();
        try{
            List<Account> accts = [Select Id,Name,Parent.Status__c From Account where Id = :recordId];
            bord = [Select id,Cart_Status__c,Year_of_CreatedDate__c,Month_of_CreatedDate__c From Bandhan_Orders__c Where Account__c=:recordId];
            res.put('ACCOUNT', accts);
            res.put('ORDERS', bord);
            return res;
        }catch (Exception ex){
            throw new AuraHandledException('Apex error: '+ ex.getMessage());
        } 
    }    
	  
}