Partial_14Dec2021/force-app/main/default/objects/Bandhan_Orders__c/Bandhan_Orders__c.object-meta.xml
<CustomObject>
    <description>For  the Account with Bandhan checked. And in order to show product names as column name, fields are created with product name</description>
    <label>Bandhan Order</label>
    <nameField>
        <displayFormat>BO - {000000}</displayFormat>
        <label>Bandhan Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bandhan Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Bandhan_Orders__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bandhan Orders</relationshipLabel>
    <relationshipName>Bandhan_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/Test_BandhanOrders.cls
@isTest
public class Test_BandhanOrders{
    private static Account testAccount1;
    public static testMethod void one(){
        testAccount1 = Initial_Test_Data.createAccount('Testount1', 'Dealer');
        testAccount1.Contact_Number_Mobile__c ='7253452222';
        testAccount1.Party_Type__c='Dealer';
        testAccount1.District__c='Bangalore';
        testAccount1.State__c='Karnataka';
        testAccount1.Business_Line__c='Plumbing';
        insert testAccount1;

        Bandhan_Orders__c bandhanOBJ1 = new Bandhan_Orders__c();
       // bandhanOBJ1.account__c=testAccount1.id;
       // insert bandhanOBJ1;

        test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(bandhanOBJ1);
        Bandhan_Order_Controller BndhnOBJ=new Bandhan_Order_Controller(sc);
        PageReference pageRef = Page.Bandhan_Orders;
        pageRef.getParameters().put('pid', String.valueOf(testAccount1.Id));
        Test.setCurrentPage(pageRef);
        BndhnOBJ.accountId=ApexPages.currentPage().getParameters().get('pid');
        bandhanOBJ1.account__c=BndhnOBJ.accountId;
        BndhnOBJ.callPersonName='Call Executive1';
        BndhnOBJ.getbandhanOBJ();
    
        BndhnOBJ.save();
        //insert bandhanOBJ1;
        //insert obj;
        
        test.stopTest();
 }
    public static testMethod void two(){
        testAccount1 = Initial_Test_Data.createAccount('Testount1', 'Dealer');
        testAccount1.Contact_Number_Mobile__c ='7253452222';
        testAccount1.Party_Type__c='Dealer';
        testAccount1.District__c='Bangalore';
        testAccount1.State__c='Karnataka';
        testAccount1.Business_Line__c='Plumbing';
        insert testAccount1;

        Bandhan_Orders__c bandhanOBJ1 = new Bandhan_Orders__c();
       // bandhanOBJ1.account__c=testAccount1.id;
       // insert bandhanOBJ1;

     

        test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(bandhanOBJ1);
        Bandhan_Order_Controller BndhnOBJ=new Bandhan_Order_Controller(sc);
        PageReference pageRef = Page.Bandhan_Orders;
        pageRef.getParameters().put('pid', String.valueOf(testAccount1.Id));
        Test.setCurrentPage(pageRef);
        BndhnOBJ.AccountId=ApexPages.currentPage().getParameters().get('pid');
        bandhanOBJ1.account__c=BndhnOBJ.AccountId;
        BndhnOBJ.callPersonName='';
        BndhnOBJ.getbandhanOBJ();
    
       
        BndhnOBJ.saveAndNew();
              
        test.stopTest();
 }

}