Partial_14Dec2021/force-app/main/default/objects/Bandhan_Orders__c/Bandhan_Orders__c.object-meta.xml
<CustomObject>
    <description>For  the Account with Bandhan checked. And in order to show product names as column name, fields are created with product name</description>
    <label>Bandhan Order</label>
    <nameField>
        <displayFormat>BO - {000000}</displayFormat>
        <label>Bandhan Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bandhan Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Bandhan_Orders__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bandhan Orders</relationshipLabel>
    <relationshipName>Bandhan_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/Bandhan_Order_Controller.cls
public class Bandhan_Order_Controller{
public string AccountId;

public ApexPages.StandardController controller;
 Public String callPersonName {get; set;}

 Public Bandhan_Orders__c bandhanOBJ = new Bandhan_Orders__c();
    public Bandhan_Orders__c getbandhanOBJ()
    {
        return bandhanOBJ;
    }
 public Bandhan_Order_Controller(ApexPages.StandardController Controller){ 
         AccountId=ApexPages.currentPage().getParameters().get('pid') ;
         bandhanOBJ = (Bandhan_Orders__c)Controller.getRecord(); 
         this.controller=Controller;  
     }
 //method to save
    public PageReference save() {       
      system.debug(bandhanOBJ);
      bandhanOBJ.Account__c=AccountId;//bandhanId;
      system.debug(bandhanOBJ);
      insert bandhanOBJ; 
      PageReference returnPage=new PageReference('/'+bandhanOBJ.id);
      return returnPage;
    }  
         //method to save & new 
      public PageReference saveAndNew() {
          system.debug(bandhanOBJ);
          bandhanOBJ.Account__c=AccountId;//bandhanId;
          system.debug(bandhanOBJ);
          insert bandhanOBJ; 
          String url = '/apex/Bandhan_Orders?pid='+AccountId;
          PageReference pr= new PageReference(url);
          pr.setRedirect(true);
          system.debug(url+'&&**URL**&&');
          return pr;          
    }  
}