Partial_14Dec2021/force-app/main/default/objects/Bandhan_Orders__c/Bandhan_Orders__c.object-meta.xml
<CustomObject>
    <description>For  the Account with Bandhan checked. And in order to show product names as column name, fields are created with product name</description>
    <label>Bandhan Order</label>
    <nameField>
        <displayFormat>BO - {000000}</displayFormat>
        <label>Bandhan Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bandhan Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Bandhan_Orders__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Related Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bandhan Orders</relationshipLabel>
    <relationshipName>Bandhan_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Bandhan_Orders__c/fields/Cart_Status__c.field-meta.xml
<CustomField>
    <fullName>Cart_Status__c</fullName>
    <label>Cart Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Given</fullName>
            </value>
            <value>
                <fullName>No order given</fullName>
            </value>
            <value>
                <fullName>Call later</fullName>
            </value>
            <value>
                <fullName>Invalid/Wrong Number</fullName>
            </value>
            <value>
                <fullName>RNR/Busy/Call Divert</fullName>
            </value>
            <value>
                <fullName>Not dealing with ashirvad</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Bandhan_Orders__c/fields/Month_of_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>Month_of_CreatedDate__c</fullName>
    <formula>MONTH( DATEVALUE( CreatedDate ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month of CreatedDate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Bandhan_Orders__c/fields/Year_of_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>Year_of_CreatedDate__c</fullName>
    <formula>YEAR( DATEVALUE( CreatedDate ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year of CreatedDate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/BandhanOrderClsTest.cls
@isTest
public class BandhanOrderClsTest {
    static testMethod void BandhanOrderClsMethod() {
        Account acc = new Account();
        acc.Name = 'Bandhan';
        acc.Status__c = 'Existing';
        acc.Discount__c = 10;
        acc.Contact_Number_Mobile__c = '9859000000';
        Insert acc;
        
        Bandhan_Orders__c bandhan = new Bandhan_Orders__c();
        bandhan.Cart_Status__c = 'Order Given';
     //   bandhan.Year_of_CreatedDate__c = '';
     //   bandhan.Month_of_CreatedDate__c = '';
        bandhan.Account__c = acc.Id;
        
        Insert bandhan;
        
        BandhanOrderCls.getBandhanOrdRec(acc.Id);
            
    }
}