Partial_14Dec2021/force-app/main/default/objects/Opportunities__c/Opportunities__c.object-meta.xml
<CustomObject>
    <label>Opportunities</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Opportunities__c/fields/LastModified_Difference__c.field-meta.xml
<CustomField>
    <fullName>LastModified_Difference__c</fullName>
    <formula>Today()- DATEVALUE(LastModifiedDate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LastModified Difference</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Opportunities__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Opportunity_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Firm Enquiry</fullName>
            </value>
            <value>
                <fullName>Quotation Sent</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Invitation to Tender</fullName>
            </value>
            <value>
                <fullName>Technical Bid</fullName>
            </value>
            <value>
                <fullName>Technical Clearance</fullName>
            </value>
            <value>
                <fullName>Commercial Bid</fullName>
            </value>
            <value>
                <fullName>Technical Pre-Bid</fullName>
            </value>
            <value>
                <fullName>Bid Qualification</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>LOI Receipt</fullName>
            </value>
            <value>
                <fullName>BG Submission</fullName>
            </value>
            <value>
                <fullName>RFQ</fullName>
            </value>
            <value>
                <fullName>RFQ Validation &amp; Recommendation</fullName>
            </value>
            <value>
                <fullName>Product Team/Pricing Team</fullName>
            </value>
            <value>
                <fullName>Offer Mailed</fullName>
            </value>
            <value>
                <fullName>Final Order</fullName>
            </value>
            <value>
                <fullName>Technical Discussion</fullName>
            </value>
            <value>
                <fullName>Technical Acceptance by customer</fullName>
            </value>
            <value>
                <fullName>Offer Submission</fullName>
            </value>
            <value>
                <fullName>Submission of Tech Docs / Drawings</fullName>
            </value>
            <value>
                <fullName>Manufacturing Clearance</fullName>
            </value>
            <value>
                <fullName>Production / Import</fullName>
            </value>
            <value>
                <fullName>Order Won</fullName>
            </value>
            <value>
                <fullName>Order Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/OpportunityStageCheckTest.cls
@isTest
public class OpportunityStageCheckTest {

    static testMethod void testMethod1() 
    {
        List<Opportunities__c> lstOpp= new List<Opportunities__c>();
        for(Integer i=0 ;i <200;i++)
        {
            Opportunities__c acc = new Opportunities__c();
            acc.Name ='Name'+i;
            acc.Stage__c='Technical Pre-Bid';
            //acc.LastModified_Difference__c=62;
            lstOpp.add(acc);
        }
        
        insert lstOpp;
        
        Opportunities__c oppc = new Opportunities__c();
            oppc.Name ='Namess';
            oppc.Stage__c='Technical Pre-Bid';
        insert oppc;
        for(Opportunities__c op:lstOpp){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        list<string> toAddressees1 = new list<string>();
                toAddressees1.add('suryapriya.s@kvpcorp.com');
     
            mail.setToAddresses(toAddressees1);
        mail.setSubject('Remainder on Opportunity Stage Changes ');
        
        mail.setPlainTextBody('Please go to the Opportunity  ' + op.Name + '  Where the Stage '+op.Stage__c+ ' is not changed for the last 2 months, So Kinldy check the Opportunity and '+
                              'Please find the link    ' +'https://appl-ashirvadpipes.lightning.force.com/'+op.id);

             //Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
        
        
        
        Test.startTest();

            OpportunityStageCheckSchedular obj = new OpportunityStageCheckSchedular();
            obj.execute(null); 
            OpportunityStageCheckSchedular.testingcovering();
        Test.stopTest();
    }


}