Partial_14Dec2021/force-app/main/default/objects/Meeting_Atendee__c/Meeting_Atendee__c.object-meta.xml
<CustomObject>
    <label>Meeting Attendee</label>
    <nameField>
        <displayFormat>MA-{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Attendees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Meeting_Atendee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Meeting Attendees</relationshipLabel>
    <relationshipName>Meeting_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Meeting_Atendee__c/fields/Meeting_Attended_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Attended_Date__c</fullName>
    <label>Meeting Attended Date</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Meeting_Atendee__c/fields/Meeting_Attendee_Status__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Attendee_Status__c</fullName>
    <label>Meeting Attendee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Meeting_Atendee__c/fields/Meeting_Type__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Type__c</fullName>
    <label>Meeting Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Meeting_Atendee__c/fields/Meetings__c.field-meta.xml
<CustomField>
    <fullName>Meetings__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Meetings</label>
    <referenceTo>Meetings__c</referenceTo>
    <relationshipLabel>Meeting Attendees</relationshipLabel>
    <relationshipName>Meeting_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/MeetingAttendeeFilter__mdt/MeetingAttendeeFilter__mdt.object-meta.xml
<CustomObject>
    <label>MeetingAttendeeFilter</label>
    <pluralLabel>MeetingAttendeeFilters</pluralLabel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/MeetingAttendeeFilter__mdt/fields/Meeting_Type__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Type__c</fullName>
    <label>Meeting Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mini Meet</fullName>
            </value>
            <value>
                <fullName>Mega Meet</fullName>
            </value>
            <value>
                <fullName>Vikaas Awards</fullName>
            </value>
            <value>
                <fullName>Wives Connect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/MeetingAttendeeFilter__mdt/fields/Months__c.field-meta.xml
<CustomField>
    <fullName>Months__c</fullName>
    <label>Months</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Meetings__c/Meetings__c.object-meta.xml
<CustomObject>
    <label>Meetings</label>
    <nameField>
        <displayFormat>M-{000}</displayFormat>
        <label>Meeting Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Meetings__c/fields/Meeting_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Start_Time__c</fullName>
    <label>Meeting Start Time</label>
    <type>DateTime</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Meetings__c/fields/Meeting_Type__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Type__c</fullName>
    <label>Meeting Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mini Meet</fullName>
            </value>
            <value>
                <fullName>Mega Meet</fullName>
            </value>
            <value>
                <fullName>Vikaas Awards</fullName>
            </value>
            <value>
                <fullName>Wives Connect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Meetings__c/fields/Plumber_Club__c.field-meta.xml
<CustomField>
    <fullName>Plumber_Club__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Plumber club</label>
    <referenceTo>Plumber_club__c</referenceTo>
    <relationshipLabel>Meetings</relationshipLabel>
    <relationshipName>Meetings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Plumber_club__c/Plumber_club__c.object-meta.xml
<CustomObject>
    <label>Plumber club</label>
    <nameField>
        <label>Plumber club Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plumber club</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/MultiSelectController.cls
/* Controller called from components MultiSelectUsageDemo and  MultiSelect */
public with sharing class MultiSelectController {
    /* Fetch meeting type from given recordId and month from custom metda data for given meeting type*/
    
	@AuraEnabled
    public static String fetchMeetingTypeMonth(String recordId){
        Meetings__c m =  [select Id, Meeting_Type__c from Meetings__C where id=: recordId limit 1];
        String meetingType = m.Meeting_Type__c;
        Integer month = MultiSelectController.fetchMeetingAttendeeFilter(meetingType);
        String typeMonth = meetingType+':'+month;
        return typeMonth;
    }    
    
    /* Method called from  MultiSelectUsageDemoController.js
     * It fetches final  account list to be shown in dropdown list
	*/
	@AuraEnabled
    public static List<Account> fetchAccounts(String recordId){
        Meetings__c m =  [select Id, Name, Plumber_club__c,Meeting_Type__c,Meeting_Start_Time__c from Meetings__C where id=: recordId limit 1];
        String plumberClubId = m.Plumber_club__c;
        String meetingType = m.Meeting_Type__c;
        Date meetingStartDate = Date.valueOf(m.Meeting_Start_Time__c);
        System.debug('Plumber CLub: '+ plumberClubId +' Meeting Type: '+meetingType +' Meeting Start Date: '+meetingStartDate);
        List<Account> acc = new List<Account>();
        if(plumberClubId != null){
            acc = [select Id, Name from Account where Plumber_club__c=:plumberClubId];
        }
        
        
        Integer month = MultiSelectController.fetchMeetingAttendeeFilter(meetingType);
        System.debug('Month from Custom Metadata type: '+ month);
        
        List<Account> finalAccList = MultiSelectController.fetchAccoountsFromMeetingAttendee(meetingType,month,meetingStartDate,acc);
        
       	return finalAccList;
        
         // return acc;
        
    }
    
    /*fetch month value from custome metadata type */
    @AuraEnabled
    public static Integer fetchMeetingAttendeeFilter(String meetingType){
        Integer month;
        MeetingAttendeeFilter__mdt mAF = [SELECT MasterLabel, QualifiedApiName, Meeting_Type__c,Months__c FROM 	MeetingAttendeeFilter__mdt where Meeting_Type__c=: meetingType];
		System.debug(mAF.Meeting_Type__c + '=> '+ mAF.Months__c);
        month = Integer.valueOf(mAF.Months__c);
        return month;
    }
    
    /* fetch list of attended accounts from meeting attendee object for specified months */
    @AuraEnabled
    public static List<Account> fetchAccoountsFromMeetingAttendee(String meetingType, Integer month, Date meetingStartDate, List<Account> allAccounts){
        Date earlierDate = meetingStartDate.addMonths(-month);
        System.debug('Start Date: '+meetingStartDate +' Earlier: '+earlierDate);
        List<Meeting_Atendee__c> maAccList = [SELECT Account__c, Meeting_Attended_Date__c,Meeting_Attendee_Status__c,Meeting_Type__c FROM Meeting_Atendee__c where 
                                Meeting_Attendee_Status__c='Attended' and Meeting_Type__c =:meetingType and Meeting_Attended_Date__c >=: earlierDate and Meeting_Attended_Date__c <=: meetingStartDate];
        System.debug('Accounts from MeetingAttendee: '+ maAccList);
        Map<Id,Meeting_Atendee__c> mapAcc = new Map<Id,Meeting_Atendee__c>();
        for(Meeting_Atendee__c ma : maAccList){
            mapAcc.put(ma.Account__c,ma);
        }
        System.debug('Records in Map: '+mapAcc);
        List<Account> finalAccList = new List<Account>();
        for(Account ac:allAccounts){
            if(mapAcc.containsKey(ac.Id)){
                System.debug('#### Duplicate account found '+ ac.Id +' Name: '+ac.Name);
            }else{
                finalAccList.add(ac);
            }
        }
        return finalAccList;
    }
    
    
    /* Method called from  MultiSelectController.js */
    @AuraEnabled
    public static void addAccountsToMeetingAttendee(String recordId, List<Account> accountList){
        System.debug('Meeting record ID: ' + recordId);
        for(Account ac : accountList){
            System.debug('New Account Id: '+ac.Id +' => Name: '+ac.Name);
        }

        Map<Id,Meeting_Atendee__c> mapAcc = new Map<Id,Meeting_Atendee__c>();
        List<Meeting_Atendee__c> accList = [select Account__c from Meeting_Atendee__c where Meetings__c=: recordId];
        for(Meeting_Atendee__c ma : accList){
            mapAcc.put(ma.Account__c,ma);
        }
        System.debug('Records in Map: '+mapAcc);

        List<Meeting_Atendee__c> maList = new List<Meeting_Atendee__c>();
        for(Account ac:accountList){
            if(mapAcc.containsKey(ac.Id)){
                System.debug('Duplicate account found '+ ac.Id +' Name: '+ac.Name);
            }else{
            	Meeting_Atendee__c ma = new Meeting_Atendee__c(Meetings__c=recordId, Account__c=ac.Id);
            	maList.add(ma);
            }
        }
        if(maList.size() > 0){
          insert maList;
        }
        System.debug('Number of records added: '+ maList.size());

    }
}