Partial_14Dec2021/force-app/main/default/objects/Meeting_Atendee__c/Meeting_Atendee__c.object-meta.xml
<CustomObject>
    <label>Meeting Attendee</label>
    <nameField>
        <displayFormat>MA-{000}</displayFormat>
        <label>Attendee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meeting Attendees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Meeting_Atendee__c/fields/Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Reason__c</fullName>
    <label>Rejection Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Not Feeling Well</fullName>
            </value>
            <value>
                <fullName>Have some other work</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/RejectionReasonPickList.cls
@RestResource(urlMapping='/rejection-reason-picklist/*')
global class RejectionReasonPickList {
    // View Class to obtain Rejection Reason Picklist values from MeetingAttendee Table.

    @HttpGet
    global static Map<String, List<String>> getAddress(){
        Map<String, List<String>> result = new Map<String, List<String>>();

        try{
                String objectName = 'meeting_atendee__c';
                String rejectionReason ='Rejection_Reason__c';
                Schema.SObjectType s = Schema.getGlobalDescribe().get(objectName) ;
                Schema.DescribeSObjectResult r = s.getDescribe() ;
                Map<String,Schema.SObjectField> fields = r.fields.getMap() ;
                 //Obtain Rejection Reason Picklist Values
                Schema.DescribeFieldResult fieldResult = fields.get(rejectionReason).getDescribe();
                List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
                List<String> rejectionReasonResult = new List<String>();
                for( Schema.PicklistEntry pickListVal : ple){
                    rejectionReasonResult.add(pickListVal.getLabel());
                }
                
                result.put('rejectionReason',rejectionReasonResult);
                return result;
            }
            catch(Exception  e){
                System.debug('error occured while fetching address picklist'+e.getMessage());
                return null;
            }
    }
}