Partial_14Dec2021/force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Promotion No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/Promotion_Member__c.object-meta.xml
<CustomObject>
    <label>Promotion Member</label>
    <nameField>
        <displayFormat>PM-{YY}-{MM}-{DD}-{00}</displayFormat>
        <label>Promotion Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Promotion_Members1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Call_Status__c.field-meta.xml
<CustomField>
    <fullName>Call_Status__c</fullName>
    <label>Call Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Reachable</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>RNR</fullName>
            </value>
            <value>
                <fullName>Wrong/Invalid Number</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Person not available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Promotions2__c.field-meta.xml
<CustomField>
    <fullName>Promotions2__c</fullName>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipName>Promotion_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/ToDeactivateAccountOnInvalicPhoneNo_Test.cls
@isTest
public class ToDeactivateAccountOnInvalicPhoneNo_Test{
    public static testmethod void PromoMemberMethod(){
         Account newAccount = new Account(
                                Name  = 'Test Name',
                                BillingState = 'Gujarat',
                                BillingStreet = 'Abc Street',
                                BillingCity = 'Abc City',
                                BillingCountry = 'India',
                                AccountNumber = '12345',
                                Contact_Number_Mobile__c = '9876543210'
                                );
        insert newAccount;
        Promotion__c pm = new Promotion__c();
        insert pm;
        Promotion_Member__c pmem1 = new Promotion_Member__c(Account__c = newAccount.ID, Promotions2__c = pm.ID, Call_Status__c = 'RNR');
        insert pmem1;
        Promotion_Member__c pmem2 = new Promotion_Member__c(ID = pmem1.ID, Call_Status__c = 'Wrong/Invalid Number');
        update pmem2;   
    }//end of PromoMemberMethod
}//end of class