Partial_14Dec2021/force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Promotion No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Advance_Received__c.field-meta.xml
<CustomField>
    <fullName>Advance_Received__c</fullName>
    <description>Advance received from Ashirvad in rupees</description>
    <inlineHelpText>Advance received from Ashirvad in rupees</inlineHelpText>
    <label>Advance Received</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Amount_spent_by_the_dealer__c.field-meta.xml
<CustomField>
    <fullName>Amount_spent_by_the_dealer__c</fullName>
    <description>Amount spent by the dealer in rupees</description>
    <inlineHelpText>Amount spent by the dealer in rupees</inlineHelpText>
    <label>Amount spent by the dealer</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Call_Center_Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Call_Center_Person_Name__c</fullName>
    <label>Call Center Person Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Call Center Executive 1</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 2</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 3</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 4</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 5</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 6</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 7</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 8</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 9</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 10</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 11</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 12</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 13</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 14</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 15</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 16</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 17</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 18</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 19</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 20</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 21</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 22</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 23</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 24</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 25</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 26</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 27</fullName>
            </value>
            <value>
                <fullName>Call Center Executive 28</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Company_Share__c.field-meta.xml
<CustomField>
    <fullName>Company_Share__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Company Share</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Credit_Note__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note__c</fullName>
    <description>Credit Note amount to dealer in rupees</description>
    <inlineHelpText>Credit Note amount to dealer in rupees</inlineHelpText>
    <label>Credit Note amount to Dealer</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Dealer1__c.field-meta.xml
<CustomField>
    <fullName>Dealer1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Party_Type__c</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Promotions (Dealer)</relationshipLabel>
    <relationshipName>Promotions_New</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Dealer_share__c.field-meta.xml
<CustomField>
    <fullName>Dealer_share__c</fullName>
    <label>Dealer share</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Party_Type__c</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Existing</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Promotions (Distributor)</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <formula>Owner:User.EmployeeNumber</formula>
    <label>Employee Number</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Actual Location</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Percent_of_attendees__c.field-meta.xml
<CustomField>
    <fullName>Percent_of_attendees__c</fullName>
    <formula>if(OR(Actual_No_of_Members__c ==0 ,Total_no_of_attendees__c ==0),0,Actual_No_of_Members__c  /  Total_no_of_attendees__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Percent of attendees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Taluka__c.field-meta.xml
<CustomField>
    <fullName>Taluka__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Taluka</label>
    <referenceTo>AP_Taluk_Master__c</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/TL_Manager__c.field-meta.xml
<CustomField>
    <fullName>TL_Manager__c</fullName>
    <formula>CreatedBy.Manager_Name__c</formula>
    <label>TL/Manager</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Total_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Total_Expenses__c</fullName>
    <label>Total Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Total_no_of_attendees__c.field-meta.xml
<CustomField>
    <fullName>Total_no_of_attendees__c</fullName>
    <label>No. of members attended</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Architects / Engineers / Consultants Factory Visit</fullName>
            </value>
            <value>
                <fullName>Architects Meets</fullName>
            </value>
            <value>
                <fullName>Boarers Meets</fullName>
            </value>
            <value>
                <fullName>Builders Meets</fullName>
            </value>
            <value>
                <fullName>Column Dealer / Distributor Meets</fullName>
            </value>
            <value>
                <fullName>Column Distributors / Dealers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Column DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Engineers Meets</fullName>
            </value>
            <value>
                <fullName>Exhibition / Agri Fairs</fullName>
            </value>
            <value>
                <fullName>Exhibition / Construction Fairs</fullName>
            </value>
            <value>
                <fullName>Group Activity</fullName>
            </value>
            <value>
                <fullName>Inshop Boarers Meets</fullName>
            </value>
            <value>
                <fullName>Inshop Mechanic Meets</fullName>
            </value>
            <value>
                <fullName>Inshop Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Jeep Campaign</fullName>
            </value>
            <value>
                <fullName>Mechanics Factory Visit</fullName>
            </value>
            <value>
                <fullName>Mega Farmer Meets</fullName>
            </value>
            <value>
                <fullName>Mega Mechanic Meets</fullName>
            </value>
            <value>
                <fullName>Mega Plumbers Meets</fullName>
            </value>
            <value>
                <fullName>Mini Farmer Meet</fullName>
            </value>
            <value>
                <fullName>Naaka Meets</fullName>
            </value>
            <value>
                <fullName>Onsite Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Plumbers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealer / Distributor Meets</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealers Factory Visits</fullName>
            </value>
            <value>
                <fullName>Plumbing DSM Meet/Training</fullName>
            </value>
            <value>
                <fullName>Product Presentation</fullName>
            </value>
            <value>
                <fullName>Projects DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Shandy Shows</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/PromotionExpenseTable__c/PromotionExpenseTable__c.object-meta.xml
<CustomObject>
    <description>to use in promotion page .</description>
    <label>PromotionExpenseTable</label>
    <nameField>
        <label>PromotionExpenseTable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PromotionExpenseTables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/PromotionExpenseTable__c/fields/Dealer_share__c.field-meta.xml
<CustomField>
    <fullName>Dealer_share__c</fullName>
    <label>Dealer share</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/PromotionExpenseTable__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <description>look up to promotions</description>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>PromotionExpenseTables</relationshipLabel>
    <relationshipName>PromotionExpenseTables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/NewPromotionPDFController.cls
/*
************XXX*********************

    Developer       :Balagopal G.
    Class Name       :NewPromotionPDFController
    version         :1.0
    Date            :17-Feb-2017
    Modified Date   :22-Feb-2017
    Description     : For Promotion Details from visit entry page in Target
     
****************XXX**********************
*/
public class NewPromotionPDFController{
    public string promoId;
    public boolean showPDF {get;set;}

    public Promotion__c promoRecord{get;set;} 
    public List<PromotionExpenseTable__c> promoExpenseTableRecords{get;set;} 
    public NewPromotionPDFController(){ 
        showPDF =false;
        promoId=ApexPages.currentPage().getParameters().get('id');
        system.debug('Promotion id from page::::'+promoId);
        promoRecord=[select Name,Percent_of_attendees__c,District__c,Location__c,
                     Taluka__r.Name,Type__c,Date__c,Total_no_of_attendees__c,Total_Expenses__c,
                     Dealer1__r.Name,Distributor__r.Name,Owner.Name,Employee_Number__c
                     ,Call_Center_Person_Name__c,Verified__c ,
                     Credit_Note__c,Amount_spent_by_the_dealer__c,Advance_Received__c,Dealer_Share__c
                     ,Company_Share__c,TL_Manager__c from Promotion__c where Id=:promoId];
        promoExpenseTableRecords=[select Nature_of_Expenditure__c ,Total_Expenses__c,APPL_Share__c,Dealer_share__c,Remarks__c from PromotionExpenseTable__c where Promotion__c=:promoId];
            if(promoRecord.Percent_of_attendees__c>=70){
                showPDF =True;
            }
        
    }

}