Partial_14Dec2021/force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Promotion No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Difference__c.field-meta.xml
<CustomField>
    <fullName>Difference__c</fullName>
    <formula>TODAY() - Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Difference</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/NewPromotionApex.cls
/******************************************
 * Created By  : Ajeet Singh Shekhawat
 * Created On  : 03 Sep 2018
 * Modified By : 
 * Modified On : 03 Sep 2018
 * Description : fetch Difference__c from particular record id of Promotion__c object.
				
******************************************/ 
public class NewPromotionApex {
	@AuraEnabled
    public static Decimal fetchPromotionRecord (Id accountId) {
        try {
            Decimal difference;
            List<Promotion__c> promoList;
            promoList = [select Difference__c from Promotion__c where Id =: accountId];
            difference = promoList[0].Difference__c;
            System.debug('difference ' + difference);
            return difference;
        } catch (Exception ex){
            throw new AuraHandledException('Something went wrong: '+ ex.getMessage());
         } 
        
    }
}