Partial_14Dec2021/force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Promotion No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Party_Type__c</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Existing</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Promotions (Distributor)</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Actual Location</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhatisgarh</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Pondicherry</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttaranchal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Total_Expenses__c.field-meta.xml
<CustomField>
    <fullName>Total_Expenses__c</fullName>
    <label>Total Expenses</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Total_no_of_attendees__c.field-meta.xml
<CustomField>
    <fullName>Total_no_of_attendees__c</fullName>
    <label>No. of members attended</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Architects / Engineers / Consultants Factory Visit</fullName>
            </value>
            <value>
                <fullName>Architects Meets</fullName>
            </value>
            <value>
                <fullName>Boarers Meets</fullName>
            </value>
            <value>
                <fullName>Builders Meets</fullName>
            </value>
            <value>
                <fullName>Column Dealer / Distributor Meets</fullName>
            </value>
            <value>
                <fullName>Column Distributors / Dealers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Column DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Engineers Meets</fullName>
            </value>
            <value>
                <fullName>Exhibition / Agri Fairs</fullName>
            </value>
            <value>
                <fullName>Exhibition / Construction Fairs</fullName>
            </value>
            <value>
                <fullName>Group Activity</fullName>
            </value>
            <value>
                <fullName>Inshop Boarers Meets</fullName>
            </value>
            <value>
                <fullName>Inshop Mechanic Meets</fullName>
            </value>
            <value>
                <fullName>Inshop Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Jeep Campaign</fullName>
            </value>
            <value>
                <fullName>Mechanics Factory Visit</fullName>
            </value>
            <value>
                <fullName>Mega Farmer Meets</fullName>
            </value>
            <value>
                <fullName>Mega Mechanic Meets</fullName>
            </value>
            <value>
                <fullName>Mega Plumbers Meets</fullName>
            </value>
            <value>
                <fullName>Mini Farmer Meet</fullName>
            </value>
            <value>
                <fullName>Naaka Meets</fullName>
            </value>
            <value>
                <fullName>Onsite Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Plumbers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealer / Distributor Meets</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealers Factory Visits</fullName>
            </value>
            <value>
                <fullName>Plumbing DSM Meet/Training</fullName>
            </value>
            <value>
                <fullName>Product Presentation</fullName>
            </value>
            <value>
                <fullName>Projects DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Shandy Shows</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/ContentDocTrigger_Test.cls
/* ***************************************************************************************
Created By    : Srilakshmi, KVP Business Solutions
Description   : Test class for ContentDocTrigger
******************************************************************************************** */
@isTest

public class ContentDocTrigger_Test{
    private static Account dis1;
    
    
    static testmethod void method_1(){
        try {
            dis1 = Initial_Test_Data.createAccount('test Account1','Individual Contacts');
            dis1.Contact_Number_Mobile__c ='7259582222'; 
            dis1.Party_Type__c = 'Distributor';
            dis1.Status__c = 'Existing';
            dis1.Ramco_ID__c = 'abc123';
            insert dis1;
            
            Promotion__c prm = new Promotion__c();            
            prm.Date__c=System.today();
            prm.Type__c='Dealers Meet';
            prm.Total_Expenses__c = 1000;
            prm.Total_no_of_attendees__c = 0;
            prm.State__c = 'Karnataka';
            prm.Location__c = 'BTM';
            prm.Distributor__c=dis1.id;
            insert prm; 
            
            system.assert(prm.id != null);
            
            ContentVersion cver = new ContentVersion();
            cver.ContentLocation = 'S';
            cver.VersionData = Blob.valueOf('Unit Test Attachment Body');
            cver.PathOnClient = 'Retailer.png';
            cver.Title = 'Retailer Image';
            insert cver;     
            
            ContentVersion contentVersion = new ContentVersion(
                Title = 'Penguins',
                PathOnClient = 'Penguins.jpg',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true
            );
            insert contentVersion;
            
            ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cver.Id];
            ContentVersion testContent1 = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :contentVersion.Id];
            
            Promotion__c promo = [select id from Promotion__c where id=:prm.id];
            
            //create ContentDocumentLink  record 
            ContentDocumentLink cdl = New ContentDocumentLink();
            cdl.LinkedEntityId = prm.Id;  // a0a2F000002whylQAA
            cdl.ContentDocumentId = testcontent.ContentDocumentId;
            cdl.shareType = 'V';
            insert cdl; 
            
            //create ContentDocumentLink  record 
            ContentDocumentLink cd2 = New ContentDocumentLink();
            cd2.LinkedEntityId = prm.Id;  // a0a2F000002whylQAA
            cd2.ContentDocumentId = testcontent1.ContentDocumentId;
            cd2.shareType = 'V';
            insert cd2; 
            
            List<ContentDocument> cdoc = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument where id=:testcontent.ContentDocumentId];
            
            delete cdoc;
            
        } catch(Exception ex) {
            System.debug('Exception Test ' + ex);
            System.debug('Exception Test1 ' + ex.getMessage());
        }       
    }
     static testmethod void method_2(){
        try {
            Account  dis2 = new Account();
         
            dis2.Name='testee';
            //dis2.recordtype.name='Individual Contacts';
           dis2.RecordTypeId='01230000001DIm0AAG';
            dis2.Contact_Number_Mobile__c ='7259582223'; 
            dis2.Party_Type__c = 'Plumber';
            dis2.Status__c = 'Existing';
            dis2.Ramco_ID__c = 'abc123';
            dis2.Count_Attachment__c=2;
            insert dis2;
            
            system.assert(dis2.id != null);
            
            ContentVersion cver = new ContentVersion();
            cver.ContentLocation = 'S';
            cver.VersionData = Blob.valueOf('Unit Test Attachment Body');
            cver.PathOnClient = 'Retailer.png';
            cver.Title = 'Retailer Image';
            insert cver;     
            
            ContentVersion contentVersion = new ContentVersion(
                Title = 'Penguins',
                PathOnClient = 'Penguins.jpg',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true
            );
            insert contentVersion;
            
            ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cver.Id];
            ContentVersion testContent1 = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :contentVersion.Id];
            
           // Promotion__c promo = [select id from Promotion__c where id=:prm.id];
       
            Account acc=[select id from Account where ID =:dis2.id];
            
            //create ContentDocumentLink  record 
            ContentDocumentLink cdl = New ContentDocumentLink();
            cdl.LinkedEntityId = dis2.Id;  // a0a2F000002whylQAA
            cdl.ContentDocumentId = testcontent.ContentDocumentId;
            cdl.shareType = 'V';
            insert cdl; 
            
            //create ContentDocumentLink  record 
            ContentDocumentLink cd2 = New ContentDocumentLink();
            cd2.LinkedEntityId = dis2.Id;  // a0a2F000002whylQAA
            cd2.ContentDocumentId = testcontent1.ContentDocumentId;
            cd2.shareType = 'V';
            insert cd2; 
            
            List<ContentDocument> cdoc = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument where id=:testcontent.ContentDocumentId];
            
            delete cdoc;
            
        } catch(Exception ex) {
            System.debug('Exception Test ' + ex);
            System.debug('Exception Test1 ' + ex.getMessage());
        }       
    }
    
}