Partial_14Dec2021/force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Promotion No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Difference__c.field-meta.xml
<CustomField>
    <fullName>Difference__c</fullName>
    <formula>TODAY() - Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Difference</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Architects / Engineers / Consultants Factory Visit</fullName>
            </value>
            <value>
                <fullName>Architects Meets</fullName>
            </value>
            <value>
                <fullName>Boarers Meets</fullName>
            </value>
            <value>
                <fullName>Builders Meets</fullName>
            </value>
            <value>
                <fullName>Column Dealer / Distributor Meets</fullName>
            </value>
            <value>
                <fullName>Column Distributors / Dealers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Column DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Engineers Meets</fullName>
            </value>
            <value>
                <fullName>Exhibition / Agri Fairs</fullName>
            </value>
            <value>
                <fullName>Exhibition / Construction Fairs</fullName>
            </value>
            <value>
                <fullName>Group Activity</fullName>
            </value>
            <value>
                <fullName>Inshop Boarers Meets</fullName>
            </value>
            <value>
                <fullName>Inshop Mechanic Meets</fullName>
            </value>
            <value>
                <fullName>Inshop Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Jeep Campaign</fullName>
            </value>
            <value>
                <fullName>Mechanics Factory Visit</fullName>
            </value>
            <value>
                <fullName>Mega Farmer Meets</fullName>
            </value>
            <value>
                <fullName>Mega Mechanic Meets</fullName>
            </value>
            <value>
                <fullName>Mega Plumbers Meets</fullName>
            </value>
            <value>
                <fullName>Mini Farmer Meet</fullName>
            </value>
            <value>
                <fullName>Naaka Meets</fullName>
            </value>
            <value>
                <fullName>Onsite Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Plumbers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealer / Distributor Meets</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealers Factory Visits</fullName>
            </value>
            <value>
                <fullName>Plumbing DSM Meet/Training</fullName>
            </value>
            <value>
                <fullName>Product Presentation</fullName>
            </value>
            <value>
                <fullName>Projects DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Shandy Shows</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/AddPromotionalMember.cls
public With sharing class AddPromotionalMember {
@AuraEnabled
    public static list<string> addmember (String PromotionId) {
        system.debug('test2   '+'a0a3000000EpPOAAA3');
        list<string> stringlist=new list<string>();
          string Gtype;
        decimal difference;
        difference = [select Difference__c from Promotion__c where Id =: PromotionId].Difference__c;
        Gtype=[select type__c from Promotion__c where Id =: PromotionId].type__c;
        String stringdifference = String.valueOf(difference.format());
        stringlist.add(stringdifference);
        stringlist.add(Gtype);
        system.debug('test'+stringlist);
        return stringlist;
        
        
    }
    
    
}