Partial_14Dec2021/force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Promotion No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Architects / Engineers / Consultants Factory Visit</fullName>
            </value>
            <value>
                <fullName>Architects Meets</fullName>
            </value>
            <value>
                <fullName>Boarers Meets</fullName>
            </value>
            <value>
                <fullName>Builders Meets</fullName>
            </value>
            <value>
                <fullName>Column Dealer / Distributor Meets</fullName>
            </value>
            <value>
                <fullName>Column Distributors / Dealers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Column DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Engineers Meets</fullName>
            </value>
            <value>
                <fullName>Exhibition / Agri Fairs</fullName>
            </value>
            <value>
                <fullName>Exhibition / Construction Fairs</fullName>
            </value>
            <value>
                <fullName>Group Activity</fullName>
            </value>
            <value>
                <fullName>Inshop Boarers Meets</fullName>
            </value>
            <value>
                <fullName>Inshop Mechanic Meets</fullName>
            </value>
            <value>
                <fullName>Inshop Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Jeep Campaign</fullName>
            </value>
            <value>
                <fullName>Mechanics Factory Visit</fullName>
            </value>
            <value>
                <fullName>Mega Farmer Meets</fullName>
            </value>
            <value>
                <fullName>Mega Mechanic Meets</fullName>
            </value>
            <value>
                <fullName>Mega Plumbers Meets</fullName>
            </value>
            <value>
                <fullName>Mini Farmer Meet</fullName>
            </value>
            <value>
                <fullName>Naaka Meets</fullName>
            </value>
            <value>
                <fullName>Onsite Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Plumbers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealer / Distributor Meets</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealers Factory Visits</fullName>
            </value>
            <value>
                <fullName>Plumbing DSM Meet/Training</fullName>
            </value>
            <value>
                <fullName>Product Presentation</fullName>
            </value>
            <value>
                <fullName>Projects DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Shandy Shows</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/Promotion_Member__c.object-meta.xml
<CustomObject>
    <label>Promotion Member</label>
    <nameField>
        <displayFormat>PM-{YY}-{MM}-{DD}-{00}</displayFormat>
        <label>Promotion Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Promotions2__c.field-meta.xml
<CustomField>
    <fullName>Promotions2__c</fullName>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipName>Promotion_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Type1__c.field-meta.xml
<CustomField>
    <fullName>Type1__c</fullName>
    <label>Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/NewPromotionMemberClass.cls
public with sharing class NewPromotionMemberClass {
  
    public NewPromotionMemberClass (ApexPages.StandardController controller) {
    wrappers=new List<TaskWrapper>();
    for (Integer idx=0; idx<1; idx++)
    {
    wrappers.add(new TaskWrapper(nextIdent++));
    }

    }

    public List<TaskWrapper> wrappers {get; set;}
    public static Integer toDelIdent {get; set;}
    public static Integer addCount {get; set;}
    public id dId;
    private Integer nextIdent=0;

public void delWrapper()
    {
    Integer toDelPos=-1;
        for (Integer idx=0; idx<wrappers.size(); idx++)
        {
            if (wrappers[idx].ident==toDelIdent)
            {
            toDelPos=idx;
            }
        }
    
            if (-1!=toDelPos)
            {
            wrappers.remove(toDelPos);
            }
    }

    public void addRows()
    {
        for (Integer idx=0; idx<addCount; idx++)
        {
        wrappers.add(new TaskWrapper(nextIdent++));
        }
    }
    
    public PageReference save()
    {
        List<Promotion_Member__c> tsks=new List<Promotion_Member__c>();
        for (TaskWrapper wrap : wrappers)
            {
            tsks.add(wrap.tsk);
            }
        
            insert tsks;
            
            return new PageReference('/'+ ApexPages.currentPage().getParameters().get('id'));
        }

    public PageReference cancel()
    { 
            return new PageReference('/'+ ApexPages.currentPage().getParameters().get('id'));
    }
    
    public class TaskWrapper
    {
        public Promotion_Member__c tsk {get; private set;}
        public Integer ident {get; private set;}
        
        public TaskWrapper(Integer inIdent)
        {
            ident=inIdent;
            Promotion__c pm=[select Type__c,id from  Promotion__c where id=:ApexPages.currentPage().getParameters().get('id')];
            System.debug('Id: ' + ApexPages.currentPage().getParameters().get('id'));
            tsk=new Promotion_Member__c(Promotions2__c = ApexPages.currentPage().getParameters().get('id'),Type1__c=pm.Type__c);
        }
    }
}