Partial_14Dec2021/force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Promotion No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Site_Visit__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Site Visit</label>
    <referenceTo>Site_Visit__c</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SVN-{00000000}</displayFormat>
        <label>Site Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/promotionclass.cls
public with sharing class promotionclass {

   
public String sid{get;set;}
    public promotionclass() {
 sid=Apexpages.currentpage().getparameters().get('id');
    prm=new Promotion__c(Site_Visit__c=sid);
    }


   
    public Promotion__c prm{get;set;}
    public PageReference Cancel()
    {
    pageReference p1=new PageReference('/home/home.jsp');
    return p1;
    }
     


    public PageReference quicksave() {
        upsert prm;
        
       pageReference p=new pageReference('/apex/PageforPromotion?id='+sid);
       p.setRedirect(true);
        return p;
    }


    public PageReference save() {
       
       
       insert prm;
   PageReference pr= new PageReference('/'+prm.id);
      pr.setRedirect(true);
       return pr;
       
    }

   

}