Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/AP_Site_Visit__c.object-meta.xml
<CustomObject>
    <label>APPL Site Visit</label>
    <nameField>
        <displayFormat>Visit-{000000}</displayFormat>
        <label>AP Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Adopted_Dealer__c.field-meta.xml
<CustomField>
    <fullName>Adopted_Dealer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Adopted Dealer</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Adopted_Plumber__c.field-meta.xml
<CustomField>
    <fullName>Adopted_Plumber__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Adopted Plumber</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Party_Name__c.field-meta.xml
<CustomField>
    <fullName>Party_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Name/Firm Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Party_Type__c</field>
            <operation>equals</operation>
            <valueField>Account.Party_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Party_RcrdType_Name__c.field-meta.xml
<CustomField>
    <fullName>Party_RcrdType_Name__c</fullName>
    <formula>Party_Name__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Party_RcrdType_Name</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Party_Type__c.field-meta.xml
<CustomField>
    <fullName>Party_Type__c</fullName>
    <label>Party Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Borer</fullName>
            </value>
            <value>
                <fullName>Borewell Office</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Dealers Salesman</fullName>
            </value>
            <value>
                <fullName>Direct Dealer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Farmer</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Institution</fullName>
            </value>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Panchayat Head</fullName>
            </value>
            <value>
                <fullName>Plumber</fullName>
            </value>
            <value>
                <fullName>Plumber Cum Mechanic</fullName>
            </value>
            <value>
                <fullName>Plumbing Contractor</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Project Owner/Developer</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
            <value>
                <fullName>Purchase Manager</fullName>
            </value>
            <value>
                <fullName>Site Engineer</fullName>
            </value>
            <value>
                <fullName>Site Incharge / Supervisor</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Winders</fullName>
            </value>
            <value>
                <fullName>Plumber club member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/RecordType_Name__c.field-meta.xml
<CustomField>
    <fullName>RecordType_Name__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RecordType_Name</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <description>Target</description>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/recordTypes/Visits.recordType-meta.xml
<RecordType>
    <fullName>Visits</fullName>
    <active>true</active>
    <label>Visits</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Adopted_Dealer_Actual_Count__c.field-meta.xml
<CustomField>
    <fullName>Adopted_Dealer_Actual_Count__c</fullName>
    <label>Adopted Dealer Actual Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Adopted_Plumber_Actual_Count__c.field-meta.xml
<CustomField>
    <fullName>Adopted_Plumber_Actual_Count__c</fullName>
    <label>Adopted Plumber Actual Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/AdoptedPlumberAndDealer.cls
/***********************************************************************************************************************
Created By: Rakesh Mallya
Created Date: 18/05/2018
Description: This trigger handler class calculates Adopted Plumber Actuals and Adopted Dealer Actuals.
***********************************************************************************************************************/
public class AdoptedPlumberAndDealer{
    public static void AdoptedDealerAndPlumberMethod(List<AP_Site_Visit__c> SVtrigger){
        String partyNameDlr;
        List<ID> TgrDlrIdList = new List<ID>();
        Set<ID> TgtDlrIdSet = new Set<ID>();
        ID acntRcrdTyp;
        ID stVstRcrdTyp;
        Boolean AdptDlrChkbx = false;
        Boolean AdptPbrChkbx = false;
        List<Target__c> tgtList = new List<Target__c>();
        List<AP_Site_Visit__c> dlrCnt = new List<AP_Site_Visit__c>();
        List<AP_Site_Visit__c> pbrCnt = new List<AP_Site_Visit__c>();
        List<AP_Site_Visit__c> StVstList = new List<AP_Site_Visit__c>();
        List<AP_Site_Visit__c> StVstListToUpdt = new List<AP_Site_Visit__c>();
        for(AP_Site_Visit__c  apsv : SVtrigger){
            TgrDlrIdList.add(apsv.ID);
            TgtDlrIdSet.add(apsv.Target__c);            
        }
        StVstList.addAll([SELECT ID,Adopted_Dealer__c,Adopted_Plumber__c,RecordTypeID,Party_Name__c,Party_Name__r.RecordTypeID,Party_Name__r.Classification__c,Target__c,Party_RcrdType_Name__c,RecordType_Name__c,Party_Name__r.Party_Type__c,Party_Name__r.Premium_plumber__c FROM AP_Site_Visit__c WHERE Target__c IN: TgtDlrIdSet AND ID IN: TgrDlrIdList]);
        for(AP_Site_Visit__c dlrSV : StVstList){
            if(dlrSV.RecordType_Name__c == 'Visits' && dlrSV.Party_Name__c != NULL && dlrSV.Party_RcrdType_Name__c == 'Dealer' && dlrSV.Party_Name__r.Classification__c == 'Adopted'){
                dlrSV.Adopted_Dealer__c = true;
                StVstListToUpdt.add(dlrSV);
            }else if(dlrSV.RecordType_Name__c == 'Visits' && dlrSV.Party_Name__c != NULL && dlrSV.Party_RcrdType_Name__c == 'Individual Contacts' && dlrSV.Party_Name__r.Party_Type__c == 'Plumber' && dlrSV.Party_Name__r.Premium_plumber__c == 'Yes'){
                dlrSV.Adopted_Plumber__c = true;
                StVstListToUpdt.add(dlrSV);
            }
            system.debug('---------------------------dlrSV.RecordType_Name__c------------'+dlrSV.RecordType_Name__c);
            system.debug('---------------------------dlrSV.Party_Name__c------------'+dlrSV.Party_Name__c);
            system.debug('---------------------------dlrSV.Party_RcrdType_Name__c------------'+dlrSV.Party_RcrdType_Name__c);
            system.debug('---------------------------dlrSV.Party_Name__r.Classification__c------------'+dlrSV.Party_Name__r.Classification__c);    
        }
        
        update StVstListToUpdt;
        
        dlrCnt.addall([SELECT ID FROM AP_Site_Visit__c WHERE Target__c IN: TgtDlrIdSet AND Adopted_Dealer__c = true]);
        pbrCnt.addall([SELECT ID FROM AP_Site_Visit__c WHERE Target__c IN: TgtDlrIdSet AND Adopted_Plumber__c = true]);
        if(dlrCnt.size() > 0 || pbrCnt.size() > 0){
            for(Target__c tar : [SELECT ID,Adopted_Dealer_Actual_Count__c,Adopted_Plumber_Actual_Count__c FROM Target__c WHERE ID IN: TgtDlrIdSet]){
                tar.Adopted_Dealer_Actual_Count__c = dlrCnt.size();
                tar.Adopted_Plumber_Actual_Count__c = pbrCnt.size();
                tgtList.add(tar);
            }
        }
        system.debug('---------------------------tgtList------------'+tgtList);
        system.debug('---------------------------dlrCnt.size()------------'+dlrCnt.size()); 
        update tgtList;      
    }//end of AdoptedDealerAndPlumberMethod   
}//end of AdoptedPlumberAndDealsver