Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/AP_Site_Visit__c.object-meta.xml
<CustomObject>
    <label>APPL Site Visit</label>
    <nameField>
        <displayFormat>Visit-{000000}</displayFormat>
        <label>AP Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Party_Name__c.field-meta.xml
<CustomField>
    <fullName>Party_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Name/Firm Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Party_Type__c</field>
            <operation>equals</operation>
            <valueField>Account.Party_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Party_Type__c.field-meta.xml
<CustomField>
    <fullName>Party_Type__c</fullName>
    <label>Party Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Borer</fullName>
            </value>
            <value>
                <fullName>Borewell Office</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Dealers Salesman</fullName>
            </value>
            <value>
                <fullName>Direct Dealer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Farmer</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Institution</fullName>
            </value>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Panchayat Head</fullName>
            </value>
            <value>
                <fullName>Plumber</fullName>
            </value>
            <value>
                <fullName>Plumber Cum Mechanic</fullName>
            </value>
            <value>
                <fullName>Plumbing Contractor</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Project Owner/Developer</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
            <value>
                <fullName>Purchase Manager</fullName>
            </value>
            <value>
                <fullName>Site Engineer</fullName>
            </value>
            <value>
                <fullName>Site Incharge / Supervisor</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Winders</fullName>
            </value>
            <value>
                <fullName>Plumber club member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Target_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Target_Vertical__c</fullName>
    <formula>AP_Tour_Plan__r.Target_Vertical__c</formula>
    <label>Target Vertical</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/firmSearchClass.cls
public class firmSearchClass {
public Account accField{get;set;}
public list <AP_Site_Visit__c> accList{get;set;}
public set<AP_Site_Visit__c> firmname{get;set;}
public Boolean displayTable{get;set;}
public string firmclass{get;set;}
public static final string account_RTYPE = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Individual Contacts').getRecordTypeId();

 public firmSearchClass(){
  accField= new Account();
  accList= new list<AP_Site_Visit__c>();
  firmname = new set<AP_Site_Visit__c>();
  displayTable=false;
  
  }
  
  public  pagereference searchFirm(){
  
  if(accField.Firm_Name__c == null || accField.Firm_Name__c =='' ){
   ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please enter a Firm Name ')); 
   displayTable=false;
  accList= new list<AP_Site_Visit__c>();
  
   }
   
  if(accField.Firm_Name__c <> null && accField.Firm_Name__c <>'' ){
   displayTable=true;
   system.debug('firmname :'+accField.Firm_Name__c);
   
   string fname='%'+accField.Firm_Name__c+'%';
   //accList= [select Id,Name from Account where Firm_Name__c=: accField.Firm_Name__c and recordTypeid=:account_RTYPE];
  accList=[select id,Name,Party_Name__r.Id,Party_Name__r.Name,Target_Vertical__c,Party_Type__c,Party_Name__r.Firm_Name__c from AP_Site_Visit__c where Party_Name__r.Firm_Name__c like :fname and Party_Name__r.recordTypeid=:account_RTYPE];
   firmname.addall(accList);
 
   system.debug('accList:'+accList);
  if(accList.isEmpty()){
    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Info,'No results found')); 
    displayTable=false;
  }
 }
 
  return null;
}
}