Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/AP_Site_Visit__c.object-meta.xml
<CustomObject>
    <label>APPL Site Visit</label>
    <nameField>
        <displayFormat>Visit-{000000}</displayFormat>
        <label>AP Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/AP_Tour_Plan__c.field-meta.xml
<CustomField>
    <fullName>AP_Tour_Plan__c</fullName>
    <label>Tour Plan</label>
    <referenceTo>AP_Tour_Plan__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Party_Type__c.field-meta.xml
<CustomField>
    <fullName>Party_Type__c</fullName>
    <label>Party Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Borer</fullName>
            </value>
            <value>
                <fullName>Borewell Office</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Dealers Salesman</fullName>
            </value>
            <value>
                <fullName>Direct Dealer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Farmer</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Institution</fullName>
            </value>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Panchayat Head</fullName>
            </value>
            <value>
                <fullName>Plumber</fullName>
            </value>
            <value>
                <fullName>Plumber Cum Mechanic</fullName>
            </value>
            <value>
                <fullName>Plumbing Contractor</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Project Owner/Developer</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
            <value>
                <fullName>Purchase Manager</fullName>
            </value>
            <value>
                <fullName>Site Engineer</fullName>
            </value>
            <value>
                <fullName>Site Incharge / Supervisor</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Winders</fullName>
            </value>
            <value>
                <fullName>Plumber club member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <description>Target</description>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/AP_Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>APPL Tour Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>AP TourPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPL Tour Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>APPL Tour Plans</relationshipLabel>
    <relationshipName>AP_TourPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/No_of_Visits_Actual_Project__c.field-meta.xml
<CustomField>
    <fullName>No_of_Visits_Actual_Project__c</fullName>
    <label>No of Visits Actual(Project)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/test_NoOfProjectVisitRollUp_Batch.cls
@isTest
public class test_NoOfProjectVisitRollUp_Batch{
    public static User userdata;
     @isTest static void testmethodbatch(){
    Test.startTest();
     AP_Tour_Plan__c a1 = new AP_Tour_Plan__c();
      insert a1;
       target__c tc=new target__C(No_of_Visits_Actual_Project__c=7);
       
      
       insert tc;
         system.debug('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'+tc.No_of_Visits_Actual_Project__c);
         AP_Site_Visit__c visit1= new AP_Site_Visit__c(AP_Tour_Plan__c=a1.id,target__c=tc.id,Party_type__C='farmer' );
     
       insert visit1;
      userdata= Initial_Test_Data.createUser('test111','test','BD');
       userdata.EmployeeNumber='123';
       userdata.id=a1.ownerid;
       insert userdata;
       
          Map<id, AP_Site_Visit__c> visitmap= new Map<id, AP_Site_Visit__c>();
          visitmap.put(userdata.id,visit1);
         visitmap.get(userdata.id);
    

          NoOfProjectVisitRollUp_Batch obj = new NoOfProjectVisitRollUp_Batch ();
            DataBase.executebatch(obj); 
            
        
        
     
     NoOfProjectVisitRollUp_scheduler abc = new NoOfProjectVisitRollUp_scheduler ();
      String sch = '0 0 10 1/1 * ? *'; //schedule interval time
        system.schedule('ProjectVisitWarningmail',sch , abc); //system method to schedule apex class
        
         Test.stopTest();

  }
}