Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/AP_Site_Visit__c.object-meta.xml
<CustomObject>
    <label>APPL Site Visit</label>
    <nameField>
        <displayFormat>Visit-{000000}</displayFormat>
        <label>AP Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Actual_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Created_Date__c</fullName>
    <label>Actual Created Date</label>
    <type>DateTime</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Actual_LastModified_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_LastModified_Date__c</fullName>
    <label>Actual LastModified Date</label>
    <type>DateTime</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Order_Value__c.field-meta.xml
<CustomField>
    <fullName>Order_Value__c</fullName>
    <label>Order Value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Othet_Activities__c.field-meta.xml
<CustomField>
    <fullName>Othet_Activities__c</fullName>
    <label>Other Activities</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exhibitions/Shows</fullName>
            </value>
            <value>
                <fullName>Depot Meet/Office Meet</fullName>
            </value>
            <value>
                <fullName>Holiday/ Market Closed</fullName>
            </value>
            <value>
                <fullName>Leave</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Promotional Activity</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Post Visit Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Purpose_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Purpose_of_Visit__c</fullName>
    <label>Purpose of Visit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Party_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Approval for Ashirvad Brand</fullName>
            </value>
            <value>
                <fullName>Building Relationship</fullName>
            </value>
            <value>
                <fullName>Complaints-Aqua</fullName>
            </value>
            <value>
                <fullName>Complaints-column</fullName>
            </value>
            <value>
                <fullName>Complaints-CPVC</fullName>
            </value>
            <value>
                <fullName>Complaints-SWR</fullName>
            </value>
            <value>
                <fullName>Dispatch</fullName>
            </value>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Follow Up</fullName>
            </value>
            <value>
                <fullName>Market Survey</fullName>
            </value>
            <value>
                <fullName>New Order Booking</fullName>
            </value>
            <value>
                <fullName>Order Follow Up</fullName>
            </value>
            <value>
                <fullName>Payment Follow Up</fullName>
            </value>
            <value>
                <fullName>Product Presentation</fullName>
            </value>
            <value>
                <fullName>Attending Complaint</fullName>
            </value>
            <value>
                <fullName>Recce</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Survey/Audit</fullName>
            </value>
            <value>
                <fullName>Give for Print/Print Delivery</fullName>
            </value>
            <value>
                <fullName>Courtesy Call</fullName>
            </value>
            <value>
                <fullName>Repair/Rework</fullName>
            </value>
            <value>
                <fullName>Events / Exhibitions</fullName>
            </value>
            <value>
                <fullName>Design Development</fullName>
            </value>
            <value>
                <fullName>Facility Visit/Vendor Evaluation</fullName>
            </value>
            <value>
                <fullName>Review Meet</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Promotional activity</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <description>Target</description>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/recordTypes/Visits.recordType-meta.xml
<RecordType>
    <fullName>Visits</fullName>
    <active>true</active>
    <label>Visits</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/visit_with_new_order_booking__c.field-meta.xml
<CustomField>
    <fullName>visit_with_new_order_booking__c</fullName>
    <label>visit with new order booking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/ProductiveVisitWithOrders.cls
/***************************************************
 * Name:SudhaMurthy
 * Description: class to create count  and sum of visits on target
 * Trigger:AdoptedPlumberAndDealer 
 * created date :22/22/2018***********************/



public class ProductiveVisitWithOrders {
      
    public static void neworderbooking(list<AP_Site_Visit__c> visitlist){
        list<target__c> newtargetlisttoupdate = new list<target__C>();
        system.debug('test for trigegr.ner........'+visitlist);
        //system.debug('test for trigegr.old........'+oldvisitlist);
        
        set<id> visitset= new set<id>();
        if(!visitlist.isempty() && visitlist!=null){
            for(AP_Site_Visit__c apvisit :visitlist) {
                if(apvisit.target__C!=null){
                    visitset.add(apvisit.target__C);
                    system.debug('test for set after insert........'+visitset);
                }
            }
        }  
           
        list<Target__C> targetlist=  new list<target__C>([select id,name,visit_with_new_order_booking__c,(select id,name,Purpose_of_Visit__c,Order_Value__c,Othet_Activities__c from AP_Site_Visits__r where (Purpose_of_Visit__c='New Order Booking' or Othet_Activities__c='Post Visit Order') and Order_Value__c>0) from Target__C where id in:visitset limit 999]);
            for(Target__C targets:Targetlist){
                target__C newtarget = new target__C();
                newtarget.id= targets.id;
                newtarget.visit_with_new_order_booking__c=targets.AP_Site_Visits__r.size();
                newtargetlisttoupdate.add(newtarget);
                                
            }
         
        if(!newtargetlisttoupdate.isempty() && newtargetlisttoupdate.size()>0 && newtargetlisttoupdate!=null){
            try{
            update newtargetlisttoupdate;
            }catch(System.Exception e){
                
            }    
            
        }

    }
    public static void neworderbookingforupdate(map<id,AP_Site_Visit__c> oldmapvisit,list<AP_Site_Visit__c> newlist){
               list<target__c> newtargetlisttoupdate = new list<target__C>();
        set<id> visitset2= new set<id>();
        system.debug('newlist'+newlist);
        if(!newlist.isempty()){
                for(AP_Site_Visit__c apvisitold :newlist) {
                    system.debug('test new id'+apvisitold);
                    
                    if((apvisitold.Actual_Created_Date__c!=oldmapvisit.get(apvisitold.id).Actual_Created_Date__c) || (apvisitold.Actual_LastModified_Date__c!=oldmapvisit.get(apvisitold.id).Actual_LastModified_Date__c)){
                    
                    
                    }else if(apvisitold.Target__c!=null){
                        visitset2.add(apvisitold.target__C);
                    }
                    system.debug('set id'+visitset2);
                }
           } 
    
     list<Target__C> targetlist=  new list<target__C>([select id,name,visit_with_new_order_booking__c,(select id,name,Purpose_of_Visit__c,Order_Value__c,Othet_Activities__c,Actual_Created_Date__c,Actual_LastModified_Date__c from AP_Site_Visits__r where (Purpose_of_Visit__c='New Order Booking' or Othet_Activities__c='Post Visit Order') and Order_Value__c>0) from Target__C where id in:visitset2 limit 999]);
            for(Target__C targets:Targetlist){
                target__C newtarget = new target__C();
                newtarget.id= targets.id;
                newtarget.visit_with_new_order_booking__c=targets.AP_Site_Visits__r.size();
                newtargetlisttoupdate.add(newtarget);
                                
            }
        system.debug('newtargetlisttoupdate........'+newtargetlisttoupdate);
         
        if(!newtargetlisttoupdate.isempty() && newtargetlisttoupdate.size()>0 && newtargetlisttoupdate!=null){
            try{
            update newtargetlisttoupdate;
            }catch(System.Exception e){
                
            }    
            

    }   

    }
     public static void neworderbookingdelete(list<AP_Site_Visit__c> oldvisitlist){
         list<target__c> newtargetlisttoupdate = new list<target__C>();
        set<id> visitset2= new set<id>();
        if(!oldvisitlist.isempty() && oldvisitlist!=null){
                for(AP_Site_Visit__c apvisitold :oldvisitlist) {
                    if(apvisitold.Target__c!=null){
                    visitset2.add(apvisitold.target__C);
                    system.debug('test for set after update........'+oldvisitlist);
                    }
                }
           } 
    
     list<Target__C> targetlist=  new list<target__C>([select id,name,visit_with_new_order_booking__c,(select id,name,Purpose_of_Visit__c,Order_Value__c,Othet_Activities__c from AP_Site_Visits__r where (Purpose_of_Visit__c='New Order Booking' or Othet_Activities__c='Post Visit Order') and Order_Value__c>0) from Target__C where id in:visitset2 limit 999]);
            for(Target__C targets:Targetlist){
                target__C newtarget = new target__C();
                newtarget.id= targets.id;
                newtarget.visit_with_new_order_booking__c=targets.AP_Site_Visits__r.size();
                newtargetlisttoupdate.add(newtarget);
                                
            }
         
        if(!newtargetlisttoupdate.isempty() && newtargetlisttoupdate.size()>0 && newtargetlisttoupdate!=null){
            try{
            update newtargetlisttoupdate;
            }catch(System.Exception e){
                
            }    
            
        }

    }
}