Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/AP_Site_Visit__c.object-meta.xml
<CustomObject>
    <label>APPL Site Visit</label>
    <nameField>
        <displayFormat>Visit-{000000}</displayFormat>
        <label>AP Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/AP_Tour_Plan__c.field-meta.xml
<CustomField>
    <fullName>AP_Tour_Plan__c</fullName>
    <label>Tour Plan</label>
    <referenceTo>AP_Tour_Plan__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <description>Target</description>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/recordTypes/Visits.recordType-meta.xml
<RecordType>
    <fullName>Visits</fullName>
    <active>true</active>
    <label>Visits</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/AP_Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>APPL Tour Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>AP TourPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPL Tour Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>APPL Tour Plans</relationshipLabel>
    <relationshipName>AP_TourPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/visit_with_new_order_booking__c.field-meta.xml
<CustomField>
    <fullName>visit_with_new_order_booking__c</fullName>
    <label>visit with new order booking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/Test_ProductivevisitOrders.cls
/***************************************************
 * Name:SudhaMurthy
 * Description: class to create count  and sum of visits on target
 * Trigger:AdoptedPlumberAndDealer 
 * created date :22/22/2018***********************/
@isTest
public class Test_ProductivevisitOrders {
    @isTest static void Testforproductivevisits(){
    AP_Tour_Plan__c a1 = new AP_Tour_Plan__c();
    insert a1;
    AP_Tour_Plan__c a2 = new AP_Tour_Plan__c();
    insert a2;
       Target__C t1= new target__C();
        insert t1;
        target__C t2= new target__C();
        insert t2;
        Test.startTest();
        AP_Site_Visit__c visit1= new AP_Site_Visit__c(AP_Tour_Plan__c=a1.id,target__c=t1.id);
        insert visit1;
        AP_Site_Visit__c visit2= new AP_Site_Visit__c(AP_Tour_Plan__c=a2.id,target__c=t1.id);
        insert visit2;
        //System.assertEquals(1, [Select visit_with_new_order_booking__c   From target__c Where Id =: t1.Id].visit_with_new_order_booking__c  );
        
        update visit1;
       // System.assertEquals(2, [Select visit_with_new_order_booking__c   From target__c Where Id =: t1.Id].visit_with_new_order_booking__c  );
          
        update visit2;
        delete visit1;
        // System.assertEquals(0, [Select visit_with_new_order_booking__c  From target__c Where Id =: t1.Id].visit_with_new_order_booking__c  );
        undelete visit1;
         Test.stopTest();   
        
    }

}