Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/AP_Site_Visit__c.object-meta.xml
<CustomObject>
    <label>APPL Site Visit</label>
    <nameField>
        <displayFormat>Visit-{000000}</displayFormat>
        <label>AP Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/AP_Tour_Plan__c.field-meta.xml
<CustomField>
    <fullName>AP_Tour_Plan__c</fullName>
    <label>Tour Plan</label>
    <referenceTo>AP_Tour_Plan__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Othet_Activities__c.field-meta.xml
<CustomField>
    <fullName>Othet_Activities__c</fullName>
    <label>Other Activities</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exhibitions/Shows</fullName>
            </value>
            <value>
                <fullName>Depot Meet/Office Meet</fullName>
            </value>
            <value>
                <fullName>Holiday/ Market Closed</fullName>
            </value>
            <value>
                <fullName>Leave</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Promotional Activity</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Post Visit Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Party_Type__c.field-meta.xml
<CustomField>
    <fullName>Party_Type__c</fullName>
    <label>Party Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Borer</fullName>
            </value>
            <value>
                <fullName>Borewell Office</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Dealers Salesman</fullName>
            </value>
            <value>
                <fullName>Direct Dealer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Farmer</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Institution</fullName>
            </value>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Panchayat Head</fullName>
            </value>
            <value>
                <fullName>Plumber</fullName>
            </value>
            <value>
                <fullName>Plumber Cum Mechanic</fullName>
            </value>
            <value>
                <fullName>Plumbing Contractor</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Project Owner/Developer</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
            <value>
                <fullName>Purchase Manager</fullName>
            </value>
            <value>
                <fullName>Site Engineer</fullName>
            </value>
            <value>
                <fullName>Site Incharge / Supervisor</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Winders</fullName>
            </value>
            <value>
                <fullName>Plumber club member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <description>Target</description>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/recordTypes/Visits.recordType-meta.xml
<RecordType>
    <fullName>Visits</fullName>
    <active>true</active>
    <label>Visits</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/AP_Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>APPL Tour Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>AP TourPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPL Tour Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>APPL Tour Plans</relationshipLabel>
    <relationshipName>AP_TourPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Influencer_visit_actual_column__c.field-meta.xml
<CustomField>
    <fullName>Influencer_visit_actual_column__c</fullName>
    <label>Influencer visit actual column</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Leave_Actual__c.field-meta.xml
<CustomField>
    <fullName>Leave_Actual__c</fullName>
    <label>Leave_Actual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/Test_RollupInfluencerVisitsColumn.cls
/***************************************************
* Name:SudhaMurthy
* Description: TEst class  for RollupInfluencerVisitsColumn
* Trigger:AdoptedPlumberAndDealer 
* created date :08/07/2019***********************/
@IsTest
public class Test_RollupInfluencerVisitsColumn{
    @isTest static void TestInfluencerVisitmethod(){
        List<AP_Tour_Plan__c> apList = new List<AP_Tour_Plan__c>();
        List<AP_Site_Visit__c> apVisit = new List<AP_Site_Visit__c>();
        
        AP_Tour_Plan__c a1 = new AP_Tour_Plan__c();
        apList.add(a1);
        AP_Tour_Plan__c a2 = new AP_Tour_Plan__c();
        apList.add(a2);
        
        insert apList;
        
        Target__C t1= new target__C(Influencer_visit_actual_column__c=2);
        insert t1;
        target__C t2= new target__C(Influencer_visit_actual_column__c=5);
        insert t2;
        
        Test.startTest();
        
        Id recordTypeIdVisits = Schema.SObjectType.AP_Site_Visit__c.getRecordTypeInfosByName().get('Visits').getRecordTypeId();
        
        AP_Site_Visit__c visit1= new AP_Site_Visit__c(AP_Tour_Plan__c=a1.id,target__c=t1.id,Party_type__C='farmer', recordTypeId =recordTypeIdVisits,Date__c = system.today() );
        apVisit.add(visit1);
        
        Id recordTypeIdForUserIncentiveActualsDaily = Schema.SObjectType.AP_Site_Visit__c.getRecordTypeInfosByName().get('Other Activities').getRecordTypeId();
        
        AP_Site_Visit__c visit3= new AP_Site_Visit__c(AP_Tour_Plan__c=a2.id,target__c=t1.id,recordTypeId = recordTypeIdForUserIncentiveActualsDaily, Date__c = system.today());
        apVisit.add(visit3);
        
        AP_Site_Visit__c visit5 = new AP_Site_Visit__c(AP_Tour_Plan__c=a2.id,target__c=t1.id,recordTypeId = recordTypeIdForUserIncentiveActualsDaily, Date__c = system.today());
        
        apVisit.add(visit5);
        insert apVisit;
        update visit1;
        update visit3;
        delete visit1;
        undelete visit1;
        
        Test.stopTest();   
    }
    @isTest static void TestLeavemethod(){
        AP_Tour_Plan__c a1 = new AP_Tour_Plan__c();
        insert a1;
        AP_Tour_Plan__c a2 = new AP_Tour_Plan__c();
        insert a2;
        Target__C t1= new target__C(Leave_Actual__c=2);
        insert t1;
        target__C t2= new target__C(Leave_Actual__c=5);
        insert t2;
        Test.startTest();
        AP_Site_Visit__c visit1= new AP_Site_Visit__c(AP_Tour_Plan__c=a1.id,target__c=t1.id,Othet_Activities__c='leave' );
        insert visit1;
        AP_Site_Visit__c visit2= new AP_Site_Visit__c(AP_Tour_Plan__c=a2.id,target__c=t1.id,Othet_Activities__c='leave' );
        insert visit2;
        
        
        update visit1;
        
        
        update visit2;
        delete visit1;
        
        undelete visit1;
        
        
        Test.stopTest();   
        
    }
}