Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/AP_Site_Visit__c.object-meta.xml
<CustomObject>
    <label>APPL Site Visit</label>
    <nameField>
        <displayFormat>Visit-{000000}</displayFormat>
        <label>AP Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/AP_Tour_Plan__c.field-meta.xml
<CustomField>
    <fullName>AP_Tour_Plan__c</fullName>
    <label>Tour Plan</label>
    <referenceTo>AP_Tour_Plan__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Market_Type__c.field-meta.xml
<CustomField>
    <fullName>Market_Type__c</fullName>
    <formula>IF((TEXT(AP_Tour_Plan__r.Market_Type__c)==&apos;new&apos; ), &apos;New&apos;, &apos;Existing&apos;)</formula>
    <label>Market Type</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Party_Name__c.field-meta.xml
<CustomField>
    <fullName>Party_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Name/Firm Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Party_Type__c</field>
            <operation>equals</operation>
            <valueField>Account.Party_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Party_Type__c.field-meta.xml
<CustomField>
    <fullName>Party_Type__c</fullName>
    <label>Party Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Borer</fullName>
            </value>
            <value>
                <fullName>Borewell Office</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Dealers Salesman</fullName>
            </value>
            <value>
                <fullName>Direct Dealer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Farmer</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Institution</fullName>
            </value>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Panchayat Head</fullName>
            </value>
            <value>
                <fullName>Plumber</fullName>
            </value>
            <value>
                <fullName>Plumber Cum Mechanic</fullName>
            </value>
            <value>
                <fullName>Plumbing Contractor</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Project Owner/Developer</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
            <value>
                <fullName>Purchase Manager</fullName>
            </value>
            <value>
                <fullName>Site Engineer</fullName>
            </value>
            <value>
                <fullName>Site Incharge / Supervisor</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Winders</fullName>
            </value>
            <value>
                <fullName>Plumber club member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <description>Target</description>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <description>Vertical - Depends on Party Type</description>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Column</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/AP_Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>APPL Tour Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>AP TourPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPL Tour Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Party_Type__c</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AP TourPlans</relationshipLabel>
    <relationshipName>AP_TourPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Market_Type__c.field-meta.xml
<CustomField>
    <fullName>Market_Type__c</fullName>
    <label>Market Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Promotional_Type__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Type__c</fullName>
    <label>Promotional Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Boarers Meet</fullName>
            </value>
            <value>
                <fullName>Exhibition</fullName>
            </value>
            <value>
                <fullName>Jeep Campaign</fullName>
            </value>
            <value>
                <fullName>Farmers Meet</fullName>
            </value>
            <value>
                <fullName>Tractor Show</fullName>
            </value>
            <value>
                <fullName>Shandy Show</fullName>
            </value>
            <value>
                <fullName>Mechanics Meet</fullName>
            </value>
            <value>
                <fullName>Column Dealer Meet</fullName>
            </value>
            <value>
                <fullName>Column Dealers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Column Dealers Salesman Meet</fullName>
            </value>
            <value>
                <fullName>InShop Mechanic Meet</fullName>
            </value>
            <value>
                <fullName>Mechanics Factory Visit</fullName>
            </value>
            <value>
                <fullName>Onsite Plumber Meet</fullName>
            </value>
            <value>
                <fullName>Plumbing DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Engineers Meets</fullName>
            </value>
            <value>
                <fullName>Onsite Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Naaka Meets</fullName>
            </value>
            <value>
                <fullName>Architects Meets</fullName>
            </value>
            <value>
                <fullName>Mega Plumbers Meets</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealers Factory Visits</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Consultants Factory Visits</fullName>
            </value>
            <value>
                <fullName>Plumbing factory Visits</fullName>
            </value>
            <value>
                <fullName>Inshop Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Exhibition / Construction Fairs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>APPL Tour Plans</relationshipLabel>
    <relationshipName>AP_TourPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <description>This field is used in Expense Report.</description>
    <formula>TEXT(Target__r.Vertical__c )</formula>
    <label>Vertical</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Architects_Meet__c.field-meta.xml
<CustomField>
    <fullName>Architects_Meet__c</fullName>
    <label>Architects Meets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Boarers_Meet__c.field-meta.xml
<CustomField>
    <fullName>Boarers_Meet__c</fullName>
    <label>Boarers Meets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Builders_Meet__c.field-meta.xml
<CustomField>
    <fullName>Builders_Meet__c</fullName>
    <label>Builders Meets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Column_Dealer_Meet__c.field-meta.xml
<CustomField>
    <fullName>Column_Dealer_Meet__c</fullName>
    <label>Column Dealer / Distributor Meets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Target_User__c.field-meta.xml
<CustomField>
    <fullName>Target_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Column</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
            <value>
                <fullName>Branding</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/GeoLocationInAccount_Test.cls
@isTest
public class GeoLocationInAccount_Test{
    public static testMethod void GeoLocationTestMethod(){
        Profile p = [SELECT Id, Name FROM Profile WHERE Name = 'BD']; 
        User userData1 = new User(Alias = 'standt1', 
              Email= 'FName'+'LName'+'@ashirvad.com', 
              EmailEncodingKey='UTF-8', 
              FirstName = 'FName',
              LastName = 'LName', 
              LanguageLocaleKey='en_US', 
              LocaleSidKey='en_US', 
              ProfileId = p.Id, 
              TimeZoneSidKey='Asia/Kolkata', 
              UserName='LName'+'FName'+'@ashirvadpipes.com',
              EmployeeNumber = '12345'                                  
        );
                                 
        insert userData1;
                                 
        RecordType rcdtyp = [SELECT ID FROM RecordType WHERE Name = 'Distributor'];
        Account newAccount = new Account(
            Name  = 'name',
            BillingState = 'Gujarat',
            BillingStreet = 'Abc Street',
            BillingCity = 'Abc City',
            BillingCountry = 'India',
            Contact_Number_Mobile__c = '9999999999',
            Ramco_ID__c = '1234',
            RecordTypeId = rcdtyp.ID
        );
        
        insert newAccount;
         
        Target__c target = new Target__c(
            Is_Active__c = true,
            Architects_Meet__c = 2,
            Boarers_Meet__c = 3,
            Builders_Meet__c = 4,
            Column_Dealer_Meet__c = 5,
            Target_User__c = userData1.Id,
            OwnerId = userData1.Id,
            Approval_Status__c = 'Not Submitted',
            Vertical__c        = 'Plumbing'
        );
        
        insert target;
        
        AP_Tour_Plan__c tourplan = new AP_Tour_Plan__c(
            Market_Type__c = 'New',
            Promotional_Type__c = 'Boarers Meet',
            Target__c = target.ID,
            Account__c = newAccount.Id           
        );
        
        insert tourplan;
         
        AP_Site_Visit__c apsv = new AP_Site_Visit__c(
            AP_Tour_Plan__c = tourplan.ID,
            Target__c = target.Id,
            Party_Type__c = 'Distributor',
            Party_Name__c = newAccount.Id,
            Geo_Location__Latitude__s = 12.91315,
            Geo_Location__Longitude__s = 77.62784 
        );
        
        insert apsv;
     
    } 
}//end of GeoLocationInAccount_Test