Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/AP_Site_Visit__c.object-meta.xml
<CustomObject>
    <label>APPL Site Visit</label>
    <nameField>
        <displayFormat>Visit-{000000}</displayFormat>
        <label>AP Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Actual_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Created_Date__c</fullName>
    <label>Actual Created Date</label>
    <type>DateTime</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Actual_LastModified_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_LastModified_Date__c</fullName>
    <label>Actual LastModified Date</label>
    <type>DateTime</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Party_Type__c.field-meta.xml
<CustomField>
    <fullName>Party_Type__c</fullName>
    <label>Party Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Borer</fullName>
            </value>
            <value>
                <fullName>Borewell Office</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Dealers Salesman</fullName>
            </value>
            <value>
                <fullName>Direct Dealer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Farmer</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Institution</fullName>
            </value>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Panchayat Head</fullName>
            </value>
            <value>
                <fullName>Plumber</fullName>
            </value>
            <value>
                <fullName>Plumber Cum Mechanic</fullName>
            </value>
            <value>
                <fullName>Plumbing Contractor</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Project Owner/Developer</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
            <value>
                <fullName>Purchase Manager</fullName>
            </value>
            <value>
                <fullName>Site Engineer</fullName>
            </value>
            <value>
                <fullName>Site Incharge / Supervisor</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Winders</fullName>
            </value>
            <value>
                <fullName>Plumber club member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Purpose_of_Visit__c.field-meta.xml
<CustomField>
    <fullName>Purpose_of_Visit__c</fullName>
    <label>Purpose of Visit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Party_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Approval for Ashirvad Brand</fullName>
            </value>
            <value>
                <fullName>Building Relationship</fullName>
            </value>
            <value>
                <fullName>Complaints-Aqua</fullName>
            </value>
            <value>
                <fullName>Complaints-column</fullName>
            </value>
            <value>
                <fullName>Complaints-CPVC</fullName>
            </value>
            <value>
                <fullName>Complaints-SWR</fullName>
            </value>
            <value>
                <fullName>Dispatch</fullName>
            </value>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Follow Up</fullName>
            </value>
            <value>
                <fullName>Market Survey</fullName>
            </value>
            <value>
                <fullName>New Order Booking</fullName>
            </value>
            <value>
                <fullName>Order Follow Up</fullName>
            </value>
            <value>
                <fullName>Payment Follow Up</fullName>
            </value>
            <value>
                <fullName>Product Presentation</fullName>
            </value>
            <value>
                <fullName>Attending Complaint</fullName>
            </value>
            <value>
                <fullName>Recce</fullName>
            </value>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Survey/Audit</fullName>
            </value>
            <value>
                <fullName>Give for Print/Print Delivery</fullName>
            </value>
            <value>
                <fullName>Courtesy Call</fullName>
            </value>
            <value>
                <fullName>Repair/Rework</fullName>
            </value>
            <value>
                <fullName>Events / Exhibitions</fullName>
            </value>
            <value>
                <fullName>Design Development</fullName>
            </value>
            <value>
                <fullName>Facility Visit/Vendor Evaluation</fullName>
            </value>
            <value>
                <fullName>Review Meet</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Promotional activity</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <description>Target</description>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/recordTypes/Visits.recordType-meta.xml
<RecordType>
    <fullName>Visits</fullName>
    <active>true</active>
    <label>Visits</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Influencer_visit_actual_column__c.field-meta.xml
<CustomField>
    <fullName>Influencer_visit_actual_column__c</fullName>
    <label>Influencer visit actual column</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/recordTypes/Column.recordType-meta.xml
<RecordType>
    <fullName>Column</fullName>
    <active>true</active>
    <label>Column</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/classes/RollupInfluencerVisitsColumn.cls
/***************************************************
 * Name:SudhaMurthy
 * Description: class to create count of column visits except dealer and distributor visits
 * Trigger:AdoptedPlumberAndDealer 
 * created date :08/07/2019***********************/
 
 
public class RollupInfluencerVisitsColumn{
      
    public static void InfluencerVisitsColumnforupdate(list<AP_Site_Visit__c> visitlist,map<id,AP_Site_Visit__c> oldmap){
        list<target__c> newtargetlisttoupdate = new list<target__C>();
        system.debug('test for trigegr.ner........'+visitlist);
        //system.debug('test for trigegr.old........'+oldvisitlist);
        
        set<id> visitset= new set<id>();
        if(!visitlist.isempty() && visitlist!=null){
            for(AP_Site_Visit__c ap :visitlist) {
                if((ap.Actual_Created_Date__c!=oldmap.get(ap.id).Actual_Created_Date__c) ||  (ap.Actual_LastModified_Date__c!=oldmap.get(ap.id).Actual_LastModified_Date__c)){
                    
                   
                }else{
                    visitset.add(ap.target__C);
                }
            }
        }  
           
        list<Target__C> targetlist=  new list<target__C>([select id,name,Influencer_visit_actual_column__c,(select id,name,recordtype.name,Party_type__c from AP_Site_Visits__r where recordtype.name='visits' AND (Party_type__c!='Dealer' AND Party_type__c!='Distributor') )  from Target__C where id in:visitset limit 999]);
            for(Target__C targets:Targetlist){
                target__C newtarget = new target__C();
                newtarget.id= targets.id;
                newtarget.Influencer_visit_actual_column__c=targets.AP_Site_Visits__r.size();
                newtargetlisttoupdate.add(newtarget);
                                
            }
         
        if(!newtargetlisttoupdate.isempty() && newtargetlisttoupdate.size()>0 && newtargetlisttoupdate!=null){
            try{
            update newtargetlisttoupdate;
            }catch(System.Exception e){
                
            }    
            
        }

    }
     public static void InfluencerVisitsColumndelete(list<AP_Site_Visit__c> oldvisitlist){
         list<target__c> newtargetlisttoupdate = new list<target__C>();
        set<id> visitset2= new set<id>();
        if(!oldvisitlist.isempty() && oldvisitlist!=null){
                for(AP_Site_Visit__c apvisitold :oldvisitlist) {
                    if(apvisitold.Target__c!=null){
                    visitset2.add(apvisitold.target__C);
                    system.debug('test for set after update........'+oldvisitlist);
                    }
                }
           } 
    
     list<Target__C> targetlist=  new list<target__C>([select id,name,Influencer_visit_actual_column__c,(select id,name,Purpose_of_Visit__c,Party_type__c,recordtype.name from AP_Site_Visits__r where recordtype.name='visits' AND (Party_type__c!='Dealer' AND Party_type__c!='Distributor')) from Target__C where id in:visitset2 limit 999]);
            for(Target__C targets:Targetlist){
                target__C newtarget = new target__C();
                newtarget.id= targets.id;
                newtarget.Influencer_visit_actual_column__c=targets.AP_Site_Visits__r.size();
                newtargetlisttoupdate.add(newtarget);
                                
            }
         
        if(!newtargetlisttoupdate.isempty() && newtargetlisttoupdate.size()>0 && newtargetlisttoupdate!=null){
            try{
            update newtargetlisttoupdate;
            }catch(System.Exception e){
                
            }    
            
        }

    }
    public static void InfluencerVisitsColumn(list<AP_Site_Visit__c> oldvisitlist){
         list<target__c> newtargetlisttoupdate = new list<target__C>();
        set<id> visitset2= new set<id>();
        if(!oldvisitlist.isempty() && oldvisitlist!=null){
                for(AP_Site_Visit__c apvisitold :oldvisitlist) {
                    if(apvisitold.Target__c!=null){
                    visitset2.add(apvisitold.target__C);
                    system.debug('test for set after update........'+oldvisitlist);
                    }
                }
           } 
    
     list<Target__C> targetlist=  new list<target__C>([select id,name,Influencer_visit_actual_column__c,(select id,name,Purpose_of_Visit__c,Party_type__c,recordtype.name from AP_Site_Visits__r where recordtype.name='visits' AND (Party_type__c!='Dealer' AND Party_type__c!='Distributor')) from Target__C where id in:visitset2 limit 999]);
            for(Target__C targets:Targetlist){
                target__C newtarget = new target__C();
                newtarget.id= targets.id;
                newtarget.Influencer_visit_actual_column__c=targets.AP_Site_Visits__r.size();
                newtargetlisttoupdate.add(newtarget);
                                
            }
         
        if(!newtargetlisttoupdate.isempty() && newtargetlisttoupdate.size()>0 && newtargetlisttoupdate!=null){
            try{
            update newtargetlisttoupdate;
            }catch(System.Exception e){
                
            }    
            
        }

    }
    
}