Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/AP_Site_Visit__c.object-meta.xml
<CustomObject>
    <label>APPL Site Visit</label>
    <nameField>
        <displayFormat>Visit-{000000}</displayFormat>
        <label>AP Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Adopted_Dealer__c.field-meta.xml
<CustomField>
    <fullName>Adopted_Dealer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Adopted Dealer</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Adopted_Plumber__c.field-meta.xml
<CustomField>
    <fullName>Adopted_Plumber__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Adopted Plumber</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/AP_Tour_Plan__c.field-meta.xml
<CustomField>
    <fullName>AP_Tour_Plan__c</fullName>
    <label>Tour Plan</label>
    <referenceTo>AP_Tour_Plan__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Generate_Order__c.field-meta.xml
<CustomField>
    <fullName>Generate_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generate Order</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Geo_Location__c.field-meta.xml
<CustomField>
    <fullName>Geo_Location__c</fullName>
    <label>Geo Location</label>
    <scale>5</scale>
    <type>Location</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Party_Type__c.field-meta.xml
<CustomField>
    <fullName>Party_Type__c</fullName>
    <label>Party Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Borer</fullName>
            </value>
            <value>
                <fullName>Borewell Office</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Dealers Salesman</fullName>
            </value>
            <value>
                <fullName>Direct Dealer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Farmer</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Institution</fullName>
            </value>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Panchayat Head</fullName>
            </value>
            <value>
                <fullName>Plumber</fullName>
            </value>
            <value>
                <fullName>Plumber Cum Mechanic</fullName>
            </value>
            <value>
                <fullName>Plumbing Contractor</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Project Owner/Developer</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
            <value>
                <fullName>Purchase Manager</fullName>
            </value>
            <value>
                <fullName>Site Engineer</fullName>
            </value>
            <value>
                <fullName>Site Incharge / Supervisor</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Winders</fullName>
            </value>
            <value>
                <fullName>Plumber club member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Air Admittance Valve</fullName>
            </value>
            <value>
                <fullName>Column Pipes</fullName>
            </value>
            <value>
                <fullName>Concealed Cisterns</fullName>
            </value>
            <value>
                <fullName>Concealed Valves</fullName>
            </value>
            <value>
                <fullName>CPVC</fullName>
            </value>
            <value>
                <fullName>External Drainage</fullName>
            </value>
            <value>
                <fullName>Grease Seperator</fullName>
            </value>
            <value>
                <fullName>Multiquick</fullName>
            </value>
            <value>
                <fullName>Sanitary System</fullName>
            </value>
            <value>
                <fullName>Silent SWR</fullName>
            </value>
            <value>
                <fullName>SWR</fullName>
            </value>
            <value>
                <fullName>UPVC</fullName>
            </value>
            <value>
                <fullName>V4</fullName>
            </value>
            <value>
                <fullName>Valves (BUV &amp; BFV)</fullName>
            </value>
            <value>
                <fullName>Waste &amp; Traps</fullName>
            </value>
            <value>
                <fullName>WCPC new order</fullName>
            </value>
            <value>
                <fullName>WCPC repeat order</fullName>
            </value>
            <value>
                <fullName>Agri Pipes</fullName>
            </value>
            <value>
                <fullName>Casing Pipes</fullName>
            </value>
            <value>
                <fullName>WST</fullName>
            </value>
            <value>
                <fullName>HDPE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Promotion</description>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipName>AP_Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/RecordEdit__c.field-meta.xml
<CustomField>
    <fullName>RecordEdit__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check for is New or Not</description>
    <label>RecordEdit</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Retailing_Day__c.field-meta.xml
<CustomField>
    <fullName>Retailing_Day__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retailing Day</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <description>Target</description>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Task_Tab__c.field-meta.xml
<CustomField>
    <fullName>Task_Tab__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Task Tab</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Imperial</fullName>
            </value>
            <value>
                <fullName>Royal</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Regal</fullName>
            </value>
            <value>
                <fullName>Non Club</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/recordTypes/Visits.recordType-meta.xml
<RecordType>
    <fullName>Visits</fullName>
    <active>true</active>
    <label>Visits</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/AP_Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>APPL Tour Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>AP TourPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPL Tour Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Party_Type__c</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AP TourPlans</relationshipLabel>
    <relationshipName>AP_TourPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>APPL Tour Plans</relationshipLabel>
    <relationshipName>AP_TourPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Promotion No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Geo_Location__c.field-meta.xml
<CustomField>
    <fullName>Geo_Location__c</fullName>
    <label>Geo Location</label>
    <scale>5</scale>
    <type>Location</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Architects / Engineers / Consultants Factory Visit</fullName>
            </value>
            <value>
                <fullName>Architects Meets</fullName>
            </value>
            <value>
                <fullName>Boarers Meets</fullName>
            </value>
            <value>
                <fullName>Builders Meets</fullName>
            </value>
            <value>
                <fullName>Column Dealer / Distributor Meets</fullName>
            </value>
            <value>
                <fullName>Column Distributors / Dealers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Column DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Engineers Meets</fullName>
            </value>
            <value>
                <fullName>Exhibition / Agri Fairs</fullName>
            </value>
            <value>
                <fullName>Exhibition / Construction Fairs</fullName>
            </value>
            <value>
                <fullName>Group Activity</fullName>
            </value>
            <value>
                <fullName>Inshop Boarers Meets</fullName>
            </value>
            <value>
                <fullName>Inshop Mechanic Meets</fullName>
            </value>
            <value>
                <fullName>Inshop Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Jeep Campaign</fullName>
            </value>
            <value>
                <fullName>Mechanics Factory Visit</fullName>
            </value>
            <value>
                <fullName>Mega Farmer Meets</fullName>
            </value>
            <value>
                <fullName>Mega Mechanic Meets</fullName>
            </value>
            <value>
                <fullName>Mega Plumbers Meets</fullName>
            </value>
            <value>
                <fullName>Mini Farmer Meet</fullName>
            </value>
            <value>
                <fullName>Naaka Meets</fullName>
            </value>
            <value>
                <fullName>Onsite Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Plumbers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealer / Distributor Meets</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealers Factory Visits</fullName>
            </value>
            <value>
                <fullName>Plumbing DSM Meet/Training</fullName>
            </value>
            <value>
                <fullName>Product Presentation</fullName>
            </value>
            <value>
                <fullName>Projects DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Shandy Shows</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/GeoLocationController_Test.cls
@isTest
private class GeoLocationController_Test{
  @testSetup
  static void setupTestData(){
    test.startTest();
    User user_Obj = new User(Username = 'TestUser3090520180827004346@codecoverage.com', LocaleSidKey = 'sq',EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', Alias = 'Alias833', TimeZoneSidKey = 'Pacific/Kiritimati', LastName = 'LastName760', Email = 'Email22@test.com', IsActive = true, ProfileId = '00e30000001IxrqAAC', EmployeeNumber = 'Emplo383', Vertical_Type__c = 'Column');
    Insert user_Obj; 
    Account account_Obj = new Account(Name = 'Name303', Contact_Number_Mobile__c = '9999999987', Type = 'Analyst', RecordTypeId = '01230000001DIllAAG',BillingStreet = 'PratapNagar', BillingCity = 'Jaipur', BillingState = 'Raj', BillingPostalCode = '302022', BillingCountry = 'India', Party_Type__c = 'Architect',  Inactive_Mobile_No__c = false, System_Flag__c = false, Account_Status_Flag__c = false, Bandhan_Cutsomer__c = false, Geolocation__Latitude__s = 0, Geolocation__Longitude__s = 0, Products__c = 'Column Pipes');
    Insert account_Obj; 
    Target__c targets_Obj = new Target__c();
    Insert targets_Obj;
    Promotion__c promotions_Obj = new Promotion__c(Type__c = 'Architects Meet');
    Insert promotions_Obj; 
    AP_Tour_Plan__c ap_tour_plan_Obj = new AP_Tour_Plan__c(Account__c = account_Obj.id, Target__c = targets_Obj.id);
    Insert ap_tour_plan_Obj;
    AP_Site_Visit__c ap_site_visit_Obj = new AP_Site_Visit__c(RecordTypeId = '01230000001DPwDAAW',AP_Tour_Plan__c = ap_tour_plan_Obj.id, Action_Date__c = Date.today(), Date__c = Date.today(), Generate_Order__c = false, Party_Type__c = 'Architect', RecordEdit__c = false, Task_Tab__c = false, Target__c = targets_Obj.id, Verified__c = false, Retailing_Day__c = false, Geo_Location__Latitude__s = 0, Geo_Location__Longitude__s = 0, Adopted_Plumber__c = false, Adopted_Dealer__c = false);
    Insert ap_site_visit_Obj; 
    test.stopTest();
  }
  static testMethod void test_AccountType_UseCase1(){
    Id DlrRecTypid= Schema.SObjectType.Account.RecordTypeInfosByName.get('Dealer').RecordTypeId;
    List<User> user_Obj  =  [SELECT Id,Username,LastName,Email,IsActive,ProfileId,EmployeeNumber,Vertical_Type__c from User];
    System.assertEquals(true,user_Obj.size()>0);
    List<Account> account_Obj  =  [SELECT Id,Name,Type,RecordTypeId,ParentId,BillingStreet,BillingCity,BillingState,BillingPostalCode,BillingCountry,Party_Type__c,Inactive_Mobile_No__c,System_Flag__c,Account_Status_Flag__c,Bandhan_Cutsomer__c,Geolocation__Latitude__s,Geolocation__Longitude__s,Geolocation__c from Account];
    System.assertEquals(true,account_Obj.size()>0);
    List<Promotion__c> promotions_Obj  =  [SELECT Id,Name,Type__c from Promotion__c];
    System.assertEquals(true,promotions_Obj.size()>0);
    List<AP_Site_Visit__c> ap_site_visit_Obj  =  [SELECT Id,Name,RecordTypeId,AP_Tour_Plan__c,Action_Date__c,Date__c,Generate_Order__c,Party_Type__c,RecordEdit__c,Target__c,Verified__c,Retailing_Day__c,Geo_Location__Latitude__s,Geo_Location__Longitude__s,Geo_Location__c,Adopted_Plumber__c,Adopted_Dealer__c from AP_Site_Visit__c];
    System.assertEquals(true,ap_site_visit_Obj.size()>0);
    GeoLocationController obj01 = new GeoLocationController();
    obj01.a = account_Obj[0];
    obj01.objectList = new list<SelectOption>();
    obj01.selectedObject = 'Accounts';
    obj01.accountType = new list<selectoption>();
    obj01.selectedAccountType = 'DlrRecTypid';
    obj01.accountList = account_Obj;
    //obj01.promotionList = new list<Promotion__c>();
    obj01.promotionList = promotions_Obj;
    obj01.visitList = ap_site_visit_Obj;
    obj01.fromDate = Date.today();
    obj01.toDate = Date.today();
    obj01.AccountType();
  }
  static testMethod void test_showRecords_UseCase1(){
    //Id DlrRecTypid= Schema.SObjectType.Account.RecordTypeInfosByName.get('Dealer').RecordTypeId;
    List<RecordType> DlrRec = [SELECT ID FROM RecordType WHERE Name = 'Dealer'];
    List<User> user_Obj  =  [SELECT Id,Username,LastName,Email,IsActive,ProfileId,EmployeeNumber,Vertical_Type__c from User];
    System.assertEquals(true,user_Obj.size()>0);
    List<Account> account_Obj  =  [SELECT Id,Name,OwnerID,Type,RecordTypeId,ParentId,BillingStreet,BillingCity,BillingState,BillingPostalCode,BillingCountry,Party_Type__c,Inactive_Mobile_No__c,System_Flag__c,Account_Status_Flag__c,Bandhan_Cutsomer__c,Geolocation__Latitude__s,Geolocation__Longitude__s,Geolocation__c from Account];
    System.assertEquals(true,account_Obj.size()>0);
    List<Promotion__c> promotions_Obj  =  [SELECT Id,Name,Type__c from Promotion__c];
    System.assertEquals(true,promotions_Obj.size()>0);
    List<AP_Site_Visit__c> ap_site_visit_Obj  =  [SELECT Id,Name,RecordTypeId,AP_Tour_Plan__c,Action_Date__c,Date__c,Generate_Order__c,Party_Type__c,RecordEdit__c,Target__c,Verified__c,Retailing_Day__c,Geo_Location__Latitude__s,Geo_Location__Longitude__s,Geo_Location__c,Adopted_Plumber__c,Adopted_Dealer__c from AP_Site_Visit__c];
    System.assertEquals(true,ap_site_visit_Obj.size()>0);
    GeoLocationController obj01 = new GeoLocationController();
    String type = 'Dealer';
    obj01.a = account_Obj[0];
    obj01.objectList = new list<SelectOption>();
    obj01.selectedObject = 'Accounts';
    obj01.accountType = new list<selectoption>();
    obj01.selectedAccountType = '01230000001DIllAAG';
    obj01.accountList = account_Obj;
    obj01.promotionList = promotions_Obj;
    obj01.visitList = ap_site_visit_Obj;
    obj01.fromDate = Date.today();
    obj01.toDate = Date.today();
    obj01.showRecords();
  }
  static testMethod void test_showRecords_UseCase2(){
    List<User> user_Obj  =  [SELECT Id,Username,LastName,Email,IsActive,ProfileId,EmployeeNumber,Vertical_Type__c from User];
    System.assertEquals(true,user_Obj.size()>0);
    List<Account> account_Obj  =  [SELECT Id,Name,Type,OwnerID,RecordTypeId,ParentId,BillingStreet,BillingCity,BillingState,BillingPostalCode,BillingCountry,Party_Type__c,Inactive_Mobile_No__c,System_Flag__c,Account_Status_Flag__c,Bandhan_Cutsomer__c,Geolocation__Latitude__s,Geolocation__Longitude__s,Geolocation__c from Account];
    System.assertEquals(true,account_Obj.size()>0);
    List<Promotion__c> promotions_Obj  =  [SELECT Id,Name,Owner.ID,Type__c from Promotion__c];
    System.assertEquals(true,promotions_Obj.size()>0);
    List<AP_Site_Visit__c> ap_site_visit_Obj  =  [SELECT Id,Name,RecordTypeId,AP_Tour_Plan__c,Action_Date__c,Date__c,Generate_Order__c,Party_Type__c,RecordEdit__c,Target__c,Verified__c,Retailing_Day__c,Geo_Location__Latitude__s,Geo_Location__Longitude__s,Geo_Location__c,Adopted_Plumber__c,Adopted_Dealer__c from AP_Site_Visit__c];
    System.assertEquals(true,ap_site_visit_Obj.size()>0);
    GeoLocationController obj01 = new GeoLocationController();
    obj01.objectList = new list<SelectOption>();
    obj01.selectedObject = 'Promotions';
    obj01.promotionList = promotions_Obj;
    obj01.fromDate = Date.today();
    obj01.toDate = Date.today();
    obj01.showRecords();
  }
   static testMethod void test_showRecords_UseCase3(){ 
    List<User> user_Obj  =  [SELECT Id,Username,LastName,Email,IsActive,ProfileId,EmployeeNumber,Vertical_Type__c from User];
    System.assertEquals(true,user_Obj.size()>0);
    List<Account> account_Obj  =  [SELECT Id,Name,Type,OwnerID,RecordTypeId,ParentId,BillingStreet,BillingCity,BillingState,BillingPostalCode,BillingCountry,Party_Type__c,Inactive_Mobile_No__c,System_Flag__c,Account_Status_Flag__c,Bandhan_Cutsomer__c,Geolocation__Latitude__s,Geolocation__Longitude__s,Geolocation__c from Account];
    System.assertEquals(true,account_Obj.size()>0);
    List<Promotion__c> promotions_Obj  =  [SELECT Id,Name,Type__c from Promotion__c];
    System.assertEquals(true,promotions_Obj.size()>0);
    List<AP_Site_Visit__c> ap_site_visit_Obj  =  [SELECT Id,Name,Vendor__c,RecordTypeId,AP_Tour_Plan__c,Action_Date__c,Date__c,Generate_Order__c,Party_Type__c,RecordEdit__c,Target__c,Verified__c,Retailing_Day__c,Geo_Location__Latitude__s,Geo_Location__Longitude__s,Geo_Location__c,Adopted_Plumber__c,Adopted_Dealer__c from AP_Site_Visit__c];
    System.assertEquals(true,ap_site_visit_Obj.size()>0);
    GeoLocationController obj01 = new GeoLocationController();
    obj01.objectList = new list<SelectOption>();
    obj01.selectedObject = 'Visits';
    obj01.accountType = new list<selectoption>();
    obj01.selectedAccountType = 'All';
    obj01.visitList = ap_site_visit_Obj;
    obj01.fromDate = Date.today();
    obj01.toDate = Date.today();
    obj01.showRecords();
  }
  static testMethod void test_showRecords_UseCase4(){
    List<User> user_Obj  =  [SELECT Id,Username,LastName,Email,IsActive,ProfileId,EmployeeNumber,Vertical_Type__c from User];
    System.assertEquals(true,user_Obj.size()>0);
    List<Account> account_Obj  =  [SELECT Id,Name,Type,OwnerId,RecordTypeId,ParentId,BillingStreet,BillingCity,BillingState,BillingPostalCode,BillingCountry,Party_Type__c,Inactive_Mobile_No__c,System_Flag__c,Account_Status_Flag__c,Bandhan_Cutsomer__c,Geolocation__Latitude__s,Geolocation__Longitude__s,Geolocation__c from Account];
    System.assertEquals(true,account_Obj.size()>0);
    List<Promotion__c> promotions_Obj  =  [SELECT Id,Name,Type__c from Promotion__c];
    System.assertEquals(true,promotions_Obj.size()>0);
    List<AP_Site_Visit__c> ap_site_visit_Obj  =  [SELECT Id,Name,RecordTypeId,AP_Tour_Plan__c,Action_Date__c,Date__c,Generate_Order__c,Party_Type__c,RecordEdit__c,Target__c,Verified__c,Retailing_Day__c,Geo_Location__Latitude__s,Geo_Location__Longitude__s,Geo_Location__c,Adopted_Plumber__c,Adopted_Dealer__c from AP_Site_Visit__c];
    System.assertEquals(true,ap_site_visit_Obj.size()>0);
    GeoLocationController obj01 = new GeoLocationController();
    obj01.a = account_Obj[0];
    obj01.objectList = new list<SelectOption>();
    obj01.selectedObject = 'Accounts';
    obj01.accountType = new list<selectoption>();
    obj01.selectedAccountType = 'All';
    obj01.accountList = account_Obj;
    obj01.showRecords();
  }
    static testMethod void test_showRecords_UseCase5(){ 
    //Id DlrRecTypid= Schema.SObjectType.Account.RecordTypeInfosByName.get('Dealer').RecordTypeId;
    List<RecordType> DlrRec = [SELECT ID FROM RecordType WHERE Name = 'Dealer'];
    List<User> user_Obj  =  [SELECT Id,Username,LastName,Email,IsActive,ProfileId,EmployeeNumber,Vertical_Type__c from User];
    System.assertEquals(true,user_Obj.size()>0);
    List<Account> account_Obj  =  [SELECT Id,OwnerID,Name,Type,RecordTypeId,ParentId,BillingStreet,BillingCity,BillingState,BillingPostalCode,BillingCountry,Party_Type__c,Inactive_Mobile_No__c,System_Flag__c,Account_Status_Flag__c,Bandhan_Cutsomer__c,Geolocation__Latitude__s,Geolocation__Longitude__s,Geolocation__c from Account];
    System.assertEquals(true,account_Obj.size()>0);
    List<Promotion__c> promotions_Obj  =  [SELECT Id,Name,Type__c from Promotion__c];
    System.assertEquals(true,promotions_Obj.size()>0);
    List<AP_Site_Visit__c> ap_site_visit_Obj  =  [SELECT Id,Name,Vendor__c,RecordTypeId,AP_Tour_Plan__c,Action_Date__c,Date__c,Generate_Order__c,Party_Type__c,RecordEdit__c,Target__c,Verified__c,Retailing_Day__c,Geo_Location__Latitude__s,Geo_Location__Longitude__s,Geo_Location__c,Adopted_Plumber__c,Adopted_Dealer__c from AP_Site_Visit__c];
    System.assertEquals(true,ap_site_visit_Obj.size()>0);
    GeoLocationController obj01 = new GeoLocationController();
    String type = 'Dealer';
    obj01.objectList = new list<SelectOption>();
    obj01.selectedObject = 'Visits';
    obj01.accountType = new list<selectoption>();
    obj01.selectedAccountType = '01230000001DIllAAG';
    obj01.visitList = ap_site_visit_Obj;
    obj01.fromDate = Date.today();
    obj01.toDate = Date.today();
    obj01.showRecords();
  }
 
}