Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/AP_Site_Visit__c.object-meta.xml
<CustomObject>
    <label>APPL Site Visit</label>
    <nameField>
        <displayFormat>Visit-{000000}</displayFormat>
        <label>AP Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Party_Name__c.field-meta.xml
<CustomField>
    <fullName>Party_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Name/Firm Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Party_Type__c</field>
            <operation>equals</operation>
            <valueField>Account.Party_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Party_Name__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/New_Special_Pricing_Request__c.object-meta.xml
<CustomObject>
    <description>This object stores all the line items that are checked and sent for SPR. The group of items that are selected goes for SPR everytime the project is sent for approval.</description>
    <label>New Special Pricing Request</label>
    <nameField>
        <displayFormat>SPR-{00}</displayFormat>
        <label>SPR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New Special Pricing Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Additional_Disc_on_APPL_disc2__c.field-meta.xml
<CustomField>
    <fullName>Additional_Disc_on_APPL_disc2__c</fullName>
    <description>A number field but if want to use it then please consider this as a Percent and do the required calculations</description>
    <formula>((MRP_Post_Discount2__c -  Net_Invoice_Value_from_APPL2__c ) /  MRP_Post_Discount2__c)*100</formula>
    <label>Additional Disc on APPL disc2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/APPL__c.field-meta.xml
<CustomField>
    <fullName>APPL__c</fullName>
    <label>APPL Discount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Approval_Rejection_Date__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rejection_Date__c</fullName>
    <formula>Unique_SPR__r.Approved_Rejected_Date__c</formula>
    <label>Approval/Rejection Date</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <formula>text(Unique_SPR__r.Approval_Status__c)</formula>
    <label>Approval Status</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Approver_Comments__c.field-meta.xml
<CustomField>
    <fullName>Approver_Comments__c</fullName>
    <description>This field captures the latest comment by the approver</description>
    <label>Approver Comments</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/CTC_Value__c.field-meta.xml
<CustomField>
    <fullName>CTC_Value__c</fullName>
    <description>CTC Calculation</description>
    <formula>( MRP_Value__c -  Net_Invoice_Value_from_APPL2__c )/ MRP_Value__c</formula>
    <label>CTC Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Discounted_Price2__c.field-meta.xml
<CustomField>
    <fullName>Discounted_Price2__c</fullName>
    <formula>IF( ISBLANK(Extra_Discount__c),
MRP_Post_Discount2__c ,
ABS( (MRP_Value__c) - ( Extra_Discount__c * MRP_Value__c)))</formula>
    <label>Discounted Price2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <formula>Unique_SPR__r.Distributor__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Distributor</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Extra_Discount__c.field-meta.xml
<CustomField>
    <fullName>Extra_Discount__c</fullName>
    <label>Extra Discount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/MRP_Post_Discount2__c.field-meta.xml
<CustomField>
    <fullName>MRP_Post_Discount2__c</fullName>
    <formula>(MRP_Value__c)-( APPL__c * MRP_Value__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MRP Post Discount2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Net_Invoice_Value_from_APPL2__c.field-meta.xml
<CustomField>
    <fullName>Net_Invoice_Value_from_APPL2__c</fullName>
    <description>The net invoice value from APPL</description>
    <formula>If( ISBLANK(ORC_MARGIN_TO_DLR_DIST__c ), Discounted_Price2__c , ABS(((100 - (ORC_MARGIN_TO_DLR_DIST__c * 100))/100) * Discounted_Price2__c))</formula>
    <label>Net Invoice Value from APPL2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Offer_Probability__c.field-meta.xml
<CustomField>
    <fullName>Offer_Probability__c</fullName>
    <label>Offer Probability</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>&lt;50%</fullName>
            </value>
            <value>
                <fullName>60%</fullName>
            </value>
            <value>
                <fullName>70%</fullName>
            </value>
            <value>
                <fullName>80%</fullName>
            </value>
            <value>
                <fullName>90%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100% advance with PO</fullName>
            </value>
            <value>
                <fullName>20% advance &amp; Balance against Delivery</fullName>
            </value>
            <value>
                <fullName>30 days after delivery</fullName>
            </value>
            <value>
                <fullName>45 days after delivery</fullName>
            </value>
            <value>
                <fullName>60 days after delivery</fullName>
            </value>
            <value>
                <fullName>90 days after delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Product_name__c.field-meta.xml
<CustomField>
    <fullName>Product_name__c</fullName>
    <label>Product name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup to opportunity (Project ) object</description>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>New Special Pricing Requests</relationshipLabel>
    <relationshipName>New_Special_Pricing_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Tentative_Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Tentative_Order_Date__c</fullName>
    <label>Tentative Order Date</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <description>This field is used for storing the name that is collectively given for each line item</description>
    <label>Unique Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Unique_SPR__c.field-meta.xml
<CustomField>
    <fullName>Unique_SPR__c</fullName>
    <description>related to the unique spr.</description>
    <label>Unique SPR</label>
    <referenceTo>Unique_SPR__c</referenceTo>
    <relationshipLabel>New Special Pricing Requests</relationshipLabel>
    <relationshipName>New_Special_Pricing_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/Unique_SPR__c.object-meta.xml
<CustomObject>
    <description>This object contains the unique name of each spr. Uniqueness is valid for a specific project. This record goes for approval in the new revamp structure.</description>
    <label>Unique SPR</label>
    <nameField>
        <displayFormat>UN-{000}</displayFormat>
        <label>Unique Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unique SPRs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Approval_date__c.field-meta.xml
<CustomField>
    <fullName>Approval_date__c</fullName>
    <label>Approval date</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Approved_Rejected_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Rejected_Date__c</fullName>
    <description>Captures the current date when the spr was approved or rejected</description>
    <formula>IF(ISPICKVAL( Approval_Status__c , &apos;Approved&apos;) ||  ISPICKVAL( Approval_Status__c , &apos;Rejected&apos;),
 TODAY() , NULL )</formula>
    <label>Approved/Rejected Date</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Approved_Rejected_Date_WF__c.field-meta.xml
<CustomField>
    <fullName>Approved_Rejected_Date_WF__c</fullName>
    <label>Approved/Rejected Date WF</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Average_Discount_Provided__c.field-meta.xml
<CustomField>
    <fullName>Average_Discount_Provided__c</fullName>
    <description>According to this discount the approval goes to respective manager or jayant kumar</description>
    <formula>(( MRP_Post_Discount_Sum__c -  Net_Invoice_Value_APPL_Sum__c )/ MRP_Post_Discount_Sum__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Average Discount Provided</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Unique SPRs</relationshipLabel>
    <relationshipName>Unique_SPRs</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/L1_Approver__c.field-meta.xml
<CustomField>
    <fullName>L1_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>if average is less than 7.5 then approval goes to this user. Project owner initial project approver</description>
    <inlineHelpText>if average is less than 7.5 then approval goes to this user. Project owner initial project approver</inlineHelpText>
    <label>L1 Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unique_SPRs</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/L2_Approver__c.field-meta.xml
<CustomField>
    <fullName>L2_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>if average is greater than 7.5 then approval goes to this user. Project owner Project approver</description>
    <inlineHelpText>if average is greater than 7.5 then approval goes to this user. Project owner Project approver</inlineHelpText>
    <label>L2 Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unique_SPRs1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Unique SPRs</relationshipLabel>
    <relationshipName>Unique_SPRs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Project_Number__c.field-meta.xml
<CustomField>
    <fullName>Project_Number__c</fullName>
    <formula>Project__r.Project_Number__c</formula>
    <label>Project Number</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Record_App_Rej_By__c.field-meta.xml
<CustomField>
    <fullName>Record_App_Rej_By__c</fullName>
    <description>Captures the name of the user who has approved or rejected this record. Populated through trigger</description>
    <inlineHelpText>Captures the name of the user who has approved or rejected this record. Populated through trigger</inlineHelpText>
    <label>Record App/Rej By</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <label>Unique Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/EmailToDistributorandCustomerController.cls
/**************************************************************************************************************************
Created By      :Subhajit Ghosh, KVP Business Soln
Created Date    :1.10.2019
Modified Date   :
Description     : Whenever the email Customer/ Email To DP button is checked the email with this template is fired to the customer


***********************************************************************************************************************************/

public class EmailToDistributorandCustomerController {
    public String oppId{get;set;}
    public Integer count{get;set;}
    public String uniqueSprId{get;set;}
    public String uniqueSprName{get;set;}
    public String projectName{get;set;}
    public String DistributorName{get;set;}
    public String customerName{get;set;}
    public opportunity oppDetails{get;set;}
    public string OriginalApprover{get;set;}
    public String OwnerName{get;set;}
    public Unique_SPR__c uniqueSprRecord{get;set;}
    // public List<offerSectionParentWrapper> offSectionParentList{get;set;}
    public List<New_Special_Pricing_Request__c> approvedSprList{get;set;}
    public EmailToDistributorandCustomerController(){
      uniqueSprRecord=new Unique_SPR__c(); 
        approvedSprList=new list<New_Special_Pricing_Request__c>();
        oppId=ApexPages.currentPage().getParameters().get('projectId');
        system.debug('oppId--'+oppId);
        uniqueSprId=ApexPages.currentPage().getParameters().get('uniqueSPRId');
        system.debug('uniqueSprId--'+uniqueSprId);
        if(uniqueSprId != NULL && oppId != NULL){
            
            uniqueSprRecord=[SELECT id,Approved_Rejected_Date__c,Approved_Rejected_Date_WF__c,Approval_Status__c,Approval_date__c,Average_Discount_Provided__c,CreatedDate,L1_Approver__r.Name,L2_Approver__r.Name,Approver_Comments__c,Project__r.Owner.Name,Record_App_Rej_By__c FROM Unique_SPR__c where 
                            id=: uniqueSprId LIMIT 1];
            if(uniqueSprRecord.Average_Discount_Provided__c <= 7.5){
                OriginalApprover=uniqueSprRecord.L1_Approver__r.Name;
            }else{
                 OriginalApprover=uniqueSprRecord.L2_Approver__r.Name;
            }
            
            OwnerName=uniqueSprRecord.Project__r.Owner.Name;
            approvedSprList=[SELECT ID,Product_name__c,APPL__c,CTC_Value__c,Discounted_Price2__c,Extra_Discount__c,
                             MRP_Post_Discount2__c,MRP_Value__c,Net_Invoice_Value_from_APPL2__c,Price_List_Date__c,Offer_Probability__c,Additional_Disc_on_APPL_disc2__c,
                             ORC_MARGIN_TO_DLR_DIST__c,Reason__c,Project__c,Project_Value__c,Tentative_Order_Date__c,Validity_for_the_Price__c,Approval_Rejection_Date__c,Unique_SPR__r.Unique_Name__c 
                             FROM New_Special_Pricing_Request__c where Approval_Status__c=:'Approved' AND Unique_SPR__c=: uniqueSprId AND Project__c =: oppId];
            
            uniqueSprName=approvedSprList[0].Unique_SPR__r.Unique_Name__c ;
            
            
            oppDetails=[SELECT Id,Project_By__r.Name,Name,Freight__c,Project_Number__c,Average_Discount_Provided__c,Delivery__c,Price_Basis__c,No_of_Bathrooms__c,No_of_Floors__c,Delivery_Lots__c,Project_Type__c,CloseDate,Distributor__r.Name,Taxes__c,
                        Offer_Valid_Till__c,Project_Location__c,Number_of_towers__c,State_Auto_Populate__c,Project_By__c,Number_of_kitchens__c,Payment_Term__c,Delivery_Conditions_Gurantee__c,Order_Placement__c FROM Opportunity WHERE Id =:oppId LIMIT 1];
            
            RecordType Rt = [select Id from RecordType where Name ='Project Visit' and SobjectType = 'AP_Site_Visit__c'];
            List<AP_Site_Visit__c> l = [select id from AP_Site_Visit__c where Party_Name__c=:oppDetails.Project_By__c AND Project_Name__c=:oppId AND AP_Site_Visit__c.recordtypeId =: Rt.id ];
            count=l.size();
        }
    }
    

}