Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/AP_Site_Visit__c.object-meta.xml
<CustomObject>
    <label>APPL Site Visit</label>
    <nameField>
        <displayFormat>Visit-{000000}</displayFormat>
        <label>AP Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Othet_Activities__c.field-meta.xml
<CustomField>
    <fullName>Othet_Activities__c</fullName>
    <label>Other Activities</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exhibitions/Shows</fullName>
            </value>
            <value>
                <fullName>Depot Meet/Office Meet</fullName>
            </value>
            <value>
                <fullName>Holiday/ Market Closed</fullName>
            </value>
            <value>
                <fullName>Leave</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Promotional Activity</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Post Visit Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <description>Target</description>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/recordTypes/brandingVist.recordType-meta.xml
<RecordType>
    <fullName>brandingVist</fullName>
    <active>true</active>
    <label>brandingVist</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/recordTypes/Visits.recordType-meta.xml
<RecordType>
    <fullName>Visits</fullName>
    <active>true</active>
    <label>Visits</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/No_of_days_worked_BrandingVisit_visits__c.field-meta.xml
<CustomField>
    <fullName>No_of_days_worked_BrandingVisit_visits__c</fullName>
    <label>No of days worked BrandingVisit(visits)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/No_of_days_worked_in_month_Office__c.field-meta.xml
<CustomField>
    <fullName>No_of_days_worked_in_month_Office__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of days worked in month(Office)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/No_of_days_worked_in_month_visit__c.field-meta.xml
<CustomField>
    <fullName>No_of_days_worked_in_month_visit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of days worked in month(visit)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/No_of_days_worked_ProjectVisit_visits__c.field-meta.xml
<CustomField>
    <fullName>No_of_days_worked_ProjectVisit_visits__c</fullName>
    <label>No of days worked ProjectVisit(visits)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Projects</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/classes/No_of_days_worked_Visits.cls
public class No_of_days_worked_Visits {
   public static void visitisertmethod(list<AP_Site_Visit__c> visitlist){
        set<id> targetid= new set<id>();
        set<date> dateid= new set<date>();
        list<id> targetIdList= new list<id>();
        list<Target__C> Targetlisttoupdate= new list<Target__C>();
        list<date> dateidlist= new list<date>();
        map<id,map<date,integer>> visitmap= new map<id,map<date,integer>>();
        map<id,map<date,integer>> otheractivitymap= new map<id,map<date,integer>>();
        
        try{
            if(!visitlist.IsEmpty()){
                for(AP_Site_Visit__c ap:visitlist){
                    system.debug('ap.Othet_Activities__c:: ' + ap.Othet_Activities__c);
                    if(ap.Othet_Activities__c != 'Leave' && ap.Othet_Activities__c != 'Holiday/ Market Closed'){
                    targetid.add(ap.Target__c);
                    system.debug('entering if::');
                    }
                   /* else{
                        targetid.add(ap.Target__c);
                        system.debug('entering else::');
                    }*/
                }
            }
            list<AP_Site_Visit__c> aplist=[select id,name,recordtype.name,target__C,Date__c from AP_Site_Visit__c where target__C IN : targetid and (recordtype.name='Other Activities' OR  recordtype.name='Visits')  ];
            system.debug('tset list today------->'+aplist);
            if(!aplist.IsEmpty()){
                for(AP_Site_Visit__c a:aplist){
                    
                    map<date,integer> datemap= new map<date,integer>();
                    if(a.recordtype.name=='Visits'){
                        /*system.debug('test 1'+visitmap.isEmpty());
                         system.debug('test 2'+visitmap.get(a.Target__c).isEmpty());
                         system.debug('test 3'+visitmap.containsKey(a.Target__c));*/
                        if(!visitmap.isEmpty() &&  !visitmap.get(a.Target__c).isEmpty() && visitmap.containsKey(a.Target__c)){ 
                            
                            datemap.putAll(visitmap.get(a.Target__c));
                            datemap.put(a.Date__c,(datemap.containsKey(a.Date__c)?datemap.get(a.Date__c):0)+1);
                            visitmap.put(a.Target__c,datemap);
                        }else{
                            datemap.put(a.Date__c, 1);
                            visitmap.put(a.Target__c,datemap);
                            System.debug('visitmap'+visitmap);
                            
                        }
                        
                    }else if(a.recordtype.name=='Other Activities'){
                        system.debug('visit......'+a);
                        system.debug('recordtype...'+a.recordtype.name);
                        map<date,integer> otherdatemap= new map<date,integer>();
                        system.debug('otheractivitymap empty ' + otheractivitymap.isEmpty());
                        if(!otheractivitymap.isEmpty() &&  !otheractivitymap.get(a.Target__c).IsEmpty() && otheractivitymap.containsKey(a.Target__c)){ 
                            //system.debug('otherdatemap..keyset....'+otherdatemap.KeySet());
                            otherdatemap.putAll(otheractivitymap.get(a.Target__c));
                            // system.debug('otherdatemap..keyset....'+otherdatemap.KeySet());
                            //system.debug('otherdatemap values......'+otherdatemap.Values());
                            otherdatemap.put(a.Date__c,(otherdatemap.containsKey(a.Date__c)?otherdatemap.get(a.Date__c):0)+1);
                            
                            otheractivitymap.put(a.Target__c,otherdatemap);
                        }else{
                            
                            otherdatemap.put(a.Date__c, 1);
                            otheractivitymap.put(a.Target__c,otherdatemap);
                            //system.debug('test.......otherdatemap'+otherdatemap);
                            // system.debug('test.......otheractivitymap'+otheractivitymap);
                            
                        }
                        
                    }
                    targetid.add(a.Target__c);
                    dateid.add(a.Date__c);
                }
                //targetIdList.addAll(targetid);
                dateidlist.addAll(dateid);
                system.debug('targetid in list...'+targetIdList);
                system.debug('targetid in dateidlist list...'+dateidlist);
            }
            list<Target__C> tarlist= [select id,name,No_of_days_worked_in_month_visit__c,No_of_days_worked_in_month_Office__c from Target__c where ID IN:targetid];
            for(Target__C tar:tarlist){
                Target__c t= new Target__c();
                t.id=tar.id;
                map<Date, integer> tempOmap = new map<Date, integer>();
                map<Date, integer> tempVmap = new map<Date, integer>();
                if(otheractivitymap.get(tar.ID) != null)
                    tempOmap = otheractivitymap.get(tar.ID);
                if(visitmap.get(tar.ID) != null)
                    tempVmap = visitmap.get(tar.ID);
                system.debug('tempOmap'+tempOmap);
                system.debug('tempVmap'+tempvmap);
                for(date eachdate:dateidlist){
                    
                    system.debug('tempVmap get...'+tempVmap.get(eachdate));
                    system.debug('tempOmap get...'+tempOmap.get(eachdate));
                    if((tempVmap.get(eachdate)!= null?tempVmap.get(eachdate):0)>(tempOmap.get(eachdate)!= null?tempOmap.get(eachdate):0)){
                        
                        t.No_of_days_worked_in_month_visit__c=(t.No_of_days_worked_in_month_visit__c != null?t.No_of_days_worked_in_month_visit__c:0)+1;
                    }else if((tempOmap.get(eachdate)!= null?tempOmap.get(eachdate):0)>(tempVmap.get(eachdate)!= null?tempVmap.get(eachdate):0)){
                        t.No_of_days_worked_in_month_Office__c=(t.No_of_days_worked_in_month_Office__c != null?t.No_of_days_worked_in_month_Office__c:0)+1;
                        
                    }else if((tempVmap.get(eachdate)!= null?tempVmap.get(eachdate):0)==(tempOmap.get(eachdate)!= null?tempOmap.get(eachdate):0)){
                        system.debug(t.No_of_days_worked_in_month_visit__c);
                        t.No_of_days_worked_in_month_visit__c=(t.No_of_days_worked_in_month_visit__c != null?t.No_of_days_worked_in_month_visit__c:0)+1;
                    }
                    Targetlisttoupdate.add(t);
                    
                }
                
            }
            map<id,target__c> tempmap= new map<id,target__c>();
            tempmap.putAll(Targetlisttoupdate);
            if(!tempmap.IsEmpty()){
                update tempmap.Values();
            }
            system.debug('visitmap....final----'+visitmap);
            system.debug('otheractivitymap....final---'+otheractivitymap);
        }catch(exception e){
            system.debug('exception,,,,..............no of visit handler'+e+'.........'+e.getLineNumber());
        }
        
    }
    public static void projectvisitisertmethod(list<AP_Site_Visit__c> visitlist){
        set<id> targetid= new set<id>();
        set<date> dateid= new set<date>();
        list<id> targetIdList= new list<id>();
        list<Target__C> Targetlisttoupdate= new list<Target__C>();
        list<date> dateidlist= new list<date>();
        map<id,map<date,integer>> visitmap= new map<id,map<date,integer>>();
        map<id,map<date,integer>> otheractivitymap= new map<id,map<date,integer>>();
        
        try{
            if(!visitlist.IsEmpty()){
                for(AP_Site_Visit__c ap:visitlist){
                    system.debug('ap.Othet_Activities__c:: ' + ap.Othet_Activities__c);
                    if(ap.Othet_Activities__c != 'Leave' && ap.Othet_Activities__c != 'Holiday/ Market Closed'){
                    targetid.add(ap.Target__c);
                    system.debug('entering if::');
                    }
                   /* else{
                        targetid.add(ap.Target__c);
                        system.debug('entering else::');
                    }*/
                }
            }
            list<AP_Site_Visit__c> aplist=[select id,name,recordtype.name,target__C,Date__c from AP_Site_Visit__c where target__C IN : targetid and (recordtype.name='brandingVist' OR  recordtype.name='Project Visit')  ];
            system.debug('tset list today------->'+aplist);
            if(!aplist.IsEmpty()){
                for(AP_Site_Visit__c a:aplist){
                    
                    map<date,integer> datemap= new map<date,integer>();
                    if(a.recordtype.name=='Project Visit'){
                        /*system.debug('test 1'+visitmap.isEmpty());
                         system.debug('test 2'+visitmap.get(a.Target__c).isEmpty());
                         system.debug('test 3'+visitmap.containsKey(a.Target__c));*/
                        if(!visitmap.isEmpty() &&  !visitmap.get(a.Target__c).isEmpty() && visitmap.containsKey(a.Target__c)){ 
                            
                            datemap.putAll(visitmap.get(a.Target__c));
                            datemap.put(a.Date__c,(datemap.containsKey(a.Date__c)?datemap.get(a.Date__c):0)+1);
                            visitmap.put(a.Target__c,datemap);
                        }else{
                            datemap.put(a.Date__c, 1);
                            visitmap.put(a.Target__c,datemap);
                            System.debug('visitmap'+visitmap);
                            
                        }
                        
                    }else if(a.recordtype.name=='brandingVist'){
                        system.debug('visit......'+a);
                        system.debug('recordtype...'+a.recordtype.name);
                        map<date,integer> otherdatemap= new map<date,integer>();
                        system.debug('otheractivitymap empty ' + otheractivitymap.isEmpty());
                        if(!otheractivitymap.isEmpty() &&  !otheractivitymap.get(a.Target__c).IsEmpty() && otheractivitymap.containsKey(a.Target__c)){ 
                            //system.debug('otherdatemap..keyset....'+otherdatemap.KeySet());
                            otherdatemap.putAll(otheractivitymap.get(a.Target__c));
                            // system.debug('otherdatemap..keyset....'+otherdatemap.KeySet());
                            //system.debug('otherdatemap values......'+otherdatemap.Values());
                            otherdatemap.put(a.Date__c,(otherdatemap.containsKey(a.Date__c)?otherdatemap.get(a.Date__c):0)+1);
                            
                            otheractivitymap.put(a.Target__c,otherdatemap);
                        }else{
                            
                            otherdatemap.put(a.Date__c, 1);
                            otheractivitymap.put(a.Target__c,otherdatemap);
                            //system.debug('test.......otherdatemap'+otherdatemap);
                            // system.debug('test.......otheractivitymap'+otheractivitymap);
                            
                        }
                        
                    }
                    targetid.add(a.Target__c);
                    dateid.add(a.Date__c);
                }
                //targetIdList.addAll(targetid);
                dateidlist.addAll(dateid);
                system.debug('targetid in list...'+targetIdList);
                system.debug('targetid in dateidlist list...'+dateidlist);
            }
            list<Target__C> tarlist= [select id,name,No_of_days_worked_BrandingVisit_visits__c,No_of_days_worked_ProjectVisit_visits__c from Target__c where ID IN:targetid];
            for(Target__C tar:tarlist){
                Target__c t= new Target__c();
                t.id=tar.id;
                map<Date, integer> tempOmap = new map<Date, integer>();
                map<Date, integer> tempVmap = new map<Date, integer>();
                tempOmap = otheractivitymap.get(tar.ID);
                tempVmap = visitmap.get(tar.ID);
                system.debug('tempOmap'+tempOmap);
                system.debug('tempVmap'+tempvmap);
                for(date eachdate:dateidlist){
                    
                    system.debug('tempVmap get...'+tempVmap.get(eachdate));
                    system.debug('tempOmap get...'+tempOmap.get(eachdate));
                    if((tempVmap.get(eachdate)!= null?tempVmap.get(eachdate):0)>(tempOmap.get(eachdate)!= null?tempOmap.get(eachdate):0)){
                        
                        t.No_of_days_worked_ProjectVisit_visits__c=(t.No_of_days_worked_ProjectVisit_visits__c != null?t.No_of_days_worked_ProjectVisit_visits__c:0)+1;
                    }else if((tempOmap.get(eachdate)!= null?tempOmap.get(eachdate):0)>(tempVmap.get(eachdate)!= null?tempVmap.get(eachdate):0)){
                        t.No_of_days_worked_BrandingVisit_visits__c=(t.No_of_days_worked_BrandingVisit_visits__c != null?t.No_of_days_worked_BrandingVisit_visits__c:0)+1;
                        
                    }else if((tempVmap.get(eachdate)!= null?tempVmap.get(eachdate):0)==(tempOmap.get(eachdate)!= null?tempOmap.get(eachdate):0)){
                        system.debug(t.No_of_days_worked_ProjectVisit_visits__c);
                        t.No_of_days_worked_ProjectVisit_visits__c=(t.No_of_days_worked_ProjectVisit_visits__c != null?t.No_of_days_worked_ProjectVisit_visits__c:0)+1;
                    }
                    Targetlisttoupdate.add(t);
                    
                }
                
            }
            map<id,target__c> tempmap= new map<id,target__c>();
            tempmap.putAll(Targetlisttoupdate);
            if(!tempmap.IsEmpty()){
                update tempmap.Values();
            }
            system.debug('visitmap....final----'+visitmap);
            system.debug('otheractivitymap....final---'+otheractivitymap);
        }catch(exception e){
            system.debug('exception,,,,..............no of visit handler'+e+'.........'+e.getLineNumber());
        }
        
    }
    public static void deletemethod(list<AP_Site_Visit__c> Oldlist){
        set<id> targetid= new set<id>();
        set<date> dateid= new set<date>();
        list<id> targetIdList= new list<id>();
        list<Target__C> Targetlisttoupdate= new list<Target__C>();
        list<date> dateidlist= new list<date>();
        map<id,map<date,integer>> visitmap= new map<id,map<date,integer>>();
        map<id,map<date,integer>> otheractivitymap= new map<id,map<date,integer>>();
        
        try{
            if(!Oldlist.IsEmpty()){
                for(AP_Site_Visit__c ap:Oldlist){
                    if(ap.Othet_Activities__c!='Leave' && ap.Othet_Activities__c!='Holiday/ Market Closed'){
                    targetid.add(ap.Target__c);
                    }
                }
            }
            list<AP_Site_Visit__c> aplist=[select id,name,recordtype.name,target__C,Date__c from AP_Site_Visit__c where target__C IN : targetid and (recordtype.name='Other Activities' OR  recordtype.name='Visits') ];
           system.debug('tset list today delete------->'+aplist);
            if(!aplist.IsEmpty()){
                for(AP_Site_Visit__c a:aplist){
                    
                    map<date,integer> datemap= new map<date,integer>();
                    if(a.recordtype.name=='Visits'){
                        if(!visitmap.isEmpty() &&  !visitmap.get(a.Target__c).isEmpty() && visitmap.containsKey(a.Target__c)){ 
                            
                            datemap.putAll(visitmap.get(a.Target__c));
                            datemap.put(a.Date__c,(datemap.containsKey(a.Date__c)?datemap.get(a.Date__c):0)+1);
                            visitmap.put(a.Target__c,datemap);
                        }else{
                            datemap.put(a.Date__c, 1);
                            visitmap.put(a.Target__c,datemap);
                            
                        }
                        
                    }else if(a.recordtype.name=='Other Activities'){
                        system.debug('visit......'+a);
                        system.debug('recordtype...'+a.recordtype.name);
                        map<date,integer> otherdatemap= new map<date,integer>();
                        if(!otheractivitymap.isEmpty() &&  !otheractivitymap.get(a.Target__c).IsEmpty() && otheractivitymap.containsKey(a.Target__c)){ 
                            //system.debug('otherdatemap..keyset....'+otherdatemap.KeySet());
                            otherdatemap.putAll(otheractivitymap.get(a.Target__c));
                            // system.debug('otherdatemap..keyset....'+otherdatemap.KeySet());
                            //system.debug('otherdatemap values......'+otherdatemap.Values());
                            otherdatemap.put(a.Date__c,(otherdatemap.containsKey(a.Date__c)?otherdatemap.get(a.Date__c):0)+1);
                            
                            otheractivitymap.put(a.Target__c,otherdatemap);
                        }else{
                            
                            otherdatemap.put(a.Date__c, 1);
                            otheractivitymap.put(a.Target__c,otherdatemap);
                            //system.debug('test.......otherdatemap'+otherdatemap);
                            // system.debug('test.......otheractivitymap'+otheractivitymap);
                            
                        }
                        
                    }
                    targetid.add(a.Target__c);
                    dateid.add(a.Date__c);
                }
                //targetIdList.addAll(targetid);
                dateidlist.addAll(dateid);
                system.debug('targetid in list...'+targetIdList);
                system.debug('targetid in dateidlist list...'+dateidlist);
            }
            list<Target__C> tarlist= [select id,name,No_of_days_worked_in_month_visit__c,No_of_days_worked_in_month_Office__c from Target__c where ID IN:targetid];
            for(Target__C tar:tarlist){
                Target__c t= new Target__c();
                t.id=tar.id;
                map<Date, integer> tempOmap = new map<Date, integer>();
                map<Date, integer> tempVmap = new map<Date, integer>();
                tempOmap = otheractivitymap.get(tar.ID);
                tempVmap = visitmap.get(tar.ID);
                system.debug('tempOmap'+tempOmap);
                system.debug('tempVmap'+tempvmap);
                for(date eachdate:dateidlist){
                    
                    system.debug('tempVmap get...'+tempVmap.get(eachdate));
                    system.debug('tempOmap get...'+tempOmap.get(eachdate));
                    if((tempVmap.get(eachdate)!= null?tempVmap.get(eachdate):0)>(tempOmap.get(eachdate)!= null?tempOmap.get(eachdate):0)){
                        
                        t.No_of_days_worked_in_month_visit__c=(t.No_of_days_worked_in_month_visit__c != null?t.No_of_days_worked_in_month_visit__c:0)+1;
                    }else if((tempOmap.get(eachdate)!= null?tempOmap.get(eachdate):0)>(tempVmap.get(eachdate)!= null?tempVmap.get(eachdate):0)){
                        t.No_of_days_worked_in_month_Office__c=(t.No_of_days_worked_in_month_Office__c != null?t.No_of_days_worked_in_month_Office__c:0)+1;
                        
                    }else if((tempVmap.get(eachdate)!= null?tempVmap.get(eachdate):0)==(tempOmap.get(eachdate)!= null?tempOmap.get(eachdate):0)){
                        system.debug(t.No_of_days_worked_in_month_visit__c);
                        t.No_of_days_worked_in_month_visit__c=(t.No_of_days_worked_in_month_visit__c != null?t.No_of_days_worked_in_month_visit__c:0)+1;
                    }
                    Targetlisttoupdate.add(t);
                    
                }
                
            }
            map<id,target__c> tempmap= new map<id,target__c>();
            tempmap.putAll(Targetlisttoupdate);
            if(!tempmap.IsEmpty()){
                update tempmap.Values();
            }
            system.debug('visitmap....final----'+visitmap);
            system.debug('otheractivitymap....final---'+otheractivitymap);
        }catch(exception e){
            system.debug('exception,,,,..............no of visit handler'+e+'.........'+e.getLineNumber());
        }
    }
    public static void projectVisitDeletemethod(list<AP_Site_Visit__c> Oldlist){
        set<id> targetid= new set<id>();
        set<date> dateid= new set<date>();
        list<id> targetIdList= new list<id>();
        list<Target__C> Targetlisttoupdate= new list<Target__C>();
        list<date> dateidlist= new list<date>();
        map<id,map<date,integer>> visitmap= new map<id,map<date,integer>>();
        map<id,map<date,integer>> otheractivitymap= new map<id,map<date,integer>>();
        
        try{
            if(!Oldlist.IsEmpty()){
                for(AP_Site_Visit__c ap:Oldlist){
                    if(ap.Othet_Activities__c!='Leave' && ap.Othet_Activities__c!='Holiday/ Market Closed'){
                    targetid.add(ap.Target__c);
                    }
                }
            }
            list<AP_Site_Visit__c> aplist=[select id,name,recordtype.name,target__C,Date__c from AP_Site_Visit__c where target__C IN : targetid and (recordtype.name='brandingVist' OR  recordtype.name='Project Visit') ];
           system.debug('tset list today delete------->'+aplist);
            if(!aplist.IsEmpty()){
                for(AP_Site_Visit__c a:aplist){
                    
                    map<date,integer> datemap= new map<date,integer>();
                    if(a.recordtype.name=='Project Visit'){
                        if(!visitmap.isEmpty() &&  !visitmap.get(a.Target__c).isEmpty() && visitmap.containsKey(a.Target__c)){ 
                            
                            datemap.putAll(visitmap.get(a.Target__c));
                            datemap.put(a.Date__c,(datemap.containsKey(a.Date__c)?datemap.get(a.Date__c):0)+1);
                            visitmap.put(a.Target__c,datemap);
                        }else{
                            datemap.put(a.Date__c, 1);
                            visitmap.put(a.Target__c,datemap);
                            
                        }
                        
                    }else if(a.recordtype.name=='brandingVist'){
                        system.debug('visit......'+a);
                        system.debug('recordtype...'+a.recordtype.name);
                        map<date,integer> otherdatemap= new map<date,integer>();
                        if(!otheractivitymap.isEmpty() &&  !otheractivitymap.get(a.Target__c).IsEmpty() && otheractivitymap.containsKey(a.Target__c)){ 
                            //system.debug('otherdatemap..keyset....'+otherdatemap.KeySet());
                            otherdatemap.putAll(otheractivitymap.get(a.Target__c));
                            // system.debug('otherdatemap..keyset....'+otherdatemap.KeySet());
                            //system.debug('otherdatemap values......'+otherdatemap.Values());
                            otherdatemap.put(a.Date__c,(otherdatemap.containsKey(a.Date__c)?otherdatemap.get(a.Date__c):0)+1);
                            
                            otheractivitymap.put(a.Target__c,otherdatemap);
                        }else{
                            
                            otherdatemap.put(a.Date__c, 1);
                            otheractivitymap.put(a.Target__c,otherdatemap);
                            //system.debug('test.......otherdatemap'+otherdatemap);
                            // system.debug('test.......otheractivitymap'+otheractivitymap);
                            
                        }
                        
                    }
                    targetid.add(a.Target__c);
                    dateid.add(a.Date__c);
                }
                //targetIdList.addAll(targetid);
                dateidlist.addAll(dateid);
                system.debug('targetid in list...'+targetIdList);
                system.debug('targetid in dateidlist list...'+dateidlist);
            }
            list<Target__C> tarlist= [select id,name,No_of_days_worked_BrandingVisit_visits__c,No_of_days_worked_ProjectVisit_visits__c  from Target__c where ID IN:targetid];
            for(Target__C tar:tarlist){
                Target__c t= new Target__c();
                t.id=tar.id;
                map<Date, integer> tempOmap = new map<Date, integer>();
                map<Date, integer> tempVmap = new map<Date, integer>();
                tempOmap = otheractivitymap.get(tar.ID);
                tempVmap = visitmap.get(tar.ID);
                system.debug('tempOmap'+tempOmap);
                system.debug('tempVmap'+tempvmap);
                for(date eachdate:dateidlist){
                    
                    system.debug('tempVmap get...'+tempVmap.get(eachdate));
                    system.debug('tempOmap get...'+tempOmap.get(eachdate));
                    if((tempVmap.get(eachdate)!= null?tempVmap.get(eachdate):0)>(tempOmap.get(eachdate)!= null?tempOmap.get(eachdate):0)){
                        
                        t.No_of_days_worked_ProjectVisit_visits__c=(t.No_of_days_worked_ProjectVisit_visits__c != null?t.No_of_days_worked_ProjectVisit_visits__c:0)+1;
                    }else if((tempOmap.get(eachdate)!= null?tempOmap.get(eachdate):0)>(tempVmap.get(eachdate)!= null?tempVmap.get(eachdate):0)){
                        t.No_of_days_worked_BrandingVisit_visits__c=(t.No_of_days_worked_BrandingVisit_visits__c != null?t.No_of_days_worked_BrandingVisit_visits__c:0)+1;
                        
                    }else if((tempVmap.get(eachdate)!= null?tempVmap.get(eachdate):0)==(tempOmap.get(eachdate)!= null?tempOmap.get(eachdate):0)){
                        system.debug(t.No_of_days_worked_ProjectVisit_visits__c);
                        t.No_of_days_worked_ProjectVisit_visits__c=(t.No_of_days_worked_ProjectVisit_visits__c != null?t.No_of_days_worked_ProjectVisit_visits__c:0)+1;
                    }
                    Targetlisttoupdate.add(t);
                    
                }
                
            }
            map<id,target__c> tempmap= new map<id,target__c>();
            tempmap.putAll(Targetlisttoupdate);
            if(!tempmap.IsEmpty()){
                update tempmap.Values();
            }
            system.debug('visitmap....final----'+visitmap);
            system.debug('otheractivitymap....final---'+otheractivitymap);
        }catch(exception e){
            system.debug('exception,,,,..............no of visit handler'+e+'.........'+e.getLineNumber());
        }
    }  
    public static void testMethod_1(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}