Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/AP_Site_Visit__c.object-meta.xml
<CustomObject>
    <label>APPL Site Visit</label>
    <nameField>
        <displayFormat>Visit-{000000}</displayFormat>
        <label>AP Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/AP_Tour_Plan__c.field-meta.xml
<CustomField>
    <fullName>AP_Tour_Plan__c</fullName>
    <label>Tour Plan</label>
    <referenceTo>AP_Tour_Plan__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Party_Name__c.field-meta.xml
<CustomField>
    <fullName>Party_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party Name/Firm Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Party_Type__c</field>
            <operation>equals</operation>
            <valueField>Account.Party_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Retailing_Day__c.field-meta.xml
<CustomField>
    <fullName>Retailing_Day__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retailing Day</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <description>Target</description>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/recordTypes/Visits.recordType-meta.xml
<RecordType>
    <fullName>Visits</fullName>
    <active>true</active>
    <label>Visits</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/AP_Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>APPL Tour Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>AP TourPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPL Tour Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>APPL Tour Plans</relationshipLabel>
    <relationshipName>AP_TourPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/Test_AP_Site_Visit_Trigger.cls
/*  
    Author: Satyanarayana
    Description : SMART KRA Controller : Generate SMART KRA Report for particular Month based on the User Test class.
    Date : 06/07/2015    */
@istest
public class Test_AP_Site_Visit_Trigger {
	
	public static Target__c target;
	public static Target__c target1;
    public static AP_Tour_Plan__c tourplan;
    public static User userdata;
    public static AP_Site_Visit__c sitevisit;
    public static AP_Site_Visit__c sitevisit1;
    public static AP_Site_Visit__c sitevisit2;
    public static AP_Site_Visit__c sitevisit3;
    public static void init() {
    	
	        Account objAcct = Test_Utilclass.ObjAcct();
	        objAcct.Contact_Number_Mobile__c = '9603612607';
	        objAcct.recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual Contacts').getRecordTypeId();
	        insert  objAcct;
	        
	        userdata = Test_Intial_Data_Phase2.ColumnRH('First','Last','System Administrator');
	        insert userdata ;
	        
	        target1 = Test_Intial_Data_Phase2.CreateTarget(userdata);
	        insert target1;
	        
	        target = Test_Intial_Data_Phase2.CreateTarget(userdata);
	        insert target;
	        tourplan  = Test_Intial_Data_Phase2.CreateTourPlan(target.Id);
	        tourplan.Target__c = target.ID;
	        insert tourplan;
	        
	        sitevisit = Test_Intial_Data_Phase2.createSiteVisit(tourplan.Id, 'Visits');
	        sitevisit.Target__c = target.ID;
	        sitevisit.AP_Tour_Plan__c = tourplan.Id;
	        sitevisit.Date__c = date.today();
	        sitevisit.Party_Name__c = objAcct.id;
	        insert sitevisit;
	        
	        sitevisit1 = Test_Intial_Data_Phase2.createSiteVisit(tourplan.Id, 'Visits');
	        sitevisit1.Target__c = target.ID;
	        sitevisit1.AP_Tour_Plan__c = tourplan.Id;
	        //sitevisit1.Party_Name__c = objAcct.id;
	        sitevisit1.Date__c = date.today();
	        insert sitevisit1;
        
            sitevisit3 = Test_Intial_Data_Phase2.createSiteVisit(tourplan.Id, 'Visits');
	        sitevisit3.Target__c = target.ID;
	        sitevisit3.AP_Tour_Plan__c = tourplan.Id;
	        //sitevisit1.Party_Name__c = objAcct.id;
	        sitevisit3.Date__c = date.today()+1;
	        insert sitevisit3;
	        
	        sitevisit2 = Test_Intial_Data_Phase2.createSiteVisit(tourplan.Id, 'Visits');
	        sitevisit2.Target__c = target.ID;
	        sitevisit2.AP_Tour_Plan__c = tourplan.Id;
	        sitevisit2.Date__c = date.today();
	        //sitevisit2.Party_Name__c = objAcct.id;
	        sitevisit2.Retailing_Day__c = true;
	        insert sitevisit2;
	  
    }
     public static testmethod void testone() {
        
         init();
        test.startTest();
      		AP_Site_Visit__c sitevisit12 = Test_Intial_Data_Phase2.createSiteVisit(tourplan.Id, 'Visits');
	        sitevisit12.Target__c = target.ID;
	        sitevisit12.AP_Tour_Plan__c = tourplan.Id;
	        sitevisit12.Date__c = date.today();
	        //sitevisit12.Party_Name__c = objAcct.id;
	        insert sitevisit12;
        test.stopTest();
    }
    
   
    
    
}