Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/AP_Site_Visit__c.object-meta.xml
<CustomObject>
    <label>APPL Site Visit</label>
    <nameField>
        <displayFormat>Visit-{000000}</displayFormat>
        <label>AP Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/AP_Tour_Plan__c.field-meta.xml
<CustomField>
    <fullName>AP_Tour_Plan__c</fullName>
    <label>Tour Plan</label>
    <referenceTo>AP_Tour_Plan__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <description>Target</description>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>AP Site Visits</relationshipLabel>
    <relationshipName>AP_Site_Visits</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Site_Visit__c/recordTypes/Visits.recordType-meta.xml
<RecordType>
    <fullName>Visits</fullName>
    <active>true</active>
    <label>Visits</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/AP_Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>APPL Tour Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>AP TourPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPL Tour Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>APPL Tour Plans</relationshipLabel>
    <relationshipName>AP_TourPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/No_of_Visits_Actual_Project__c.field-meta.xml
<CustomField>
    <fullName>No_of_Visits_Actual_Project__c</fullName>
    <label>No of Visits Actual(Project)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/NoOfProjectVisitRollUp_Batch.cls
/***************************************************
 * Name:SudhaMurthy
 * Description: Batch class to send email to user if less than 40 viists a week
 * Trigger:AdoptedPlumberAndDealer 
 * Test class:Test_RollupInfluencerVisitsColumn
 * created date :12/08/2019***********************/
 global class NoOfProjectVisitRollUp_Batch implements Database.Batchable<sObject>{
 
 list<AP_Site_Visit__c> visitlist1= [select id,name,AP_Tour_Plan__r.ownerId,Target__R.No_of_Visits_Actual_Project__c,Target__R.id,Target__R.ownerId from AP_Site_Visit__c  where Action_Date__c=THIS_WEEK];
  string visitlist= 'select id,name,Target__R.No_of_Visits_Actual_Project__c,AP_Tour_Plan__r.ownerId,Target__R.id,Target__R.ownerId from AP_Site_Visit__c where createddate=THIS_WEEK';
  
 
  //start method
  global  database.QueryLocator start(Database.BatchableContext BC)
    {
     
     return Database.getQueryLocator(visitlist);
    } 
     global void execute(Database.BatchableContext BC, List<AP_Site_Visit__c> scope)
    {
     Map<id, list<AP_Site_Visit__c>> visitmap= new Map<id, list<AP_Site_Visit__c>>();
         system.debug('list..'+scope);
         system.debug('list..'+scope.size());
      for(AP_Site_Visit__c visit : scope){
       system.debug('visit '+visit.AP_Tour_Plan__r.ownerId);
          system.debug('visit *** '+visit.Target__R.No_of_Visits_Actual_Project__c);
      if(visit.Target__R.No_of_Visits_Actual_Project__c<40 ){ 
          system.debug('visit 22*** '+visit.Target__R.No_of_Visits_Actual_Project__c);
           if(!visitmap.isEmpty() && visitmap.containsKey(visit.AP_Tour_Plan__r.ownerId) && visitmap.get(visit.AP_Tour_Plan__r.ownerId) != null) {
              
                 visitmap.get(visit.AP_Tour_Plan__r.ownerId).add(visit);
                //  visitmap.put(visit.AP_Tour_Plan__r.ownerId, visitmap.get(visit.AP_Tour_Plan__r.ownerId).add(visit));
                  system.debug('visitmap1'+visitmap);
               
                   system.debug('test owner'+visitmap.get(visit.AP_Tour_Plan__r.ownerId));
               } else {
                   visitmap.put(visit.AP_Tour_Plan__r.ownerId, new List<AP_Site_Visit__c>{visit});
                system.debug('test..'+visitmap.size());
               }
            }
       }
        list<user> userlist=[select id,name,email from user where id IN:visitmap.keyset()];
       List<Messaging.SingleEmailMessage> allMails = new List<Messaging.SingleEmailMessage>();
       system.debug('map...'+visitmap.keyset());
             system.debug('userlist which has less visit'+userlist);
                
          if(!userlist.IsEmpty() && userlist.size()>0){     
               for(User val : userlist){
            
                 Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                 Messaging.reserveSingleEmailCapacity(1);
                 mail.setToAddresses(new String[] { val.Email });
                 mail.setReplyTo(val.Email);
                 mail.setSubject('Warning:Less visits this week');
                 mail.setPlainTextBody('Hi ,\r\n\r\nTotal no of visits in this week is less than 40.Please ensure to make atleast 8 visits per day.Otherwise this may affect your attendance..\r\n\r\n\r\n[Note:Kindly do not reply to this email.The emails to this account are not monitored]');                  
                  allMails.add(mail);
                 
                 system.debug('####'+val.id);
                 
            }
         } 
          Messaging.sendEmail(allMails );  
       
    }
    global void finish(Database.BatchableContext BC)
    {
       
    } 
 }