Partial_14Dec2021/force-app/main/default/objects/Complaints__c/Complaints__c.object-meta.xml
<CustomObject>
    <label>Complaints</label>
    <nameField>
        <displayFormat>CASE-{0000}</displayFormat>
        <label>Complaint Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SVN-{00000000}</displayFormat>
        <label>Site Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Site_Visit__c/fields/Call_Center_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Call_Center_Remarks__c</fullName>
    <label>Call Center Remarks</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Site_Visit__c/fields/Complaint__c.field-meta.xml
<CustomField>
    <fullName>Complaint__c</fullName>
    <label>Complaint</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wrong/Invalid Number</fullName>
            </value>
            <value>
                <fullName>Not Attended</fullName>
            </value>
            <value>
                <fullName>BDM Response Poor</fullName>
            </value>
            <value>
                <fullName>Supply not in Time</fullName>
            </value>
            <value>
                <fullName>Service Poor</fullName>
            </value>
            <value>
                <fullName>Technical Issues</fullName>
            </value>
            <value>
                <fullName>Branding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Site_Visit__c/fields/Complaints__c.field-meta.xml
<CustomField>
    <fullName>Complaints__c</fullName>
    <label>Complaints</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wrong/Invalid Number</fullName>
            </value>
            <value>
                <fullName>Not Attended</fullName>
            </value>
            <value>
                <fullName>BDM Response Poor</fullName>
            </value>
            <value>
                <fullName>Supply not in Time</fullName>
            </value>
            <value>
                <fullName>Service Poor</fullName>
            </value>
            <value>
                <fullName>Technical Issues</fullName>
            </value>
            <value>
                <fullName>Branding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Site_Visit__c/fields/Verification_Type__c.field-meta.xml
<CustomField>
    <fullName>Verification_Type__c</fullName>
    <label>Verification Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Suggestion</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/SiteVisitTaskHandler.cls
public class SiteVisitTaskHandler{
    
    Public static void createSiteVisitTasks(Map<Id,Site_Visit__c> mapTriggerNew,Map<Id,Site_Visit__c> mapTriggerOld){
        Map<id,Id> mapUserIdVsMgrId = new Map<id,Id>(); 
        List<Task> lstTask = new List<Task>();
           
        for(user u :[Select id,email,ManagersId__c from User where isActive = true and ManagersId__c <> null]){ 
            mapUserIdVsMgrId.put(u.id, u.ManagersId__c);    
        }
          
        for(Site_Visit__c p: mapTriggerNew.Values()){
            if(p.Verified__c = true && ((p.Verification_Type__c == 'Complaint' && p.Verification_Type__c <> mapTriggerOld.get(p.Id).Verification_Type__c)
                                          || (p.Verification_Type__c == 'Suggestion' && p.Verification_Type__c <> mapTriggerOld.get(p.Id).Verification_Type__c)
                                          ||  (p.Verification_Type__c == 'Suggestion;Complaint' && p.Verification_Type__c <> mapTriggerOld.get(p.Id).Verification_Type__c))){
                if(mapUserIdVsMgrId.containsKey(p.CreatedById)){
                    
                    for(integer i=0; i<=1; i++){
                        Task t = new task();
                        if(i == 0){
                            t.ownerid = p.CreatedById;
                        }
                        if(i == 1){
                            t.ownerid = mapUserIdVsMgrId.get(p.CreatedById);
                        }
                        t.Call_Center_Comments__c = p.Call_Center_Remarks__c;
                        t.WhatId = p.id;
                        t.Suggestion__c = p.Suggestion__c;
                        t.Complaint__c = p.Complaints__c;
                        t.ActivityDate = system.today();
                        t.Priority = 'Normal';
                        if(p.Verification_Type__c == 'Suggestion'){
                           t.Subject = 'SiteVisit Suggestion'; 
                        }
                        else{
                            t.Subject = 'SiteVisit Complaint';
                        }
                        
                        lstTask.add(t);
                   }
                }
            } 
        }

        if(!lstTask.isEMpty()){
            insert lstTask;
        }   
    }
}