Partial_14Dec2021/force-app/main/default/objects/Complaints__c/Complaints__c.object-meta.xml
<CustomObject>
    <label>Complaints</label>
    <nameField>
        <displayFormat>CASE-{0000}</displayFormat>
        <label>Complaint Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Complaints__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/Promotion_Member__c.object-meta.xml
<CustomObject>
    <label>Promotion Member</label>
    <nameField>
        <displayFormat>PM-{YY}-{MM}-{DD}-{00}</displayFormat>
        <label>Promotion Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Promotion_Members1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Call_Status__c.field-meta.xml
<CustomField>
    <fullName>Call_Status__c</fullName>
    <label>Call Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Reachable</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>RNR</fullName>
            </value>
            <value>
                <fullName>Wrong/Invalid Number</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Person not available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Complaints__c.field-meta.xml
<CustomField>
    <fullName>Complaints__c</fullName>
    <label>Complaints</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wrong/Invalid Number</fullName>
            </value>
            <value>
                <fullName>Not Attended</fullName>
            </value>
            <value>
                <fullName>BDM Response Poor</fullName>
            </value>
            <value>
                <fullName>Supply not in Time</fullName>
            </value>
            <value>
                <fullName>Service Poor</fullName>
            </value>
            <value>
                <fullName>Technical Issues</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/ToDeactivateAccountOnInvalicPhNo.cls
/*********************************************************************************************************************************
Name: ToDeactivateAccountOnInvalicPhNo
Description: To populate respective values in fields, which depends on Call Status.
Created By: Rakesh Mallya(KVP Business Solutions Pvt. Ltd.)
Created Date: 25/07/2018  
*********************************************************************************************************************************/
public class ToDeactivateAccountOnInvalicPhNo{
    public static void ValueAssigningMethod(List<Promotion_Member__c> proMembList){       
        for(Promotion_Member__c pro : proMembList){
            if(pro.Call_Status__c == 'Wrong/Invalid Number'){
                pro.Call_Center_Remarks__c = 'Phone number is Wrong/Invalid';
                pro.Complaints__c = 'Wrong/Invalid Number';               
            }else if(pro.Call_Status__c == 'Person not available'){
                pro.Call_Center_Remarks__c = 'Required person is not available';              
            }else if(pro.Call_Status__c == 'Busy'){
                pro.Call_Center_Remarks__c = 'Person is busy';              
            }else if(pro.Call_Status__c == 'RNR'){
                pro.Call_Center_Remarks__c = 'Ring Not Response';              
            }else if(pro.Call_Status__c == 'Not Reachable'){
                pro.Call_Center_Remarks__c = 'Not Reachable';               
            }
        } 
    }//end of DeactivatingMethod
    
    public static void InactivatingAccountMethod(List<Promotion_Member__c> proMembList){
        List<Account> accList = new List<Account>(); 
        List<Promotion_Member__c> proList = new List<Promotion_Member__c>(); 
        Set<ID> accIDSet = new Set<ID>();
        for(Promotion_Member__c pro : proMembList){
            if(pro.Call_Status__c == 'Wrong/Invalid Number'){
                accIDSet.add(pro.Account__c); 
            }
        }   
        accList = [SELECT ID,Inactive_Mobile_No__c FROM Account WHERE ID IN: accIDSet]; 
        for(Account acc : accList){
            acc.Inactive_Mobile_No__c = True;
            acc.Preference__c = '';
            acc.Status__c = 'Prospective';
        }
        update accList;
    }//end of InactivatingAccountMethod  
    
}//end of class