Partial_14Dec2021/force-app/main/default/objects/Distributor_Dealer__c/Distributor_Dealer__c.object-meta.xml
<CustomObject>
    <label>Distributor/Dealer(O)</label>
    <nameField>
        <label>Firm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors/Dealers(O)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Distributor_Dealer__c/fields/Contact_Number_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number_Mobile__c</fullName>
    <label>Contact Number (Mobile)</label>
    <type>Phone</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Distributor_Dealer__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aqua Life</fullName>
            </value>
            <value>
                <fullName>Column Pipes</fullName>
            </value>
            <value>
                <fullName>CPVC</fullName>
            </value>
            <value>
                <fullName>SWR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Distributor_Dealer__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu and Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
            <value>
                <fullName>Pondicherry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Distributor_Dealer__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dealer</fullName>
                <default>true</default>
                <label>Dealer</label>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Promotion No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer(o)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Distributor_Dealer__c.Type__c</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Distributor_Dealer__c</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Total_no_of_attendees__c.field-meta.xml
<CustomField>
    <fullName>Total_no_of_attendees__c</fullName>
    <label>No. of members attended</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Architects / Engineers / Consultants Factory Visit</fullName>
            </value>
            <value>
                <fullName>Architects Meets</fullName>
            </value>
            <value>
                <fullName>Boarers Meets</fullName>
            </value>
            <value>
                <fullName>Builders Meets</fullName>
            </value>
            <value>
                <fullName>Column Dealer / Distributor Meets</fullName>
            </value>
            <value>
                <fullName>Column Distributors / Dealers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Column DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Engineers Meets</fullName>
            </value>
            <value>
                <fullName>Exhibition / Agri Fairs</fullName>
            </value>
            <value>
                <fullName>Exhibition / Construction Fairs</fullName>
            </value>
            <value>
                <fullName>Group Activity</fullName>
            </value>
            <value>
                <fullName>Inshop Boarers Meets</fullName>
            </value>
            <value>
                <fullName>Inshop Mechanic Meets</fullName>
            </value>
            <value>
                <fullName>Inshop Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Jeep Campaign</fullName>
            </value>
            <value>
                <fullName>Mechanics Factory Visit</fullName>
            </value>
            <value>
                <fullName>Mega Farmer Meets</fullName>
            </value>
            <value>
                <fullName>Mega Mechanic Meets</fullName>
            </value>
            <value>
                <fullName>Mega Plumbers Meets</fullName>
            </value>
            <value>
                <fullName>Mini Farmer Meet</fullName>
            </value>
            <value>
                <fullName>Naaka Meets</fullName>
            </value>
            <value>
                <fullName>Onsite Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Plumbers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealer / Distributor Meets</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealers Factory Visits</fullName>
            </value>
            <value>
                <fullName>Plumbing DSM Meet/Training</fullName>
            </value>
            <value>
                <fullName>Product Presentation</fullName>
            </value>
            <value>
                <fullName>Projects DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Shandy Shows</fullName>
            </value>
            <value>
                <fullName>Shop Anniversary Dinner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Column</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
            <value>
                <fullName>Branding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/Promotion_Member__c.object-meta.xml
<CustomObject>
    <label>Promotion Member</label>
    <nameField>
        <displayFormat>PM-{YY}-{MM}-{DD}-{00}</displayFormat>
        <label>Promotion Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Promotion_Members1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <formula>IF( ISBLANK(Contacts__c), Account__r.Contact_Number_Mobile__c, Contacts__r.Mobile__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Number</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Distributor_Dealer__c.Type__c</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Distributor_Dealer__c</referenceTo>
    <relationshipLabel>Promotion Members</relationshipLabel>
    <relationshipName>Promotion_Members1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Party_type__c.field-meta.xml
<CustomField>
    <fullName>Party_type__c</fullName>
    <formula>TEXT(Account__r.Party_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Party type</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Promotion_Member__c/fields/Promotions2__c.field-meta.xml
<CustomField>
    <fullName>Promotions2__c</fullName>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipName>Promotion_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/APPL_ADD_MEMBERS_DETAIL_CTRL.cls
public class APPL_ADD_MEMBERS_DETAIL_CTRL {

 
    public string mem{get;set;}
    public APPL_ADD_MEMBERS_DETAIL_CTRL cc;
      public String promotionId {get; set;}
      public Promotion__c newpromotion {get; set;}
     public static Promotion__c newpromotion1 {get; set;}
     public  string newpromotionId;
      public boolean showAddMemberPanel {get; set;}
      public list<string> productList {get; set;}
      public String accRecTypeId {get; set;}
      public String dealerRtId {get; set;}
      public String directDealerId {get; set;}
      public String distrubutorId {get; set;}
      public integer oldNumber {get; set;}
      public boolean validationCheck {get; set;}
      //public boolean isDinner {get; set;}
      public Boolean showMemberSaveBtn {get; set;}
      public list<Promotion_Member__c> oldMembersAdded {get; set;}
      public Set<String>  oldPromoMembers {get; set;}
      public list<Account> proAccounts {get; set;}
      public boolean errorFlag{get;set;}
      public string incompleteAccount{get;set;}
      public String accToRemove{get;set;}
      public String accToRefresh{get;set;}
      public Boolean validationRequired{get;set;}
      public Boolean disabled{get; set;}
     
    public APPL_ADD_MEMBERS_DETAIL_CTRL(ApexPages.StandardController controller) {
       
        
       // mem=0;
       // isDinner = false;
        showMemberSaveBtn                =     true;
        newpromotion                     =     new Promotion__c();
        showAddMemberPanel               =     false;
        proAccounts                      =     new List<Account>();
        productList                      =     new List<String>();
        validationCheck                  =     false;
        oldPromoMembers                  =     new Set<String>();
        validationRequired =false;
        disabled=true;
         //Getting Products of Travel Dynamic
         Schema.DescribeFieldResult productsResult = Account.Products__c.getDescribe();
         list<Schema.PicklistEntry> pro = productsResult.getPicklistValues();
         
         for( Schema.PicklistEntry f : pro) {
            productList.add(f.getValue());
         }

        //Get the Account Record Type.

        for(RecordType rt : [SELECT DeveloperName,Id,Name FROM RecordType WHERE SobjectType = 'Account']) {

          if(rt.DeveloperName == 'Dealer') {
            dealerRtId = rt.id;
          }else if(rt.DeveloperName == 'Direct_Dealer') {
             directDealerId = rt.id;
          }else if(rt.DeveloperName == 'Distributor') {
             distrubutorId = rt.id;
          }else if(rt.DeveloperName == 'Individual_Contacts') {
             accRecTypeId = rt.id;//individaul contacts
          }
        }

        promotionId = ApexPages.currentPage().getParameters().get('id');
          newpromotion1= new Promotion__c();
        if(promotionId != null && promotionId != '') {
            newpromotion = [Select Id, Name,Vertical__c, Total_no_of_attendees__c,Type__c from Promotion__c where Id =:promotionId];
            newpromotion1=newpromotion;
            newpromotionId = newpromotion.Type__c;
        }
        
        oldNumber = Integer.valueOf(newpromotion.Total_no_of_attendees__c);
        newpromotion.Total_no_of_attendees__c = null;
        
        //Get the Members Already added to Promotion
        oldMembersAdded     =   new List<Promotion_Member__c>();
        oldMembersAdded     =   [Select Id,Account__c,Contact_Number__c from Promotion_Member__c where Promotions2__c =:promotionId];

        if(!oldMembersAdded.isEmpty()) {
          for(Promotion_Member__c oldMember : oldMembersAdded) {
              oldPromoMembers.add(oldMember.Contact_Number__c);
          }
        }
        errorFlag=false;
    }

    
    
    public void ShowMembers() {
               showAddMemberPanel = true;
        
        try {
            for(Integer i=0; i<newpromotion.Total_no_of_attendees__c;i++){
                
                    proAccounts.add(new Account());
                
            }
                
             
    } catch(exception ex){
              ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,ex.getMessage()));
       // ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,ex.getLineNumber()));
        
        }
     }
  
    
     public PageReference more() {
        String numbr=Apexpages.currentPage().getParameters().get('addrowsvalue');
        system.debug('adddding membersssss'+numbr);
        //showAddMemberPanel = true;
        Integer newAddMore=Integer.valueOf(numbr);
        try {
        System.debug(proAccounts.size());
            for(Integer i=0; i<newAddMore;i++)
             proAccounts.add(new Account());
            System.debug(proAccounts.size());
             return null;
    } catch(exception ex){
              ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,ex.getMessage()));
              return null;
        }
     }
  

   public PageReference addMember() {
      
    system.debug('No. Of Members ='+newpromotion.Total_no_of_attendees__c);
    proAccounts.add(new Account());
    system.debug(proAccounts);
    system.debug(proAccounts.size());
    return null;
   }

    /*  Search Customer based on the Name. */
   @RemoteAction
     public static list<Account> getCustomer( string cusMob, string promotype) {
        list<account> accList = new list<Account>();
        try {
            //system.debug('---rectype id is---'+recTypeId);
            if(promotype=='Shop Anniversary Dinner'){ 
            System.debug(promotype);
            accList = [SELECT Id,Name,recordTypeId,Contact_Number_Mobile__c,PARTY_type__c FROM Account WHERE  PARTY_type__c='Dealers Salesman' AND Contact_Number_Mobile__c LIKE :cusMob+'%'];
            }else{
            accList = [SELECT Id,Name,recordTypeId,Contact_Number_Mobile__c FROM Account WHERE Contact_Number_Mobile__c LIKE :cusMob+'%'];
            }
            System.debug(accList);
        } catch(Exception e) {
            system.debug(e.getMessage());
        }
        return accList;
    }


     //Action Fucntion proAccounts
    public PageReference getAccoutRow(){

       String tempRow = String.valueOf(ApexPages.currentPage().getParameters().get('rowIndex'));
       String mobileNumber = String.valueOf(ApexPages.currentPage().getParameters().get('cusMobile'));

       Integer rowNumber = Integer.valueOf(tempRow);
       system.debug('RowNumber ='+rowNumber);
       system.debug('mobileNumber ='+mobileNumber);
       system.debug('proAccounts ='+proAccounts.get(rowNumber-1));

       List<Account> accList = new List<Account>();

       accList = [Select RecordTypeId,Id, Name, Dealer__r.name,Dealer__c, Account__r.name,Account__c, Contact_Number_Mobile__c,Taluk_Tehsil__c,Visit_Type__c, Firm_Name__c,State__c, District__c, City__c,Contact_Number_Phone__c, Status__c,
                   PIN_Code__c,Party_Type__c, Primary_Contact_Person_Name__c, Products__c,Street_Address__c,Custom_Dealer_LookUp__c,Custom_Distributor_LookUp__c,Custom_Taluk_LookUp__c,APPL_Taluk__c,APPL_Taluk__r.name from Account where Contact_Number_Mobile__c =:mobileNumber];
       system.debug('acc ='+accList);

       //Check for Null
       if( !accList.isEmpty() && accList.size() > 0){
           proAccounts.set(rowNumber-1, accList.get(0));
       }else{
          proAccounts.set(rowNumber-1, new Account(Contact_Number_Mobile__c =mobileNumber ));
       }
       if(proAccounts[rowNumber-1].District__c =='' || proAccounts[rowNumber-1].District__c==null){
            errorFlag=true;
            incompleteAccount='/'+proAccounts[rowNumber-1].Id;
       }
       else{
        errorFlag=false;
       }
      return null;
    }

    
    //Save Functionality
    public PageReference SavePromotionMembers(){
    validationRequired = true;
        PageReference pg ;
        List<Promotion_Member__c> pmsList = new List<Promotion_Member__c>();
        system.debug('Save Promomotion Members'+newpromotion.Id);

      try{
          
          if(newpromotion.Id != null){
            system.debug('Save Account Members'+proAccounts);

             for(Account acc : proAccounts){
                  acc.System_Flag__c = true;
                  /****acc.Account__c = acc.Custom_Distributor_LookUp__c;
                  acc.Dealer__c= acc.Custom_Dealer_LookUp__c;
                  acc.APPL_Taluk__c= acc.Custom_Taluk_LookUp__c;********/
                if(acc.RecordTypeId == null){
                     if(acc.Party_Type__c == 'Dealer'){
                              acc.recordtypeId = dealerRtId;
                        }else{
                               acc.recordtypeId = accRecTypeId;
                        } 
                  }
             }
              list<account> proAccountsInsert = new list<account>();
              list<account> proAccountsUpdate = new list<account>();
              for(account acc :proAccounts){
                  if(acc.id != null){
                     proAccountsUpdate.add(acc); 
                  }
                  else{
                      proAccountsInsert.add(acc);
                  }
              }

              set<id> failAccIds = new set<id>();
              Database.SaveResult[] srList = Database.update(proAccountsUpdate,false);
    Integer i=0;
    for (Database.SaveResult sr : srList) {
        if (!sr.isSuccess()) {
            for(Database.Error err : sr.getErrors()) { 
                System.debug(proAccountsUpdate.get(i).Id + ': ' + err.getMessage());
                 ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,err.getMessage()));
                failAccIds.add(proAccountsUpdate.get(i).Id);
            }
        }
        i++;
    }  
              Database.SaveResult[] srList1 = Database.Insert(proAccountsInsert,false);
    Integer i1=0;
    for (Database.SaveResult sr : srList1) {
        if (!sr.isSuccess()) {
            for(Database.Error err : sr.getErrors()) { 
                System.debug(proAccountsInsert.get(i1).Id + ': ' + err.getMessage());
                
                failAccIds.add(proAccountsInsert.get(i1).Id);
            }
        }
        i1++;
    }  
              string failedAccNames = '';
              if(failAccIds.size()>0){
                  for(Account acc :[select name from account where id in :failAccIds]){
                      failedAccNames+= acc.name+',';
                  }
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,'Please check their is an error in Account: '+failedAccNames+' ')); 
                  return null;
              }

                  // upsert proAccounts;
               set<account> proSetAccounts=new set<account>();
                proSetAccounts.addAll(proaccounts);
                
                for(Account acc : proSetAccounts){                           
                Promotion_Member__c pms = new Promotion_Member__c();
                pms.Account__c = acc.Id; 
                pms.Promotions2__c = newpromotion.Id;

                pmsList.add(pms);
              }   

              if(!pmsList.isEmpty()){
                  insert pmsList;
              }

              //Updating the Number of Members in Promotion
              if(proAccounts.size() != Integer.valueOf(newpromotion.Total_no_of_attendees__c)){
                system.debug('Members are not equal.. So Update it');
                newpromotion.Total_no_of_attendees__c = proAccounts.size();
                //Update newpromotion;
              }else{
                System.debug('Members are equal, So No Update..');
              }
          }
          ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Confirm,'Promotion Members Added Succesfully'));
          validationCheck = true;
          showMemberSaveBtn = false;
          disabled=false;
             pg = new PageReference('/'+newpromotion.Id);
             pg.setRedirect(true); 
             return pg ;
      }catch(exception ex){
          System.debug('********Promotion member List and Account List******'+pmsList +proAccounts);
          system.debug('*****exception********'+ex);
        validationCheck = false;
         // ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,'Exception when saving'+String.valueOf(ex)));
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error,'Exception: ' + ex.getTypeName() + ': ' + ex.getMessage() + ' -- ' + ex.getCause())); 
          showMemberSaveBtn = true;
          disabled=true;
          return null;
      } 
      
    }
    //Cancel
   public PageReference closeWindow(){
     PageReference pg = new PageReference('/'+newpromotion.Id);
      return pg;
   }

   //Delete Entry
    public PageReference DeleteEntry(){
    validationRequired = false;
   
    system.debug('proAccounts::'+proAccounts);
    //String tempRow = String.valueOf(ApexPages.currentPage().getParameters().get('rowIndex'));
   // String mobileNumber = String.valueOf(ApexPages.currentPage().getParameters().get('cusMobile'));
    Integer rowNumber = Integer.valueOf(accToRemove);
    system.debug('rowNumber:::'+ rowNumber );
    proAccounts.remove(rowNumber - 1);
    
    return null;
    }
    
    //Refresh Entry
    public PageReference RefreshEntry(){
    
        Integer rowNumber = Integer.valueOf(accToRemove);
        
       if(accToRefresh != ''){
        List<Account> accList = new List<Account>();
        accList = [Select RecordTypeId,Id, Name, Dealer__c,Dealer__r.Name, Account__c,Account__r.Name, Contact_Number_Mobile__c,Visit_Type__c, Firm_Name__c,State__c, District__c, City__c,Contact_Number_Phone__c, Status__c,
                    PIN_Code__c,Party_Type__c, Primary_Contact_Person_Name__c, Products__c,Street_Address__c,Taluk_Tehsil__c,Taluk_Tehsil__r.Name,Custom_Dealer_LookUp__c,Custom_Distributor_LookUp__c,Custom_Taluk_LookUp__c,APPL_Taluk__c,APPL_Taluk__r.name  from Account where Contact_Number_Mobile__c =:accToRefresh];
       
        if( !accList.isEmpty() && accList.size() > 0){
            proAccounts.set(rowNumber-1, accList.get(0));
        }else{
            proAccounts.set(rowNumber-1, new Account(Contact_Number_Mobile__c =accToRefresh));
        }
        }
        return null;
    }

    public void SaveBtnHide(){    //taken from production
        showMemberSaveBtn = true;
        disabled = true;
    }
}