Partial_14Dec2021/force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Custom Order Line Item object used after the project revamp</description>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{0000}</displayFormat>
        <label>Order Line Items Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Order_Line_Item__c/fields/APPL__c.field-meta.xml
<CustomField>
    <fullName>APPL__c</fullName>
    <label>APPL Discount</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order_Line_Item__c/fields/Extra_Discount__c.field-meta.xml
<CustomField>
    <fullName>Extra_Discount__c</fullName>
    <label>Extra Discount</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order_Line_Item__c/fields/MRP_Post_Discount__c.field-meta.xml
<CustomField>
    <fullName>MRP_Post_Discount__c</fullName>
    <label>MRP Post Discount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order_Line_Item__c/fields/MRP_Value__c.field-meta.xml
<CustomField>
    <fullName>MRP_Value__c</fullName>
    <label>MRP Value</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order_Line_Item__c/fields/Net_Invoice_Value_from_APPL2__c.field-meta.xml
<CustomField>
    <fullName>Net_Invoice_Value_from_APPL2__c</fullName>
    <formula>If( ISBLANK(ORC_MARGIN_TO_DLR_DIST__c ), Discounted_Price2__c , ABS(((100 - (ORC_MARGIN_TO_DLR_DIST__c * 100))/100) * Discounted_Price2__c))</formula>
    <label>Net Invoice Value from APPL2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order_Line_Item__c/fields/Offer_Probability__c.field-meta.xml
<CustomField>
    <fullName>Offer_Probability__c</fullName>
    <label>Offer Probability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&lt;50%</fullName>
            </value>
            <value>
                <fullName>60%</fullName>
            </value>
            <value>
                <fullName>70%</fullName>
            </value>
            <value>
                <fullName>80%</fullName>
            </value>
            <value>
                <fullName>90%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order_Line_Item__c/fields/ORC_MARGIN_TO_DLR_DIST__c.field-meta.xml
<CustomField>
    <fullName>ORC_MARGIN_TO_DLR_DIST__c</fullName>
    <label>ORC/ MARGIN TO DLR/DIST</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order_Line_Item__c/fields/ORC_Status__c.field-meta.xml
<CustomField>
    <fullName>ORC_Status__c</fullName>
    <label>ORC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Not Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order_Line_Item__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Received</fullName>
            </value>
            <value>
                <fullName>Part Received</fullName>
            </value>
            <value>
                <fullName>Order Lost</fullName>
            </value>
            <value>
                <fullName>Order Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order_Line_Item__c/fields/Order_Value__c.field-meta.xml
<CustomField>
    <fullName>Order_Value__c</fullName>
    <label>Order Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order_Line_Item__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20% advance with PO</fullName>
            </value>
            <value>
                <fullName>30 Days credit with PO</fullName>
            </value>
            <value>
                <fullName>90 Days credit with PO</fullName>
            </value>
            <value>
                <fullName>100% payment against delivery</fullName>
            </value>
            <value>
                <fullName>100% advance with PO</fullName>
            </value>
            <value>
                <fullName>20% advance &amp; Balance against Delivery</fullName>
            </value>
            <value>
                <fullName>30 days after delivery</fullName>
            </value>
            <value>
                <fullName>45 days after delivery</fullName>
            </value>
            <value>
                <fullName>60 days after delivery</fullName>
            </value>
            <value>
                <fullName>90 days after delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order_Line_Item__c/fields/Price_List_Date__c.field-meta.xml
<CustomField>
    <fullName>Price_List_Date__c</fullName>
    <label>Price List Date</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order_Line_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order_Line_Item__c/fields/Unique_Name_relation__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name_relation__c</fullName>
    <label>Unique Name relation</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order_Line_Item__c/fields/Validity_for_the_Price__c.field-meta.xml
<CustomField>
    <fullName>Validity_for_the_Price__c</fullName>
    <label>Validity for the Price</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/EditOrderPage2Controller.cls
public class EditOrderPage2Controller {
    Public List<Order_Line_Item__c> orderLineItemList{get;set;}
    public String ProjectId{get;set;}
    
    public EditOrderPage2Controller(){
        orderLineItemList=new List<Order_Line_Item__c>();
        ProjectId=ApexPages.currentPage().getParameters().get('id');
       orderLineItemList= [SELECT ID,Product_name__c, MRP_Post_Discount__c,Extra_Discount__c,Net_Invoice_Value_from_APPL2__c,ORC_Status__c,ORC_Markup__c,
                            Supply_End_Date__c,Competitors_name__c,ORC_MARGIN_TO_DLR_DIST__c,Payment_Terms__c,Project__c,APPL__c,Order_Status__c,Validity_for_the_Price__c,
                            Price_List_Date__c,Unique_Name_relation__c,Order_Value__c,Offer_Probability__c,MRP_Value__c,Tentative_Order_Date__c,Supply_Start_Date__c 
                             FROM Order_Line_Item__c WHERE Project__c=:ProjectId Order BY Product_name__c];
    }
    
    public PageReference onSave(){
        try{
            upsert orderLineItemList;
             PageReference pf = new PageReference('/'+ProjectId);
             return pf; 
            
        }
        catch(Exception e){
             PageReference pf = new PageReference('/'+ProjectId);
             return pf;
        }
    }
    
   public PageReference onCancel(){
        try{
             PageReference pf = new PageReference('/'+ProjectId);
             return pf; 
            
        }
        catch(Exception e){
             PageReference pf = new PageReference('/'+ProjectId);
             return pf;
        }
    }

}