Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/Tour_Program__c.object-meta.xml
<CustomObject>
    <label>Tour Program</label>
    <nameField>
        <label>Tour Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/Manager_ID__c.field-meta.xml
<CustomField>
    <fullName>Manager_ID__c</fullName>
    <formula>Owner:User.ManagerId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Manager ID</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/ProfileId__c.field-meta.xml
<CustomField>
    <fullName>ProfileId__c</fullName>
    <formula>CreatedBy.ProfileId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ProfileId</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/Tour_Program_Approved__c.field-meta.xml
<CustomField>
    <fullName>Tour_Program_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tour Program Approved</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/MassUpdateTourPlan.cls
/******************************************
 * Created By  : Ajeet Singh Shekhawat
 * Created On  : 04 Sep 2018
 * Modified By : 
 * Modified On : 04 Sep 2018
 * Description :  return type is wrapper class type which contains current user id along with Tour_Program__c object record
				
******************************************/ 


public class MassUpdateTourPlan {
    
    public class WrapMassUpdateTourPlan {
        @AuraEnabled public List<Tour_Program__c> tourDataWrapper {get; set;}
        @AuraEnabled public Id userIdWrapper {get; set;}
    }
    
	@AuraEnabled
    public static WrapMassUpdateTourPlan fetchTourProgramRecords (Id accountId) {
        try {
            
            Id userId;
            List<Tour_Program__c> tourData;
            userId = UserInfo.getUserId();
            tourData = [select ProfileId__c, Manager_ID__c, Tour_Program_Approved__c from Tour_Program__c 
                        	where Id =: accountId];
            
            WrapMassUpdateTourPlan wrapObject = new WrapMassUpdateTourPlan();
            wrapObject.tourDataWrapper = tourData;
            wrapObject.userIdWrapper = userId;
            System.debug('wrapObject ' + wrapObject);
            return wrapObject;
        } catch (Exception ex){
            throw new AuraHandledException('Something went wrong: '+ ex.getMessage());
        }        
    }
}