Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/Tour_Program__c.object-meta.xml
<CustomObject>
    <label>Tour Program</label>
    <nameField>
        <label>Tour Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/Expenses_Approved__c.field-meta.xml
<CustomField>
    <fullName>Expenses_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expenses Approved</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/BdExpense_Test.cls
@isTest
public class BdExpense_Test {
    static testMethod void BdExpenses() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        
        User u1 = new User(Alias = 'standt1',Country='India',Email='demo2@kvpdomain.com',EmailEncodingKey='UTF-8', 
                           LastName='KVPTesting2', LanguageLocaleKey='en_US',LocaleSidKey='en_US',ProfileId = p.Id,TimeZoneSidKey='America/Los_Angeles',
                           UserName='demo2@kvpdomain.com', EmployeeNumber = '10');
        
        Insert u1;
		Tour_Program__c tp = new Tour_Program__c();
        tp.Expenses_Approved__c = true;
        Insert tp;
        BdExpense.fetchprofilename(tp.Id);
    }
}