Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/Tour_Program__c.object-meta.xml
<CustomObject>
    <label>Tour Program</label>
    <nameField>
        <label>Tour Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/Tour_Program_Approved__c.field-meta.xml
<CustomField>
    <fullName>Tour_Program_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tour Program Approved</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/TourPlanMassUpdate_Test.cls
@isTest
public class TourPlanMassUpdate_Test {
    static testMethod void tourPlan() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        
        User u1 = new User(Alias = 'standt1',Country='India',Email='demo1@kvpdomain.com',EmailEncodingKey='UTF-8', 
                           LastName='KVPTesting', LanguageLocaleKey='en_US',LocaleSidKey='en_US',ProfileId = p.Id,TimeZoneSidKey='America/Los_Angeles',
                           UserName='demo1@kvpdomain.com', EmployeeNumber = '10');
        
        Insert u1;
        Tour_Program__c tp = new Tour_Program__c();
        tp.Tour_Program_Approved__c = true;
        
        Insert tp;
       // TourPlanMassUpdate tpms = new TourPlanMassUpdate();
        TourPlanMassUpdate.fetchMassupdateTP(tp.Id);
    }
}