Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/Vendor_Details__c.object-meta.xml
<CustomObject>
    <label>Vendor Details</label>
    <nameField>
        <label>Vendor Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vendor</description>
    <inlineHelpText>Vendor</inlineHelpText>
    <label>Vendor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vendor_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/fields/Vendor_Code__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Code__c</fullName>
    <description>Vendor Code</description>
    <inlineHelpText>Vendor Code</inlineHelpText>
    <label>Vendor Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/vendorController_UT.cls
@isTest
public class vendorController_UT{
   static testMethod void vendorControllerSearch(){
    
    Profile profile= [Select Id from Profile where name='System Administrator' limit 1];
    User user= new User( role__c='abc',FirstName='Test', LastName='User', alias='abcd', email='testuser@abc.com', username='testuser123@abc.com', profileId=profile.Id, TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
    insert user;
    
    User user2= new User( role__c='abc',FirstName='Test', LastName='User2', alias='abcd', email='testuser@abc.com', username='tes2tuser123@abc.com', profileId=profile.Id, TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
    insert user2;
     test.starttest();
     System.runAs(user)
    {
    Vendor_Details__c ven = new Vendor_Details__c();
    ven.name ='XYZ';
    ven.vendor_code__c ='111de';
    ven.Vendor__c=user2.id;
    insert ven;
   
     ApexPages.currentPage().getParameters().put('id',user.id);    
     ApexPages.StandardController sc = new ApexPages.StandardController(new User());
    vendorController UI= new vendorController((sc));
    UI.caseRecord.Vendor_Details__c = ven.id;
     UI.getVendorDetails();
      PageReference ref1=UI.saveVendorDetails();
     
    }    
    test.stoptest();
    
   }
}