Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/Vendor_Details__c.object-meta.xml
<CustomObject>
    <label>Vendor Details</label>
    <nameField>
        <label>Vendor Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vendor</description>
    <inlineHelpText>Vendor</inlineHelpText>
    <label>Vendor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vendor_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/fields/Vendor_Code__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Code__c</fullName>
    <description>Vendor Code</description>
    <inlineHelpText>Vendor Code</inlineHelpText>
    <label>Vendor Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/vendorController.cls
public with sharing class vendorController {

public String currentuserId{get;set;}

public String vendor{get; set;}

public String vendor_code{get; set;}

public String vendorId{get; set;}

public Case caseRecord{get; set;}

public Boolean flagVar{get;set;}

private ApexPages.StandardController stdCtrl;

    public vendorController(ApexPages.StandardController controller) {
    flagVar= false;
    stdCtrl=controller;
     currentuserId = System.currentPageReference().getParameters().get('id');
     system.debug('currentuserId');
     caseRecord = new Case();
    }

public PageReference saveVendorDetails(){
   User user = [select id,Vendor__c,Vendor_Code__c from user where id=:currentuserId];
   
  user.Vendor__c=vendorId;
   user.vendor_code__c =vendor_code;
   
   update user;
   flagVar= true;
   return null;
   }

public void getVendorDetails(){
//case cont=(case) stdCtrl.getRecord();
system.debug('cont::'+caseRecord.Vendor_Details__c+ 'cont::');
   if(caseRecord.Vendor_Details__c!=null){
   Vendor_Details__c venDetail =[select vendor__r.name,vendor__c, vendor_code__c from Vendor_Details__c where id=:caseRecord.Vendor_Details__c];

   vendor =venDetail.vendor__r.name;
   vendor_code=venDetail.vendor_code__c;
    vendorId =venDetail.vendor__c;
   }
   }

}