Partial_14Dec2021/force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <label>Enquiry  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Order_value_from_task__c.field-meta.xml
<CustomField>
    <fullName>Order_value_from_task__c</fullName>
    <description>To get the order value related to the enquiry</description>
    <label>Order value from task</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/Test_TriggerTopopluateOrderValue.cls
@isTest(SeeAllData=False)
public class Test_TriggerTopopluateOrderValue {
Public static TestMethod void test1(){

RecordType recrd=[Select Id,RecordType.Name From RecordType  Where SobjectType = 'Task' And RecordType.Name='Normal' limit 1];
//Task tasklist1=[Select WhatId ,RecordType.Name From Task where RecordType.Name='Normal'  AND What.type='Enquiry__c' limit 1];
System.debug('recrd'+recrd);
Enquiry__c acc =new Enquiry__c ();
acc.Name='test1';
insert acc;
Task tasklist=new Task();

tasklist.OwnerId=UserInfo.getUserId();//'00530000007uDS6AAM';
tasklist.ActivityDate=Date.Today();

tasklist.RecordTypeId=recrd.Id;//'01230000001DIvX';
tasklist.WhatId= acc.Id;//'a014C000000dJVmQAM';
tasklist.Order_value__c=123;
System.debug(tasklist);


Target__c newTarget =new Target__c();
newTarget.OwnerId=UserInfo.getUserId();//'00530000007uDS6AAM';
newTarget.End_Date__c=Date.Today();
newTarget.End_Date__c.addDays(37);
newTarget.Order_value_from_task__c =6;



tasklist.OwnerId = UserInfo.getUserId();
/*
  update tasklist;
List<Task>tsk=new List<Task>();
    tsk.add(tasklist);
*/
insert newTarget ;
    insert tasklist;
system.debug('Target'+newTarget );
system.debug('Task'+tasklist);
test.startTest();
try{
//Trigger_ToPopulateOrderValueFromTask.PopulateOrderValue(tsk);

}
catch(Exception exs){
System.debug(exs.getMessage());
}
test.StopTest();
}
}