Partial_14Dec2021/force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <label>Enquiry  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Order_value_from_task__c.field-meta.xml
<CustomField>
    <fullName>Order_value_from_task__c</fullName>
    <description>To get the order value related to the enquiry</description>
    <label>Order value from task</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/ToPopulateOrderValueFromTask.cls
global class ToPopulateOrderValueFromTask  implements Database.Batchable<sObject> {
      
    string tempName = 'Normal';
      string tempName2 = 'Enquiry__c';
    String query='Select OwnerId,Order_value__c,ActivityDate,What.type,RecordType.Name From Task where Recordtype.Name=:tempName AND Order_value__c!=null AND What.type=:tempName2 limit 40000';
    global Database.QueryLocator start(Database.BatchableContext BC) {
    
         
         
    return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC,List<Task> tasklist) {
        map<Id,Task> m=new map<Id,Task>();
                set<String> Ownernme=new set<String>();
    
   // List<Task> tasklist =[Select Owner.name,Order_value__c,ActivityDate,What.type,RecordType.Name From Task where RecordType.Name='Normal' AND Order_value__c!=null AND What.type='Enquiry__c' limit 4000];
    for(Task tsk:tasklist){
    Ownernme.add(tsk.OwnerId);
    m.put(tsk.OwnerId,tsk);
    }
         System.debug('Set'+Ownernme);
    Integer month1,month2;
    List<Target__c> targetList=[Select OwnerId,End_Date__c,Order_value_from_task__c From Target__c where OwnerId IN:Ownernme limit 4000];
    List<Target__c> newTargetUpdated =new List<Target__c>();
    for(Target__c targetlist2:targetList){
        
        try{
        if(m.containsKey(targetlist2.OwnerId)){
   if(m.get(targetlist2.OwnerId).ActivityDate!=null  && targetlist2.End_Date__c!=null){
           month1=targetlist2.End_Date__c.month();
        month2=m.get(targetlist2.OwnerId).ActivityDate.month();
  
        if(m.get(targetlist2.OwnerId)!=null  && m.get(targetlist2.OwnerId).Order_value__c!=null && month1==month2 ){

       targetlist2.Order_value_from_task__c=targetlist2.Order_value_from_task__c+m.get(targetlist2.OwnerId).Order_value__c;
    
  
    
    }
        }
        
    newTargetUpdated .add(targetlist2);
       }
        }
        catch(Exception e)
        {
            System.debug('The error is'+e.getMessage()+'At line number'+e.getLineNumber());
        }
        System.debug(' targetlist2'+targetlist2);
        
        }
    
  
     
      
      
    update newTargetUpdated ;
    system.debug(newTargetUpdated);
    
    }
    
    global void finish(Database.BatchableContext BC) {
    }
    
    }