Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/New_Offer_Section__c.object-meta.xml
<CustomObject>
    <description>We are using this as an alternative to the OpportunityLineItem. Data is created as soon as new project is inserted or edited. Data is calculated on the basis of ProbabilityMaster__c object</description>
    <label>New Offer Section</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New Offer Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/APPL__c.field-meta.xml
<CustomField>
    <fullName>APPL__c</fullName>
    <description>APPL Discount is based on the discount in different states</description>
    <label>APPL Discount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Delivery_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Schedule__c</fullName>
    <label>Delivery Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Qty</fullName>
            </value>
            <value>
                <fullName>1 LOT</fullName>
            </value>
            <value>
                <fullName>2 LOTS</fullName>
            </value>
            <value>
                <fullName>3 LOTS</fullName>
            </value>
            <value>
                <fullName>4 LOTS</fullName>
            </value>
            <value>
                <fullName>5 LOTS</fullName>
            </value>
            <value>
                <fullName>6 LOTS</fullName>
            </value>
            <value>
                <fullName>7 LOTS</fullName>
            </value>
            <value>
                <fullName>8 LOTS</fullName>
            </value>
            <value>
                <fullName>9 LOTS</fullName>
            </value>
            <value>
                <fullName>10 LOTS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>New Offer Sections</relationshipLabel>
    <relationshipName>New_Offer_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Extra_Discount__c.field-meta.xml
<CustomField>
    <fullName>Extra_Discount__c</fullName>
    <description>Extra discount on the APPL Discount</description>
    <label>Extra Discount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Lost_to_brand__c.field-meta.xml
<CustomField>
    <fullName>Lost_to_brand__c</fullName>
    <description>If the product status is loss the this field is mandatory</description>
    <label>Lost to brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACO</fullName>
            </value>
            <value>
                <fullName>Ajay NA</fullName>
            </value>
            <value>
                <fullName>Arecon</fullName>
            </value>
            <value>
                <fullName>Astral</fullName>
            </value>
            <value>
                <fullName>Cosmoplast</fullName>
            </value>
            <value>
                <fullName>Finolex</fullName>
            </value>
            <value>
                <fullName>Geberit</fullName>
            </value>
            <value>
                <fullName>George Fischer</fullName>
            </value>
            <value>
                <fullName>Hindware</fullName>
            </value>
            <value>
                <fullName>Jain Pipes</fullName>
            </value>
            <value>
                <fullName>Jaquar</fullName>
            </value>
            <value>
                <fullName>Kissan</fullName>
            </value>
            <value>
                <fullName>Kohler</fullName>
            </value>
            <value>
                <fullName>Oriplast</fullName>
            </value>
            <value>
                <fullName>Parryware</fullName>
            </value>
            <value>
                <fullName>Poloplast</fullName>
            </value>
            <value>
                <fullName>Prince</fullName>
            </value>
            <value>
                <fullName>Rakhsha</fullName>
            </value>
            <value>
                <fullName>Supreme</fullName>
            </value>
            <value>
                <fullName>Valsir</fullName>
            </value>
            <value>
                <fullName>Viega</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/MRP_Post_Discount__c.field-meta.xml
<CustomField>
    <fullName>MRP_Post_Discount__c</fullName>
    <formula>(MRP_Value__c)-( APPL__c * MRP_Value__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MRP Post Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/MRP_Value__c.field-meta.xml
<CustomField>
    <fullName>MRP_Value__c</fullName>
    <description>MRP value of the product</description>
    <label>MRP Value</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Net_Invoice_Value_from_APPL__c.field-meta.xml
<CustomField>
    <fullName>Net_Invoice_Value_from_APPL__c</fullName>
    <description>This the calculated from the given orc %</description>
    <formula>If( ISBLANK(ORC_MARGIN_TO_DLR_DIST__c ), Discounted_Price__c , ABS(((100 - (ORC_MARGIN_TO_DLR_DIST__c * 100))/100) *  Discounted_Price__c))</formula>
    <label>Net Invoice Value from APPL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/ORC_MARGIN_TO_DLR_DIST__c.field-meta.xml
<CustomField>
    <fullName>ORC_MARGIN_TO_DLR_DIST__c</fullName>
    <label>ORC/ MARGIN TO DLR/DIST</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Others_Lost_Sales__c.field-meta.xml
<CustomField>
    <fullName>Others_Lost_Sales__c</fullName>
    <description>This field is mandatory if the reason of lost sales chosen is empty</description>
    <inlineHelpText>This field is mandatory if the reason of lost sales chosen is empty</inlineHelpText>
    <label>Others</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Payment_terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_terms__c</fullName>
    <label>Payment terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20% advance with PO</fullName>
            </value>
            <value>
                <fullName>30 Days credit with PO</fullName>
            </value>
            <value>
                <fullName>90 Days credit with PO</fullName>
            </value>
            <value>
                <fullName>100% Payment against Delivery</fullName>
            </value>
            <value>
                <fullName>45 days after delivery</fullName>
            </value>
            <value>
                <fullName>60 days after delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Name of the product</description>
    <inlineHelpText>Name of the product</inlineHelpText>
    <label>Product Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Product_Specified__c.field-meta.xml
<CustomField>
    <fullName>Product_Specified__c</fullName>
    <label>Product Specified</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Specified</fullName>
            </value>
            <value>
                <fullName>Not Specified</fullName>
            </value>
            <value>
                <fullName>Specification Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <label>Product Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Win</fullName>
            </value>
            <value>
                <fullName>Loss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>New Offer Sections</relationshipLabel>
    <relationshipName>New_Offer_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Project_Value__c.field-meta.xml
<CustomField>
    <fullName>Project_Value__c</fullName>
    <label>Project Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Send_for_SPR__c.field-meta.xml
<CustomField>
    <fullName>Send_for_SPR__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this is true and the Extra discount field is not equal to null then an approval will go to the manager</description>
    <label>Send for SPR</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Tentative_Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Tentative_Order_Date__c</fullName>
    <label>Tentative Order Date</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jan 16</fullName>
            </value>
            <value>
                <fullName>Feb 16</fullName>
            </value>
            <value>
                <fullName>Mar 16</fullName>
            </value>
            <value>
                <fullName>Apr 16</fullName>
            </value>
            <value>
                <fullName>May 16</fullName>
            </value>
            <value>
                <fullName>Jun 16</fullName>
            </value>
            <value>
                <fullName>Jul 16</fullName>
            </value>
            <value>
                <fullName>Aug 16</fullName>
            </value>
            <value>
                <fullName>Sept 16</fullName>
            </value>
            <value>
                <fullName>Oct 16</fullName>
            </value>
            <value>
                <fullName>Nov 16</fullName>
            </value>
            <value>
                <fullName>Dec 16</fullName>
            </value>
            <value>
                <fullName>Jan 17</fullName>
            </value>
            <value>
                <fullName>Feb 17</fullName>
            </value>
            <value>
                <fullName>Mar 17</fullName>
            </value>
            <value>
                <fullName>Apr 17</fullName>
            </value>
            <value>
                <fullName>May 17</fullName>
            </value>
            <value>
                <fullName>Jun 17</fullName>
            </value>
            <value>
                <fullName>Jul 17</fullName>
            </value>
            <value>
                <fullName>Aug 17</fullName>
            </value>
            <value>
                <fullName>Sept 17</fullName>
            </value>
            <value>
                <fullName>Oct 17</fullName>
            </value>
            <value>
                <fullName>Nov 17</fullName>
            </value>
            <value>
                <fullName>Dec 17</fullName>
            </value>
            <value>
                <fullName>Jan 18</fullName>
            </value>
            <value>
                <fullName>Feb 18</fullName>
            </value>
            <value>
                <fullName>Mar 18</fullName>
            </value>
            <value>
                <fullName>Apr 18</fullName>
            </value>
            <value>
                <fullName>May 18</fullName>
            </value>
            <value>
                <fullName>Jun 18</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Validity_for_the_Price__c.field-meta.xml
<CustomField>
    <fullName>Validity_for_the_Price__c</fullName>
    <defaultValue>TODAY() + 30</defaultValue>
    <label>Validity for the Price</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/EditAllNewOfferSection_Controller.cls
/***********************************************************************************************
* Created By: Subhajit Ghosh
* Company: KVP
* Description: Used when the edit button is clicked for the editing the Indicative product fitment list. It is used to update the offers in the
              new offer section.
*Test  :     EditAllNewOfferTest
*******************************************************************************************/
public class EditAllNewOfferSection_Controller {
    public String oppProId{get;set;}
    
    
    
    // public List<WrapperNewOffer> wrapListOfferList{set;get;}
    public  List<New_Offer_Section__c> newOfferSectlist{set;get;}
    public Opportunity oppTC {get;set;}
    public List<Opportunity> oppTClist;
    public String pageTypeValue{get;set;}// to get the fromPage value from URL so that one the basis it would return to respective page
    
    public EditAllNewOfferSection_Controller(){
        //wrapListOfferList=new List<WrapperNewOffer>();
        newOfferSectlist=new List<New_Offer_Section__c>();
        oppTC=new Opportunity();
        oppProId = Apexpages.currentPage().getParameters().get('id'); 
        pageTypeValue=Apexpages.currentPage().getParameters().get('fromPage');
        oppTClist=new List<Opportunity>();
        system.debug('oppProId  @@@'+oppProId);
        if(oppProId != NULL){
            newOfferSectlist=[SELECT id,Product_Name__c,MRP_Value__c,Send_for_SPR__c,Net_Invoice_Value_from_APPL__c,Lost_to_brand__c,Reason_of_lost_sales__c,Others_Lost_Sales__c,APPL__c,Extra_Discount__c,ORC_MARGIN_TO_DLR_DIST__c,Tentative_Order_Date__c,Offer_Probability__c,Delivery_Start_Date__c,Delivery_End_Date__c,
                              Competitors_name__c,Distributor__c,MRP_Post_Discount__c,Product_Specified__c,Payment_terms__c,Delivery_Schedule__c,Product_Status__c ,Project_Value__c,Why_Additional_Discount__c,Validity_for_the_Price__c FROM New_Offer_Section__c WHERE Project__c =: oppProId AND Send_for_SPR__c != TRUE];
            
            oppTC = [SELECT Id,Freight__c,Delivery__c,Price_Basis__c,Delivery_Lots__c,Taxes__c,Offer_Valid_Till__c,Payment_Term__c,Delivery_Conditions_Gurantee__c,Order_Placement__c FROM Opportunity WHERE Id =:oppProId];  
        }
        
    }
    public PageReference saveUpdatedOffers() { 
        oppTClist.add(oppTC);
        Integer orderLoss=0;
        Integer otherLossReason=0;
        integer orderWin=0;
        integer selectPrevDates=0;
        integer projvalue=0;
        
        system.debug('oppProId PageReference-->>'+oppProId);
        for(New_Offer_Section__c newOff:newOfferSectlist){
            if(newOff.Product_Status__c=='Loss' && (newOff.Lost_to_brand__c==NULL || newOff.Reason_of_lost_sales__c==NULL)){
                orderLoss++;
            }
            if(newOff.Product_Status__c=='Loss' && newOff.Reason_of_lost_sales__c=='Others' && newOff.Others_Lost_Sales__c==NULL){
                otherLossReason++;
            }
            if((newOff.Product_Status__c=='Win' || newOff.Product_Status__c==NULL) && (newOff.Lost_to_brand__c!=NULL || newOff.Reason_of_lost_sales__c!=NULL || newOff.Others_Lost_Sales__c!=NULL) ){
                orderWin++;
            }
            
            if(newOff.Delivery_Start_Date__c < Date.today() || newOff.Validity_for_the_Price__c < date.today()){
                selectPrevDates++;
            }
            
            if(newOff.Project_Value__c ==NULL){
                projvalue++;
            }
            
        }
        if(orderLoss > 0){
            ApexPages.Message theMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'If Product Status is Loss then please fill the Lost to brand and Reason for lost sales');
            ApexPages.addMessage(theMessage);
            return null;   
        }
        if(otherLossReason > 0){
            ApexPages.Message theMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'If Reason for lost sales is others then please fill the Others(Reason) field next to it');
            ApexPages.addMessage(theMessage);
            // new myException('Please fill the extra discount field in order to submit it for special pricing request for the selected products');
            return null;
        }
        if(orderWin>0){
            ApexPages.Message theMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'If Product status is Win/--None-- then Lost to brand,Reason Of Lost Sales, Others(Reason) must be empty');
            ApexPages.addMessage(theMessage);
            return null;
        }
        if(selectPrevDates>0){
            ApexPages.Message theMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'Delivery Start Date and Validity of the Price dates cannot be less than today');
            ApexPages.addMessage(theMessage);
            return null;
        }
        if(projvalue>0){
            ApexPages.Message theMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'Project Value cannot be empty');
            ApexPages.addMessage(theMessage);
            return null;
        }   
        
        for(Opportunity opp:oppTClist){
            if(opp.Freight__c==NULL || opp.Delivery__c==NULL || opp.Price_Basis__c==NULL || opp.Delivery_Lots__c==NULL || opp.Payment_Term__c==NULL || opp.Taxes__c==NULL || opp.Offer_Valid_Till__c==NULL || opp.Delivery_Conditions_Gurantee__c==NULL || opp.Order_Placement__c==NULL){
                ApexPages.Message theMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please fill all the fields in terms and conditions section');
                ApexPages.addMessage(theMessage);
                return null;
            }
        }
        try{
            system.debug('newOfferSectlist-->>'+newOfferSectlist);
            system.debug('newOfferSectlist-------@@@@@@@@@@@@@@@@@@@@@@'+newOfferSectlist.size());
            upsert newOfferSectlist;
            upsert oppTC;
            if(pageTypeValue.equalsIgnoreCase('SPRPage') ){
                //PageReference pf = new PageReference('/'+oppProId);
                PageReference pf=new PageReference('/apex/SPR_NewOffer?id='+oppProId+'&applType=offerType');
                return pf;
            }
            else{
                PageReference pf = new PageReference('/'+oppProId);
                return pf;
            }
            
            
        }
        catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, e.getMessage()));
            return null;
        }
        
    }
    public PageReference cancelEdit() { 
        try{
             if(pageTypeValue.equalsIgnoreCase('SPRPage') ){
                //PageReference pf = new PageReference('/'+oppProId);
                PageReference pf=new PageReference('/apex/SPR_NewOffer?id='+oppProId+'&applType=offerType');
                return pf;
            }
            else{
                PageReference pf = new PageReference('/'+oppProId);
                return pf;
            }
            
        }
        catch(Exception e){
            system.debug('exception occured while cancelling page---'+e);
             PageReference pf = new PageReference('/'+oppProId);
             return pf;
        }
        
        
    }
    
}