Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/New_Offer_Section__c.object-meta.xml
<CustomObject>
    <description>We are using this as an alternative to the OpportunityLineItem. Data is created as soon as new project is inserted or edited. Data is calculated on the basis of ProbabilityMaster__c object</description>
    <label>New Offer Section</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New Offer Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Additional_Disc_on_APPL_disc__c.field-meta.xml
<CustomField>
    <fullName>Additional_Disc_on_APPL_disc__c</fullName>
    <description>Additional discount on the APPL discount. A number field but if want to use it then consider this as a percent field. This field is used in the project level to calculate the average discount that has been provided under a particular project</description>
    <formula>((MRP_Post_Discount__c -  Net_Invoice_Value_from_APPL__c ) /  MRP_Post_Discount__c)*100</formula>
    <label>Additional Disc on APPL disc</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/APPL__c.field-meta.xml
<CustomField>
    <fullName>APPL__c</fullName>
    <description>APPL Discount is based on the discount in different states</description>
    <label>APPL Discount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/CTC__c.field-meta.xml
<CustomField>
    <fullName>CTC__c</fullName>
    <description>CTC value</description>
    <formula>( (MRP_Value__c - Net_Invoice_Value_from_APPL__c ) / MRP_Value__c)</formula>
    <label>CTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Extra_Discount__c.field-meta.xml
<CustomField>
    <fullName>Extra_Discount__c</fullName>
    <description>Extra discount on the APPL Discount</description>
    <label>Extra Discount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/MRP_Value__c.field-meta.xml
<CustomField>
    <fullName>MRP_Value__c</fullName>
    <description>MRP value of the product</description>
    <label>MRP Value</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Net_Invoice_Value_from_APPL__c.field-meta.xml
<CustomField>
    <fullName>Net_Invoice_Value_from_APPL__c</fullName>
    <description>This the calculated from the given orc %</description>
    <formula>If( ISBLANK(ORC_MARGIN_TO_DLR_DIST__c ), Discounted_Price__c , ABS(((100 - (ORC_MARGIN_TO_DLR_DIST__c * 100))/100) *  Discounted_Price__c))</formula>
    <label>Net Invoice Value from APPL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/ORC_MARGIN_TO_DLR_DIST__c.field-meta.xml
<CustomField>
    <fullName>ORC_MARGIN_TO_DLR_DIST__c</fullName>
    <label>ORC/ MARGIN TO DLR/DIST</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Name of the product</description>
    <inlineHelpText>Name of the product</inlineHelpText>
    <label>Product Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>New Offer Sections</relationshipLabel>
    <relationshipName>New_Offer_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Tentative_Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Tentative_Order_Date__c</fullName>
    <label>Tentative Order Date</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jan 16</fullName>
            </value>
            <value>
                <fullName>Feb 16</fullName>
            </value>
            <value>
                <fullName>Mar 16</fullName>
            </value>
            <value>
                <fullName>Apr 16</fullName>
            </value>
            <value>
                <fullName>May 16</fullName>
            </value>
            <value>
                <fullName>Jun 16</fullName>
            </value>
            <value>
                <fullName>Jul 16</fullName>
            </value>
            <value>
                <fullName>Aug 16</fullName>
            </value>
            <value>
                <fullName>Sept 16</fullName>
            </value>
            <value>
                <fullName>Oct 16</fullName>
            </value>
            <value>
                <fullName>Nov 16</fullName>
            </value>
            <value>
                <fullName>Dec 16</fullName>
            </value>
            <value>
                <fullName>Jan 17</fullName>
            </value>
            <value>
                <fullName>Feb 17</fullName>
            </value>
            <value>
                <fullName>Mar 17</fullName>
            </value>
            <value>
                <fullName>Apr 17</fullName>
            </value>
            <value>
                <fullName>May 17</fullName>
            </value>
            <value>
                <fullName>Jun 17</fullName>
            </value>
            <value>
                <fullName>Jul 17</fullName>
            </value>
            <value>
                <fullName>Aug 17</fullName>
            </value>
            <value>
                <fullName>Sept 17</fullName>
            </value>
            <value>
                <fullName>Oct 17</fullName>
            </value>
            <value>
                <fullName>Nov 17</fullName>
            </value>
            <value>
                <fullName>Dec 17</fullName>
            </value>
            <value>
                <fullName>Jan 18</fullName>
            </value>
            <value>
                <fullName>Feb 18</fullName>
            </value>
            <value>
                <fullName>Mar 18</fullName>
            </value>
            <value>
                <fullName>Apr 18</fullName>
            </value>
            <value>
                <fullName>May 18</fullName>
            </value>
            <value>
                <fullName>Jun 18</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Offer_Section__c/fields/Validity_for_the_Price__c.field-meta.xml
<CustomField>
    <fullName>Validity_for_the_Price__c</fullName>
    <defaultValue>TODAY() + 30</defaultValue>
    <label>Validity for the Price</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/New_Special_Pricing_Request__c.object-meta.xml
<CustomObject>
    <description>This object stores all the line items that are checked and sent for SPR. The group of items that are selected goes for SPR everytime the project is sent for approval.</description>
    <label>New Special Pricing Request</label>
    <nameField>
        <displayFormat>SPR-{00}</displayFormat>
        <label>SPR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New Special Pricing Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Additional_Disc_on_APPL_disc2__c.field-meta.xml
<CustomField>
    <fullName>Additional_Disc_on_APPL_disc2__c</fullName>
    <description>A number field but if want to use it then please consider this as a Percent and do the required calculations</description>
    <formula>((MRP_Post_Discount2__c -  Net_Invoice_Value_from_APPL2__c ) /  MRP_Post_Discount2__c)*100</formula>
    <label>Additional Disc on APPL disc2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/APPL__c.field-meta.xml
<CustomField>
    <fullName>APPL__c</fullName>
    <label>APPL Discount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <formula>text(Unique_SPR__r.Approval_Status__c)</formula>
    <label>Approval Status</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/CTC_Value__c.field-meta.xml
<CustomField>
    <fullName>CTC_Value__c</fullName>
    <description>CTC Calculation</description>
    <formula>( MRP_Value__c -  Net_Invoice_Value_from_APPL2__c )/ MRP_Value__c</formula>
    <label>CTC Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Discounted_Price2__c.field-meta.xml
<CustomField>
    <fullName>Discounted_Price2__c</fullName>
    <formula>IF( ISBLANK(Extra_Discount__c),
MRP_Post_Discount2__c ,
ABS( (MRP_Value__c) - ( Extra_Discount__c * MRP_Value__c)))</formula>
    <label>Discounted Price2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Extra_Discount__c.field-meta.xml
<CustomField>
    <fullName>Extra_Discount__c</fullName>
    <label>Extra Discount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/MRP_Post_Discount2__c.field-meta.xml
<CustomField>
    <fullName>MRP_Post_Discount2__c</fullName>
    <formula>(MRP_Value__c)-( APPL__c * MRP_Value__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MRP Post Discount2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Net_Invoice_Value_from_APPL2__c.field-meta.xml
<CustomField>
    <fullName>Net_Invoice_Value_from_APPL2__c</fullName>
    <description>The net invoice value from APPL</description>
    <formula>If( ISBLANK(ORC_MARGIN_TO_DLR_DIST__c ), Discounted_Price2__c , ABS(((100 - (ORC_MARGIN_TO_DLR_DIST__c * 100))/100) * Discounted_Price2__c))</formula>
    <label>Net Invoice Value from APPL2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Offer_Probability__c.field-meta.xml
<CustomField>
    <fullName>Offer_Probability__c</fullName>
    <label>Offer Probability</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>&lt;50%</fullName>
            </value>
            <value>
                <fullName>60%</fullName>
            </value>
            <value>
                <fullName>70%</fullName>
            </value>
            <value>
                <fullName>80%</fullName>
            </value>
            <value>
                <fullName>90%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Payment_Term__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term__c</fullName>
    <label>Payment Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100% advance with PO</fullName>
            </value>
            <value>
                <fullName>20% advance &amp; Balance against Delivery</fullName>
            </value>
            <value>
                <fullName>30 days after delivery</fullName>
            </value>
            <value>
                <fullName>45 days after delivery</fullName>
            </value>
            <value>
                <fullName>60 days after delivery</fullName>
            </value>
            <value>
                <fullName>90 days after delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Product_name__c.field-meta.xml
<CustomField>
    <fullName>Product_name__c</fullName>
    <label>Product name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup to opportunity (Project ) object</description>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>New Special Pricing Requests</relationshipLabel>
    <relationshipName>New_Special_Pricing_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Tentative_Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Tentative_Order_Date__c</fullName>
    <label>Tentative Order Date</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Unique_SPR__c.field-meta.xml
<CustomField>
    <fullName>Unique_SPR__c</fullName>
    <description>related to the unique spr.</description>
    <label>Unique SPR</label>
    <referenceTo>Unique_SPR__c</referenceTo>
    <relationshipLabel>New Special Pricing Requests</relationshipLabel>
    <relationshipName>New_Special_Pricing_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/Unique_SPR__c.object-meta.xml
<CustomObject>
    <description>This object contains the unique name of each spr. Uniqueness is valid for a specific project. This record goes for approval in the new revamp structure.</description>
    <label>Unique SPR</label>
    <nameField>
        <displayFormat>UN-{000}</displayFormat>
        <label>Unique Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unique SPRs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Number_of_SPR_s__c.field-meta.xml
<CustomField>
    <fullName>Number_of_SPR_s__c</fullName>
    <description>count the number of spr under a particular record</description>
    <label>Number of SPR&apos;s</label>
    <summaryForeignKey>New_Special_Pricing_Request__c.Unique_SPR__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Unique SPRs</relationshipLabel>
    <relationshipName>Unique_SPRs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/OfferForClientController.cls
/**************************************************************************************************************************
Created By      :Subhajit Ghosh
Created Date    :23-July-2019
Modified Date   :
Description     : generates the PDF for Offer for Client Button in the Project Detail Page 

***********************************************************************************************************************************/

public class OfferForClientController {
    public List<New_Special_Pricing_Request__c> offerList{set;get;}
    public List<New_Offer_Section__c> sprReviewList{set;get;}
    public Opportunity oppDetails{set;get;}
    public Decimal netInvoiceValueSum{set;get;}
    public String projectId{get;set;}
    public boolean emptyTCProject{set;get;}
    public List<Decimal> netInvoiceValueList;
    public List<Decimal> netMRPPostDisc2SumList;
    public Decimal mrpPostDiscSum{get;set;}
    public Decimal AverageDisc{get;set;}
    
    public OfferForClientController(){
        offerList=new List<New_Special_Pricing_Request__c>();
        sprReviewList=new List<New_Offer_Section__c>();
        emptyTCProject=false;
        netInvoiceValueSum=0;
        mrpPostDiscSum=0;
        AverageDisc=0;
        netInvoiceValueList=new List<Decimal>();
        netMRPPostDisc2SumList=new List<Decimal>();
        oppDetails=new Opportunity();
        projectId=ApexPages.currentPage().getParameters().get('id');
        system.debug('************projectId*********'+projectId);
        if(projectId != NULL){
            netInvoiceValueList.clear();
            oppDetails=[SELECT Id,Project_By__r.Name,Name,Freight__c,Delivery__c,Price_Basis__c,Delivery_Lots__c,Taxes__c,Offer_Valid_Till__c,Payment_Term__c,Delivery_Conditions_Gurantee__c,Order_Placement__c FROM Opportunity WHERE Id =:projectId];
            if(oppDetails.Freight__c == NULL || oppDetails.Delivery__c ==NULL || oppDetails.Price_Basis__c == NULL || oppDetails.Delivery_Lots__c == NULL || oppDetails.Taxes__c == NULL 
               || oppDetails.Offer_Valid_Till__c == NULL || oppDetails.Payment_Term__c == NULL || oppDetails.Delivery_Conditions_Gurantee__c == NULL || oppDetails.Order_Placement__c == NULL){
                   emptyTCProject=true;
               }
            
            offerList=[SELECT ID,Product_name__c,APPL__c,CTC_Value__c,Discounted_Price2__c,Additional_Disc_on_APPL_disc2__c,Extra_Discount__c,MRP_Value__c,
                       MRP_Post_Discount2__c,Net_Invoice_Value_from_APPL2__c,Unique_SPR__c,
                       ORC_MARGIN_TO_DLR_DIST__c,Project__c,Validity_for_the_Price__c,
                       Price_List_Date__c,Offer_Probability__c,Tentative_Order_Date__c,Reason__c
                       FROM New_Special_Pricing_Request__c WHERE Unique_SPR__r.Number_of_SPR_s__c>=:1
                       AND Project__c=:projectId AND Approval_Status__c='Approved'];
            
            if(offerList.size()>0){
                for(New_Special_Pricing_Request__c nos:offerList){
                    if(nos.Net_Invoice_Value_from_APPL2__c != NULL ){
                        netInvoiceValueList.add(nos.Net_Invoice_Value_from_APPL2__c);
                    }
                    if(nos.Net_Invoice_Value_from_APPL2__c != NULL){
                        netInvoiceValueList.add(0);
                    }
                    if(nos.MRP_Post_Discount2__c != NULL ){
                        netMRPPostDisc2SumList.add(nos.MRP_Post_Discount2__c);
                    }
                    if(nos.MRP_Post_Discount2__c == NULL){
                        netMRPPostDisc2SumList.add(0); 
                    }
                }
            }
            if(netInvoiceValueList.size()>0){
                for(Decimal sum:netInvoiceValueList){
                    netInvoiceValueSum=netInvoiceValueSum+sum;             
                } 
            }
            if(netMRPPostDisc2SumList.size()>0){
                for(Decimal sum:netMRPPostDisc2SumList){
                    mrpPostDiscSum=mrpPostDiscSum+sum;             
                } 
            }
            if(mrpPostDiscSum != 0){
                decimal AverageDisc2= ((mrpPostDiscSum - netInvoiceValueSum)/ mrpPostDiscSum)*100;
                AverageDisc=AverageDisc2.setScale(2);
            }
            
            sprReviewList=[SELECT id,Product_Name__c,MRP_Value__c,APPL__c,Extra_Discount__c,CTC__c,Additional_Disc_on_APPL_disc__c,Net_Invoice_Value_from_APPL__c,ORC_MARGIN_TO_DLR_DIST__c,Competitors_name__c,MRP_Post_Discount__c,Delivery_Start_Date__c,Tentative_Order_Date__c,Discounted_Price__c,Approval_Status__c ,Validity_for_the_Price__c,Project__c FROM New_Offer_Section__c WHERE Project__c =: projectId];
        }
        String myGeneratedFileName = 'Offerfor'+oppDetails.Name;
        //Apexpages.currentPage().getHeaders().put('content-disposition', 'attachment; filename='+myGeneratedFilename);
        Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename='+myGeneratedFilename); 
        
        
    }
    
    
}