Partial_14Dec2021/force-app/main/default/objects/iep_influencer__c/iep_influencer__c.object-meta.xml
<CustomObject>
    <label>IEP Influencer</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Influencer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IEP Influencers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/iep_influencer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.Party_Type__c</field>
            <operation>equals</operation>
            <value>Plumbing Contractor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>IEP Influencers</relationshipLabel>
    <relationshipName>IEP_Influencers</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/iep_influencer__c/fields/Current_point__c.field-meta.xml
<CustomField>
    <fullName>Current_point__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Current point</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/TriggerAccountHelper.cls
/* 
	Helper class of TrigggerAccount
	Helper adds Account id into IEP_Influncer__c custom object after insert & update on Account
	Author: Mohit
*/
public class TriggerAccountHelper {
public static void insertAccountIntoIEPInfluncer(List<Account> accNew){
        List<iep_influencer__c> iepList = [select Id, Account__c from iep_influencer__c];
        Map<Id, iep_influencer__c> mapIep = new Map<Id, iep_influencer__c>();
        for(iep_influencer__c i : iepList){
            mapIep.put(i.Account__c,i);
        }
        for(Account ac : accNew){
            if(ac.is_active__c){
                if(!mapIep.containsKey(ac.Id)){
                    iep_influencer__c iep = new iep_influencer__c(Account__c=ac.Id, Current_point__c=0.00);
                    insert iep;
                }
            }
        }
    }
}