Partial_14Dec2021/force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SVN-{00000000}</displayFormat>
        <label>Site Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Site_Visit__c/fields/Architects_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Architects_Meet_Actuals__c</fullName>
    <label>Architects Meet (Actuals)(not used)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Site_Visit__c/fields/Boarers_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Boarers_Meet_Actuals__c</fullName>
    <label>Boarers Meet (Actuals)(not used)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Site_Visit__c/fields/Builders_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Builders_Meet_Actuals__c</fullName>
    <label>Builders Meet (Actuals)(not used)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Site_Visit__c/fields/Tour_Plan1__c.field-meta.xml
<CustomField>
    <fullName>Tour_Plan1__c</fullName>
    <label>Tour Plan</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND 2) AND ((3 AND 4) OR (5 AND 6) OR (7 AND 8)))</booleanFilter>
        <filterItems>
            <field>Tour_Plan1__c.Tour_Program__r.Tour_Program_Approved__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Tour_Plan1__c.Date__c</field>
            <operation>equals</operation>
            <valueField>$Source.Date__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>BD, TL NEW,Exports,BD Branding</value>
        </filterItems>
        <filterItems>
            <field>Tour_Plan1__c.Validation_Date__c</field>
            <operation>greaterOrEqual</operation>
            <value>-1</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>HO NEW</value>
        </filterItems>
        <filterItems>
            <field>Tour_Plan1__c.Validation_Date__c</field>
            <operation>greaterOrEqual</operation>
            <value>-4</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>Tour_Plan1__c.Validation_Date__c</field>
            <operation>greaterOrEqual</operation>
            <value>-365</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tour_Plan1__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/Tour_Plan1__c.object-meta.xml
<CustomObject>
    <label>Tour Plans</label>
    <nameField>
        <label>Tour Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Architects_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Architects_Meet_Actuals__c</fullName>
    <label>Architects Meet (Actuals)(not used)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Boarers_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Boarers_Meet_Actuals__c</fullName>
    <label>Boarers Meet (Actuals)(not used)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Builders_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Builders_Meet_Actuals__c</fullName>
    <label>Builders Meet (Actuals)(not used)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Tour_Program__c.field-meta.xml
<CustomField>
    <fullName>Tour_Program__c</fullName>
    <label>Tour Program</label>
    <referenceTo>Tour_Program__c</referenceTo>
    <relationshipLabel>Tour Plans</relationshipLabel>
    <relationshipName>Tour_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Tour_Program_Approved__c.field-meta.xml
<CustomField>
    <fullName>Tour_Program_Approved__c</fullName>
    <formula>Tour_Program__r.Tour_Program_Approved__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tour Program Approved</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/Tour_Program__c.object-meta.xml
<CustomObject>
    <label>Tour Program</label>
    <nameField>
        <label>Tour Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/Architects_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Architects_Meet_Actuals__c</fullName>
    <label>Architects Meet (Actuals)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/Boarers_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Boarers_Meet_Actuals__c</fullName>
    <label>Boarers Meet (Actuals)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/Builders_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Builders_Meet_Actuals__c</fullName>
    <label>Builders Meet (Actuals)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/Tour_Program_Approved__c.field-meta.xml
<CustomField>
    <fullName>Tour_Program_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tour Program Approved</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/TestRollupTourProgram.cls
@istest
Private Class TestRollupTourProgram
{
    Static TestMethod Void TestRollupTourProg()
    {
    Test.StartTest();
    
     Profile p = [SELECT Id, Name FROM Profile WHERE Name =: 'BD']; 
        User userData = new User(Alias = 'standt1', 
                                  Email= 'FName'+'LName'+'@TestUser99.com', 
                                  EmailEncodingKey='UTF-8', 
                                  FirstName = 'FName',
                                  LastName = 'LName', 
                                  LanguageLocaleKey='en_US', 
                                  LocaleSidKey='en_AU', 
                                  ProfileId = p.Id, 
                                  TimeZoneSidKey='Australia/Sydney', 
                                  UserName= 'FName+LName+@TestUser3.com'
                                  );
                                  
           system.runAs(userData) {
           	
           
    List<Tour_Program__c> TourProg=new List<Tour_Program__c>();
       Tour_Program__c tr=new Tour_Program__c();
        tr.From_Date__c=date.newinstance(2014, 3, 1);
        tr.To_Date__c=date.newinstance(2014, 3, 15);
        tr.Tour_Program_Approved__c = true;
       TourProg.add(tr);
       insert TourProg;
       Update TourProg;
       List<Tour_Plan1__c > TourPlan=new List<Tour_Plan1__c >();
       Tour_Plan1__c tp=new Tour_Plan1__c();
       tp.Name='Tour Palan';
       tp.Tour_Program__c=tr.id;
       tp.Date__c = Date.today();
       TourPlan.add(tp);
       insert TourPlan;
       Update TourPlan;
       
       Site_Visit__c sv=new Site_Visit__c();
       sv.Tour_Plan1__c=tp.id;
       sv.Architects_Meet_Actuals__c=1;
       sv.Boarers_Meet_Actuals__c=2;
       sv.Builders_Meet_Actuals__c=3;
       sv.Date__c = Date.today();
       insert sv;
       Update sv;
           }
       Test.StopTest(); 
    }
}