Partial_14Dec2021/force-app/main/default/objects/Column_dealer_Survey__c/Column_dealer_Survey__c.object-meta.xml
<CustomObject>
    <label>Column dealer Survey</label>
    <nameField>
        <displayFormat>SUR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Column dealer Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Column_dealer_Survey__c/fields/Agri_fast_moving_Size_Inch__c.field-meta.xml
<CustomField>
    <fullName>Agri_fast_moving_Size_Inch__c</fullName>
    <label>Agri fast moving Size( Inch)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4 KG - 2 Inch</fullName>
            </value>
            <value>
                <fullName>4 KG - 2½ Inch</fullName>
            </value>
            <value>
                <fullName>4 KG - 3 Inch</fullName>
            </value>
            <value>
                <fullName>4 KG - 4 Inch</fullName>
            </value>
            <value>
                <fullName>4 KG - 4½ Inch</fullName>
            </value>
            <value>
                <fullName>4 KG - 5 Inch</fullName>
            </value>
            <value>
                <fullName>4 KG - 6 Inch</fullName>
            </value>
            <value>
                <fullName>4 KG - 7 Inch</fullName>
            </value>
            <value>
                <fullName>4 KG - 8 Inch</fullName>
            </value>
            <value>
                <fullName>4 KG - 9 Inch</fullName>
            </value>
            <value>
                <fullName>4 KG - 10 Inch</fullName>
            </value>
            <value>
                <fullName>4 KG - 12 Inch</fullName>
            </value>
            <value>
                <fullName>6 KG - 1¼ Inch</fullName>
            </value>
            <value>
                <fullName>6 KG - 1½ Inch</fullName>
            </value>
            <value>
                <fullName>6 KG - 2 Inch</fullName>
            </value>
            <value>
                <fullName>6 KG - 2½ Inch</fullName>
            </value>
            <value>
                <fullName>6 KG - 3 Inch</fullName>
            </value>
            <value>
                <fullName>6 KG - 4 Inch</fullName>
            </value>
            <value>
                <fullName>6 KG - 4½ Inch</fullName>
            </value>
            <value>
                <fullName>6 KG - 5 Inch</fullName>
            </value>
            <value>
                <fullName>6 KG - 6 Inch</fullName>
            </value>
            <value>
                <fullName>6 KG - 7 Inch</fullName>
            </value>
            <value>
                <fullName>6 KG - 8 Inch</fullName>
            </value>
            <value>
                <fullName>6 KG - 9 Inch</fullName>
            </value>
            <value>
                <fullName>6 KG - 10 Inch</fullName>
            </value>
            <value>
                <fullName>6 KG - 12 Inch</fullName>
            </value>
            <value>
                <fullName>2.5 KG - 3 Inch</fullName>
            </value>
            <value>
                <fullName>2.5 KG - 4 Inch</fullName>
            </value>
            <value>
                <fullName>2.5 KG - 4½ Inch</fullName>
            </value>
            <value>
                <fullName>2.5 KG - 5 Inch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Column_dealer_Survey__c/fields/Casting_fast_moving_Size_Inch__c.field-meta.xml
<CustomField>
    <fullName>Casting_fast_moving_Size_Inch__c</fullName>
    <label>Casing fast moving Size( Inch)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2&quot;</fullName>
            </value>
            <value>
                <fullName>3&quot;</fullName>
            </value>
            <value>
                <fullName>4&quot;</fullName>
            </value>
            <value>
                <fullName>4½&quot;</fullName>
            </value>
            <value>
                <fullName>5&quot;</fullName>
            </value>
            <value>
                <fullName>6&quot;</fullName>
            </value>
            <value>
                <fullName>6½</fullName>
            </value>
            <value>
                <fullName>7&quot;</fullName>
            </value>
            <value>
                <fullName>8&quot;</fullName>
            </value>
            <value>
                <fullName>10&quot;</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Column_dealer_Survey__c/fields/Color_of_tank__c.field-meta.xml
<CustomField>
    <fullName>Color_of_tank__c</fullName>
    <label>Color of tank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Cream</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Pink</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Column_dealer_Survey__c/fields/Column_fast_moving_Size_Inch__c.field-meta.xml
<CustomField>
    <fullName>Column_fast_moving_Size_Inch__c</fullName>
    <label>Column fast moving Size( Inch)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>1.25</fullName>
            </value>
            <value>
                <fullName>1.5</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>2.5</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Column_dealer_Survey__c/fields/Conversion_Time_From_GI_to_Column__c.field-meta.xml
<CustomField>
    <fullName>Conversion_Time_From_GI_to_Column__c</fullName>
    <label>ConversionTime From GI to Col(in years)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1-3</fullName>
            </value>
            <value>
                <fullName>3-5</fullName>
            </value>
            <value>
                <fullName>More than 5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Column_dealer_Survey__c/fields/Credit_Facility_given_to_dealer_by_Pipe__c.field-meta.xml
<CustomField>
    <fullName>Credit_Facility_given_to_dealer_by_Pipe__c</fullName>
    <label>Credit Facility given to dealer by Pipe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>less than 30</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>greater than 90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Column_dealer_Survey__c/fields/Electricity_connection__c.field-meta.xml
<CustomField>
    <fullName>Electricity_connection__c</fullName>
    <label>Electricity connection</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Phase</fullName>
            </value>
            <value>
                <fullName>Three Phase</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Column_dealer_Survey__c/fields/Fast_Moving_Size__c.field-meta.xml
<CustomField>
    <fullName>Fast_Moving_Size__c</fullName>
    <label>Vectus Fast Moving Ltr</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>500</fullName>
            </value>
            <value>
                <fullName>700</fullName>
            </value>
            <value>
                <fullName>750</fullName>
            </value>
            <value>
                <fullName>1000</fullName>
            </value>
            <value>
                <fullName>1500</fullName>
            </value>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2500</fullName>
            </value>
            <value>
                <fullName>3000</fullName>
            </value>
            <value>
                <fullName>5000</fullName>
            </value>
            <value>
                <fullName>7500</fullName>
            </value>
            <value>
                <fullName>10000</fullName>
            </value>
            <value>
                <fullName>15000</fullName>
            </value>
            <value>
                <fullName>20000</fullName>
            </value>
            <value>
                <fullName>25000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Column_dealer_Survey__c/fields/Hdpe_fast_moving_Size_Inch__c.field-meta.xml
<CustomField>
    <fullName>Hdpe_fast_moving_Size_Inch__c</fullName>
    <label>Hdpe fast moving Size( Inch)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>1.25</fullName>
            </value>
            <value>
                <fullName>1.5</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>2.5</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Column_dealer_Survey__c/fields/Product_sold_by_dealer__c.field-meta.xml
<CustomField>
    <fullName>Product_sold_by_dealer__c</fullName>
    <label>Product sold by dealer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Column Pipe</fullName>
            </value>
            <value>
                <fullName>Casing</fullName>
            </value>
            <value>
                <fullName>HDPE Pipes</fullName>
            </value>
            <value>
                <fullName>GI Pipe</fullName>
            </value>
            <value>
                <fullName>Agri Pipes</fullName>
            </value>
            <value>
                <fullName>Pumps</fullName>
            </value>
            <value>
                <fullName>Water tank</fullName>
            </value>
            <value>
                <fullName>Cables</fullName>
                <isActive>false</isActive>
                <label>Cables</label>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/Test_Column_Dealer_Survey_Handler.cls
@isTest
public class Test_Column_Dealer_Survey_Handler {
     @isTest static void columntest(){
         Test.startTest();
         //Column_Dealer_Survey_Handler  col= new Column_Dealer_Survey_Handler ();
         //Id RecordTypeIdCol = Schema.SObjectType.Column_dealer_Survey__c.getRecordTypeInfosByName().get('DeveloperNameOfRecordType').getRecordTypeId();
         Column_dealer_Survey__c col2 = new Column_dealer_Survey__c ();
         list<Column_dealer_Survey__c> col= new list<Column_dealer_Survey__c>();
         insert col;
         
         Column_Dealer_Survey_Handler.getOtherPickListValues('Conversion_Time_From_GI_to_Column__c');
         Column_Dealer_Survey_Handler.getOtherPickListValues('Credit_Facility_given_to_dealer_by_Pipe__c');
         Column_Dealer_Survey_Handler.getOtherPickListValues('Electricity_connection__c');
         Column_Dealer_Survey_Handler.getOtherPickListValues('Hdpe_fast_moving_Size_Inch__c');
          Column_Dealer_Survey_Handler.getOtherPickListValues('Fast_Moving_Size__c');
          Column_Dealer_Survey_Handler.getOtherPickListValues('Color_of_tank__c');
          Column_Dealer_Survey_Handler.getOtherPickListValues('Agri_fast_moving_Size_Inch__c');
         Column_Dealer_Survey_Handler.getOtherPickListValues('Casting_fast_moving_Size_Inch__c');
         Column_Dealer_Survey_Handler.getOtherPickListValues('Column_fast_moving_Size_Inch__c');
         Column_Dealer_Survey_Handler.getDependentMap(col2,'Product_sold_by_dealer__c','Name_of_Brands__c');
         Column_Dealer_Survey_Handler.decimalToBinary(1234);
         Column_Dealer_Survey_Handler.base64ToBits('test');
         Column_Dealer_Survey_Handler.getFieldLabelNameAndApi();
         Column_Dealer_Survey_Handler.abc();
         Column_Dealer_Survey_Handler.saveColumnRecords(col );
         

     }
}