Partial_14Dec2021/force-app/main/default/objects/Project_Tracker__c/Project_Tracker__c.object-meta.xml
<CustomObject>
    <label>Project Tracker</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Project Tracker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Project_Tracker__c/fields/Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan__c</fullName>
    <label>Action Plan</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Project_Tracker__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Tracker</relationshipLabel>
    <relationshipName>Project_Tracker</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Project_Tracker__c/fields/Project_Order__c.field-meta.xml
<CustomField>
    <fullName>Project_Order__c</fullName>
    <label>Project Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Project_Tracker__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/MassEditProjectTracker.cls
/*******************XXX**********************************

Created By      :Mohd.Numaan Ahmed
Created Date    :29-Dec-2014
Modified Date   :
Version         :1.0
Description     :

********************XXX***********************************/
public class MassEditProjectTracker {
	
   	public String projectId {get;set;}
    
    public List<Project_Tracker__c> projectTrackerList{get;set;}
    
    public MassEditProjectTracker(){

    	projectId = ApexPages.currentPage().getParameters().get('ProjectId');
        projectTrackerList = new List<Project_Tracker__c>();
        projectTrackerList = [SELECT Opportunity__c,Question__c,Remarks__c,Response__c,Project_Order__c,Action_Plan__c,Action_Date__c FROM Project_Tracker__c WHERE Opportunity__c = :projectId ORDER By Project_Order__c Asc];
    }
    
    
     public PageReference updateProjectTracker(){
     	
        PageReference pf = new PageReference('/'+projectId);
        try{
        	update projectTrackerList;
            return pf;
        }
        catch(exception e){

            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, e.getMessage()));
            return null;

        }
    }
    
    
    public PageReference cancel(){

        PageReference pf = new PageReference('/'+projectId);
        return pf;
    }
}