Partial_14Dec2021/force-app/main/default/objects/Town_Master__c/Town_Master__c.object-meta.xml
<CustomObject>
    <label>Town Master</label>
    <nameField>
        <label>Town Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Town Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Town_Master__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Town Master</relationshipLabel>
    <relationshipName>Town_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/AccountTriggerHelper.cls
public class AccountTriggerHelper {
    public static void CityMapping(Map<Id,Account> mapOfAccount){
     set<Id> setIds=new set<Id>();
        System.debug('asdfgh');
     for(Account acc:mapOfAccount.values()){
         If(acc.Town_Name__c!=null){
            setIds.add( acc.Town_Name__c);
          System.debug('setIds'+setIds);
         }}
        Map<Id,Town_Master__c> mapOfTerritory=new Map<Id,Town_Master__c>([Select id,Service_Territory__c from Town_Master__c where id=:setIds]);
       if(!mapOfTerritory.isEmpty()){
        System.debug('mapOfTerritory'+mapOfTerritory);
        for(Account acc:mapOfAccount.values()){
            System.debug('entering here');
            acc.City_lookup__c=mapOfTerritory.get(acc.Town_Name__c).Service_Territory__c;
            System.debug('hjhkj'+acc.City_lookup__c);
                    
            }
        }}
    }