Partial_14Dec2021/force-app/main/default/objects/Service_Charge__c/Service_Charge__c.object-meta.xml
<CustomObject>
    <label>Service Charge</label>
    <nameField>
        <displayFormat>SERCH-{000000}</displayFormat>
        <label>Service  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Service_Charge__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Service Charges</relationshipLabel>
    <relationshipName>Service_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/ServiceChargeHandler.cls
public class ServiceChargeHandler {
    public static void onAfterInsert(List<Service_Charge__c> listOfService){
        Map<Id,Service_Charge__c> mapOfServiceWithWorkorder=new Map<Id,Service_Charge__c>();
        for(Service_Charge__c ser:listOfService){
            if(ser.Work_Order__c!=null){
               mapOfServiceWithWorkorder.put(ser.Work_Order__c,ser) ;
            }
        }
        If(!mapOfServiceWithWorkorder.isEmpty()){
           ServiceChargeHelper.updateWorkorderDetails(mapOfServiceWithWorkorder) ;
        }
    }

}