Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/Branding_Request__c.object-meta.xml
<CustomObject>
    <label>Branding Request</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Branding Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branding Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Branding_Request__c.field-meta.xml
<CustomField>
    <fullName>Branding_Request__c</fullName>
    <label>Branding Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Branding Requests</relationshipLabel>
    <relationshipName>Branding_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Branding_Type__c.field-meta.xml
<CustomField>
    <fullName>Branding_Type__c</fullName>
    <label>Branding Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Shop</fullName>
            </value>
            <value>
                <fullName>Outshop</fullName>
            </value>
            <value>
                <fullName>Full Shop</fullName>
            </value>
            <value>
                <fullName>Recce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/Recce_Detail__c.object-meta.xml
<CustomObject>
    <description>Object to hold Recce report details for a branding request that is generted by the vendor.</description>
    <label>Recce Detail</label>
    <nameField>
        <displayFormat>RD-{000000}</displayFormat>
        <label>Recce Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recce Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Approximate_Cost__c.field-meta.xml
<CustomField>
    <fullName>Approximate_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Approximate Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Branding_Request__c.field-meta.xml
<CustomField>
    <fullName>Branding_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branding Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Recce Details</relationshipLabel>
    <relationshipName>Recce_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Branding_Type__c.field-meta.xml
<CustomField>
    <fullName>Branding_Type__c</fullName>
    <label>Branding Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Shop</fullName>
            </value>
            <value>
                <fullName>Out Shop</fullName>
            </value>
            <value>
                <fullName>Full Shop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branding_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Vinyl</fullName>
            </value>
            <value>
                <fullName>Vinyl on Sunboard</fullName>
            </value>
            <value>
                <fullName>One-way-Vision</fullName>
            </value>
            <value>
                <fullName>Front lit Flex Board</fullName>
            </value>
            <value>
                <fullName>Back lit board (GSB)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>Branding_Request__r.CaseNumber &amp;&quot; - &quot;&amp; Shop__r.Name &amp;&quot; - &quot;&amp; Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shop</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Direct Dealer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recce Details</relationshipLabel>
    <relationshipName>Recce_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/ctrlReceeObjectRelatedList.cls
/***************************************************************************************
Copyright © 2015 Ashirvad. All rights reserved.
Author: Pranitha S
Email:Pranitha_S@infosys.com
Description:class for recce related list
 ****************************************************************************************/ 
public class ctrlReceeObjectRelatedList {

// variable Declaration

public List<Recce_Detail__c> recList{get;set;}

//private variables
private id Recid {get;set;}
private Recce_Detail__c curRec{get;set;}
private integer counter;
private integer total_size{get; set;}
private integer list_size;
private string soql;

 /**
 * Name: ctrlReceeObjectRelatedList
 * Params: None
 * Description: Constructor for initializing variables
 */
 public ctrlReceeObjectRelatedList(ApexPages.StandardController controller) {
    try{
        curRec= new Recce_Detail__c();
        recList= new List<Recce_Detail__c>();
        list_size=5;
        counter=0;
        fetchRecords();
    }Catch(Exception e){
        system.debug('Exception Occured'+e.getMessage());
    }
 }

 /**
 * Name: fetchRecords
 * Params: None
 * Description: Method to fetch recce records for a case.
 */
public void fetchRecords(){
try{  
    Recid=ApexPages.currentPage().getParameters().get('id');
    curRec=[select id,Branding_Request__c,Branding_Request__r.casenumber from Recce_Detail__c where id=:Recid];
    String caseId=curRec.Branding_Request__c;
    String curRecId=curRec.id;
    soql = 'select id,Name,Shop__r.name,Branding_Type__c,Job_Type__c,Approximate_Cost__c,Name__c from Recce_Detail__c where Branding_Request__c=:caseId and Id!=:curRecId';     
    recList= Database.query(soql);
    total_size =recList.size();
    soql+= ' limit '+list_size+'offset '+counter ;   
    recList= Database.query(soql);
    }Catch(Exception e){
        system.debug('Exception Occured'+e.getMessage());
    }

}

 /**
 * Name: newRequest
 * Params: None
 * Description: Method to create new recce records for a case.
 */
/*public pagereference newRequest(){
PageReference pageReference = new PageReference ('/a19/e?CF00NV0000000qqnd='+curRec.Branding_Request__r.casenumber+'&CF00NV0000000qqnd_lkid='+curRec.Branding_Request__c+'&retURL='+Recid);
      return pageReference;
}*/

 /**
 * Name: Beginning
 * Params: None
 * Description: Method called when user clicks Beginning
 */
public PageReference Beginning() {
try{
      counter = 0;
      fetchRecords();
      return null;
    }Catch(Exception e){
        system.debug('Exception Occured'+e.getMessage());
        return null;
    }
 }

/**
 * Name: Previous
 * Params: None
 * Description: Method called when user clicks previous
 */ 
public PageReference Previous() {
try{      
    counter -= list_size;
    fetchRecords();
    return null;
    }Catch(Exception e){
        system.debug('Exception Occured'+e.getMessage());
        return null;
    }
 }
 
/**
 * Name: Next
 * Params: None
 * Description: Method called when user clicks Next
 */  
public PageReference Next() {
try{
      counter += list_size;
      fetchRecords();
      }Catch(Exception e){
        system.debug('Exception Occured'+e.getMessage());
    }
    return null;
   }

/**
 * Name: End
 * Params: None
 * Description: Method called when user clicks End
 */   
public PageReference End() { 
   try{
      counter = total_size - math.mod(total_size, list_size);
        fetchRecords();
      }Catch(Exception e){
        system.debug('Exception Occured'+e.getMessage());
    }
     return null;
   }

/**
 * Name: getDisablePrevious
 * Params: None
 * Description: Method that will disable the previous and beginning buttons
 */   
public Boolean getDisablePrevious() {
      if (counter>0) return false; else return true;
 }

/**
 * Name: getDisableNext
 * Params: None
 * Description: Method that will disable the next and end buttons
 */  
public Boolean getDisableNext() { 
      if (counter + list_size < total_size) return false; else return true;
 }

/**
 * Name: getTotal_size
 * Params: None
 * Description: Method that returns total size of records.
 */  
public Integer getTotal_size() {
      return total_size;
 }
}