Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/Branding_Request__c.object-meta.xml
<CustomObject>
    <label>Branding Request</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Branding Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branding Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Branding_Request__c.field-meta.xml
<CustomField>
    <fullName>Branding_Request__c</fullName>
    <label>Branding Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Branding Requests</relationshipLabel>
    <relationshipName>Branding_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Branding_Type__c.field-meta.xml
<CustomField>
    <fullName>Branding_Type__c</fullName>
    <label>Branding Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Shop</fullName>
            </value>
            <value>
                <fullName>Outshop</fullName>
            </value>
            <value>
                <fullName>Full Shop</fullName>
            </value>
            <value>
                <fullName>Recce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Metro_Non_Metro__c.field-meta.xml
<CustomField>
    <fullName>Metro_Non_Metro__c</fullName>
    <label>Metro/Non-Metro</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Metro</fullName>
            </value>
            <value>
                <fullName>Non Metro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Details</label>
    <referenceTo>Vendor_Details__c</referenceTo>
    <relationshipLabel>Branding Requests</relationshipLabel>
    <relationshipName>Branding_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Vendor_Code__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Code__c</fullName>
    <formula>IF(ISBLANK(Vendor_Account__c),User1__r.Vendor_Code__c, Vendor_Account__r.SAP_Vendor_Code__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Code</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Vendor_Details__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Details</label>
    <referenceTo>Vendor_Details__c</referenceTo>
    <relationshipLabel>Branding Requests (Vendor Details)</relationshipLabel>
    <relationshipName>Branding_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Recce_Cost_Setting__c/Recce_Cost_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting for calculating the cost per sq feet in recce</description>
    <label>Recce Cost Setting</label>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Recce_Cost_Setting__c/fields/Cost_sqft__c.field-meta.xml
<CustomField>
    <fullName>Cost_sqft__c</fullName>
    <label>Cost/sqft</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Cost_Setting__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/Recce_Detail__c.object-meta.xml
<CustomObject>
    <description>Object to hold Recce report details for a branding request that is generted by the vendor.</description>
    <label>Recce Detail</label>
    <nameField>
        <displayFormat>RD-{000000}</displayFormat>
        <label>Recce Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recce Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Approximate_Cost__c.field-meta.xml
<CustomField>
    <fullName>Approximate_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Approximate Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Branding_Request__c.field-meta.xml
<CustomField>
    <fullName>Branding_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branding Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Recce Details</relationshipLabel>
    <relationshipName>Recce_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Branding_Type__c.field-meta.xml
<CustomField>
    <fullName>Branding_Type__c</fullName>
    <label>Branding Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Shop</fullName>
            </value>
            <value>
                <fullName>Out Shop</fullName>
            </value>
            <value>
                <fullName>Full Shop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Height_in_Inches__c.field-meta.xml
<CustomField>
    <fullName>Height_in_Inches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Height in Inches</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branding_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Vinyl</fullName>
            </value>
            <value>
                <fullName>Vinyl on Sunboard</fullName>
            </value>
            <value>
                <fullName>One-way-Vision</fullName>
            </value>
            <value>
                <fullName>Front lit Flex Board</fullName>
            </value>
            <value>
                <fullName>Back lit board (GSB)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shop</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Direct Dealer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recce Details</relationshipLabel>
    <relationshipName>Recce_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Total_Updated_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Updated_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Updated Cost for shop</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Updated_Approximate_Cost__c.field-meta.xml
<CustomField>
    <fullName>Updated_Approximate_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Updated Approximate Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Updated_Height_in_Inches__c.field-meta.xml
<CustomField>
    <fullName>Updated_Height_in_Inches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Updated Height in Inches</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Updated_Width_in_Inches__c.field-meta.xml
<CustomField>
    <fullName>Updated_Width_in_Inches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Updated Width in Inches</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Width_in_Inches__c.field-meta.xml
<CustomField>
    <fullName>Width_in_Inches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Width in Inches</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/Vendor_Details__c.object-meta.xml
<CustomObject>
    <label>Vendor Details</label>
    <nameField>
        <label>Vendor Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vendor</description>
    <inlineHelpText>Vendor</inlineHelpText>
    <label>Vendor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vendor_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/fields/Vendor_Code__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Code__c</fullName>
    <description>Vendor Code</description>
    <inlineHelpText>Vendor Code</inlineHelpText>
    <label>Vendor Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/CtrlRecceCostUpdation_UT.cls
/*  
 * Modified By: Renjay Surendran
 */ 
@isTest
public class CtrlRecceCostUpdation_UT{

static testmethod void calculateCostTest(){

List<id> recID=new List<id>();

Profile profileID = [select id from profile where Name='System Administrator' limit 1];

User user1 = new User(LastName='XYZ',ProfileId=profileID.Id,Alias='test',EmailEncodingKey='UTF-8',
        Email='vasanthi_KN@infosys.com',UserName='vasanthi_KN111@infosys.com',
        User_State__c ='Karnataka',
        TimeZoneSidKey='America/New_York',
        LocaleSidKey='en_US',LanguageLocaleKey='en_US',vendor_code__c ='GUW100903' );

insert user1;

Schema.DescribeSObjectResult cfrSchemaa = Schema.SObjectType.Account; 
Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfoa = cfrSchemaa.getRecordTypeInfosByName();

Id ii= AccountRecordTypeInfoa.get('Distributor').getRecordTypeId();

Account acc1=new Account(recordtypeid =ii,name ='testAccount', Primary_Contact_Person_Name__c='Test',market__c='Prospect',
      classification__c='C', Purchase_Cycle__c='Monthly', status__c='Cold Call', Conversion_Probability__c='Low', Description='abcd',
      state__c='Goa', Street_Address__c='xyzx', Products__c='SWR', 
      Contact_Number_Mobile__c='7156784489',Media__c='In Shop', No_of_Salesmen__c=1, No_of_Vehicles__c=2, Approx_Size_of_shop_in_Sq_ft__c=10, Display_of_our_product__c='Prominent');

insert acc1;

Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Case; 
Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = cfrSchema.getRecordTypeInfosByName();

Id i= AccountRecordTypeInfo.get('Branding Request').getRecordTypeId();
Recce_Cost_Setting__c recCost = new Recce_Cost_Setting__c();
recCost.Cost_sqft__c=10;
recCost.name='GUW100903-Vinyl';
recCost.vendor_code__c='GUW100903';
insert recCost;

 Vendor_Details__c ven = new Vendor_Details__c();
            ven.name ='XYZ';
            ven.vendor_code__c ='GUW100903';
            ven.Vendor__c=user1.id;
            insert ven;

Case caseRec= new Case(recordtypeId = i,
        status ='New', origin='Self', Priority='Medium', Is_In_Approval_Process__c =false,
        Team_Lead__c =user1.id, depo__c=user1.id, Metro_Non_Metro__c = 'Metro',
        city__c='Bangalore',vendor__c=user1.id, Vendor_Details__c=ven.id);
insert caseRec;

List<Recce_Detail__c> recList = new List<Recce_Detail__c>();

Recce_Detail__c recDet = new Recce_Detail__c(
        Branding_Request__c = caseRec.id,
        Height_in_Inches__c =10,
        Width_in_Inches__c =10,
        Updated_Height_in_Inches__c =10,
        Updated_Width_in_Inches__c =10,
        Total_Updated_Cost__c=0.0,
        Approximate_Cost__c=0.0,
        Updated_Approximate_Cost__c=0.0,
        Branding_Type__c='In Shop',
        Shop__c =acc1.id,
        Job_Type__c= 'Vinyl');

Recce_Detail__c recDet2 = new Recce_Detail__c(
        Branding_Request__c = caseRec.id,
        Height_in_Inches__c =12,
        Width_in_Inches__c =10,
        Updated_Height_in_Inches__c =10,
        Updated_Width_in_Inches__c =10,
        Total_Updated_Cost__c=0.0,
        Approximate_Cost__c=0.0,
        Updated_Approximate_Cost__c=0.0,
        Branding_Type__c='In Shop',
        Shop__c =acc1.id,
        Job_Type__c= 'Vinyl');
        
Recce_Detail__c recDet3 = new Recce_Detail__c(
        Branding_Request__c = caseRec.id,
        Height_in_Inches__c =15,
        Width_in_Inches__c =10,
        Updated_Height_in_Inches__c =10,
        Updated_Width_in_Inches__c =10,
        Total_Updated_Cost__c=0.0,
        Approximate_Cost__c=0.0,
        Updated_Approximate_Cost__c=0.0,
        Branding_Type__c='In Shop',
        Shop__c =acc1.id,
        Job_Type__c= 'Vinyl');        

Recce_Detail__c recDet4 = new Recce_Detail__c(
        Branding_Request__c = caseRec.id,
        Height_in_Inches__c =15,
        Width_in_Inches__c =10,
        Updated_Height_in_Inches__c =10,
        Updated_Width_in_Inches__c =10,
        Total_Updated_Cost__c=0.0,
        Approximate_Cost__c=0.0,
        Updated_Approximate_Cost__c=0.0,
        Branding_Type__c='In Shop',
        Shop__c =acc1.id,
        Job_Type__c= 'Vinyl');     
              
        system.runas(user1)
        {
                test.starttest();                  
                
                id r=insertTest(recDet);
                RecursiveHandler.isNotRecursive=true;
                delTest(r);
                
                RecursiveHandler.isNotRecursive=false;
                r=insertTest(recDet2);
                recID.add(r);
                
                RecursiveHandler.isNotRecursive=true;
                r=insertTest(recDet3);
                recID.add(r);
                
                RecursiveHandler.isNotRecursive=true;
                r=insertTest(recDet4);
                recID.add(r);
                
                upRec(recID);
                
                RecursiveHandler.isNotRecursive=true;
                delTest(r);
                
                test.stoptest();                       
        }
}

static void upRec(List<id> recId){

    List<Recce_Detail__c> recList=[Select Job_Type__c, Shop__c, Branding_Type__c, Total_Updated_Cost__c, Updated_Approximate_Cost__c, Approximate_Cost__c, Branding_Request__c,Updated_Height_in_Inches__c,Updated_Width_in_Inches__c, Height_in_Inches__c,Width_in_Inches__c from Recce_Detail__c where  id IN: recId];
    
    recList[0].Updated_Width_in_Inches__c=25;
    recList[0].Updated_Height_in_Inches__c=20;
    RecursiveHandler.isNotRecursive=true;
    update recList[0]; 
    
    recList[0].Updated_Width_in_Inches__c=24;
    recList[0].Updated_Height_in_Inches__c=20;
    RecursiveHandler.isNotRecursive=false;
    update recList[0]; 
}

static id insertTest(Recce_Detail__c rec){
    insert rec;
    
    return rec.id;
}
static void delTest(id r){
    
    Recce_Detail__c rec=[select id from Recce_Detail__c where id=:r];
    
    delete rec;
}
}