Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/Branding_Request__c.object-meta.xml
<CustomObject>
    <label>Branding Request</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Branding Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branding Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Branding_Request__c.field-meta.xml
<CustomField>
    <fullName>Branding_Request__c</fullName>
    <label>Branding Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Branding Requests</relationshipLabel>
    <relationshipName>Branding_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Branding_Type__c.field-meta.xml
<CustomField>
    <fullName>Branding_Type__c</fullName>
    <label>Branding Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Shop</fullName>
            </value>
            <value>
                <fullName>Outshop</fullName>
            </value>
            <value>
                <fullName>Full Shop</fullName>
            </value>
            <value>
                <fullName>Recce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Details</label>
    <referenceTo>Vendor_Details__c</referenceTo>
    <relationshipLabel>Branding Requests</relationshipLabel>
    <relationshipName>Branding_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Vendor_Code__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Code__c</fullName>
    <formula>IF(ISBLANK(Vendor_Account__c),User1__r.Vendor_Code__c, Vendor_Account__r.SAP_Vendor_Code__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Code</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Vendor_Details__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Details</label>
    <referenceTo>Vendor_Details__c</referenceTo>
    <relationshipLabel>Branding Requests (Vendor Details)</relationshipLabel>
    <relationshipName>Branding_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Cost_Setting__c/Recce_Cost_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting for calculating the cost per sq feet in recce</description>
    <label>Recce Cost Setting</label>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Recce_Cost_Setting__c/fields/Cost_sqft__c.field-meta.xml
<CustomField>
    <fullName>Cost_sqft__c</fullName>
    <label>Cost/sqft</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Cost_Setting__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/Recce_Detail__c.object-meta.xml
<CustomObject>
    <description>Object to hold Recce report details for a branding request that is generted by the vendor.</description>
    <label>Recce Detail</label>
    <nameField>
        <displayFormat>RD-{000000}</displayFormat>
        <label>Recce Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recce Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Branding_Request__c.field-meta.xml
<CustomField>
    <fullName>Branding_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branding Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Recce Details</relationshipLabel>
    <relationshipName>Recce_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Branding_Type__c.field-meta.xml
<CustomField>
    <fullName>Branding_Type__c</fullName>
    <label>Branding Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Shop</fullName>
            </value>
            <value>
                <fullName>Out Shop</fullName>
            </value>
            <value>
                <fullName>Full Shop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Height_in_Inches__c.field-meta.xml
<CustomField>
    <fullName>Height_in_Inches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Height in Inches</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branding_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Vinyl</fullName>
            </value>
            <value>
                <fullName>Vinyl on Sunboard</fullName>
            </value>
            <value>
                <fullName>One-way-Vision</fullName>
            </value>
            <value>
                <fullName>Front lit Flex Board</fullName>
            </value>
            <value>
                <fullName>Back lit board (GSB)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/Vendor_Details__c.object-meta.xml
<CustomObject>
    <label>Vendor Details</label>
    <nameField>
        <label>Vendor Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vendor</description>
    <inlineHelpText>Vendor</inlineHelpText>
    <label>Vendor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vendor_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/fields/Vendor_Code__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Code__c</fullName>
    <description>Vendor Code</description>
    <inlineHelpText>Vendor Code</inlineHelpText>
    <label>Vendor Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/ctrlReceeObjectRelatedList_UT.cls
@isTest
public class ctrlReceeObjectRelatedList_UT{
static testmethod void ctrlReceeObjectRelatedListTest(){
 Profile profileID = [select id from profile where Name='System Administrator' limit 1];
 
 User user1 = new User(LastName='XYZ',ProfileId=profileID.Id,Alias='test',EmailEncodingKey='UTF-8',
       Email='vasanthi_KN@infosys.com',UserName='vasanthi_KN112@infosys.com',
        User_State__c ='Karnataka',
        TimeZoneSidKey='America/New_York',
        LocaleSidKey='en_US',LanguageLocaleKey='en_US');
     
 insert user1;

 Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Case; 
 Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = cfrSchema.getRecordTypeInfosByName();
 
Id i= AccountRecordTypeInfo.get('Branding Request').getRecordTypeId();

Recce_Cost_Setting__c recCost = new Recce_Cost_Setting__c();
recCost.Cost_sqft__c=10;
recCost.name='GUW100903-Vinyl';
recCost.vendor_code__c='GUW100903';
insert recCost;

 Vendor_Details__c ven = new Vendor_Details__c();
            ven.name ='XYZ';
            ven.vendor_code__c ='GUW100903';
            ven.Vendor__c=user1.id;
            insert ven;

  Case caset= new Case(recordtypeId = i, Request_Raised_By__c = user1.id,
  status ='New',vendor__c=user1.id, Vendor_Details__c=ven.id);
  
 insert caset;
 
 Recce_Detail__c rec= new Recce_Detail__c(Branding_Request__c=caset.id,Branding_Type__c='In Shop',Height_in_Inches__c=10.00,Job_Type__c= 'Vinyl');
 insert rec;
 
 Recce_Detail__c rec1= new Recce_Detail__c(Branding_Request__c=caset.id, Branding_Type__c='In Shop',Height_in_Inches__c=20.00,Job_Type__c= 'Vinyl');
 insert rec1;
 
 Recce_Detail__c rec3= new Recce_Detail__c(Branding_Request__c=caset.id, Branding_Type__c='In Shop',Height_in_Inches__c=30.00,Job_Type__c= 'Vinyl');
 insert rec3;
 
 Recce_Detail__c rec4= new Recce_Detail__c(Branding_Request__c=caset.id, Branding_Type__c='In Shop',Height_in_Inches__c=40.00,Job_Type__c= 'Vinyl');
 insert rec4;
 
  ApexPages.currentPage().getParameters().put('Id', rec.id);
  Apexpages.StandardController stdController = new Apexpages.StandardController(rec); 
  ctrlReceeObjectRelatedList recobj= new ctrlReceeObjectRelatedList(stdController );
  recobj.fetchRecords();
  //recobj.newRequest();
  recobj.Beginning();
 // recobj.Previous();
  recobj.Next();
  recobj.End();
  recobj.getDisablePrevious();
  recobj.getDisableNext();
  recobj.getTotal_size();
 }
 }