Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/Branding_Request__c.object-meta.xml
<CustomObject>
    <label>Branding Request</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Branding Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branding Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Branding_Request__c.field-meta.xml
<CustomField>
    <fullName>Branding_Request__c</fullName>
    <label>Branding Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Branding Requests</relationshipLabel>
    <relationshipName>Branding_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/Recce_Detail__c.object-meta.xml
<CustomObject>
    <description>Object to hold Recce report details for a branding request that is generted by the vendor.</description>
    <label>Recce Detail</label>
    <nameField>
        <displayFormat>RD-{000000}</displayFormat>
        <label>Recce Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recce Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Branding_Request__c.field-meta.xml
<CustomField>
    <fullName>Branding_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branding Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Recce Details</relationshipLabel>
    <relationshipName>Recce_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Height_in_Inches__c.field-meta.xml
<CustomField>
    <fullName>Height_in_Inches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Height in Inches</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Updated_Height_in_Inches__c.field-meta.xml
<CustomField>
    <fullName>Updated_Height_in_Inches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Updated Height in Inches</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Updated_Width_in_Inches__c.field-meta.xml
<CustomField>
    <fullName>Updated_Width_in_Inches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Updated Width in Inches</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Recce_Detail__c/fields/Width_in_Inches__c.field-meta.xml
<CustomField>
    <fullName>Width_in_Inches__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Width in Inches</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/RecceHWUpdation.cls
/***************************************************************************************
Copyright © 2015 Ashirvad. All rights reserved.
Author: Pranitha S
Email: Pranitha_S@infosys.com
Description:  Handler class for trigBrandingRequestTrigger for recce height and width updation.
 ****************************************************************************************/
public class RecceHWUpdation{

/**
 * Name: updtHeightWidth
 * Params: None
 * Description: Method to update height and width in Recce records.
 */ 
public void updtHeightWidth(){

try{
    if(trigger.isafter && trigger.isupdate)
      {     
            List<Recce_Detail__c> finalRecce = new List<Recce_Detail__c>();
            List<id> caseRecordDB=new List<id>();
            Id Rt = [select Id from RecordType where Name ='Branding Request' and SobjectType = 'case' limit 1].id;
            for(sobject caseData : trigger.new){
               case cas= (case)caseData;
                 if(cas.RecordTypeId==Rt){
                    if(cas.status.equals(System.Label.Branding_Request_Recce_Approved_by_Branding_team ))
                    {   
                        caseRecordDB.add(cas.id); 
                    }
                  }
            } 
            List<Recce_Detail__c> recceRecords =[select id, Updated_Height_in_Inches__c, Updated_Width_in_Inches__c, Height_in_Inches__c, Width_in_Inches__c from Recce_Detail__c where Branding_Request__c IN: caseRecordDB];    
            for(Recce_Detail__c recData : recceRecords)
            {    
                if(recData.Updated_Height_in_Inches__c==null||recData.Updated_Width_in_Inches__c==null|| 
                recData.Updated_Height_in_Inches__c==0||recData.Updated_Width_in_Inches__c==0){  
                recData.Updated_Height_in_Inches__c=recData.Height_in_Inches__c;
                recData.Updated_Width_in_Inches__c=recData.Width_in_Inches__c;

                finalRecce.add(recData);
                } 
            }
            
            update finalRecce;   
      }
   }
   catch(exception e){system.debug('Exception Occurred'+e.getMessage());}  
}
}