Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/Branding_Request__c.object-meta.xml
<CustomObject>
    <label>Branding Request</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Branding Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branding Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Branding_Request__c.field-meta.xml
<CustomField>
    <fullName>Branding_Request__c</fullName>
    <label>Branding Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Branding Requests</relationshipLabel>
    <relationshipName>Branding_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Shop_Name__c.field-meta.xml
<CustomField>
    <fullName>Shop_Name__c</fullName>
    <label>Shop Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Direct Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branding Requests</relationshipLabel>
    <relationshipName>Branding_Requests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/trigBrandingRequestHandler.cls
/***************************************************************************************
Copyright © 2015 Ashirvad. All rights reserved.
Author: Pranitha S
Email: Pranitha_S@infosys.com
Description:  handler class for trigBrandingRequest to concatenate shop Names
 ****************************************************************************************/
public class trigBrandingRequestHandler {
 public void trigBrandingRequests() {
  List<Id> brcaseids = new List<Id>();
  Map<Id,String> brToShopNameMap = new Map<Id,String>();
  try{
   if(Trigger.Isinsert || Trigger.Isupdate) {
      for(Sobject brs :Trigger.new ) {
         Branding_Request__c brRequest = (Branding_Request__c)brs;
         brcaseids.add(brRequest.Branding_Request__c);
      } 
      for(Branding_Request__c br : [Select Id,Shop_Name__r.Name,Branding_Request__c from Branding_Request__c where Branding_Request__c IN :brcaseids]) {
         if(brToShopNameMap.containsKey(br.Branding_Request__c )) {
            brToShopNameMap.put(br.Branding_Request__c ,brToShopNameMap.get(br.Branding_Request__c)+';'+br.Shop_Name__r.Name); 
         }
         else {
            brToShopNameMap.put(br.Branding_Request__c,br.Shop_Name__r.Name);
         }
       }
       List<Case> cases = new List<Case>();
       for(Case c : [SELECT ID,Shop_Names__c from Case where Id IN :brToShopNameMap.keyset()]) {
          c.Shop_Names__c = brToShopNameMap.get(c.id);
          cases.add(c);
       }
       update cases;
   }
   if(Trigger.Isdelete) {
     for(SObject brs :Trigger.old ) {
         Branding_Request__c brRequest = (Branding_Request__c)brs;
         brcaseids.add(brRequest.Branding_Request__c);
      } 
      for(Branding_Request__c br : [Select Id,Shop_Name__r.Name,Branding_Request__c from Branding_Request__c where Branding_Request__c IN :brcaseids ]) {
         if(brToShopNameMap.containsKey(br.Branding_Request__c )) {
            brToShopNameMap.put(br.Branding_Request__c ,brToShopNameMap.get(br.Branding_Request__c)+';'+br.Shop_Name__r.Name); 
         }
         else {
            brToShopNameMap.put(br.Branding_Request__c,br.Shop_Name__r.Name);
         }
       }
       List<Case> cases = new List<Case>();
       for(Case c : [SELECT ID,Shop_Names__c from Case where Id IN :brToShopNameMap.keyset()]) {
          c.Shop_Names__c = brToShopNameMap.get(c.id);
          cases.add(c);
       }
       update cases;
   }
  } catch(exception e){system.debug('Exception Occurred'+e.getMessage());}
}
}