Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/Branding_Request__c.object-meta.xml
<CustomObject>
    <label>Branding Request</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Branding Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branding Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Branding_Approved_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Branding_Approved_Rejected__c</fullName>
    <label>Branding Approved/Rejected</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted To TL</fullName>
            </value>
            <value>
                <fullName>Approved by TL</fullName>
            </value>
            <value>
                <fullName>Rejected by TL</fullName>
            </value>
            <value>
                <fullName>Escalated by  Head Branding</fullName>
            </value>
            <value>
                <fullName>Submitted To RBM</fullName>
            </value>
            <value>
                <fullName>Approved by RBM</fullName>
            </value>
            <value>
                <fullName>Rejected by RBM</fullName>
            </value>
            <value>
                <fullName>Escalated by RBM</fullName>
            </value>
            <value>
                <fullName>Submitted To Branding Head</fullName>
            </value>
            <value>
                <fullName>Approved By Branding Head</fullName>
            </value>
            <value>
                <fullName>Rejected By Branding Head</fullName>
            </value>
            <value>
                <fullName>Submitted To Vendor</fullName>
            </value>
            <value>
                <fullName>Approved By Vendor</fullName>
            </value>
            <value>
                <fullName>Rejected By Vendor</fullName>
            </value>
            <value>
                <fullName>Request Created</fullName>
            </value>
            <value>
                <fullName>Vendor Assigned-Rework</fullName>
            </value>
            <value>
                <fullName>Vendor Assigned-Completed</fullName>
            </value>
            <value>
                <fullName>Request Completed and Submitted</fullName>
            </value>
            <value>
                <fullName>Vendor Assigned</fullName>
            </value>
            <value>
                <fullName>Escalated to Branding Head</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Branding_Request__c.field-meta.xml
<CustomField>
    <fullName>Branding_Request__c</fullName>
    <label>Branding Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Branding Requests</relationshipLabel>
    <relationshipName>Branding_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Branding_Type__c.field-meta.xml
<CustomField>
    <fullName>Branding_Type__c</fullName>
    <label>Branding Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Shop</fullName>
            </value>
            <value>
                <fullName>Outshop</fullName>
            </value>
            <value>
                <fullName>Full Shop</fullName>
            </value>
            <value>
                <fullName>Recce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Media_Type__c.field-meta.xml
<CustomField>
    <fullName>Media_Type__c</fullName>
    <description>field from Branding Request</description>
    <label>Media Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/RBM__c.field-meta.xml
<CustomField>
    <fullName>RBM__c</fullName>
    <formula>CASESAFEID(Submitted_By__r.Branding_Team_Member__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RBM</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/RejectComment__c.field-meta.xml
<CustomField>
    <fullName>RejectComment__c</fullName>
    <label>RejectComment</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Shop_Name__c.field-meta.xml
<CustomField>
    <fullName>Shop_Name__c</fullName>
    <label>Shop Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Direct Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branding Requests</relationshipLabel>
    <relationshipName>Branding_Requests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rework</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Dealer Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/User1__c.field-meta.xml
<CustomField>
    <fullName>User1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Branding_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Vendor_Fee__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Fee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Vendor Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Vendor_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Submitted_Date__c</fullName>
    <label>Vendor Submitted Date</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Vertical_type__c.field-meta.xml
<CustomField>
    <fullName>Vertical_type__c</fullName>
    <formula>TEXT( CreatedBy.Vertical_Type__c )</formula>
    <label>Vertical type</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/City__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/VendorPageController.cls
public without sharing class VendorPageController{
    
    public final static String afterFolderId='00l4C000000M6b1QAC';
    public final static String beforeFolderId='00l4C000000M6b6QAC';
    public string getShopId {get;set;}
    @RemoteAction
    public static List<Branding_Request__c> collectVendorBrand(){
     
        List<String> condition=new List<String>();
        condition.add('Vendor Assigned-Rework');
        condition.add('Vendor Assigned');
        condition.add('Request Completed and Submitted');
        
        
        List<String> profName=new List<String>();
         profName.add('Head Branding');
         profName.add('Regional Branding Manager'); 
         profName.add('System Administrator');
         profName.add('Ashirvad Partner Community User');
         String usrProfileId=userInfo.getProfileId();     
         List<Profile> proflist=[select id,name from profile where name in:profName];
         String prof='';
          System.debug(prof);
          for(Profile pf:proflist){
            if(pf.id==usrProfileId){
                prof=pf.Name;
                break;
              
            }
         }
         List<Branding_Request__c> brdLst=new List<Branding_Request__c>();
         
         if(prof=='Ashirvad Partner Community User'){

          brdLst.addAll([select id,RejectComment__c,Vendor_Submitted_Date__c,Branding_Approved_Rejected__c,Name,(select id, name,ParentId from Attachments limit 2),Branding_Type__c,media_type__c,Request_Type__c,Type__c,Shop_Name__r.Name,Shop_Name__r.Primary_Contact_Person_Name__c,Shop_Name__r.Contact_Number_Phone_1__c,Shop_Name__r.Contact_Number_Mobile__c,Shop_Name__r.Contact_Number_Phone__c,shop_Name__r.PIN_Code__c,shop_Name__r.State__c,shop_Name__r.District__c,shop_Name__r.City__c,shop_Name__r.Street_Address__c,vertical_type__c from Branding_Request__c where user1__c=:userInfo.getUserId() and  Branding_Approved_Rejected__c in:condition]);
         
         
        }else if(prof=='System Administrator' || prof=='Regional Branding Manager' || prof=='Head Branding' ){

          brdLst.addAll([select id,Vendor_Fee__c,Vendor_Submitted_Date__c,Branding_Approved_Rejected__c,Name,(select id, name,ParentId from Attachments limit 2),Branding_Type__c,media_type__c,Request_Type__c,Type__c,vertical_type__c,Shop_Name__r.Name,Shop_Name__r.Primary_Contact_Person_Name__c,Shop_Name__r.Contact_Number_Phone_1__c,Shop_Name__r.Contact_Number_Mobile__c,Shop_Name__r.Contact_Number_Phone__c,shop_Name__r.PIN_Code__c,shop_Name__r.State__c,shop_Name__r.District__c,shop_Name__r.City__c,shop_Name__r.Street_Address__c from Branding_Request__c where Branding_Approved_Rejected__c in:condition]);
        
         }          

        return(brdLst);
        
    }
    
   
    @RemoteAction
    public static List<Branding_Request__c> collectApproveBrand(){
         List<String> profName=new List<String>();
         profName.add('Regional Branding Manager'); 
         profName.add('System Administrator');
         List<Branding_Request__c> brdLst=new List<Branding_Request__c>();
         String usrProfileId=userInfo.getProfileId();     
         List<Profile> proflist=[select id,name from profile where name in:profName];
         String prof='';
          System.debug(prof);
          for(Profile pf:proflist){
            if(pf.id==usrProfileId){
                prof=pf.Name;
                break;
            }
         }
         
         if(prof=='Regional Branding Manager' || prof=='System Administrator'){
             brdLst.addAll([select id,Vendor_Fee__c,Vendor_Submitted_Date__c,Branding_Approved_Rejected__c,Name,status__c,(select id, name,ParentId from Attachments limit 2),Branding_Type__c,media_type__c,Request_Type__c,Shop_Name__r.Name,Shop_Name__r.Primary_Contact_Person_Name__c,Shop_Name__r.Contact_Number_Mobile__c,Shop_Name__r.Contact_Number_Phone__c,shop_Name__r.PIN_Code__c,shop_Name__r.State__c,shop_Name__r.District__c,shop_Name__r.City__c,shop_Name__r.Street_Address__c ,Vertical_type__c from Branding_Request__c where RBM__c=:userInfo.getUserId() AND Branding_Approved_Rejected__c='Request Completed and Submitted']);
      
         }
        return(brdLst);
    }
        
    @RemoteAction
   public static boolean approveRequest(List<String> vendlst,String comment){
        return (approvalProcess(vendlst,comment,'Approve'));
   }
   
   @RemoteAction
   public static boolean rejectRequest(List<String> vendlst,String comment){
        return (approvalProcess(vendlst,comment,'Reject'));
   }
    
    @RemoteAction
    public static boolean approvalProcess(List<String> venIds,String comment, String action){
        try{
           
            System.debug(venIds);
            System.debug(comment);
            System.debug(action);
            
            Set<Id> brdIdSet=new Set<Id>();
            List<Branding_Request__c> brdlst=new List<Branding_Request__c>();                               
            List<ProcessInstance> PIList=new List<ProcessInstance>();
            List<ProcessInstanceWorkitem> PIWList;
            List<Approval.ProcessWorkitemRequest> APWRList;            
            PIList.addAll([SELECT Id, Status,TargetObjectId FROM ProcessInstance WHERE TargetObjectId IN :venIds and Status = 'Pending']);
            System.debug(PIList);
            Set<Id> targetIdSet=new Set<Id>();
            for(ProcessInstance temp:PIList){
                targetIdSet.add(temp.Id);
            }
            
            
            System.debug('target'+targetIdSet);
            PIWList=new List<ProcessInstanceWorkitem>();            
            if(targetIdSet.size()>0){
                PIWList.addAll([SELECT Id,ProcessInstanceId FROM ProcessInstanceWorkitem where ProcessInstanceId IN: targetIdSet]);
                System.debug('zzz'+PIWList);
                APWRList=new List<Approval.ProcessWorkitemRequest>();
                for(ProcessInstanceWorkitem temp:PIWList){
                    Approval.ProcessWorkitemRequest appReq = new Approval.ProcessWorkitemRequest();
                    appReq.setComments(comment);
                    appReq.setAction(action);
                    appReq.setWorkitemId(temp.Id);
                    APWRList.add(appReq);   
                }
                System.debug(APWRList);
                if(APWRList.size()>0){
                    list<Approval.ProcessResult> Result=  Approval.process(APWRList);
                    System.debug(Result);
                    for(Approval.ProcessResult tempResult:Result){
                        if(tempResult.isSuccess() && tempResult.getInstanceStatus()=='Rejected' ){
                          brdIdSet.add(tempResult.getEntityId());
                        }
                    }
                    for(id tt:brdIdSet){
                      Branding_Request__c tmp=new Branding_Request__c();
                      tmp.Id=tt;
                      tmp.RejectComment__c=comment;
                      brdlst.add(tmp);
                    }
                    if(brdlst.size()>0){
                      update brdlst;
                    }
                                   
                }else{
                    return false;
                }
            }else{
                return false;
            }
            
            return true;
        }catch(Exception ex){
            System.debug(ex.getMessage());
            System.debug(ex);
            return false;
        }
    }   
   
    @RemoteAction
    public static boolean submitData(List<VenBrandWrap> venlst){
        try{
            List<Branding_Request__c> brdList=new List<Branding_Request__c>();
            for(VenBrandWrap ven:venlst){
                Branding_Request__c temp=new Branding_Request__c();
                temp.Id=ven.BrandId;
                temp.Branding_Approved_Rejected__c=ven.Status;
                temp.Vendor_Submitted_Date__c=System.today();
                brdList.add(temp);  
            }
            if(brdList.size()>0)
                update brdList;
                
            return true;
        }catch(Exception ex){
            System.debug(ex);
            return false;
        }
    }
        
    @RemoteAction 
    public static String uploadImage(VenBrandWrap ven,boolean bol){
       try{
           Attachment doc=new Attachment();
           if(bol){
               
               if(ven.beforeDocId!=''){
                  doc.id=ven.beforeDocId;
                  doc.name='Before'+ven.BrandId+''+ven.beforeDocExt;
                  doc.body=EncodingUtil.base64Decode(ven.beforeDoc.substring(ven.beforeDoc.indexOf(',')+1,ven.beforeDoc.length()));
                  update doc;
                 
               }else{
                   doc.body=EncodingUtil.base64Decode(ven.beforeDoc.substring(ven.beforeDoc.indexOf(',')+1,ven.beforeDoc.length()));
                   doc.name='Before'+ven.BrandId+''+ven.beforeDocExt;
                   doc.ParentId=ven.BrandId;
                   insert doc;
               }  
           }else{
               if(ven.afterDocId!=''){
                  doc.id=ven.afterDocId;
                  doc.name='After'+ven.BrandId+''+ven.afterDocExt;
                  doc.body=EncodingUtil.base64Decode(ven.afterDoc.substring(ven.afterDoc.indexOf(',')+1,ven.afterDoc.length()));
                  update doc;
               }else{
                   doc.body=EncodingUtil.base64Decode(ven.afterDoc.substring(ven.afterDoc.indexOf(',')+1,ven.afterDoc.length()));
                   doc.name='After'+ven.BrandId+''+ven.afterDocExt;
                   doc.ParentId=ven.BrandId;
                   insert doc;
               }  
           
           }
           return doc.Id;
       }catch(Exception ex){
           System.debug(ex);
           return 'Failed';
       }  
    } 
    
    public class VenBrandWrap{
        public String BrandId{get;set;}
        public String Status{get;set;}
        public String afterDoc{get;set;}
        public String beforeDoc{get;set;}
        public String afterDocId{get;set;}
        public String beforeDocId{get;set;}
        public String afterDocExt{get;set;}
        public String beforeDocExt{get;set;}
    }
    
 
}