Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/Branding_Request__c.object-meta.xml
<CustomObject>
    <label>Branding Request</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Branding Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branding Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Branding_Request__c.field-meta.xml
<CustomField>
    <fullName>Branding_Request__c</fullName>
    <label>Branding Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Branding Requests</relationshipLabel>
    <relationshipName>Branding_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Shop_Name__c.field-meta.xml
<CustomField>
    <fullName>Shop_Name__c</fullName>
    <label>Shop Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Direct Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branding Requests</relationshipLabel>
    <relationshipName>Branding_Requests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Shop_Type__c.field-meta.xml
<CustomField>
    <fullName>Shop_Type__c</fullName>
    <label>Shop Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Dealer</fullName>
            </value>
            <value>
                <fullName>Existing Dealer</fullName>
            </value>
            <value>
                <fullName>Repair/Rework Dealer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/ctrlBrandingRequest.cls
/***************************************************************************************
Copyright © 2015 Ashirvad. All rights reserved.
Author: Pranitha S
Email:Pranitha_S@infosys.com
Description:class for showing branding requests on an account
 ****************************************************************************************/ 
public with sharing class ctrlBrandingRequest{
  
 // variable Declaration
 public list<Branding_Request__c > brandingRequests{get;set;}
 private String currentAccountId{get;set;}

 /**
 * Name: ctrlBrandingRequest
 * Params: None
 * Description: Constructor for initializing variables
 */
 public ctrlBrandingRequest(ApexPages.StandardController controller){
    try{
        currentAccountId = System.currentPageReference().getParameters().get('id');
        showBrandingRequestCases();
    }Catch(Exception e){
        system.debug('Exception Occured'+e.getMessage());
    }
  }
  
   /**
   * Name: showBrandingRequests
   * Description: To get branding requests for an account
   */
  public List<Branding_Request__c > showBrandingRequestCases(){
      brandingRequests = new List<Branding_Request__c >();
      brandingRequests = [select id,Branding_Request__c,Branding_Request__r.status,Shop_Type__c,Branding_Request__r.CaseNumber,Branding_Request__r.owner.name
      from Branding_Request__c 
      where Shop_Name__c =: currentAccountId ];
      return brandingRequests ;
  }
  
  /**
   * Name: newRequest
   * Description: To create a new case for branding.
   */
  public PageReference newRequest(){
      PageReference pageReference = new PageReference ('/setup/ui/recordtypeselect.jsp?ent=Case&retURL='+currentAccountId+'&save_new_url=/500/e?retURL='+currentAccountId );
      return pageReference;
  }
}