Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/Branding_Request__c.object-meta.xml
<CustomObject>
    <label>Branding Request</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Branding Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branding Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Bhandhan_Check__c.field-meta.xml
<CustomField>
    <fullName>Bhandhan_Check__c</fullName>
    <formula>Shop_Name__r.Bandhan_Cutsomer__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bhandhan Check</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Branding_Approved_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Branding_Approved_Rejected__c</fullName>
    <label>Branding Approved/Rejected</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted To TL</fullName>
            </value>
            <value>
                <fullName>Approved by TL</fullName>
            </value>
            <value>
                <fullName>Rejected by TL</fullName>
            </value>
            <value>
                <fullName>Escalated by  Head Branding</fullName>
            </value>
            <value>
                <fullName>Submitted To RBM</fullName>
            </value>
            <value>
                <fullName>Approved by RBM</fullName>
            </value>
            <value>
                <fullName>Rejected by RBM</fullName>
            </value>
            <value>
                <fullName>Escalated by RBM</fullName>
            </value>
            <value>
                <fullName>Submitted To Branding Head</fullName>
            </value>
            <value>
                <fullName>Approved By Branding Head</fullName>
            </value>
            <value>
                <fullName>Rejected By Branding Head</fullName>
            </value>
            <value>
                <fullName>Submitted To Vendor</fullName>
            </value>
            <value>
                <fullName>Approved By Vendor</fullName>
            </value>
            <value>
                <fullName>Rejected By Vendor</fullName>
            </value>
            <value>
                <fullName>Request Created</fullName>
            </value>
            <value>
                <fullName>Vendor Assigned-Rework</fullName>
            </value>
            <value>
                <fullName>Vendor Assigned-Completed</fullName>
            </value>
            <value>
                <fullName>Request Completed and Submitted</fullName>
            </value>
            <value>
                <fullName>Vendor Assigned</fullName>
            </value>
            <value>
                <fullName>Escalated to Branding Head</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Branding_Request__c.field-meta.xml
<CustomField>
    <fullName>Branding_Request__c</fullName>
    <label>Branding Request</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Branding Requests</relationshipLabel>
    <relationshipName>Branding_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Branding_Type__c.field-meta.xml
<CustomField>
    <fullName>Branding_Type__c</fullName>
    <label>Branding Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Shop</fullName>
            </value>
            <value>
                <fullName>Outshop</fullName>
            </value>
            <value>
                <fullName>Full Shop</fullName>
            </value>
            <value>
                <fullName>Recce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <description>Cluster from the page selected from Branding request.</description>
    <label>Cluster</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>Tamil</fullName>
            </value>
            <value>
                <fullName>Telugu</fullName>
            </value>
            <value>
                <fullName>Kannada</fullName>
            </value>
            <value>
                <fullName>Gujarati</fullName>
            </value>
            <value>
                <fullName>Marathi</fullName>
            </value>
            <value>
                <fullName>Bengali</fullName>
            </value>
            <value>
                <fullName>Assamese</fullName>
            </value>
            <value>
                <fullName>Oriya</fullName>
            </value>
            <value>
                <fullName>Punjabi</fullName>
            </value>
            <value>
                <fullName>English + Hindi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Media_Type__c.field-meta.xml
<CustomField>
    <fullName>Media_Type__c</fullName>
    <description>field from Branding Request</description>
    <label>Media Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Shop_Name__c.field-meta.xml
<CustomField>
    <fullName>Shop_Name__c</fullName>
    <label>Shop Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Direct Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branding Requests</relationshipLabel>
    <relationshipName>Branding_Requests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Branding_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Dealer Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Details</label>
    <referenceTo>Vendor_Details__c</referenceTo>
    <relationshipLabel>Branding Requests</relationshipLabel>
    <relationshipName>Branding_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Vendor_Details__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Details</label>
    <referenceTo>Vendor_Details__c</referenceTo>
    <relationshipLabel>Branding Requests (Vendor Details)</relationshipLabel>
    <relationshipName>Branding_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Branding_Request__c/fields/Vertical_type__c.field-meta.xml
<CustomField>
    <fullName>Vertical_type__c</fullName>
    <formula>TEXT( CreatedBy.Vertical_Type__c )</formula>
    <label>Vertical type</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/City__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/Vendor_Details__c.object-meta.xml
<CustomObject>
    <label>Vendor Details</label>
    <nameField>
        <label>Vendor Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendor Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vendor</description>
    <inlineHelpText>Vendor</inlineHelpText>
    <label>Vendor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vendor_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Vendor_Details__c/fields/Vendor_Cluster__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Cluster__c</fullName>
    <label>Vendor Cluster</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AHMEDABAD</fullName>
            </value>
            <value>
                <fullName>ALLAHABAD</fullName>
            </value>
            <value>
                <fullName>AMARAVATHI</fullName>
            </value>
            <value>
                <fullName>AMBIKAPUR</fullName>
            </value>
            <value>
                <fullName>AMRITSAR</fullName>
            </value>
            <value>
                <fullName>BANGALORE</fullName>
            </value>
            <value>
                <fullName>BARODA</fullName>
            </value>
            <value>
                <fullName>BATHINDA</fullName>
            </value>
            <value>
                <fullName>BELGAUM</fullName>
            </value>
            <value>
                <fullName>BHOPAL</fullName>
            </value>
            <value>
                <fullName>BHANDARA</fullName>
            </value>
            <value>
                <fullName>BIJAPUR</fullName>
            </value>
            <value>
                <fullName>BIKANER</fullName>
            </value>
            <value>
                <fullName>BILASPUR</fullName>
            </value>
            <value>
                <fullName>BLR ZONE</fullName>
            </value>
            <value>
                <fullName>CENTRAL BIHAR</fullName>
            </value>
            <value>
                <fullName>CHENNAI</fullName>
            </value>
            <value>
                <fullName>COIMBATORE</fullName>
            </value>
            <value>
                <fullName>DELHI-NCR</fullName>
            </value>
            <value>
                <fullName>DEL-PROJECT</fullName>
            </value>
            <value>
                <fullName>DURG</fullName>
            </value>
            <value>
                <fullName>GOA</fullName>
            </value>
            <value>
                <fullName>GORAKHPUR</fullName>
            </value>
            <value>
                <fullName>GUWAHATI</fullName>
            </value>
            <value>
                <fullName>GWALIOR</fullName>
            </value>
            <value>
                <fullName>HIMACHAL PRADESH</fullName>
            </value>
            <value>
                <fullName>HISSAR</fullName>
            </value>
            <value>
                <fullName>HUBLI</fullName>
            </value>
            <value>
                <fullName>HYDERABAD</fullName>
            </value>
            <value>
                <fullName>INDORE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/BandhanController.cls
public without sharing class BandhanController{
    public static Final String BrandingRequest='01230000001DRzUAAW';
    public String Ids;
    public String Vertical {get;set;}
    public Boolean paramCheck{get;set;}

    public BandhanController(){
        try{
            String accid='';
            accid=apexpages.currentpage().getparameters().get('id');
            Account acc=[select id,OwnerId,APPL_Taluk__c,APPL_Taluk__r.Name,APPL_Taluk__r.Cluster__c,PIN_Code__c,State__c,District__c,City__c,Street_Address__c,Contact_Number_Mobile__c from Account where id=:accid];

            User u=[select Vertical_Type__c from User where id=:acc.OwnerId];
            Vertical=u.Vertical_Type__c;
            paramCheck=true;
       }catch(Exception ex){
           System.debug(ex);
           paramCheck=false;
       }
    }

     @RemoteAction
public static List<Branding_Request__c> collectStoredBranding(){
    List<Branding_Request__c> brandingList=new List<Branding_Request__c>();

  /*Commented By Pooja*/
  //  brandingList.addAll([select id,Submitted_By__c,Language__c,Shop_Name__c,Cluster__c,Type__c,Media_Type__c,Branding_type__c,Branding_Request__r.CaseNumber,Shop_Name__r.Name,shop_Name__r.APPL_Taluk__c,shop_Name__r.ShippingCity,shop_Name__r.ShippingStreet,shop_Name__r.ShippingState,shop_Name__r.ShippingPostalCode,shop_Name__r.ShippingCountry from Branding_Request__c where CreatedBy.id=:userinfo.getUserId() and shop_Name__r.APPL_Taluk__c!='' and Branding_Approved_Rejected__c='Request Created' and Bhandhan_Check__c=true ]);
    /*Added By Pooja*/
     brandingList.addAll([select id,Submitted_By__c,Language__c,Shop_Name__c,Cluster__c,Type__c,Media_Type__c,Branding_type__c,Branding_Request__r.CaseNumber,Shop_Name__r.Name,shop_Name__r.APPL_Taluk__c,shop_Name__r.PIN_Code__c,shop_Name__r.State__c,shop_Name__r.District__c,shop_Name__r.City__c,shop_Name__r.Street_Address__c from Branding_Request__c where CreatedBy.id=:userinfo.getUserId() and shop_Name__r.APPL_Taluk__c!='' and Branding_Approved_Rejected__c='Request Created' and Bhandhan_Check__c=true ]);
    
    return brandingList;
}


@RemoteAction
public static Account collectAccount(String accid){
   
   /*Commented By Pooja*/
   // return([SELECT Name,OwnerId, Id, ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, ShippingCountry,APPL_Taluk__r.Cluster__c,APPL_Taluk__r.Name,APPL_Taluk__r.User__c FROM Account where id=:accid]);
    /*Added By Pooja*/
    return([SELECT Name,OwnerId, Id,PIN_Code__c,State__c,District__c,City__c,Street_Address__c ,APPL_Taluk__r.Cluster__c,APPL_Taluk__r.Name,APPL_Taluk__r.User__c FROM Account where id=:accid]);


}

/*
@RemoteAction
public static  boolean changeAddress(String id,String street,String city,String state,String country,String pin){
    try{
        Account acc=new Account();
        acc.id=id;
        acc.ShippingStreet=street;
        acc.ShippingCity=city;
        acc.ShippingState=state;
        acc.ShippingCountry=country;
        acc.ShippingPostalCode=pin;
        update acc;
        return true;
   }catch(Exception ex){
       System.debug(ex);
       return false;
   }
}
*/

@RemoteAction
public static  boolean changeAddress(String id,String street,String city,String state,String district,String pin){
    try{
        Account acc=new Account();
        acc.id=id;
        acc.Street_Address__c=street;      
        acc.City__c=city;
        acc.State__c=state;
        acc.District__c=district;
        acc.PIN_Code__c=pin;
        update acc;
        return true;
   }catch(Exception ex){
       System.debug(ex);
       return false;
   }
}




@RemoteAction
    public static String saveReloaded(List<BrandWrap> bwlist,boolean casebol,String caseId){
        try{


            List<Branding_Request__c>newBrand= new List<Branding_Request__c>();

            DateTime d2=System.Today()-180;
            Set<String> accSet=new Set<String>();
            Set<String> clusSet=new Set<String>();
            for(BrandWrap temp:bwlist){
                accSet.add(temp.Shop);
                //Need to change for Cluster

                clusSet.add(temp.Cluster);
            }

           List<Vendor_Details__c> vendorNames=new List<Vendor_Details__c>();
           vendorNames.addAll([select Primary_Vendor__c,Vendor_Cluster__c,vendor__c from Vendor_Details__c where Primary_Vendor__c=true AND Vendor_Cluster__c IN: clusSet]);
           System.debug('Vendorrr List'+vendorNames);

           map<String,Id> mGetVendor =new map<String,Id>();
           for(Vendor_Details__c vid:vendorNames){
                mGetVendor.put(vid.Vendor_Cluster__c,vid.vendor__c);

            }

            List<Branding_Request__c> brandaingReqlst= [SELECT id,Escalated_To_Branding_Head__c, Branding_Approved_Rejected__c,Shop_Name__c,Shop_Name__r.Name,CreatedDate  FROM  Branding_Request__c WHERE Shop_Name__c IN:accSet];


            Integer errcnt=0;
            Boolean bool;
            String ErroMessage='';
            for(BrandWrap temp:bwlist){
                if(temp.Id==''){
                    bool=false;
                    for(Branding_Request__c r:brandaingReqlst){
                        if(r.Shop_Name__c==temp.Shop && r.Branding_Approved_Rejected__c!='Rejected by RBM' && r.Branding_Approved_Rejected__c!='Request Created' && (r.Branding_Approved_Rejected__c=='Submitted To RBM' || r.Branding_Approved_Rejected__c=='Vendor Assigned' || r.Branding_Approved_Rejected__c=='Vendor Assigned-Rework' || r.Branding_Approved_Rejected__c=='Vendor Assigned-Completed' || r.Branding_Approved_Rejected__c=='Request Completed and Submitted' || r.Escalated_To_Branding_Head__c==true ||  r.Branding_Approved_Rejected__c=='Request Created')){
                        ErroMessage= ErroMessage + r.Shop_Name__r.Name+ ' is already in progress.';
                            bool=true;
                            break;
                        }


                    }
                    if(bool){
                        return ErroMessage ;
                    }else{




                        Branding_Request__c brdcrt=new Branding_Request__c();

                        if(mGetVendor.containsKey(temp.Cluster.toUpperCase())){
                           brdcrt.user1__c=mGetVendor.get(temp.Cluster.toUpperCase());
                           System.debug(mGetVendor.get(temp.Cluster.toUpperCase()));
                        }
                        brdcrt.Language__c=temp.Language;
                        brdcrt.Branding_Approved_Rejected__c='Request Created';
                        brdcrt.Shop_Name__c=temp.Shop;
                        brdcrt.Branding_Type__c=temp.BrandType;
                       
                        //Commented By Pooja
                       /*  brdcrt.Cluster__c=temp.TalukName+'-'+temp.Cluster;  */
                       
                        brdcrt.Media_Type__c=temp.MediaType;
                        brdcrt.Type__c=temp.MediaChild;
                         brdcrt.Submitted_By__c=temp.OwnerId;  /* Added recent item */
                        brdcrt.Request_Type__c='New';
                        brdcrt.Escalated_To_Branding_Head__c=false;

                        for(Branding_Request__c r:brandaingReqlst){
                            if(r.Shop_Name__c==temp.Shop && (r.createdDate+180)> System.Today()){
                                brdcrt.Request_Type__c='Repair';
                            }
                        }

                        newBrand.add(brdcrt);
                    }


                }
            }//BrandWrap
             if(caseId==''){
                           case  c=new case();
                           /* Recordtype rcdid=[select id,name from recordtype where name=:'Branding Request' and SobjectType='Case' limit 1];
                           c.recordtypeid=rcdid.id;   */
                           c.recordtypeid=BrandingRequest;
                           c.status='Open';
                           c.subject='';
                           insert c;
                           caseId=''+c.id;
                       }
           for(Branding_Request__c r:newBrand){
               r.Branding_Request__c=caseId;
           }
           if(newBrand.size()>0)
           {
               insert newBrand;
           }


        return 'success';


        }
        catch(Exception ex){ System.debug(ex);return 'failed'; return String.valueOf(ex);  }
    }

 @RemoteAction
    public static String updateReloaded(List<BrandWrap> bwlist,boolean casebol,String caseId){
        try{
            List<Branding_Request__c> newBrand= new List<Branding_Request__c>();
            List<Branding_Request__c> oldBrand= new List<Branding_Request__c>();

            Set<String> accSet=new Set<String>();
            Set<String> clusSet=new Set<String>();
            for(BrandWrap temp:bwlist){
                accSet.add(temp.Shop);
                clusSet.add(temp.Cluster);
            }

           List<Vendor_Details__c> vendorNames=new List<Vendor_Details__c>();
           vendorNames.addAll([select Primary_Vendor__c,Vendor_Cluster__c,vendor__c from Vendor_Details__c where Primary_Vendor__c=true AND Vendor_Cluster__c IN: clusSet]);
           System.debug('Vendorrr List'+vendorNames);

           map<String,Id> mGetVendor =new map<String,Id>();
           for(Vendor_Details__c vid:vendorNames){
                mGetVendor.put(vid.Vendor_Cluster__c,vid.vendor__c);

            }

            List<Branding_Request__c> brandaingReqlst= [SELECT id,Escalated_To_Branding_Head__c, Branding_Approved_Rejected__c,Shop_Name__c,Shop_Name__r.Name,CreatedDate  FROM  Branding_Request__c WHERE Shop_Name__c IN:accSet];


            Integer errcnt=0;
            Boolean bool;
            String ErroMessage='';
            for(BrandWrap temp:bwlist){
                if(temp.Id==''){
                    bool=false;
                    for(Branding_Request__c r:brandaingReqlst){
                        if(r.Shop_Name__c==temp.Shop && r.Branding_Approved_Rejected__c!='Rejected by RBM'   && (r.Branding_Approved_Rejected__c=='Submitted To RBM' || r.Branding_Approved_Rejected__c=='Vendor Assigned' || r.Branding_Approved_Rejected__c=='Vendor Assigned-Rework' || r.Branding_Approved_Rejected__c=='Vendor Assigned-Completed' || r.Branding_Approved_Rejected__c=='Request Completed and Submitted' ||r.Escalated_To_Branding_Head__c==true ||  r.Branding_Approved_Rejected__c=='Request Created')){
                        //if(r.Shop_Name__c==temp.Shop && r.Branding_Approved_Rejected__c=='Submitted To RBM'){
                        ErroMessage= ErroMessage + r.Shop_Name__r.Name+ ' is already in progress.';
                            bool=true;
                            break;
                        }


                    }
                    if(bool){
                        return ErroMessage ;
                    }else{




                        Branding_Request__c brdcrt=new Branding_Request__c();
                        if(mGetVendor.containsKey(temp.Cluster.toUpperCase())){
                           brdcrt.user1__c=mGetVendor.get(temp.Cluster.toUpperCase());
                           System.debug(mGetVendor.get(temp.Cluster.toUpperCase()));
                        }
                        brdcrt.Language__c=temp.Language;
                        brdcrt.Branding_Approved_Rejected__c='Request Created';
                        brdcrt.Shop_Name__c=temp.Shop;
                        brdcrt.Branding_Type__c=temp.BrandType;
                     
                        //Commented By Pooja
                       /* brdcrt.Cluster__c=temp.TalukName+'-'+temp.Cluster;*/
                        
                        brdcrt.Media_Type__c=temp.MediaType;
                        brdcrt.Type__c=temp.MediaChild;
                        brdcrt.Submitted_By__c=temp.OwnerId;   /* Added recent item */
                        brdcrt.Request_Type__c='New';
                        brdcrt.Escalated_To_Branding_Head__c=false;
                        for(Branding_Request__c r:brandaingReqlst){
                            if(r.Shop_Name__c==temp.Shop && (r.createdDate+180)> System.Today()){
                                brdcrt.Request_Type__c='Repair';
                            }
                        }

                        newBrand.add(brdcrt);
                    }


                }else{
                    Branding_Request__c brdcrt=new Branding_Request__c();
                    brdcrt.id=temp.Id;
                    if(temp.BrandType=='Recce'){
                        brdcrt.Branding_Approved_Rejected__c='Submitted';
                    }else{
                        brdcrt.Branding_Approved_Rejected__c='Submitted To RBM';
                    }
                    brdcrt.Submit_For_Aprroval_Date__c=System.today();
                    //brdcrt.Branding_Approved_Rejected__c='Submitted To RBM';
                    oldBrand.add(brdcrt);
                }
            }//BrandWrap
             if(caseId==''){
                           case  c=new case();
                           /* Recordtype rcdid=[select id,name from recordtype where name=:'Branding Request' and SobjectType='Case' limit 1];
                           c.recordtypeid=rcdid.id;   */
                           c.recordtypeid=BrandingRequest;
                           c.status='Open';
                           c.subject='';
                           insert c;
                           caseId=''+c.id;
                       }
           for(Branding_Request__c r:newBrand){
               r.Branding_Request__c=caseId;
           }
           if(oldBrand.size()>0)
               update oldBrand;

           if(newBrand.size()>0)
           {
               insert newBrand;
               for(Branding_Request__c r:newBrand){
                   r.Submit_For_Aprroval_Date__c=System.today();
                   if(r.Branding_Type__c=='Recce'){
                       r.Branding_Approved_Rejected__c='Submitted';
                   }else{
                       r.Branding_Approved_Rejected__c='Submitted To RBM';
                   }
               }
               update newBrand;

           }

           case cas=new Case();
           cas.id=caseId;
           cas.status='In Progress';
           update cas;


        return 'success';


        }
        catch(Exception ex){ System.debug(ex);return 'failed'; return String.valueOf(ex);  }
    }






public class BrandWrap{
    public String Id{get;set;}
    public String Shop{get;set;}
    public String BrandType{get;set;}
    public String MediaType{get;set;}
    public String MediaChild{get;set;}
    public String Language{get;set;}
    public String Cluster{get;set;}
 
 //Commented By Pooja
   /* public String TalukName{get;set;} */
   
    public String OwnerId{get;set;}
    /*boolean check*/
    public Boolean mediabol{get;set;}
    public Boolean mchildbol{get;set;}
    public Boolean updbol{get;set;}

    public String error{get;set;}
}

}