Partial_14Dec2021/force-app/main/default/objects/Bank_Details__c/Bank_Details__c.object-meta.xml
<CustomObject>
    <label>Bank Detail</label>
    <nameField>
        <displayFormat>BD-{000}</displayFormat>
        <label>Bank Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Bank_Details__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>20</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Bank_Details__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Details</relationshipLabel>
    <relationshipName>Bank_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Bank_Details__c/fields/Name_of_your_Bank__c.field-meta.xml
<CustomField>
    <fullName>Name_of_your_Bank__c</fullName>
    <label>Name of Your Bank</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Business_Activity_History__c/Business_Activity_History__c.object-meta.xml
<CustomObject>
    <label>Business Activity/History</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Activity/History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Business_Activity_History__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Activity/History</relationshipLabel>
    <relationshipName>Business_Activity_History</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Business_Activity_History__c/fields/Projected_Sales_In_Lacs__c.field-meta.xml
<CustomField>
    <fullName>Projected_Sales_In_Lacs__c</fullName>
    <label>Projected Sales(In Lacs)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Business_Activity_History__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DISTRIBUTION</fullName>
            </value>
            <value>
                <fullName>RETAIL</fullName>
            </value>
            <value>
                <fullName>MANUFACTURING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/DP_Detail__c/DP_Detail__c.object-meta.xml
<CustomObject>
    <label>DP Detail</label>
    <nameField>
        <displayFormat>DP-{000}</displayFormat>
        <label>DP Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DP Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/DP_Detail__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>DP Details</relationshipLabel>
    <relationshipName>DP_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/DP_Detail__c/fields/Year_1__c.field-meta.xml
<CustomField>
    <fullName>Year_1__c</fullName>
    <label>Year 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/DP_Detail__c/recordTypes/Turnover_Details.recordType-meta.xml
<RecordType>
    <fullName>Turnover_Details</fullName>
    <active>true</active>
    <label>Turnover Details</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/objects/Partner_Detail__c/Partner_Detail__c.object-meta.xml
<CustomObject>
    <label>Partner Detail</label>
    <nameField>
        <displayFormat>PD-{000}</displayFormat>
        <label>Partner Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Partner_Detail__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Details</relationshipLabel>
    <relationshipName>Partner_Details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Partner_Detail__c/fields/Name_of_the_Project_Handled__c.field-meta.xml
<CustomField>
    <fullName>Name_of_the_Project_Handled__c</fullName>
    <label>Name of the Project Handled</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Partner_Detail__c/fields/Year_2__c.field-meta.xml
<CustomField>
    <fullName>Year_2__c</fullName>
    <label>Year 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Partner_Detail__c/recordTypes/Distribution_Partner.recordType-meta.xml
<RecordType>
    <fullName>Distribution_Partner</fullName>
    <active>true</active>
    <label>Distribution Partner</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/objects/Sales_Projection__c/Sales_Projection__c.object-meta.xml
<CustomObject>
    <label>Sales Projection</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Sales Projection</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Projections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Sales_Projection__c/fields/Distributer__c.field-meta.xml
<CustomField>
    <fullName>Distributer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Projections</relationshipLabel>
    <relationshipName>Sales_Projections</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Sales_Projection__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Sanitary</fullName>
            </value>
            <value>
                <fullName>Agriculture</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Sales_Projection__c/recordTypes/Sales_Projection.recordType-meta.xml
<RecordType>
    <fullName>Sales_Projection</fullName>
    <active>true</active>
    <label>Sales Projection</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/classes/Test_dpAppointmentApplicationForm.cls
@isTest
public class Test_dpAppointmentApplicationForm {
    
   public static Account testAccount;
    public  static Account test1Account;
    public static DP_Detail__c testdpdetail;
   public  static Bank_Details__c testbank;
   public  static Contact testcon;
    public static Sales_Projection__c testsp;
    public static Partner_Detail__c pdeatil;
    public static Business_Activity_History__c Bactivity;
    @istest
     static void prepareTestData()
     {
         Account newaccount = new Account();
         Account testAccount = new Account(
             RecordTypeId= Schema.SObjectType.Account.getRecordTypeInfosByName().get('Dealer').recordTypeId,
         ParentId = 'Testing',
             Name = 'Dealer',
             Primary_Contact_Person_Name__c='Primary',
             Status__c='Cold Call',
             Business_Line__c='All Product',
             Classification__c='A',
             Party_Type__c='Dealer',
             Purchase_Cycle__c='Weekly',
             Contact_Number_Mobile__c='1234567890',
             APPL_Taluk__c='Taluk Junction',
             Display_of_our_product__c='Prominent',
             Media__c='N',
             Type_of_Dealer__c='HARDWEAR',
             Salutation__c='Mr.'
         );
         Test.startTest(); 
         insert testAccount;
         Account test1Account =  [select Id,Name,Primary_Contact_Person_Name__c,Status__c,Business_Line__c,Classification__c,Party_Type__c,
                    Purchase_Cycle__c,Contact_Number_Mobile__c,APPL_Taluk__c,Display_of_our_product__c ,Media__c,Type_of_Dealer__c
                    from Account Limit 1];
        
         Bank_Details__c testbank1 = new Bank_Details__c(Distributor__c=testAccount.id,
                                                        Name_of_your_Bank__c='HSB', Bank_Account_Number__c='34563456' );
         Insert  testbank1;
         Partner_Detail__c prdeatil = new Partner_Detail__c(
             RecordTypeId= Schema.SObjectType.Partner_Detail__c.getRecordTypeInfosByName().get('Distribution_Partner').recordTypeId, 
             Name_of_the_Project_Handled__c='one',
            Value__c=10000 ,Distributor__c= testAccount.id                                              
         );
         insert prdeatil;
         Sales_Projection__c onesp = new Sales_Projection__c(
          Distributer__c =testAccount.id,
          RecordTypeId= Schema.SObjectType.Sales_Projection__c.getRecordTypeInfosByName().get('Sales_Projection').recordTypeId,
          Product_Type__c= 'Agriculture'
         );
         Insert onesp;
         DP_Detail__c onedpdetail = new DP_Detail__c(
         Distributor__c =testAccount.id,
         RecordTypeId= Schema.SObjectType.DP_Detail__c.getRecordTypeInfosByName().get('Turnover_Details').recordTypeId,
             Year_1__c= 2000, Year_2__c=3909
         );
         insert onedpdetail;
          Business_Activity_History__c Bsactivity = new  Business_Activity_History__c(
          Name='New Brand',
              Type__c='RETAIL',
              Projected_Sales_In_Lacs__c = 5
          );
         insert Bsactivity;
          Test.stopTest();
     }
     @isTest
    public static void UpdateAccount()
    {
        prepareTestData();
      testAccount.ParentId = 'Testingone';
            testAccount.Name = 'Contract';
             testAccount.Primary_Contact_Person_Name__c='Secondary';
        update testAccount;
    
    }
    
    
    

}