Partial_14Dec2021/force-app/main/default/objects/Beat_Master__c/Beat_Master__c.object-meta.xml
<CustomObject>
    <label>Beat Master</label>
    <nameField>
        <label>Beat Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beat Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Beat_Master_Account__c/Beat_Master_Account__c.object-meta.xml
<CustomObject>
    <label>Beat Master Account</label>
    <nameField>
        <displayFormat>BA-{0000}</displayFormat>
        <label>Beat Master Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beat Master Account</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Beat_Master_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beat Master Account</relationshipLabel>
    <relationshipName>Beat_Master_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Beat_Master_Account__c/fields/Beat_Master__c.field-meta.xml
<CustomField>
    <fullName>Beat_Master__c</fullName>
    <label>Beat Master</label>
    <referenceTo>Beat_Master__c</referenceTo>
    <relationshipLabel>Beat Master Account</relationshipLabel>
    <relationshipName>Beat_Master_Account</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/City__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Cities</relationshipLabel>
    <relationshipName>Cities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/AddingDealerInBeatController.cls
public with sharing class AddingDealerInBeatController{
    @AuraEnabled 
    public static Object fetchAccountWrapper(){     
        List<accountListWrapper> lstaccountListWrapper = new List<accountListWrapper>();
        Set<Id> beatMastetrId = new Set<Id>();
        Set<Id> accIds = new Set<Id>();
        Date todays =System.today();
        System.debug('todays.day()'+todays.day());  
        
        
        if( todays.day()> 0){
            for(Beat_Master__c beatMaster : [Select Id from Beat_Master__c]){
                beatMastetrId.add(beatMaster.Id);
                
            }
            for(Beat_Master_Account__c beat : [Select id,Account__c from Beat_Master_Account__c where Beat_Master__c In :beatMastetrId And Account__c != null]){
                accIds.add(beat.Account__c);
            }
            // query account records and create 'accountListWrapper' class instance for each record. 
            String s;
            for(Account acc : [Select id,Name,City__c,District__c,State__c,Sparsh_Code__c,Contact_Number_Mobile__c from Account where Id NOT IN : accIds And  Beat_Area__c =false And Party_Type__c ='Dealer' And RecordType.Name='Dealer' Order By Name]){
                s=acc.Name+(acc.Sparsh_Code__c != null && acc.Sparsh_Code__c != ''?acc.Sparsh_Code__c:'')+(acc.City__c != null && acc.City__c != ''?acc.City__c:'')+(acc.Contact_Number_Mobile__c != null && acc.Contact_Number_Mobile__c != ''?acc.Contact_Number_Mobile__c:'')+(acc.State__c != null && acc.State__c != ''?acc.State__c:'')+(acc.District__c != null && acc.District__c != ''?acc.District__c:'');
                // by default checkbox should be false 
                lstaccountListWrapper.add(new accountListWrapper(false,acc,s));
            } 
            // return the 'lstaccountListWrapper' list 
            return lstaccountListWrapper;  
        }else{
            return null;  
        }
        
        
        
        
    }
    
    /* wrapper class */  
    public class accountListWrapper {
        @AuraEnabled public boolean isChecked;
        @AuraEnabled public account objAccount;
        @AuraEnabled public  String searchField;
        
        public accountListWrapper(boolean isChecked, account objAccount,String searchField){
            this.isChecked = isChecked;
            this.objAccount = objAccount;
            this.searchField =searchField;
        }
    }
    
}