Partial_14Dec2021/force-app/main/default/objects/Beat_Master__c/Beat_Master__c.object-meta.xml
<CustomObject>
    <label>Beat Master</label>
    <nameField>
        <label>Beat Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beat Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Beat_Master__c/fields/Beat_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Beat_Frequency__c</fullName>
    <label>Beat Frequency</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday Week1</fullName>
            </value>
            <value>
                <fullName>Monday Week2</fullName>
            </value>
            <value>
                <fullName>Monday Week3</fullName>
            </value>
            <value>
                <fullName>Monday Week4</fullName>
            </value>
            <value>
                <fullName>Tuesday Week1</fullName>
            </value>
            <value>
                <fullName>Tuesday Week2</fullName>
            </value>
            <value>
                <fullName>Tuesday Week3</fullName>
            </value>
            <value>
                <fullName>Tuesday Week4</fullName>
            </value>
            <value>
                <fullName>Wednesday Week1</fullName>
            </value>
            <value>
                <fullName>Wednesday Week2</fullName>
            </value>
            <value>
                <fullName>Wednesday Week3</fullName>
            </value>
            <value>
                <fullName>Wednesday Week4</fullName>
            </value>
            <value>
                <fullName>Thursday Week1</fullName>
            </value>
            <value>
                <fullName>Thursday Week2</fullName>
            </value>
            <value>
                <fullName>Thursday Week3</fullName>
            </value>
            <value>
                <fullName>Thursday Week4</fullName>
            </value>
            <value>
                <fullName>Friday Week1</fullName>
            </value>
            <value>
                <fullName>Friday Week2</fullName>
            </value>
            <value>
                <fullName>Friday Week3</fullName>
            </value>
            <value>
                <fullName>Friday Week4</fullName>
            </value>
            <value>
                <fullName>Saturday Week1</fullName>
            </value>
            <value>
                <fullName>Saturday Week2</fullName>
            </value>
            <value>
                <fullName>Saturday Week3</fullName>
            </value>
            <value>
                <fullName>Saturday Week4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Column</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
            <value>
                <fullName>Branding</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/recordTypes/Column.recordType-meta.xml
<RecordType>
    <fullName>Column</fullName>
    <active>true</active>
    <label>Column</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/classes/Batch_AutoTourPlanCreation_Test.cls
@isTest
public class Batch_AutoTourPlanCreation_Test {
    @isTest
    Public static void TestBatchMethod() {
        User userObj =[select id,Name from User Limit 1];
        List<Beat_Master__c> beatList = new List<Beat_Master__c>();
        Beat_Master__c beatObj = new Beat_Master__c(Name='Test Class Record',Beat_Frequency__c='Monday Week1;Monday Week2',OwnerId=userObj.id);
        beatList.add(beatObj);
        INSERT beatList;
        Target__c tergetObj = new Target__c(Start_Date__c=date.newInstance(2021,12,1),End_Date__c=date.newInstance(2021,12,31),Approval_Status__c='Not Submitted',Vertical__c='Column',State__c='Karnataka',OwnerId=userObj.id);
        INSERT tergetObj;
        Batch_AutoTourPlanCreation TargBatch = new Batch_AutoTourPlanCreation(null,'');
        Database.executeBatch(TargBatch,1);
    }
}