Partial_14Dec2021/force-app/main/default/objects/AP_Expenses__c/AP_Expenses__c.object-meta.xml
<CustomObject>
    <label>APPL Expense</label>
    <nameField>
        <displayFormat>Exp-{000000}</displayFormat>
        <label>AP Expenses Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Expenses__c/fields/TourPlan__c.field-meta.xml
<CustomField>
    <fullName>TourPlan__c</fullName>
    <label>TourPlan</label>
    <referenceTo>AP_Tour_Plan__c</referenceTo>
    <relationshipLabel>AP Expenses</relationshipLabel>
    <relationshipName>AP_Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/AP_Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>APPL Tour Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>AP TourPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPL Tour Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>APPL Tour Plans</relationshipLabel>
    <relationshipName>AP_TourPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/Test_UploadExpenseAttachments.cls
@isTest
public  class Test_UploadExpenseAttachments {
    public static AP_Expenses__c expense;
    public static Target__c target;
    public static AP_Tour_Plan__c tourplan;
    public static User userdata;

   static testMethod void init() {
        userdata = Test_Intial_Data_Phase2.ColumnRH('First','Last','System Administrator');
        insert userdata ;
        target = Test_Intial_Data_Phase2.CreateTarget(userdata);
        insert target;
        tourplan  = Test_Intial_Data_Phase2.CreateTourPlan(target.Id);
        tourplan.Target__c = target.ID;
        insert tourplan;
        expense = Test_Intial_Data_Phase2.CreateExpense(tourplan.Id);
        expense.TourPlan__c = tourplan.ID;
        insert expense ; 
        Test.setCurrentPageReference(new PageReference('Page.AP_Expenses_Sheet')); 
        System.currentPageReference().getParameters().put('expId', expense.id);

        Blob b = Blob.valueOf('Test Data');
        Attachment attachment1 = new Attachment();
        attachment1.ParentId = expense.ID;
        attachment1.Name = 'Test Attachment for Parent';
        attachment1.Body = b;
        List<Attachment> att=new List<Attachment>();
        att.add(attachment1);
        test.starttest();
        UploadExpenseAttachments_Ctrl uploadexp = new UploadExpenseAttachments_Ctrl();
        uploadexp.allFileList=att;
        uploadexp.FileCount = '1';
        
        uploadexp.SaveAttachments();
        //uploadexp.ChangeCount();
        test.stoptest();   
    }
    public static  testmethod void init2(){
      
   

   
        userdata = Test_Intial_Data_Phase2.ColumnRH('First','Last','System Administrator');
        insert userdata ;
        target = Test_Intial_Data_Phase2.CreateTarget(userdata);
        insert target;
        tourplan  = Test_Intial_Data_Phase2.CreateTourPlan(target.Id);
        tourplan.Target__c = target.ID;
        insert tourplan;
        expense = Test_Intial_Data_Phase2.CreateExpense(tourplan.Id);
        expense.TourPlan__c = tourplan.ID;
        insert expense ; 
        Test.setCurrentPageReference(new PageReference('Page.AP_Expenses_Sheet')); 
        System.currentPageReference().getParameters().put('expId', expense.id);

        Blob b = Blob.valueOf('Test Data');
        Attachment attachment1 = new Attachment();
        attachment1.ParentId = expense.ID;
        attachment1.Name = 'Test Attachment for Parent';
        attachment1.Body = b;
        List<Attachment> att=new List<Attachment>();
        att.add(attachment1);
        test.starttest();
        UploadExpenseAttachments_Ctrl uploadexp = new UploadExpenseAttachments_Ctrl();
        uploadexp.allFileList=att;
        uploadexp.FileCount = '1';
         uploadexp.ChangeCount();
        uploadexp.SaveAttachments();
       
        test.stoptest();   
  
    }
}