Partial_14Dec2021/force-app/main/default/objects/AP_Expenses__c/AP_Expenses__c.object-meta.xml
<CustomObject>
    <label>APPL Expense</label>
    <nameField>
        <displayFormat>Exp-{000000}</displayFormat>
        <label>AP Expenses Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Expenses__c/fields/Expens_Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Expens_Visit_Type__c</fullName>
    <label>Expense Visit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Headquarter-Metro</fullName>
            </value>
            <value>
                <fullName>Headquarter-State Capital</fullName>
            </value>
            <value>
                <fullName>Headquarter</fullName>
            </value>
            <value>
                <fullName>Ex-station</fullName>
            </value>
            <value>
                <fullName>Outstation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/AP_Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>APPL Tour Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>AP TourPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPL Tour Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>APPL Tour Plans</relationshipLabel>
    <relationshipName>AP_TourPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Supply__c/Supply__c.object-meta.xml
<CustomObject>
    <label>Supply</label>
    <nameField>
        <displayFormat>Supply-{00000000}</displayFormat>
        <label>Supply Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/SupplyLineItem__c.object-meta.xml
<CustomObject>
    <label>SupplyLineItem</label>
    <nameField>
        <displayFormat>SupplyItem-{0000000000}</displayFormat>
        <label>SupplyLineItem Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SupplyLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Order_Value__c.field-meta.xml
<CustomField>
    <fullName>Order_Value__c</fullName>
    <label>Supply Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100% advance with PO</fullName>
            </value>
            <value>
                <fullName>20% advance &amp; Balance against Delivery</fullName>
            </value>
            <value>
                <fullName>30 days after delivery</fullName>
            </value>
            <value>
                <fullName>45 days after delivery</fullName>
            </value>
            <value>
                <fullName>60 days after delivery</fullName>
            </value>
            <value>
                <fullName>90 days after delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Supply_Status__c.field-meta.xml
<CustomField>
    <fullName>Supply_Status__c</fullName>
    <label>Supply Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fully Received</fullName>
            </value>
            <value>
                <fullName>Part Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Boxes</fullName>
            </value>
            <value>
                <fullName>Mtrs</fullName>
            </value>
            <value>
                <fullName>No.&apos;s</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Projects</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/classes/Test_Utilclass.cls
@isTest
public class Test_Utilclass {

    public static Account ObjAcct(){
        Account objAcct = new Account();
        objAcct.Name = 'Test Account';
        return objAcct;
    }
    public static Opportunity oppObj(){
        Opportunity objOpp = new Opportunity();
        objOpp.Name = 'TestOpprtunity';
        objOpp.CloseDate = date.today();
        objOpp.StageName = 'ClosedWon';
        return objOpp;
    }
    
    public static Product2 objProd(){
        Product2 objProd = new Product2();
        objProd.Name = 'Test Product';
        objProd.IsActive = true;
        return objProd;
    }
    
    
    public static pricebook2 objPricebook(){
        pricebook2 objPricebook = new pricebook2();
        objPricebook.Name = 'Project';
        objPricebook.IsActive = true;
        return objPricebook;
    }
    
    public static PricebookEntry objPricebookEntry(){
        PricebookEntry objPricebookentry = new PricebookEntry();
        objPricebookentry.isActive = true;
        objPricebookentry.UnitPrice = 12345;
        return objPricebookentry;
    }
    
    public static Order objOrder(){
        Order objOrder = new Order();
        objOrder.Name = 'TestOrder';
        return objOrder;
    }
    
    public static OpportunityLineItem  objOpportunityLineitem(){
        OpportunityLineItem objOpplineItem = new OpportunityLineItem();
        objOpplineItem.Quantity = 1;
        objOpplineItem.unitprice  = 2345;
        objOpplineItem.Order_Loss_Check__c = true;
        return objOpplineItem;
    }
    
    public static OpportunityLineItem  objOpportunityLineitem1(){
        OpportunityLineItem objOpplineItem = new OpportunityLineItem();
        objOpplineItem.Quantity = 1;
        objOpplineItem.unitprice  = 2345;
        objOpplineItem.Offer_Check__c = true;
        return objOpplineItem;
    }
    
    public static OpportunityLineItem  objOpportunityLineitem2(){
        OpportunityLineItem objOpplineItem = new OpportunityLineItem();
        objOpplineItem.Quantity = 1;
        objOpplineItem.unitprice  = 2345;
        objOpplineItem.Probability_Check__c = true;
        return objOpplineItem;
    }
    
    public static OrderItem objOrderItem(){
        OrderItem objOrderItem = new OrderItem();
        objOrderItem.Quantity = 2;
        return objOrderItem;       
    }
    
    public static Supply__c objSupply(){
        Supply__c objSupply = new Supply__c();
        return objSupply;
    }
    
    public static SupplyLineItem__c objSupplyLineItem(){
        SupplyLineItem__c objSupplyLineItem = new SupplyLineItem__c();
        objSupplyLineItem.Quantity__c = 1;
        objSupplyLineItem.Unit__c = 'Boxes';
        objSupplyLineItem.Order_Value__c = 50;
        objSupplyLineItem.Invoice_Date__c = date.today();
        objSupplyLineItem.Payment_Terms__c = '100% advance with PO';
        objSupplyLineItem.Supply_Status__c = 'Fully Received';
        return objSupplyLineItem;
    }
    
   public static Target__c objTarget(){
      Target__c objTarget = new Target__c();
      objTarget.Start_Date__c = date.today();
      objTarget.End_Date__c = date.today().adddays(1);
      return objTarget;
   }
   
   public static AP_Tour_Plan__c objTourPlan() {
   	  AP_Tour_Plan__c objTourPlan = new AP_Tour_Plan__c();
   	  return objTourPlan;
   }
   
   public static AP_Expenses__c objExpensive() {
   	  AP_Expenses__c objExpensive = new AP_Expenses__c();
   	  objExpensive.Expens_Visit_Type__c = 'Headquarter';
   	  return objExpensive;
   }

}