Partial_14Dec2021/force-app/main/default/objects/inventory__c/inventory__c.object-meta.xml
<CustomObject>
    <description>Object created to hold the data of the inventory</description>
    <label>inventory</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>inventories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Closing_Stocks__c.field-meta.xml
<CustomField>
    <fullName>Closing_Stocks__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Stocks</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Color_Language_Size__c.field-meta.xml
<CustomField>
    <fullName>Color_Language_Size__c</fullName>
    <label>Color/Language/Size</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ENGLISH</fullName>
            </value>
            <value>
                <fullName>HINDI</fullName>
            </value>
            <value>
                <fullName>GUJARATI</fullName>
            </value>
            <value>
                <fullName>MARATI</fullName>
            </value>
            <value>
                <fullName>KANNADA</fullName>
            </value>
            <value>
                <fullName>TELUGU</fullName>
            </value>
            <value>
                <fullName>TAMIL</fullName>
            </value>
            <value>
                <fullName>RED</fullName>
            </value>
            <value>
                <fullName>VIOLET</fullName>
            </value>
            <value>
                <fullName>INDIGO</fullName>
            </value>
            <value>
                <fullName>BLUE</fullName>
            </value>
            <value>
                <fullName>GREEN</fullName>
            </value>
            <value>
                <fullName>YELLOW</fullName>
            </value>
            <value>
                <fullName>ORANGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/opening_stock__c.field-meta.xml
<CustomField>
    <fullName>opening_stock__c</fullName>
    <label>Opening Stock</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Owner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>COLUMN</fullName>
            </value>
            <value>
                <fullName>CASING</fullName>
            </value>
            <value>
                <fullName>V4</fullName>
            </value>
            <value>
                <fullName>CPVC</fullName>
            </value>
            <value>
                <fullName>AQUALIFE</fullName>
            </value>
            <value>
                <fullName>SWR</fullName>
            </value>
            <value>
                <fullName>PAN CONNECTORS</fullName>
            </value>
            <value>
                <fullName>SILENT SWR</fullName>
            </value>
            <value>
                <fullName>UNDER GROUND</fullName>
            </value>
            <value>
                <fullName>AAV</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>GI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>SILENT PLUS</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>PLUMBING</fullName>
            </value>
            <value>
                <fullName>MINI</fullName>
            </value>
            <value>
                <fullName>MEGA</fullName>
            </value>
            <value>
                <fullName>SWR_PUSHFIT</fullName>
            </value>
            <value>
                <fullName>SWR_SOLFIT</fullName>
            </value>
            <value>
                <fullName>SWR SILENT</fullName>
            </value>
            <value>
                <fullName>SWR SILENT PLUS</fullName>
            </value>
            <value>
                <fullName>UNDERGROUND</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>LEAFLETS</fullName>
            </value>
            <value>
                <fullName>HAND BILL</fullName>
            </value>
            <value>
                <fullName>STICKERS</fullName>
            </value>
            <value>
                <fullName>BANNERS</fullName>
            </value>
            <value>
                <fullName>SCROLL 3&apos;x2&apos;</fullName>
            </value>
            <value>
                <fullName>STALL TENT</fullName>
            </value>
            <value>
                <fullName>FLEX BOARD 6&apos; x 3&apos;</fullName>
            </value>
            <value>
                <fullName>FLEX BOARD 8&apos; x 4&apos;</fullName>
            </value>
            <value>
                <fullName>POP BOARDS</fullName>
            </value>
            <value>
                <fullName>TECHNICAL MANUAL</fullName>
            </value>
            <value>
                <fullName>PRICELIST - ALL INDIA</fullName>
            </value>
            <value>
                <fullName>PRICELIST - TAMILNADU</fullName>
            </value>
            <value>
                <fullName>PIPE SELECTION BOOK</fullName>
            </value>
            <value>
                <fullName>THERMOFOAM BOARD</fullName>
            </value>
            <value>
                <fullName>PRICELIST FOLDERS</fullName>
            </value>
            <value>
                <fullName>CORPORATE BROUCHER (EXCELLENCE TO BRILLANCE)</fullName>
            </value>
            <value>
                <fullName>APPLICATION FORM (CHANNEL PARTNERSHIP)</fullName>
            </value>
            <value>
                <fullName>CORPORATE  LEAFLETS</fullName>
            </value>
            <value>
                <fullName>BLUE TAPE (SHELF STICKERS)</fullName>
            </value>
            <value>
                <fullName>WHITE FOLDER</fullName>
            </value>
            <value>
                <fullName>STANDEES</fullName>
            </value>
            <value>
                <fullName>ALL PRODUCT CLUSTER_STANDEES</fullName>
            </value>
            <value>
                <fullName>MULTI USE KNIFE</fullName>
            </value>
            <value>
                <fullName>TORCHE_EVEREADY</fullName>
            </value>
            <value>
                <fullName>TORCH_NIPPO</fullName>
            </value>
            <value>
                <fullName>UMBRELLA</fullName>
            </value>
            <value>
                <fullName>ASHIRVAD KEY CHAIN -  ENGLISH</fullName>
            </value>
            <value>
                <fullName>LEATHER  KEY CHAIN</fullName>
            </value>
            <value>
                <fullName>LEATHERITE PURSE</fullName>
            </value>
            <value>
                <fullName>LUNCH BOX_TRAVEL MATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PRODUCT COLLATERALS</fullName>
            </value>
            <value>
                <fullName>GIFT ITEMS</fullName>
            </value>
            <value>
                <fullName>PACKING MATERIALS</fullName>
            </value>
            <value>
                <fullName>SAMPLES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Type_Of_Meet__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Meet__c</fullName>
    <label>Type Of Meet</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mega Meet</fullName>
            </value>
            <value>
                <fullName>Mini Meet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Used_Stock__c.field-meta.xml
<CustomField>
    <fullName>Used_Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Used Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/Inventory_Request__c.object-meta.xml
<CustomObject>
    <label>Inventory Request</label>
    <nameField>
        <displayFormat>IR-{0000}</displayFormat>
        <label>Inventory Request  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/Comments_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Comments_Remarks__c</fullName>
    <inlineHelpText>Enter the Reason</inlineHelpText>
    <label>Comments/Remarks</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/inventory_PackMaterials__c.field-meta.xml
<CustomField>
    <fullName>inventory_PackMaterials__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>inventory_PackMaterials</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>inventory__c.Type__c</field>
            <operation>equals</operation>
            <value>PACKING MATERIALS</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>inventory__c</referenceTo>
    <relationshipLabel>Inventory Requests (inventory_PackMaterials)</relationshipLabel>
    <relationshipName>Inventory_Requests3</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/inventory_Product__c.field-meta.xml
<CustomField>
    <fullName>inventory_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>inventory_Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>inventory__c.Type__c</field>
            <operation>equals</operation>
            <value>PRODUCT COLLATERALS</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>inventory__c</referenceTo>
    <relationshipLabel>Inventory Requests (inventory_Product)</relationshipLabel>
    <relationshipName>Inventory_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/Inventory_Request_Number__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Request_Number__c</fullName>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Inventory Requests</relationshipLabel>
    <relationshipName>Inventory_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/inventory_Sample__c.field-meta.xml
<CustomField>
    <fullName>inventory_Sample__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>inventory_Sample</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>inventory__c.Type__c</field>
            <operation>equals</operation>
            <value>SAMPLES</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>inventory__c</referenceTo>
    <relationshipLabel>Inventory Requests (inventory_Sample)</relationshipLabel>
    <relationshipName>Inventory_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/Quantity_Dispatched__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Dispatched__c</fullName>
    <label>Quantity Dispatched</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/Required_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Required_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Required Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/Type_of_Item__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type of Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>inventory__c.Owner_Account__c</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>inventory__c.Type__c</field>
            <operation>equals</operation>
            <value>GIFT ITEMS</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>inventory__c</referenceTo>
    <relationshipLabel>Inventory Requests</relationshipLabel>
    <relationshipName>Inventory_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/ctrlCollateralRequest.cls
public with sharing class ctrlCollateralRequest{

    public Boolean flagVar{get;set;}
    public Case currentCase{get; set;}
    public List<Inventory_Request__c> existinginvReqList{get;set;}
    
    
    
    public List<CollateralWrapper> productCollList{get;set;}
    public List<CollateralWrapper> giftListMega{get;set;}
    public List<CollateralWrapper> giftListMini{get;set;}
    public List<CollateralWrapper> sampleList{get;set;}
    public List<CollateralWrapper> packMaterialList{get;set;}
    public List<CollateralWrapper> productCollList1{get;set;}
    public List<CollateralWrapper> giftListMega1{get;set;}
    public List<CollateralWrapper> giftListMini1{get;set;}
    public List<CollateralWrapper> sampleList1{get;set;}
    public List<CollateralWrapper> packMaterialList1{get;set;}

    public ctrlCollateralRequest(ApexPages.StandardController stdController) { 
        
        
        productCollList= new List<CollateralWrapper>();
        giftListMega= new List<CollateralWrapper>();
        giftListMini= new List<CollateralWrapper>();
        sampleList= new List<CollateralWrapper>();
        packMaterialList= new List<CollateralWrapper>();
        productCollList1= new List<CollateralWrapper>();
        giftListMega1= new List<CollateralWrapper>();
        giftListMini1= new List<CollateralWrapper>();
        sampleList1= new List<CollateralWrapper>();
        packMaterialList1= new List<CollateralWrapper>();

        currentCase = [select Request_Raised_By__c,id,Team_Lead__c,depo__c,Check_Gifts__c,origin,head_office__c, status,Is_In_Approval_Process__c, RecordTypeId from case where id =:ApexPages.currentPage().getParameters().get('id')];//'500V00000042mBuIAI'];
        existinginvReqList = new List<Inventory_Request__c>();
        existinginvReqList = [select Type_of_Item__c,Type_of_Item__r.name,Type_of_Item__r.type__c,Type_of_Item__r.type_of_meet__c, Type_of_Item__r.product__c, Type_of_Item__r.product_description__c, Type_of_Item__r.Color_Language_Size__c,
                              Type_of_Item__r.Item_Code__c, inventory_Sample__c, inventory_PackMaterials__c, inventory_Product__c,Required_Quantity__c,Quantity_Dispatched__c,Comments_Remarks__c,Inventory_Request_Number__c,Type_of_Item__r.opening_stock__c,Type_of_Item__r.Owner_Account__c,
                              Type_of_Item__r.Closing_Stocks__c,Type_of_Item__r.Used_Stock__c, inventory_Sample__r.name,inventory_Sample__r.type__c, inventory_Sample__r.product__c, inventory_Sample__r.product_description__c, inventory_Sample__r.Color_Language_Size__c,
                              inventory_Sample__r.Item_Code__c,inventory_PackMaterials__r.name,inventory_PackMaterials__r.type__c, inventory_PackMaterials__r.product__c, inventory_PackMaterials__r.product_description__c, inventory_PackMaterials__r.Color_Language_Size__c,
                              inventory_PackMaterials__r.Item_Code__c,inventory_Product__r.name,inventory_Product__r.type__c, inventory_Product__r.product__c, inventory_Product__r.product_description__c, inventory_Product__r.Color_Language_Size__c,inventory_Product__r.Item_Code__c,
                              inventory_mini__c,inventory_mini__r.name,inventory_mini__r.type__c, inventory_mini__r.product__c, inventory_mini__r.product_description__c, inventory_mini__r.Color_Language_Size__c,inventory_mini__r.Item_Code__c,
                              inventory_mega__c,inventory_mega__r.name,inventory_mega__r.type__c, inventory_mega__r.product__c, inventory_mega__r.product_description__c, inventory_mega__r.Color_Language_Size__c,inventory_mega__r.Item_Code__c
                              from Inventory_Request__c where Inventory_Request_Number__c =: currentCase.id];
        system.debug('###'+currentcase);
        system.debug('###'+existinginvReqList);

        for(Inventory_Request__c request : existinginvReqList){
            CollateralWrapper collateralRequest= new CollateralWrapper();
            if(request.Type_of_Item__r.type__c == 'PRODUCT COLLATERALS'){
                collateralRequest.invRequest= request;
                productCollList1.add(collateralRequest);
            }
            if(request.Type_of_Item__r.type__c  == 'SAMPLES'){
                collateralRequest.invRequest= request;
                sampleList1.add(collateralRequest);
            }

            if(request.Type_of_Item__r.type__c == 'PACKING MATERIALS'){
                collateralRequest.invRequest= request;
                packMaterialList1.add(collateralRequest);
            } 
            
            if(request.Type_of_Item__r.type__c == 'GIFT ITEMS' && request.Type_of_Item__r.type_of_meet__c == 'Mega Meet'){
                collateralRequest.invRequest= request;
                giftListMega1.add(collateralRequest);
            }
            
            if(request.Type_of_Item__r.type__c == 'GIFT ITEMS' && request.Type_of_Item__r.type_of_meet__c == 'Mini Meet'){
                collateralRequest.invRequest= request;
                giftListMini1.add(collateralRequest);
            }   
        } 
    }  
}