Partial_14Dec2021/force-app/main/default/objects/inventory__c/inventory__c.object-meta.xml
<CustomObject>
    <description>Object created to hold the data of the inventory</description>
    <label>inventory</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>inventories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Closing_Stocks__c.field-meta.xml
<CustomField>
    <fullName>Closing_Stocks__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Stocks</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Dispatch_Size__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Size__c</fullName>
    <label>Dispatch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/opening_stock__c.field-meta.xml
<CustomField>
    <fullName>opening_stock__c</fullName>
    <label>Opening Stock</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Owner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Threshold__c.field-meta.xml
<CustomField>
    <fullName>Threshold__c</fullName>
    <label>Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Used_Stock__c.field-meta.xml
<CustomField>
    <fullName>Used_Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Used Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/Sync_Inventory_Controller.cls
/*  
  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 * File Name  : Sync_Inventory_Controller
 * Description: Batch Apex for syncing values of opening and closing stock for object 'inventory'.
 * Author     : Renjay Surendran
 * Modification Log 
 * ===================================================================== 
 * Ver   Date        Author                         Modification 
 * ---------------------------------------------------------------------
 * 1.0   16-Jul-2015   Renjay Surendran            Initial Code 
  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
*/ 
global class Sync_Inventory_Controller implements Database.Batchable<sObject>{

    global String query ='select ID, Name, Closing_Stocks__c, opening_stock__c, Dispatch_Size__c, Owner_Account__c, Threshold__c, Used_Stock__c from inventory__c';

    global  database.QueryLocator start(Database.BatchableContext BC)
    {
        // Initiate the Batch context
       return Database.getQueryLocator(query);
       //return null;      
    }
    global void execute(Database.BatchableContext BC, List<sObject> scope)
    {
       execbatch((list<inventory__c>) scope);
    }
    
    public void execbatch(list<inventory__c> inventList)
    {             
        for(inventory__c val : inventList)
        {
           val.opening_stock__c=val.Closing_Stocks__c;  
        }        
        
        List<Database.SaveResult> uResults = Database.update(inventList,false);
        
        for(Database.SaveResult ResList: uResults)
        {
                if (ResList.isSuccess()) 
                {
                System.debug('Successfully Upserted Record: ' + ResList.getId());
                }
                else
                {
                    for(Database.Error err : ResList.getErrors())
                    {
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Record fields that affected this error: ' + err.getFields());
                    }
                }
        }

    }   
    global void finish(Database.BatchableContext BC)
    {
       
    }     
    
}