Partial_14Dec2021/force-app/main/default/objects/inventory__c/inventory__c.object-meta.xml
<CustomObject>
    <description>Object created to hold the data of the inventory</description>
    <label>inventory</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>inventories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Closing_Stocks__c.field-meta.xml
<CustomField>
    <fullName>Closing_Stocks__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Stocks</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Color_Language_Size__c.field-meta.xml
<CustomField>
    <fullName>Color_Language_Size__c</fullName>
    <label>Color/Language/Size</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ENGLISH</fullName>
            </value>
            <value>
                <fullName>HINDI</fullName>
            </value>
            <value>
                <fullName>GUJARATI</fullName>
            </value>
            <value>
                <fullName>MARATI</fullName>
            </value>
            <value>
                <fullName>KANNADA</fullName>
            </value>
            <value>
                <fullName>TELUGU</fullName>
            </value>
            <value>
                <fullName>TAMIL</fullName>
            </value>
            <value>
                <fullName>RED</fullName>
            </value>
            <value>
                <fullName>VIOLET</fullName>
            </value>
            <value>
                <fullName>INDIGO</fullName>
            </value>
            <value>
                <fullName>BLUE</fullName>
            </value>
            <value>
                <fullName>GREEN</fullName>
            </value>
            <value>
                <fullName>YELLOW</fullName>
            </value>
            <value>
                <fullName>ORANGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/opening_stock__c.field-meta.xml
<CustomField>
    <fullName>opening_stock__c</fullName>
    <label>Opening Stock</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Owner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>COLUMN</fullName>
            </value>
            <value>
                <fullName>CASING</fullName>
            </value>
            <value>
                <fullName>V4</fullName>
            </value>
            <value>
                <fullName>CPVC</fullName>
            </value>
            <value>
                <fullName>AQUALIFE</fullName>
            </value>
            <value>
                <fullName>SWR</fullName>
            </value>
            <value>
                <fullName>PAN CONNECTORS</fullName>
            </value>
            <value>
                <fullName>SILENT SWR</fullName>
            </value>
            <value>
                <fullName>UNDER GROUND</fullName>
            </value>
            <value>
                <fullName>AAV</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>GI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>SILENT PLUS</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>PLUMBING</fullName>
            </value>
            <value>
                <fullName>MINI</fullName>
            </value>
            <value>
                <fullName>MEGA</fullName>
            </value>
            <value>
                <fullName>SWR_PUSHFIT</fullName>
            </value>
            <value>
                <fullName>SWR_SOLFIT</fullName>
            </value>
            <value>
                <fullName>SWR SILENT</fullName>
            </value>
            <value>
                <fullName>SWR SILENT PLUS</fullName>
            </value>
            <value>
                <fullName>UNDERGROUND</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>LEAFLETS</fullName>
            </value>
            <value>
                <fullName>HAND BILL</fullName>
            </value>
            <value>
                <fullName>STICKERS</fullName>
            </value>
            <value>
                <fullName>BANNERS</fullName>
            </value>
            <value>
                <fullName>SCROLL 3&apos;x2&apos;</fullName>
            </value>
            <value>
                <fullName>STALL TENT</fullName>
            </value>
            <value>
                <fullName>FLEX BOARD 6&apos; x 3&apos;</fullName>
            </value>
            <value>
                <fullName>FLEX BOARD 8&apos; x 4&apos;</fullName>
            </value>
            <value>
                <fullName>POP BOARDS</fullName>
            </value>
            <value>
                <fullName>TECHNICAL MANUAL</fullName>
            </value>
            <value>
                <fullName>PRICELIST - ALL INDIA</fullName>
            </value>
            <value>
                <fullName>PRICELIST - TAMILNADU</fullName>
            </value>
            <value>
                <fullName>PIPE SELECTION BOOK</fullName>
            </value>
            <value>
                <fullName>THERMOFOAM BOARD</fullName>
            </value>
            <value>
                <fullName>PRICELIST FOLDERS</fullName>
            </value>
            <value>
                <fullName>CORPORATE BROUCHER (EXCELLENCE TO BRILLANCE)</fullName>
            </value>
            <value>
                <fullName>APPLICATION FORM (CHANNEL PARTNERSHIP)</fullName>
            </value>
            <value>
                <fullName>CORPORATE  LEAFLETS</fullName>
            </value>
            <value>
                <fullName>BLUE TAPE (SHELF STICKERS)</fullName>
            </value>
            <value>
                <fullName>WHITE FOLDER</fullName>
            </value>
            <value>
                <fullName>STANDEES</fullName>
            </value>
            <value>
                <fullName>ALL PRODUCT CLUSTER_STANDEES</fullName>
            </value>
            <value>
                <fullName>MULTI USE KNIFE</fullName>
            </value>
            <value>
                <fullName>TORCHE_EVEREADY</fullName>
            </value>
            <value>
                <fullName>TORCH_NIPPO</fullName>
            </value>
            <value>
                <fullName>UMBRELLA</fullName>
            </value>
            <value>
                <fullName>ASHIRVAD KEY CHAIN -  ENGLISH</fullName>
            </value>
            <value>
                <fullName>LEATHER  KEY CHAIN</fullName>
            </value>
            <value>
                <fullName>LEATHERITE PURSE</fullName>
            </value>
            <value>
                <fullName>LUNCH BOX_TRAVEL MATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Received_Stock__c.field-meta.xml
<CustomField>
    <fullName>Received_Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Received Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PRODUCT COLLATERALS</fullName>
            </value>
            <value>
                <fullName>GIFT ITEMS</fullName>
            </value>
            <value>
                <fullName>PACKING MATERIALS</fullName>
            </value>
            <value>
                <fullName>SAMPLES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Type_Of_Meet__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Meet__c</fullName>
    <label>Type Of Meet</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mega Meet</fullName>
            </value>
            <value>
                <fullName>Mini Meet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Used_Stock__c.field-meta.xml
<CustomField>
    <fullName>Used_Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Used Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/UserInventory.cls
/*  
 * Author     : Vasanthi K N
 */ 
public with sharing class UserInventory {
    public integer counter;
    public boolean renderSearch {get; set;}  
    public integer total_size{get; set;}
    public integer list_size;
    public string soql;
    public String  Userdata{get; set;}
    private ApexPages.StandardSetController controller;
    public inventory__c searchData {get; set;}
    public boolean prodrender{get; set;}
    public boolean renderNext{get; set;}
    public boolean renderPrevious{get; set;}

    public boolean samprender{get; set;}
    public boolean giftrender{get; set;}
    public boolean packrender{get; set;}
    public Integer countCombined = 0;
    public List<inventory__c> productCollateralList{get; set;}
    public List<inventory__c> giftList{get; set;}
    public List<inventory__c> sampleList{get; set;}
    public List<inventory__c> packageMaterialList{get; set;}
    public String searchText{get; set;}
   
    
    
       public UserInventory(ApexPages.StandardSetController stdcontroller) {
        this.controller = stdcontroller;
        list_size=10;
       
        counter=0;
        User user = [select profile.name from user where id =: userInfo.getUserId()];
        if(user.profile.name == 'CSO Depot' || user.profile.name == 'Warehouse' || user.profile.name == 'System Administrator'){
        renderSearch = true;
        }
        else 
        renderSearch = false;
        searchData =(inventory__c)stdcontroller.getRecord();
       
        Userdata = UserInfo.getname();

        getCollaterals();
    }

    public void getCollaterals(){
        List<inventory__c> inventoryList= new List<inventory__c>();
        productCollateralList =new List<inventory__c>();
        giftList=new List<inventory__c>();
        sampleList=new List<inventory__c>();
        packageMaterialList=new List<inventory__c>();
        string di=UserInfo.getUserid();
        soql = 'select product__C,name, Type__c,Product_Description__c, Item_Code__c,type_of_meet__c,Color_Language_Size__c, opening_stock__c, Used_Stock__c,Received_Stock__c, Closing_Stocks__c, Owner_Account__c  from inventory__c where Owner_Account__c =:di';     
        inventoryList = Database.query(soql);
      
        for(inventory__c userInventory : inventoryList){
            if(userInventory.type__c == System.Label.PRODUCT_COLLATERALS){
                productCollateralList.add(userInventory);
            }
            if(userInventory.type__c == System.Label.GIFT_ITEMS){
                giftList.add(userInventory);
            }

            if(userInventory.type__c == System.Label.SAMPLES){
                sampleList.add(userInventory);
            }

            if(userInventory.type__c == System.Label.PACKING_MATERIALS){
                packageMaterialList.add(userInventory);
            }    

        }
        
        countCombined =  productCollateralList.size() +  packageMaterialList.size();
        
        if(countCombined > 30){
        prodrender = true;
        samprender = true;
        giftrender = false;
        packrender = false;
        renderNext = true;
        }           
        else
        {
        prodrender = true;
        samprender = true;
        giftrender = true;
        packrender = true;
        renderNext = false;
        }
        
        Userdata = UserInfo.getname();

          }
   /* public PageReference Beginning() { //user clicked beginning
        
        counter1 = 0;
        counter2 = 0;
        counter3 = 0;
        counter4 = 0;

        
        if(Userdata == UserInfo.getname()){
        getCollaterals();}
        else{search();}
        
        return null;
    }

    public PageReference Previous() { //user clicked previous button
        counter1 -= list_size;
        
       if(Userdata == UserInfo.getname()){
        getCollaterals();}
        else{search();} 
        
        return null;
    }

    public PageReference Next() { //user clicked next button
        counter += list_size;
        
       if(Userdata == UserInfo.getname()){
        getCollaterals();}
        else{search();}        
        
        return null;
    }

    public PageReference End() { //user clicked end
        counter = total_size - math.mod(total_size, list_size);
        
        if(Userdata == UserInfo.getname()){
        getCollaterals();}
        else{search();}        
        
        return null;
    }

    public Boolean getDisablePrevious() { //this will disable the previous and beginning buttons
        if (counter>0) return false; else return true;
    }

    public Boolean getDisableNext() { //this will disable the next and end buttons
        if (counter + list_size < total_size) return false; else return true;
    }

    public Integer getTotal_size() {
      return total_size;
   }
*/
    public void search(){

        List<inventory__c> inventoryList= new List<inventory__c>();
        productCollateralList =new List<inventory__c>();
        giftList=new List<inventory__c>();
        sampleList=new List<inventory__c>();
        packageMaterialList=new List<inventory__c>();
       
        String data =searchData.Owner_Account__c;
        if(data == null){
         ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Please add the user and then click on Search'));
         data=UserInfo.getUserid();
         searchData.Owner_Account__c = data;
        }
        soql = 'select product__C,name, Type__c,Product_Description__c,type_of_meet__c, Item_Code__c,Color_Language_Size__c, opening_stock__c, Used_Stock__c,Received_Stock__c, Closing_Stocks__c, Owner_Account__c  from inventory__c where Owner_Account__c =:data';     
        inventoryList = Database.query(soql);
       // total_size =inventoryList.size();
       // soql+=' limit '+list_size+' offset '+counter ; 
       // inventoryList = Database.query(soql);

        for(inventory__c userInventory : inventoryList){
            if(userInventory.type__c == System.Label.PRODUCT_COLLATERALS){
                productCollateralList.add(userInventory);
            }
            if(userInventory.type__c == System.Label.GIFT_ITEMS){
                giftList.add(userInventory);
            }

            if(userInventory.type__c == System.Label.SAMPLES){
                sampleList.add(userInventory);
            }

            if(userInventory.type__c == System.Label.PACKING_MATERIALS){
                packageMaterialList.add(userInventory);
            }    

        }
       countCombined =  productCollateralList.size() +  packageMaterialList.size();
        
        if(countCombined > 30){
        prodrender = true;
        samprender = true;
        giftrender = false;
        packrender = false;
        renderNext = true;
        }           
        else
        {
        prodrender = true;
        samprender = true;
        giftrender = true;
        packrender = true;
        renderNext = false;
        }
        
        List<User> user =[select name from User where id =:searchData.Owner_Account__c];
        Userdata =user[0].name;
      // searchData.Owner_Account__c =null;

   
    }
    
    public void RenderNext(){
        prodrender = false;
        samprender = false;
        giftrender = true;
        packrender = true;
        renderPrevious = true;
        renderNext = false;
    }
    
     public void RenderPrevious(){
        prodrender = true;
        samprender = true;
        giftrender = false;
        packrender = false;
        renderNext= true;
    renderPrevious = false;
   
   } 
     public void searchInventory(){
     
     
        List<inventory__c> inventoryList= new List<inventory__c>();
        productCollateralList =new List<inventory__c>();
        giftList=new List<inventory__c>();
        sampleList=new List<inventory__c>();
        packageMaterialList=new List<inventory__c>();
        String usersdata =searchData.Owner_Account__c;
       if(usersdata == null){
       usersdata = userInfo.getUserId(); 
       }
        String data ='%'+searchText +'%';
        soql = 'select product__C,name, Type__c,Product_Description__c,type_of_meet__c, Color_Language_Size__c, opening_stock__c, Used_Stock__c,Received_Stock__c, Closing_Stocks__c,Item_Code__c, Owner_Account__c  from inventory__c where (product__C like :data or Type__c like :data or Item_Code__c like :data or Product_Description__c like :data) and Owner_Account__c =:usersdata'; 
        inventoryList = Database.query(soql);
       // total_size =inventoryList.size();
       // soql+=' limit '+list_size+' offset '+counter ; 
       // inventoryList = Database.query(soql);

        for(inventory__c userInventory : inventoryList){
            if(userInventory.type__c == System.Label.PRODUCT_COLLATERALS){
                productCollateralList.add(userInventory);
            }
            if(userInventory.type__c == System.Label.GIFT_ITEMS){
                giftList.add(userInventory);
            }

            if(userInventory.type__c == System.Label.SAMPLES){
                sampleList.add(userInventory);
            }

            if(userInventory.type__c == System.Label.PACKING_MATERIALS){
                packageMaterialList.add(userInventory);
            }    

        }
       countCombined =  productCollateralList.size() +  packageMaterialList.size();
        
        if(countCombined > 30){
        prodrender = true;
        samprender = true;
        giftrender = false;
        packrender = false;
        renderNext = true;
        }           
        else
        {
        prodrender = true;
        samprender = true;
        giftrender = true;
        packrender = true;
        renderNext = false;
        }
        
        searchText = null;

        }

    }