Partial_14Dec2021/force-app/main/default/objects/inventory__c/inventory__c.object-meta.xml
<CustomObject>
    <description>Object created to hold the data of the inventory</description>
    <label>inventory</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>inventories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Color_Language_Size__c.field-meta.xml
<CustomField>
    <fullName>Color_Language_Size__c</fullName>
    <label>Color/Language/Size</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ENGLISH</fullName>
            </value>
            <value>
                <fullName>HINDI</fullName>
            </value>
            <value>
                <fullName>GUJARATI</fullName>
            </value>
            <value>
                <fullName>MARATI</fullName>
            </value>
            <value>
                <fullName>KANNADA</fullName>
            </value>
            <value>
                <fullName>TELUGU</fullName>
            </value>
            <value>
                <fullName>TAMIL</fullName>
            </value>
            <value>
                <fullName>RED</fullName>
            </value>
            <value>
                <fullName>VIOLET</fullName>
            </value>
            <value>
                <fullName>INDIGO</fullName>
            </value>
            <value>
                <fullName>BLUE</fullName>
            </value>
            <value>
                <fullName>GREEN</fullName>
            </value>
            <value>
                <fullName>YELLOW</fullName>
            </value>
            <value>
                <fullName>ORANGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>COLUMN</fullName>
            </value>
            <value>
                <fullName>CASING</fullName>
            </value>
            <value>
                <fullName>V4</fullName>
            </value>
            <value>
                <fullName>CPVC</fullName>
            </value>
            <value>
                <fullName>AQUALIFE</fullName>
            </value>
            <value>
                <fullName>SWR</fullName>
            </value>
            <value>
                <fullName>PAN CONNECTORS</fullName>
            </value>
            <value>
                <fullName>SILENT SWR</fullName>
            </value>
            <value>
                <fullName>UNDER GROUND</fullName>
            </value>
            <value>
                <fullName>AAV</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>GI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>SILENT PLUS</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>PLUMBING</fullName>
            </value>
            <value>
                <fullName>MINI</fullName>
            </value>
            <value>
                <fullName>MEGA</fullName>
            </value>
            <value>
                <fullName>SWR_PUSHFIT</fullName>
            </value>
            <value>
                <fullName>SWR_SOLFIT</fullName>
            </value>
            <value>
                <fullName>SWR SILENT</fullName>
            </value>
            <value>
                <fullName>SWR SILENT PLUS</fullName>
            </value>
            <value>
                <fullName>UNDERGROUND</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>LEAFLETS</fullName>
            </value>
            <value>
                <fullName>HAND BILL</fullName>
            </value>
            <value>
                <fullName>STICKERS</fullName>
            </value>
            <value>
                <fullName>BANNERS</fullName>
            </value>
            <value>
                <fullName>SCROLL 3&apos;x2&apos;</fullName>
            </value>
            <value>
                <fullName>STALL TENT</fullName>
            </value>
            <value>
                <fullName>FLEX BOARD 6&apos; x 3&apos;</fullName>
            </value>
            <value>
                <fullName>FLEX BOARD 8&apos; x 4&apos;</fullName>
            </value>
            <value>
                <fullName>POP BOARDS</fullName>
            </value>
            <value>
                <fullName>TECHNICAL MANUAL</fullName>
            </value>
            <value>
                <fullName>PRICELIST - ALL INDIA</fullName>
            </value>
            <value>
                <fullName>PRICELIST - TAMILNADU</fullName>
            </value>
            <value>
                <fullName>PIPE SELECTION BOOK</fullName>
            </value>
            <value>
                <fullName>THERMOFOAM BOARD</fullName>
            </value>
            <value>
                <fullName>PRICELIST FOLDERS</fullName>
            </value>
            <value>
                <fullName>CORPORATE BROUCHER (EXCELLENCE TO BRILLANCE)</fullName>
            </value>
            <value>
                <fullName>APPLICATION FORM (CHANNEL PARTNERSHIP)</fullName>
            </value>
            <value>
                <fullName>CORPORATE  LEAFLETS</fullName>
            </value>
            <value>
                <fullName>BLUE TAPE (SHELF STICKERS)</fullName>
            </value>
            <value>
                <fullName>WHITE FOLDER</fullName>
            </value>
            <value>
                <fullName>STANDEES</fullName>
            </value>
            <value>
                <fullName>ALL PRODUCT CLUSTER_STANDEES</fullName>
            </value>
            <value>
                <fullName>MULTI USE KNIFE</fullName>
            </value>
            <value>
                <fullName>TORCHE_EVEREADY</fullName>
            </value>
            <value>
                <fullName>TORCH_NIPPO</fullName>
            </value>
            <value>
                <fullName>UMBRELLA</fullName>
            </value>
            <value>
                <fullName>ASHIRVAD KEY CHAIN -  ENGLISH</fullName>
            </value>
            <value>
                <fullName>LEATHER  KEY CHAIN</fullName>
            </value>
            <value>
                <fullName>LEATHERITE PURSE</fullName>
            </value>
            <value>
                <fullName>LUNCH BOX_TRAVEL MATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PRODUCT COLLATERALS</fullName>
            </value>
            <value>
                <fullName>GIFT ITEMS</fullName>
            </value>
            <value>
                <fullName>PACKING MATERIALS</fullName>
            </value>
            <value>
                <fullName>SAMPLES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Type_Of_Meet__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Meet__c</fullName>
    <label>Type Of Meet</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mega Meet</fullName>
            </value>
            <value>
                <fullName>Mini Meet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Gift_Request__c/Inventory_Gift_Request__c.object-meta.xml
<CustomObject>
    <label>Inventory_Gift_Request</label>
    <nameField>
        <displayFormat>IGR-{000000}</displayFormat>
        <label>InventoryGiftRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory_Gift_Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Gift_Request__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Inventory_Gift_Requests</relationshipLabel>
    <relationshipName>Inventory_Gift_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Gift_Request__c/fields/Request_Raised_by__c.field-meta.xml
<CustomField>
    <fullName>Request_Raised_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request Raised by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Inventory_Gift_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/Inventory_Request__c.object-meta.xml
<CustomObject>
    <label>Inventory Request</label>
    <nameField>
        <displayFormat>IR-{0000}</displayFormat>
        <label>Inventory Request  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/inventory_PackMaterials__c.field-meta.xml
<CustomField>
    <fullName>inventory_PackMaterials__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>inventory_PackMaterials</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>inventory__c.Type__c</field>
            <operation>equals</operation>
            <value>PACKING MATERIALS</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>inventory__c</referenceTo>
    <relationshipLabel>Inventory Requests (inventory_PackMaterials)</relationshipLabel>
    <relationshipName>Inventory_Requests3</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/inventory_Product__c.field-meta.xml
<CustomField>
    <fullName>inventory_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>inventory_Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>inventory__c.Type__c</field>
            <operation>equals</operation>
            <value>PRODUCT COLLATERALS</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>inventory__c</referenceTo>
    <relationshipLabel>Inventory Requests (inventory_Product)</relationshipLabel>
    <relationshipName>Inventory_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/Inventory_Request_Number__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Request_Number__c</fullName>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Inventory Requests</relationshipLabel>
    <relationshipName>Inventory_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/inventory_Sample__c.field-meta.xml
<CustomField>
    <fullName>inventory_Sample__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>inventory_Sample</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>inventory__c.Type__c</field>
            <operation>equals</operation>
            <value>SAMPLES</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>inventory__c</referenceTo>
    <relationshipLabel>Inventory Requests (inventory_Sample)</relationshipLabel>
    <relationshipName>Inventory_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/Request_Rasied_by__c.field-meta.xml
<CustomField>
    <fullName>Request_Rasied_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request Raised by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Inventory_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/Required_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Required_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Required Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/Type_of_Item__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type of Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>inventory__c.Owner_Account__c</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>inventory__c.Type__c</field>
            <operation>equals</operation>
            <value>GIFT ITEMS</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>inventory__c</referenceTo>
    <relationshipLabel>Inventory Requests</relationshipLabel>
    <relationshipName>Inventory_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/CtrlInventoryRequestPage.cls
/***************************************************************************************
Copyright Â© 2015 Ashirvad. All rights reserved.
Author: vasanthi K N
Email: vasanthi_KN@infosys.com
Description:  Class to create the collateral request
 ****************************************************************************************/
public with sharing class CtrlInventoryRequestPage{

    public Case currentCase{get;set;}
    public List<CollateralWrapper> productCollList{get;set;}
    public List<CollateralWrapper> giftList{get;set;}
    public List<CollateralWrapper> sampleList{get;set;}
    public List<CollateralWrapper> packMaterialList{get;set;}
    public List<inventory_Gift_request__c> gifReq {set; get;}
    public Map<Id,Inventory_Request__c> invReqMap{get;set;}

    
    
    public CtrlInventoryRequestPage(ApexPages.StandardController stdController) { 
        
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType='Case' AND Name='Collateral Request' LIMIT 1];
        Final Id CaseRecordType=rt.id;
        currentCase = new Case();
        currentCase.RecordTypeId = CaseRecordType;
        productCollList= new List<CollateralWrapper>();
        giftList= new List<CollateralWrapper>();
        sampleList= new List<CollateralWrapper>();
        packMaterialList= new List<CollateralWrapper>();
        gifReq = new List<inventory_Gift_request__c>();
        invReqMap= new Map<Id,Inventory_Request__c>();       
        
        currentCase.Request_Raised_by__c = UserInfo.getUserid();
        currentcase.Subject = 'Request for collateral by '+ UserInfo.getFirstname()+ ' ' + UserInfo.getLastName();
        currentCase.priority ='Medium';
        currentCase.origin = 'Self';
        User UserDetail =  [select address, depot_zone__c, depo__c, head_office__c, team_lead__c from  User where id =: UserInfo.getUserid()];    

        Address addr = UserDetail.Address;
        
        if(addr != null){
            currentcase.Shipping_Address__c = addr.getStreet()+ ' ' + addr.getcity() + ' '  + addr.getstate()+ ' '
            +  addr.getPostalCode() +' '+ addr.getcountry();
        }
        else{
            currentcase.Shipping_Address__c =''; 
        }
        currentCase.depo__c=userDetail.depo__c;
        currentCase.head_office__c = userDetail.head_office__c;
        currentCase.Team_Lead__c = userDetail.team_lead__c;
        if(userDetail.depo__c != null){
        User DepoDetail =  [select address, depot_zone__c, depo__c, head_office__c, team_lead__c from  User where id =: userDetail.depo__c];    
        if(DepoDetail !=null){
        currentCase.depot_zone__c =DepoDetail.depot_zone__c;}
        }
        String profileName =[Select Id,Name from Profile where Id=:userinfo.getProfileId()].Name;
        if(profileName == 'Warehouse'){
        currentCase.Collateral_Flows__c ='Depot';
        currentCase.depot_zone__c = userDetail.depot_zone__c;
        }
        else if(profileName  == 'CSO Depot'){
        currentCase.Collateral_Flows__c ='CSO';
        }
        else{
        currentCase.Collateral_Flows__c ='Requestor';
        }
        
        for(integer i=0; i<5; i++){
            CollateralWrapper wrapper= new CollateralWrapper();
            wrapper.invRequest.Request_Rasied_by__c= UserInfo.getUserid(); 
            productCollList.add(wrapper);

        }
        for(integer i=0; i<3; i++){
            CollateralWrapper wrapper= new CollateralWrapper();
            wrapper.invRequest.Request_Rasied_by__c= UserInfo.getUserid(); 
            giftList.add(wrapper);

        }
        
        
        
        for(integer i=0; i<5; i++){
            CollateralWrapper wrapper= new CollateralWrapper();
            wrapper.invRequest.Request_Rasied_by__c= UserInfo.getUserid(); 
            sampleList.add(wrapper);

        }

        for(integer i=0; i<5; i++){
            CollateralWrapper wrapper= new CollateralWrapper();
            wrapper.invRequest.Request_Rasied_by__c= UserInfo.getUserid(); 
            packMaterialList.add(wrapper);

        }
       
            for(integer i=0; i< 2; i++){
            inventory_Gift_request__c gifRequest = new inventory_Gift_request__c();
             gifRequest.Request_Raised_by__c = UserInfo.getUserid(); 
             if(i==0){
                 gifRequest.Type_Of_Meet__c =  'Mega Meet';}
                 else{
             gifRequest.Type_Of_Meet__c =  'Mini Meet';}
             gifReq.add(gifRequest);

            }  
            
            
          }


    public PageReference Cancel(){  
        try{
            Schema.DescribeSObjectResult result = Case.SObjectType.getDescribe();
            PageReference pageRef = new PageReference('/' + result.getKeyPrefix()+ '/o');
            pageRef.setRedirect(true);
            return pageRef;
        }

        catch(exception e){system.debug(e.getMessage()); return null;}

    }

    public PageReference getinventoryDetails(){
       
        CommonHelper.clearInventories(productCollList, sampleList, packMaterialList,giftList, giftList);
        for(Integer i=0; i<productCollList.size(); i++){
           
            if(productCollList[i].invRequest.inventory_Product__c!=null){
                Inventory__c invDetails= queryInventory(productCollList[i].invRequest.inventory_Product__c);
               
                productCollList[i].invRequest.inventory_Product__r=invDetails;
               
            }
           
        }
    
        for(Integer i=0; i<giftList.size(); i++){
            if(giftList[i].invRequest.Type_of_item__c!=null){
                Inventory__c invDetails= queryInventory(giftList[i].invRequest.Type_of_item__c);
                // if(CommonHelper.validateCreateRequestNew(accountRecord ,currentCase)){
                giftList[i].invRequest.Type_of_item__r=invDetails;
                //   }
            }
           

        }

        for(Integer i=0; i<sampleList.size(); i++){
            if(sampleList[i].invRequest.inventory_Sample__c!=null){
                Inventory__c invDetails= queryInventory(sampleList[i].invRequest.inventory_Sample__c);
                // if(CommonHelper.validateCreateRequestNew(accountRecord ,currentCase)){
                sampleList[i].invRequest.inventory_Sample__r=invDetails;
                //   }
            }
            
        }

        for(Integer i=0; i<packMaterialList.size(); i++){
            if(packMaterialList[i].invRequest.inventory_PackMaterials__c!=null){
                Inventory__c invDetails= queryInventory(packMaterialList[i].invRequest.inventory_PackMaterials__c);
                // if(CommonHelper.validateCreateRequestNew(accountRecord ,currentCase)){
                packMaterialList[i].invRequest.inventory_PackMaterials__r=invDetails;
                //   }
            }
          
        }
        return null;
    }


    Public inventory__c queryInventory(Id invId){
        inventory__c invRecord= new inventory__c();
        invRecord=[select id,name,Color_Language_Size__c, Product_Description__c, Type__c, Item_Code__c, Product__c from inventory__c where id=: invId];
        return invRecord;
    } 
    
     public PageReference saveDetails( ){
        invReqMap.clear();
        
       List<inventory_Gift_request__c> finalInvReqGiftList = new List<inventory_Gift_request__c>();
             for(Integer i=0; i<productCollList.size(); i++){
       
              if(productCollList[i].invRequest.inventory_Product__c!=null){
                    productCollList[i].invRequest.type_of_item__c = productCollList[i].invRequest.inventory_Product__c;
                invReqMap.put(productCollList[i].invRequest.inventory_Product__c,productCollList[i].invRequest);
          
                 } 
        }
             
       for(Integer i=0; i<sampleList.size(); i++){
        if(sampleList[i].invRequest.inventory_sample__c!=null ){
          sampleList[i].invRequest.type_of_item__c =sampleList[i].invRequest.inventory_sample__c;
          invReqMap.put(sampleList[i].invRequest.inventory_sample__c,sampleList[i].invRequest);
                           } 
        }
        
       for(Integer i=0; i<packMaterialList.size(); i++){
        if(packMaterialList[i].invRequest.inventory_PackMaterials__c!=null){
        packMaterialList[i].invRequest.type_of_item__c=packMaterialList[i].invRequest.inventory_PackMaterials__c;
                invReqMap.put(packMaterialList[i].invRequest.inventory_PackMaterials__c,packMaterialList[i].invRequest);
             } 
        }
        if(commonhelper.ValidateCollList(productCollList,sampleList,packMaterialList,giftList,giftList)){
        upsert currentCase;
                   
      for(inventory_Gift_request__c gif: gifReq){
        if(gif.Required_Quantity__c != null){
        gif.Case__c= currentCase.id;
        finalInvReqGiftList.add(gif);
        }
        } 
         
               
          for(inventory_Request__c req:invReqMap.values() ){
                req.Inventory_Request_Number__c=currentCase.id;
             }   
          if(commonhelper.validateCollateral(invReqMap,finalInvReqGiftList, currentCase)){
 
            insert invReqMap.values(); 
            
            if( finalInvReqGiftList.size()!= 0){
            currentCase.check_gifts__c = true;
            upsert currentCase;
            }
            insert finalInvReqGiftList;
            List<caseShare> caseShareList = new List<caseShare>();
            if(currentCase.Team_Lead__c != null){
               CaseShare caseShare=new CaseShare();
               caseShare.UserOrGroupID = currentCase.Team_Lead__c;
               caseShare.CaseAccessLevel= 'Read';
               caseShare.CaseId= currentCase.Id;
               caseShare.RowCause = 'Manual';
               caseShareList.add(CaseShare);      
            }
           if(currentCase.depo__c !=null){
            CaseShare caseShare=new CaseShare();
               caseShare.UserOrGroupID = currentCase.depo__c;
               caseShare.CaseAccessLevel= 'Edit';
               caseShare.CaseId= currentCase.Id;
               caseShare.RowCause = 'Manual';
               caseShareList.add(CaseShare); 
           }
           if(currentCase.head_office__c !=null){
            CaseShare caseShare=new CaseShare();
               caseShare.UserOrGroupID = currentCase.head_office__c;
               caseShare.CaseAccessLevel= 'Edit';
               caseShare.CaseId= currentCase.Id;
               caseShare.RowCause = 'Manual';
               caseShareList.add(CaseShare); 
           }
          if(caseShareList.size()!=0 && caseShareList !=null){
           insert caseShareList;}
           
            PageReference reference=new PageReference('/'+currentCase.id);
            reference.setRedirect(true);
            
            return reference;
            
            
        
           }
           
           }
           return null;
}
   }