Partial_14Dec2021/force-app/main/default/objects/inventory__c/inventory__c.object-meta.xml
<CustomObject>
    <description>Object created to hold the data of the inventory</description>
    <label>inventory</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>inventories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Closing_Stocks__c.field-meta.xml
<CustomField>
    <fullName>Closing_Stocks__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Stocks</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Dispatch_Size__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Size__c</fullName>
    <label>Dispatch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/opening_stock__c.field-meta.xml
<CustomField>
    <fullName>opening_stock__c</fullName>
    <label>Opening Stock</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Owner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Threshold__c.field-meta.xml
<CustomField>
    <fullName>Threshold__c</fullName>
    <label>Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Used_Stock__c.field-meta.xml
<CustomField>
    <fullName>Used_Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Used Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/Sync_Inventory_Controller_test.cls
/*  
 * Author     : Renjay Surendran
 */ 
@isTest
public Class Sync_Inventory_Controller_test{ 
    static testmethod void StartTest(){
       Database.QueryLocator QL;
       Database.BatchableContext BC;
       Sync_Inventory_Controller prog = new Sync_Inventory_Controller();
       List<inventory__c> invList = new List<inventory__c>();
       User admin = [SELECT id FROM User WHERE id =: UserInfo.getUserId() LIMIT 1]; 
       System.runAs(admin){ 
       inventory__c inv=new inventory__c();
       inv.Name='Renj'; 
       inv.Closing_Stocks__c=100;
       inv.opening_stock__c=1000;
       inv.Dispatch_Size__c=75;
       inv.Owner_Account__c=admin.id;
       inv.Threshold__c=200;
       inv.Used_Stock__c=900;
       invList.add(inv);
       
       insert invList; 
       
      test.startTest();  
      QL = prog.start(BC); 
      prog.execute(BC, invList);
      prog.finish(BC); 
      test.stopTest();
      }
}
}