Partial_14Dec2021/force-app/main/default/objects/inventory__c/inventory__c.object-meta.xml
<CustomObject>
    <description>Object created to hold the data of the inventory</description>
    <label>inventory</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>inventories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Closing_Stocks__c.field-meta.xml
<CustomField>
    <fullName>Closing_Stocks__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Stocks</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Color_Language_Size__c.field-meta.xml
<CustomField>
    <fullName>Color_Language_Size__c</fullName>
    <label>Color/Language/Size</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ENGLISH</fullName>
            </value>
            <value>
                <fullName>HINDI</fullName>
            </value>
            <value>
                <fullName>GUJARATI</fullName>
            </value>
            <value>
                <fullName>MARATI</fullName>
            </value>
            <value>
                <fullName>KANNADA</fullName>
            </value>
            <value>
                <fullName>TELUGU</fullName>
            </value>
            <value>
                <fullName>TAMIL</fullName>
            </value>
            <value>
                <fullName>RED</fullName>
            </value>
            <value>
                <fullName>VIOLET</fullName>
            </value>
            <value>
                <fullName>INDIGO</fullName>
            </value>
            <value>
                <fullName>BLUE</fullName>
            </value>
            <value>
                <fullName>GREEN</fullName>
            </value>
            <value>
                <fullName>YELLOW</fullName>
            </value>
            <value>
                <fullName>ORANGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Dispatch_Size__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Size__c</fullName>
    <label>Dispatch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/opening_stock__c.field-meta.xml
<CustomField>
    <fullName>opening_stock__c</fullName>
    <label>Opening Stock</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Owner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>COLUMN</fullName>
            </value>
            <value>
                <fullName>CASING</fullName>
            </value>
            <value>
                <fullName>V4</fullName>
            </value>
            <value>
                <fullName>CPVC</fullName>
            </value>
            <value>
                <fullName>AQUALIFE</fullName>
            </value>
            <value>
                <fullName>SWR</fullName>
            </value>
            <value>
                <fullName>PAN CONNECTORS</fullName>
            </value>
            <value>
                <fullName>SILENT SWR</fullName>
            </value>
            <value>
                <fullName>UNDER GROUND</fullName>
            </value>
            <value>
                <fullName>AAV</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>GI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>SILENT PLUS</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>PLUMBING</fullName>
            </value>
            <value>
                <fullName>MINI</fullName>
            </value>
            <value>
                <fullName>MEGA</fullName>
            </value>
            <value>
                <fullName>SWR_PUSHFIT</fullName>
            </value>
            <value>
                <fullName>SWR_SOLFIT</fullName>
            </value>
            <value>
                <fullName>SWR SILENT</fullName>
            </value>
            <value>
                <fullName>SWR SILENT PLUS</fullName>
            </value>
            <value>
                <fullName>UNDERGROUND</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>LEAFLETS</fullName>
            </value>
            <value>
                <fullName>HAND BILL</fullName>
            </value>
            <value>
                <fullName>STICKERS</fullName>
            </value>
            <value>
                <fullName>BANNERS</fullName>
            </value>
            <value>
                <fullName>SCROLL 3&apos;x2&apos;</fullName>
            </value>
            <value>
                <fullName>STALL TENT</fullName>
            </value>
            <value>
                <fullName>FLEX BOARD 6&apos; x 3&apos;</fullName>
            </value>
            <value>
                <fullName>FLEX BOARD 8&apos; x 4&apos;</fullName>
            </value>
            <value>
                <fullName>POP BOARDS</fullName>
            </value>
            <value>
                <fullName>TECHNICAL MANUAL</fullName>
            </value>
            <value>
                <fullName>PRICELIST - ALL INDIA</fullName>
            </value>
            <value>
                <fullName>PRICELIST - TAMILNADU</fullName>
            </value>
            <value>
                <fullName>PIPE SELECTION BOOK</fullName>
            </value>
            <value>
                <fullName>THERMOFOAM BOARD</fullName>
            </value>
            <value>
                <fullName>PRICELIST FOLDERS</fullName>
            </value>
            <value>
                <fullName>CORPORATE BROUCHER (EXCELLENCE TO BRILLANCE)</fullName>
            </value>
            <value>
                <fullName>APPLICATION FORM (CHANNEL PARTNERSHIP)</fullName>
            </value>
            <value>
                <fullName>CORPORATE  LEAFLETS</fullName>
            </value>
            <value>
                <fullName>BLUE TAPE (SHELF STICKERS)</fullName>
            </value>
            <value>
                <fullName>WHITE FOLDER</fullName>
            </value>
            <value>
                <fullName>STANDEES</fullName>
            </value>
            <value>
                <fullName>ALL PRODUCT CLUSTER_STANDEES</fullName>
            </value>
            <value>
                <fullName>MULTI USE KNIFE</fullName>
            </value>
            <value>
                <fullName>TORCHE_EVEREADY</fullName>
            </value>
            <value>
                <fullName>TORCH_NIPPO</fullName>
            </value>
            <value>
                <fullName>UMBRELLA</fullName>
            </value>
            <value>
                <fullName>ASHIRVAD KEY CHAIN -  ENGLISH</fullName>
            </value>
            <value>
                <fullName>LEATHER  KEY CHAIN</fullName>
            </value>
            <value>
                <fullName>LEATHERITE PURSE</fullName>
            </value>
            <value>
                <fullName>LUNCH BOX_TRAVEL MATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Received_Stock__c.field-meta.xml
<CustomField>
    <fullName>Received_Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Received Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Threshold__c.field-meta.xml
<CustomField>
    <fullName>Threshold__c</fullName>
    <label>Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PRODUCT COLLATERALS</fullName>
            </value>
            <value>
                <fullName>GIFT ITEMS</fullName>
            </value>
            <value>
                <fullName>PACKING MATERIALS</fullName>
            </value>
            <value>
                <fullName>SAMPLES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Used_Stock__c.field-meta.xml
<CustomField>
    <fullName>Used_Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Used Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/CtrlInventoryRequestPage_UT.cls
@isTest
public class CtrlInventoryRequestPage_UT{
   static testMethod void lInventoryRequestPagetest(){
   
    Profile profile= [Select Id from Profile where name='System Administrator' limit 1];
    User user= new User( FirstName='Test', LastName='User', alias='abcd', email='testuser@abc.com', username='testuser123@abc.com', profileId=profile.Id, TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
    insert user;
    
    //public static id RecordTypeId= caseRecordTypeMap.get('Collateral Reques').getrecordtypeid();
     
    Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Case; 
    Map<String,Schema.RecordTypeInfo> CaseRecordTypeInfo = cfrSchema.getRecordTypeInfosByName();
    Id i= CaseRecordTypeInfo.get('Collateral Request').getRecordTypeId(); 
     
    Case c1=new Case();
    c1.recordtypeId =i;
    c1.Shipping_Address__c='Elec,Bangalore';
    c1.Billing_Address__c='BTM,Bangalore';
    c1.depo__c=user.id;
    c1.head_office__c=user.id;
    c1.team_lead__c=user.id;
    c1.Request_Raised_By__c=user.id;
    
    insert c1;
    
    inventory__c inv1=new inventory__c();
    inv1.opening_stock__c =150;
    inv1.Closing_Stocks__c=150;
    inv1.Dispatch_Size__c=50;
    inv1.Owner_Account__c = user.id;
    inv1.Received_Stock__c = 0;
    inv1.Threshold__c=50;
    inv1.Used_Stock__c=0;
    inv1.type__c='PRODUCT COLLATERALS';
    insert inv1;
     inventory__c invPac=new inventory__c();
    invPac.opening_stock__c =150;
    invPac.Closing_Stocks__c=150;
    invPac.Dispatch_Size__c=50;
    invPac.Owner_Account__c = user.id;
    invPac.Received_Stock__c = 0;
    invPac.Threshold__c=50;
    invPac.Used_Stock__c=0;
   // invSam.type__c='SAMPLES';
    invPac.product__c='XYZ';
    invPac.Color_Language_Size__c='zzzzz';
    invPac.product_description__c='Good';
    invPac.Item_Code__c='8888';
    invPac.type__c='PACKING MATERIALS';
    
    insert invPac;
     inventory__c invSam=new inventory__c();
    invSam.opening_stock__c =150;
    invSam.Closing_Stocks__c=150;
    invSam.Dispatch_Size__c=50;
    invSam.Owner_Account__c = user.id;
    invSam.Received_Stock__c = 0;
    invSam.Threshold__c=50;
    invSam.Used_Stock__c=0;
    invSam.type__c='SAMPLES';
    invSam.product__c='XYZ';
    invSam.Color_Language_Size__c='zzzzz';
    invSam.product_description__c='Good';
    invSam.Item_Code__c='8888';
    //inv1.type__c='PACKING MATERIALS';
    
    insert invSam;
    test.startTest();
    System.runAs(user)
    { 
      ApexPages.currentPage().getParameters().put('id', c1.id);    
      ApexPages.StandardController sc = new ApexPages.StandardController(new case());
      CtrlInventoryRequestPage ctrl= new CtrlInventoryRequestPage(sc);
      
      ctrl.productCollList[0].invRequest.inventory_Product__c=inv1.id;
      ctrl.sampleList[0].invRequest.inventory_sample__c=invSam.id;
      ctrl.packMaterialList[0].invRequest.inventory_PackMaterials__c=invPac.id;
      ctrl.giftList[0].invRequest.Type_of_item__c=inv1.id;
      ctrl.packMaterialList[0].invRequest.inventory_PackMaterials__c=invPac.id;
      
       ctrl.productCollList[0].invRequest.required_quantity__c=10;
      ctrl.sampleList[0].invRequest.required_quantity__c=5;
      ctrl.packMaterialList[0].invRequest.required_quantity__c=10;
      ctrl.giftList[0].invRequest.required_quantity__c=3;
      ctrl.packMaterialList[0].invRequest.required_quantity__c=2;
      
      
      PageReference ref=ctrl.Cancel();
      PageReference ref1=ctrl.getinventoryDetails();
      ctrl.queryInventory(inv1.id);
      PageReference ref2=ctrl.saveDetails( );
      
    }
    test.stopTest();
   }
}