Partial_14Dec2021/force-app/main/default/objects/inventory__c/inventory__c.object-meta.xml
<CustomObject>
    <description>Object created to hold the data of the inventory</description>
    <label>inventory</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>inventories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Closing_Stocks__c.field-meta.xml
<CustomField>
    <fullName>Closing_Stocks__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Stocks</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Dispatch_Size__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Size__c</fullName>
    <label>Dispatch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/opening_stock__c.field-meta.xml
<CustomField>
    <fullName>opening_stock__c</fullName>
    <label>Opening Stock</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Owner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>COLUMN</fullName>
            </value>
            <value>
                <fullName>CASING</fullName>
            </value>
            <value>
                <fullName>V4</fullName>
            </value>
            <value>
                <fullName>CPVC</fullName>
            </value>
            <value>
                <fullName>AQUALIFE</fullName>
            </value>
            <value>
                <fullName>SWR</fullName>
            </value>
            <value>
                <fullName>PAN CONNECTORS</fullName>
            </value>
            <value>
                <fullName>SILENT SWR</fullName>
            </value>
            <value>
                <fullName>UNDER GROUND</fullName>
            </value>
            <value>
                <fullName>AAV</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>GI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>SILENT PLUS</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>PLUMBING</fullName>
            </value>
            <value>
                <fullName>MINI</fullName>
            </value>
            <value>
                <fullName>MEGA</fullName>
            </value>
            <value>
                <fullName>SWR_PUSHFIT</fullName>
            </value>
            <value>
                <fullName>SWR_SOLFIT</fullName>
            </value>
            <value>
                <fullName>SWR SILENT</fullName>
            </value>
            <value>
                <fullName>SWR SILENT PLUS</fullName>
            </value>
            <value>
                <fullName>UNDERGROUND</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Received_Stock__c.field-meta.xml
<CustomField>
    <fullName>Received_Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Received Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Threshold__c.field-meta.xml
<CustomField>
    <fullName>Threshold__c</fullName>
    <label>Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PRODUCT COLLATERALS</fullName>
            </value>
            <value>
                <fullName>GIFT ITEMS</fullName>
            </value>
            <value>
                <fullName>PACKING MATERIALS</fullName>
            </value>
            <value>
                <fullName>SAMPLES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Used_Stock__c.field-meta.xml
<CustomField>
    <fullName>Used_Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Used Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/UserInventory_UT.cls
@isTest
public class UserInventory_UT{
   static testMethod void CountUserInventory(){
   
    Profile profile= [Select Id from Profile where name='System Administrator' limit 1];
    User user= new User( FirstName='Test', LastName='User', alias='abcd', email='testuser@abc.com', username='testuser123@abc.com', profileId=profile.Id, TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
    insert user;
    
    List<inventory__c> invlist= new List<inventory__c>();
    inventory__c inv1= new Inventory__c();
    inv1.opening_stock__c =200;
    inv1.Closing_Stocks__c=200;
    inv1.Dispatch_Size__c=50;
    inv1.Owner_Account__c = user.id;
    inv1.Received_Stock__c = 0;
    inv1.Threshold__c=50;
    inv1.Used_Stock__c=0;
    inv1.product__C='XYZ';
    inv1.type__c='PRODUCT COLLATERALS';
    invlist.add(inv1);
    
    inventory__c inv2= new Inventory__c();
    inv2.opening_stock__c =100;
    inv2.Closing_Stocks__c=100;
    inv2.Dispatch_Size__c=50;
    inv2.Owner_Account__c = user.id;
    inv2.Received_Stock__c = 0;
    inv2.Threshold__c=50;
    inv2.Used_Stock__c=0;
    inv2.product__C='XYZ';
    inv2.type__c='GIFT ITEMS';
    invlist.add(inv2);
    
    
    inventory__c inv3= new Inventory__c();
    inv3.opening_stock__c =150;
    inv3.Closing_Stocks__c=150;
    inv3.Dispatch_Size__c=50;
    inv3.Owner_Account__c = user.id;
    inv3.Received_Stock__c = 0;
    inv3.Threshold__c=50;
    inv3.Used_Stock__c=0;
    inv3.product__C='XYZ';
    inv3.type__c='SAMPLES';
    invlist.add(inv3);
    
    
    inventory__c inv4= new Inventory__c();
    inv4.opening_stock__c =210;
    inv4.Closing_Stocks__c=210;
    inv4.Dispatch_Size__c=50;
    inv4.Owner_Account__c = user.id;
    inv4.Received_Stock__c = 0;
    inv4.Threshold__c=50;
    inv4.Used_Stock__c=0;
    inv4.product__C='XYZ';
    inv4.type__c='PACKING MATERIALS';
    invlist.add(inv4);
    
    insert invlist;
    
    test.startTest();
    System.runAs(user)
    { 
    UserInventory UI= new UserInventory(new ApexPages.StandardSetController(invlist));
    for(inventory__c userInventory : invlist){
    UI.searchData=userInventory;
    }
    
    UI.getCollaterals();
    UI.search();
    
    List<inventory__c> invlist1= new List<inventory__c>();
    for(integer i=0;i<=30;i++){
    inventory__c inv5= new Inventory__c();
    inv5.opening_stock__c =210;
    inv5.Closing_Stocks__c=210;
    inv5.Dispatch_Size__c=50;
    inv5.Owner_Account__c = user.id;
    inv5.Received_Stock__c = 0;
    inv5.Threshold__c=50;
    inv5.Used_Stock__c=0;
    inv5.product__C='XYZ';
    inv5.type__c='PACKING MATERIALS';
    invlist1.add(inv5);
    
    }
    
    insert invlist1;
    
    for(inventory__c userInventory : invlist1){
    UI.searchData=userInventory;
    }
    UI.searchText='XYZ';
    UI.searchData.owner_account__c=null;
    UI.search();
    UI.getCollaterals();
    UI.searchInventory();
    UI.countCombined=invlist1.size();
    UI.RenderNext();
    UI.RenderPrevious(); 
    }    
    test.stopTest();  
    
   }
}