Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/New_Special_Pricing_Request__c.object-meta.xml
<CustomObject>
    <description>This object stores all the line items that are checked and sent for SPR. The group of items that are selected goes for SPR everytime the project is sent for approval.</description>
    <label>New Special Pricing Request</label>
    <nameField>
        <displayFormat>SPR-{00}</displayFormat>
        <label>SPR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New Special Pricing Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Additional_Disc_on_APPL_disc2__c.field-meta.xml
<CustomField>
    <fullName>Additional_Disc_on_APPL_disc2__c</fullName>
    <description>A number field but if want to use it then please consider this as a Percent and do the required calculations</description>
    <formula>((MRP_Post_Discount2__c -  Net_Invoice_Value_from_APPL2__c ) /  MRP_Post_Discount2__c)*100</formula>
    <label>Additional Disc on APPL disc2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/APPL__c.field-meta.xml
<CustomField>
    <fullName>APPL__c</fullName>
    <label>APPL Discount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Approval_Rejection_Date__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rejection_Date__c</fullName>
    <formula>Unique_SPR__r.Approved_Rejected_Date__c</formula>
    <label>Approval/Rejection Date</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <formula>text(Unique_SPR__r.Approval_Status__c)</formula>
    <label>Approval Status</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Approver_Comments__c.field-meta.xml
<CustomField>
    <fullName>Approver_Comments__c</fullName>
    <description>This field captures the latest comment by the approver</description>
    <label>Approver Comments</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/CTC_Value__c.field-meta.xml
<CustomField>
    <fullName>CTC_Value__c</fullName>
    <description>CTC Calculation</description>
    <formula>( MRP_Value__c -  Net_Invoice_Value_from_APPL2__c )/ MRP_Value__c</formula>
    <label>CTC Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Discounted_Price2__c.field-meta.xml
<CustomField>
    <fullName>Discounted_Price2__c</fullName>
    <formula>IF( ISBLANK(Extra_Discount__c),
MRP_Post_Discount2__c ,
ABS( (MRP_Value__c) - ( Extra_Discount__c * MRP_Value__c)))</formula>
    <label>Discounted Price2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Extra_Discount__c.field-meta.xml
<CustomField>
    <fullName>Extra_Discount__c</fullName>
    <label>Extra Discount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/MRP_Post_Discount2__c.field-meta.xml
<CustomField>
    <fullName>MRP_Post_Discount2__c</fullName>
    <formula>(MRP_Value__c)-( APPL__c * MRP_Value__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MRP Post Discount2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Net_Invoice_Value_from_APPL2__c.field-meta.xml
<CustomField>
    <fullName>Net_Invoice_Value_from_APPL2__c</fullName>
    <description>The net invoice value from APPL</description>
    <formula>If( ISBLANK(ORC_MARGIN_TO_DLR_DIST__c ), Discounted_Price2__c , ABS(((100 - (ORC_MARGIN_TO_DLR_DIST__c * 100))/100) * Discounted_Price2__c))</formula>
    <label>Net Invoice Value from APPL2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Product_name__c.field-meta.xml
<CustomField>
    <fullName>Product_name__c</fullName>
    <label>Product name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup to opportunity (Project ) object</description>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>New Special Pricing Requests</relationshipLabel>
    <relationshipName>New_Special_Pricing_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <description>This field is used for storing the name that is collectively given for each line item</description>
    <label>Unique Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Unique_SPR__c.field-meta.xml
<CustomField>
    <fullName>Unique_SPR__c</fullName>
    <description>related to the unique spr.</description>
    <label>Unique SPR</label>
    <referenceTo>Unique_SPR__c</referenceTo>
    <relationshipLabel>New Special Pricing Requests</relationshipLabel>
    <relationshipName>New_Special_Pricing_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/Unique_SPR__c.object-meta.xml
<CustomObject>
    <description>This object contains the unique name of each spr. Uniqueness is valid for a specific project. This record goes for approval in the new revamp structure.</description>
    <label>Unique SPR</label>
    <nameField>
        <displayFormat>UN-{000}</displayFormat>
        <label>Unique Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unique SPRs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Number_of_SPR_s__c.field-meta.xml
<CustomField>
    <fullName>Number_of_SPR_s__c</fullName>
    <description>count the number of spr under a particular record</description>
    <label>Number of SPR&apos;s</label>
    <summaryForeignKey>New_Special_Pricing_Request__c.Unique_SPR__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Unique SPRs</relationshipLabel>
    <relationshipName>Unique_SPRs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <label>Unique Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/EditSprByManagerController.cls
/*****************************************************************************************************************************
 Created By     :Subhajit Ghosh
Created Date    :25-Sept-2019
Modified Date   :
Version         :1.0
Description     :Controller of EditSprByManager Page. This class is used for editing the records in the offer section by the manager and sys admin only.

****************************************************************************************************************************/
global class EditSprByManagerController {
    public List<New_Special_Pricing_Request__c> newsprUpdateList{get;set;}
    public String uniqueSprId{get;set;}
    public String oppProId{get;set;}
    public String UniqueSPRName{get;set;}
    public String ProductName{get;set;}//to get history
    public EditSprByManagerController(){
        uniqueSprId=Apexpages.currentPage().getParameters().get('id');
        oppProId=Apexpages.currentPage().getParameters().get('projectId');
        newsprUpdateList=new List<New_Special_Pricing_Request__c>();
        UniqueSPRName='';
        if(uniqueSprId!=NULL){
            newsprUpdateList=[SELECT ID,Product_name__c,APPL__c,CTC_Value__c,Discounted_Price2__c,Additional_Disc_on_APPL_disc2__c,Extra_Discount__c,MRP_Value__c,
                              MRP_Post_Discount2__c,Net_Invoice_Value_from_APPL2__c,Unique_SPR__c,Unique_SPR__r.Unique_Name__c,
                              ORC_MARGIN_TO_DLR_DIST__c,Project__c,Validity_for_the_Price__c 
                              FROM New_Special_Pricing_Request__c WHERE Unique_SPR__r.Number_of_SPR_s__c>=:1
                              AND Unique_SPR__c=:uniqueSprId AND (Approval_Status__c='Pending' OR Approval_Status__c='Approved')];
            UniqueSPRName=newsprUpdateList[0].Unique_SPR__r.Unique_Name__c;
        }
        
        
    }
    public PageReference saveUpdatedOffers() { 
        try{
            upsert newsprUpdateList;
            PageReference pf = new PageReference('/'+oppProId);
            return pf;
        }
        catch(Exception e){
            system.debug('in exception block');
            PageReference pf = new PageReference('/'+oppProId);
            return pf;
        }
        
        
    }
    public PageReference cancelEdit() { 
        try{
            
            PageReference pf = new PageReference('/'+oppProId);
            return pf;
        }
        catch(Exception e){
            system.debug('in exception block');
            PageReference pf = new PageReference('/'+oppProId);
            return pf;
        }
        
        
    }
    @RemoteAction
    global static  List<New_Special_Pricing_Request__c> getApprovalHistory(String nm,String proId){
        try{
            List<New_Special_Pricing_Request__c>  newsprHistoryList=new List<New_Special_Pricing_Request__c>();
        String ProductName=nm;
        String oppProId=proId;
        system.debug('called from javascript-----------------'+ProductName);
    system.debug('called from javascript-----------------'+oppProId);
        newsprHistoryList=[SELECT ID,Product_name__c,APPL__c,CTC_Value__c,Discounted_Price2__c,Additional_Disc_on_APPL_disc2__c,Extra_Discount__c,MRP_Value__c,
                              MRP_Post_Discount2__c,Net_Invoice_Value_from_APPL2__c,Unique_SPR__c,Unique_SPR__r.Unique_Name__c,
                              ORC_MARGIN_TO_DLR_DIST__c,Project__c,Validity_for_the_Price__c,Approval_Status__c,Unique_SPR__r.Approver_Comments__c 
                              FROM New_Special_Pricing_Request__c WHERE Unique_SPR__r.Number_of_SPR_s__c>=:1
                              AND Project__c=:oppProId AND Product_name__c=:ProductName AND (Approval_Status__c='Approved' OR Approval_Status__c='Rejected') ORDER BY Approval_Rejection_Date__c  DESC LIMIT 5];
        
       
            system.debug('newsprHistoryList---'+newsprHistoryList);
            return newsprHistoryList;
             
    }
        catch(exception e){
            system.debug('exception occured'+e.getMessage());
             system.debug('exception occured'+e.getLineNumber());
            return null;
        }
        }
       
   
}