Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/New_Special_Pricing_Request__c.object-meta.xml
<CustomObject>
    <description>This object stores all the line items that are checked and sent for SPR. The group of items that are selected goes for SPR everytime the project is sent for approval.</description>
    <label>New Special Pricing Request</label>
    <nameField>
        <displayFormat>SPR-{00}</displayFormat>
        <label>SPR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New Special Pricing Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/APPL__c.field-meta.xml
<CustomField>
    <fullName>APPL__c</fullName>
    <label>APPL Discount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <formula>text(Unique_SPR__r.Approval_Status__c)</formula>
    <label>Approval Status</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Extra_Discount__c.field-meta.xml
<CustomField>
    <fullName>Extra_Discount__c</fullName>
    <label>Extra Discount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Net_Invoice_Value_from_APPL2__c.field-meta.xml
<CustomField>
    <fullName>Net_Invoice_Value_from_APPL2__c</fullName>
    <description>The net invoice value from APPL</description>
    <formula>If( ISBLANK(ORC_MARGIN_TO_DLR_DIST__c ), Discounted_Price2__c , ABS(((100 - (ORC_MARGIN_TO_DLR_DIST__c * 100))/100) * Discounted_Price2__c))</formula>
    <label>Net Invoice Value from APPL2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Product_name__c.field-meta.xml
<CustomField>
    <fullName>Product_name__c</fullName>
    <label>Product name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup to opportunity (Project ) object</description>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>New Special Pricing Requests</relationshipLabel>
    <relationshipName>New_Special_Pricing_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <description>This field is used for storing the name that is collectively given for each line item</description>
    <label>Unique Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Unique_SPR__c.field-meta.xml
<CustomField>
    <fullName>Unique_SPR__c</fullName>
    <description>related to the unique spr.</description>
    <label>Unique SPR</label>
    <referenceTo>Unique_SPR__c</referenceTo>
    <relationshipLabel>New Special Pricing Requests</relationshipLabel>
    <relationshipName>New_Special_Pricing_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/Unique_SPR__c.object-meta.xml
<CustomObject>
    <description>This object contains the unique name of each spr. Uniqueness is valid for a specific project. This record goes for approval in the new revamp structure.</description>
    <label>Unique SPR</label>
    <nameField>
        <displayFormat>UN-{000}</displayFormat>
        <label>Unique Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unique SPRs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Approval_date__c.field-meta.xml
<CustomField>
    <fullName>Approval_date__c</fullName>
    <label>Approval date</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Unique SPRs</relationshipLabel>
    <relationshipName>Unique_SPRs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Project_Number__c.field-meta.xml
<CustomField>
    <fullName>Project_Number__c</fullName>
    <formula>Project__r.Project_Number__c</formula>
    <label>Project Number</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <label>Unique Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/WS_SPR_Details.cls
@RestResource(urlMapping='/getSprDetails')
global with sharing class WS_SPR_Details { 
    @HttpGet
    global static Response getSprDetails() {
        Response resObj = new Response();
        List<Opportunity> projList = new List<Opportunity>();
        List<Unique_SPR__c> sprList = new List<Unique_SPR__c>();
        List<SPRWrap> sprWrapList = new List<SPRWrap>();
        List<String> prodNameList = new List<String>();
        Map<String,Product2> prdNameValueMap = new Map<String,Product2>();
        List<Product2> prodList = new List<Product2>();
        resObj.SPR_Details = sprWrapList;
        String startDateString = System.Label.SprAPI_StartDate;
        String endDateString = System.Label.SprAPI_EndDate;
        Date startDate;
        Date endDate;
        if(startDateString != 'N/A' && endDateString != 'N/A'){
            startDate = Date.valueOf(startDateString);
            endDate = Date.valueOf(endDateString);            
            sprList = [SELECT Id,Unique_Name__c,Project__r.SAP_ID__c,Project__r.Project_Number__c,
                       (Select Id,Extra_Discount__c,Product_name__c,APPL__c,ORC_MARGIN_TO_DLR_DIST__c,Validity_for_the_Price__c,Net_Invoice_Value_from_APPL2__c FROM New_Special_Pricing_Requests__r) FROM Unique_SPR__c WHERE Approval_Status__c = 'Approved'AND Approval_date__c>= :startDate AND Approval_date__c<= :endDate]; 
        }else{
            sprList = [SELECT Id,Unique_Name__c,Project__r.SAP_ID__c,Project__r.Project_Number__c,
                       (Select Id,Extra_Discount__c,Product_name__c,APPL__c,ORC_MARGIN_TO_DLR_DIST__c,Validity_for_the_Price__c,Net_Invoice_Value_from_APPL2__c FROM New_Special_Pricing_Requests__r) FROM Unique_SPR__c WHERE Approval_Status__c = 'Approved'AND Approval_date__c= TODAY];   
        }
        for(Unique_SPR__c uqSPR : sprList){
            for(New_Special_Pricing_Request__c newSPR : uqSPR.New_Special_Pricing_Requests__r){
                if(newSPR.Product_name__c != null)
                    prodNameList.add(newSPR.Product_name__c);
            }
        }
        if(prodNameList.size() > 0)
            prodList = [SELECT Id,Name,ProductCode,Product_Group_Code__c,Product_Group_Description__c,Family,Product_Category_Code_Discount_Group__c,Product_Category_Description_Discount__c FROM Product2 WHERE Product_Category_Description_Discount__c IN :prodNameList];
        for(Product2 prodObj : prodList){
            prdNameValueMap.put(prodObj.Product_Category_Description_Discount__c,prodObj);
        }
        for(Unique_SPR__c uqSPR : sprList){
            List<SPRPricingWrap> sprPricingWrapList = new List<SPRPricingWrap>();
            SPRWrap sprDet = new SPRWrap();
            sprDet.distributorCode = uqSPR.Project__r.SAP_ID__c!= null ? uqSPR.Project__r.SAP_ID__c : '';
            sprDet.sprNumber = uqSPR.Unique_Name__c != null ? uqSPR.Unique_Name__c : '';
            sprDet.projNumber = uqSPR.Project__r.Project_Number__c != null ? uqSPR.Project__r.Project_Number__c : '';
            
            for(New_Special_Pricing_Request__c newSPR : uqSPR.New_Special_Pricing_Requests__r){
                if(newSPR.Extra_Discount__c != null && newSPR.ORC_MARGIN_TO_DLR_DIST__c != null && newSPR.Extra_Discount__c != 0 && newSPR.ORC_MARGIN_TO_DLR_DIST__c != 0){
                    SPRPricingWrap sprPricingDet = new SPRPricingWrap();
                    List<ProdDescription> prodDetails = new List<ProdDescription>();
                    System.debug(newSPR.Product_name__c);
                    System.debug(prdNameValueMap.get(newSPR.Product_name__c));
                    sprPricingDet.prodCode = prdNameValueMap.get(newSPR.Product_name__c) != null && prdNameValueMap.get(newSPR.Product_name__c).ProductCode != null ? Decimal.valueOf(prdNameValueMap.get(newSPR.Product_name__c).ProductCode) :null;
                    sprPricingDet.prodGroupCode = prdNameValueMap.get(newSPR.Product_name__c) != null && prdNameValueMap.get(newSPR.Product_name__c).Product_Group_Code__c != null ? prdNameValueMap.get(newSPR.Product_name__c).Product_Group_Code__c : '' ;
                    sprPricingDet.prodGroupDesc = prdNameValueMap.get(newSPR.Product_name__c) != null && prdNameValueMap.get(newSPR.Product_name__c).Product_Group_Description__c != null ? prdNameValueMap.get(newSPR.Product_name__c).Product_Group_Description__c : '';
                    sprPricingDet.prodCatCode = prdNameValueMap.get(newSPR.Product_name__c) != null && prdNameValueMap.get(newSPR.Product_name__c).Product_Category_Code_Discount_Group__c != null ? Decimal.valueOf(prdNameValueMap.get(newSPR.Product_name__c).Product_Category_Code_Discount_Group__c) : null;
                    sprPricingDet.prodCatDesc = prdNameValueMap.get(newSPR.Product_name__c) != null && prdNameValueMap.get(newSPR.Product_name__c).Product_Category_Description_Discount__c != null ? prdNameValueMap.get(newSPR.Product_name__c).Product_Category_Description_Discount__c : '';
                    
                    sprPricingDet.stdDiscount = newSPR.APPL__c;
                    sprPricingDet.sprDiscount = newSPR.Extra_Discount__c != null ? newSPR.Extra_Discount__c : 0;
                    sprPricingDet.orcPercentage = newSPR.ORC_MARGIN_TO_DLR_DIST__c != null ? newSPR.ORC_MARGIN_TO_DLR_DIST__c : 0;
                    sprPricingDet.validity = newSPR.Validity_for_the_Price__c != null ? newSPR.Validity_for_the_Price__c.format() : '';
                    sprPricingDet.netInvoice = newSPR.Net_Invoice_Value_from_APPL2__c != null ? newSPR.Net_Invoice_Value_from_APPL2__c :0;
                    //sprPricingDet.prodDetails = prodDetails;
                    sprPricingWrapList.add(sprPricingDet);
                }
            }
            sprDet.pricingDetails = sprPricingWrapList;
            sprWrapList.add(sprDet);
        }
        RETURN resObj;
    }
    global class Response{
        List<SPRWrap> SPR_Details = new List<SPRWrap>();
    }
    global class SPRWrap{
        String distributorCode;
        String sprNumber;
        String projNumber;
        List<SPRPricingWrap> pricingDetails;
    }
    global class SPRPricingWrap{
        Decimal prodCode;
        String prodGroupCode;
        String prodGroupDesc;
        Decimal prodCatCode;
        String prodCatDesc;
        Decimal stdDiscount;
        Decimal sprDiscount;
        Decimal orcPercentage;
        String validity;
        Decimal netInvoice;
        //List<ProdDescription> prodDetails;
    }
    global class ProdDescription{
        Decimal prodCode;
        String prodName;
        String prodDesc;
    }
}