Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/New_Special_Pricing_Request__c.object-meta.xml
<CustomObject>
    <description>This object stores all the line items that are checked and sent for SPR. The group of items that are selected goes for SPR everytime the project is sent for approval.</description>
    <label>New Special Pricing Request</label>
    <nameField>
        <displayFormat>SPR-{00}</displayFormat>
        <label>SPR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New Special Pricing Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Additional_Disc_on_APPL_disc2__c.field-meta.xml
<CustomField>
    <fullName>Additional_Disc_on_APPL_disc2__c</fullName>
    <description>A number field but if want to use it then please consider this as a Percent and do the required calculations</description>
    <formula>((MRP_Post_Discount2__c -  Net_Invoice_Value_from_APPL2__c ) /  MRP_Post_Discount2__c)*100</formula>
    <label>Additional Disc on APPL disc2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/APPL__c.field-meta.xml
<CustomField>
    <fullName>APPL__c</fullName>
    <label>APPL Discount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/CTC_Value__c.field-meta.xml
<CustomField>
    <fullName>CTC_Value__c</fullName>
    <description>CTC Calculation</description>
    <formula>( MRP_Value__c -  Net_Invoice_Value_from_APPL2__c )/ MRP_Value__c</formula>
    <label>CTC Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Discounted_Price2__c.field-meta.xml
<CustomField>
    <fullName>Discounted_Price2__c</fullName>
    <formula>IF( ISBLANK(Extra_Discount__c),
MRP_Post_Discount2__c ,
ABS( (MRP_Value__c) - ( Extra_Discount__c * MRP_Value__c)))</formula>
    <label>Discounted Price2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Extra_Discount__c.field-meta.xml
<CustomField>
    <fullName>Extra_Discount__c</fullName>
    <label>Extra Discount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Loss_to_brand__c.field-meta.xml
<CustomField>
    <fullName>Loss_to_brand__c</fullName>
    <label>Lost to brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACO</fullName>
            </value>
            <value>
                <fullName>Ajay NA</fullName>
            </value>
            <value>
                <fullName>Arecon</fullName>
            </value>
            <value>
                <fullName>Astral</fullName>
            </value>
            <value>
                <fullName>Cosmoplast</fullName>
            </value>
            <value>
                <fullName>Finolex</fullName>
            </value>
            <value>
                <fullName>Geberit</fullName>
            </value>
            <value>
                <fullName>George Fischer</fullName>
            </value>
            <value>
                <fullName>Hindware</fullName>
            </value>
            <value>
                <fullName>Jain Pipes</fullName>
            </value>
            <value>
                <fullName>Jaquar</fullName>
            </value>
            <value>
                <fullName>Kissan</fullName>
            </value>
            <value>
                <fullName>Kohler</fullName>
            </value>
            <value>
                <fullName>Oriplast</fullName>
            </value>
            <value>
                <fullName>Parryware</fullName>
            </value>
            <value>
                <fullName>Poloplast</fullName>
            </value>
            <value>
                <fullName>Prince</fullName>
            </value>
            <value>
                <fullName>Rakhsha</fullName>
            </value>
            <value>
                <fullName>Supreme</fullName>
            </value>
            <value>
                <fullName>Valsir</fullName>
            </value>
            <value>
                <fullName>Viega</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/MRP_Post_Discount2__c.field-meta.xml
<CustomField>
    <fullName>MRP_Post_Discount2__c</fullName>
    <formula>(MRP_Value__c)-( APPL__c * MRP_Value__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MRP Post Discount2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Net_Invoice_Value_from_APPL2__c.field-meta.xml
<CustomField>
    <fullName>Net_Invoice_Value_from_APPL2__c</fullName>
    <description>The net invoice value from APPL</description>
    <formula>If( ISBLANK(ORC_MARGIN_TO_DLR_DIST__c ), Discounted_Price2__c , ABS(((100 - (ORC_MARGIN_TO_DLR_DIST__c * 100))/100) * Discounted_Price2__c))</formula>
    <label>Net Invoice Value from APPL2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Offer_Probability__c.field-meta.xml
<CustomField>
    <fullName>Offer_Probability__c</fullName>
    <label>Offer Probability</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>&lt;50%</fullName>
            </value>
            <value>
                <fullName>60%</fullName>
            </value>
            <value>
                <fullName>70%</fullName>
            </value>
            <value>
                <fullName>80%</fullName>
            </value>
            <value>
                <fullName>90%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Others_Lost_Sales__c.field-meta.xml
<CustomField>
    <fullName>Others_Lost_Sales__c</fullName>
    <description>reason for lost sales</description>
    <label>Others</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Product_name__c.field-meta.xml
<CustomField>
    <fullName>Product_name__c</fullName>
    <label>Product name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <label>Product Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Win</fullName>
            </value>
            <value>
                <fullName>Loss</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup to opportunity (Project ) object</description>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>New Special Pricing Requests</relationshipLabel>
    <relationshipName>New_Special_Pricing_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Reason_of_lost_sales__c.field-meta.xml
<CustomField>
    <fullName>Reason_of_lost_sales__c</fullName>
    <label>Reason of lost sales</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Competition offered lower pricing</fullName>
            </value>
            <value>
                <fullName>Product unavailable</fullName>
            </value>
            <value>
                <fullName>Party demanding higher credit period</fullName>
            </value>
            <value>
                <fullName>Party is bad paymaster</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Tentative_Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Tentative_Order_Date__c</fullName>
    <label>Tentative Order Date</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <description>This field is used for storing the name that is collectively given for each line item</description>
    <label>Unique Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/New_Special_Pricing_Request__c/fields/Unique_SPR__c.field-meta.xml
<CustomField>
    <fullName>Unique_SPR__c</fullName>
    <description>related to the unique spr.</description>
    <label>Unique SPR</label>
    <referenceTo>Unique_SPR__c</referenceTo>
    <relationshipLabel>New Special Pricing Requests</relationshipLabel>
    <relationshipName>New_Special_Pricing_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/Unique_SPR__c.object-meta.xml
<CustomObject>
    <description>This object contains the unique name of each spr. Uniqueness is valid for a specific project. This record goes for approval in the new revamp structure.</description>
    <label>Unique SPR</label>
    <nameField>
        <displayFormat>UN-{000}</displayFormat>
        <label>Unique Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unique SPRs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Number_of_SPR_s__c.field-meta.xml
<CustomField>
    <fullName>Number_of_SPR_s__c</fullName>
    <description>count the number of spr under a particular record</description>
    <label>Number of SPR&apos;s</label>
    <summaryForeignKey>New_Special_Pricing_Request__c.Unique_SPR__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Unique SPRs</relationshipLabel>
    <relationshipName>Unique_SPRs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <label>Unique Name</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/EditOfferRevampController.cls
/*****************************************************************************************************************************************
*Created By:  Subhajit Ghosh
*Company:     KVP
*Created Date : 23.09.2019
*Description: This page is for edit of offers in the new project revamp structure. VF- EditOfferRevampSection
*Test:        EditOfferRevampControllerTest
***********************************************************************************************************************************/

public class EditOfferRevampController {
    
    public List<New_Special_Pricing_Request__c> newsprUpdateList{get;set;}
    public String uniqueSprId{get;set;}
    public String oppProId{get;set;}
    public EditOfferRevampController(){
        uniqueSprId=Apexpages.currentPage().getParameters().get('id');
        system.debug('uniqueSprId--'+uniqueSprId);
        oppProId=Apexpages.currentPage().getParameters().get('projectId');
        newsprUpdateList=new List<New_Special_Pricing_Request__c>();
        
        if(uniqueSprId!=NULL){
            newsprUpdateList=[SELECT ID,Product_name__c,APPL__c,CTC_Value__c,Discounted_Price2__c,Additional_Disc_on_APPL_disc2__c,Extra_Discount__c,MRP_Value__c,
                              MRP_Post_Discount2__c,Net_Invoice_Value_from_APPL2__c,Unique_SPR__c,Unique_SPR__r.Unique_Name__c,
                              ORC_MARGIN_TO_DLR_DIST__c,Project__c,Validity_for_the_Price__c,Product_Status__c,Others_Lost_Sales__c,
                              Loss_to_brand__c,Reason_of_lost_sales__c,Reason__c,Offer_Probability__c,Tentative_Order_Date__c,Price_List_Date__c 
                              FROM New_Special_Pricing_Request__c WHERE Unique_SPR__r.Number_of_SPR_s__c>=:1
                              AND Unique_SPR__c=:uniqueSprId AND Product_Status__c != 'Loss']; 
            system.debug('newsprUpdateList---'+newsprUpdateList);
            system.debug('newsprUpdateList---'+newsprUpdateList.size());
        }
        
        
    }
    public PageReference saveUpdatedOffers() { 
        try{
            
            Integer orderLoss=0;
            Integer otherLossReason=0;
            integer orderWin=0;
            integer selectPrevDates=0;
            system.debug('newsprUpdateList----'+newsprUpdateList);
             for(New_Special_Pricing_Request__c newOff:newsprUpdateList){
            if(newOff.Product_Status__c=='Loss' && (newOff.Loss_to_brand__c==NULL || newOff.Reason_of_lost_sales__c==NULL)){
              ApexPages.Message theMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'If Product Status is Loss then please fill the Lost to brand and Reason for lost sales');
            ApexPages.addMessage(theMessage);
            return null;   
            }
            if(newOff.Product_Status__c=='Loss' && newOff.Reason_of_lost_sales__c=='Others' && newOff.Others_Lost_Sales__c==NULL){
               ApexPages.Message theMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'If Reason for lost sales is others then please fill the Others(Reason) field next to it');
            ApexPages.addMessage(theMessage);
            // new myException('Please fill the extra discount field in order to submit it for special pricing request for the selected products');
            return null;
            }
            if((newOff.Product_Status__c=='Win' || newOff.Product_Status__c==NULL) && (newOff.Loss_to_brand__c!=NULL || newOff.Reason_of_lost_sales__c!=NULL || newOff.Others_Lost_Sales__c!=NULL) ){
               ApexPages.Message theMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'If Product status is Win/--None-- then Lost to brand,Reason Of Lost Sales, Others(Reason) must be empty');
            ApexPages.addMessage(theMessage);
            return null;
            }
            
             } 
            
            upsert newsprUpdateList;
            PageReference pf = new PageReference('/'+oppProId);
            return pf;
        }
        catch(Exception e){
            system.debug('in exception block');
            PageReference pf = new PageReference('/'+oppProId);
            return pf;
        }
        
        
    }
    public PageReference cancelEdit() { 
        try{
            
            PageReference pf = new PageReference('/'+oppProId);
            return pf;
        }
        catch(Exception e){
            system.debug('in exception block');
            PageReference pf = new PageReference('/'+oppProId);
            return pf;
        }
        
        
    }
    
}