Partial_14Dec2021/force-app/main/default/objects/Influencer__c/Influencer__c.object-meta.xml
<CustomObject>
    <label>Influencer</label>
    <nameField>
        <displayFormat>INF-{0000}</displayFormat>
        <label>Influencer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Influencer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Influencer</relationshipLabel>
    <relationshipName>Influencer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/OpportunitySearchController_UT.cls
@isTest
public class OpportunitySearchController_UT{

static testMethod void testMethod1(){
test.StartTest();

Opportunity opp=new Opportunity();
opp.Name='test';
opp.StageName='Designing';
Date myDate=date.newInstance(2015,12,31);
opp.CloseDate=myDate;
insert opp;

Influencer__c influencer=new Influencer__c();
influencer.Opportunity__c=opp.id;

OpportunitySearchController oppSearch=new OpportunitySearchController(new ApexPages.StandardController(new Account()));
oppSearch.searchInflu();


test.StopTest();

}

}