Partial_14Dec2021/force-app/main/default/objects/Influencer__c/Influencer__c.object-meta.xml
<CustomObject>
    <label>Influencer</label>
    <nameField>
        <displayFormat>INF-{0000}</displayFormat>
        <label>Influencer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Influencer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual Contacts</value>
        </filterItems>
        <filterItems>
            <field>Account.Party_Type__c</field>
            <operation>equals</operation>
            <value>Architect, Contractor, Plumbing Contractor, Project Manager, Purchase Manager, Site Engineer, Project Owner/Developer, Plumbing Consultant, Consultant</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Influencer</relationshipLabel>
    <relationshipName>Influencer</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Influencer</relationshipLabel>
    <relationshipName>Influencer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/OpportunitySearchController.cls
public class OpportunitySearchController {

private ApexPages.StandardController controller {get; set;}
    // the actual account
    private Account a;
    public boolean display{get;set;}
    // the results from the search.
    public List<Influencer__c> searchResults {get;set;}

  public OpportunitySearchController(ApexPages.StandardController controller) {

        //initialize the stanrdard controller
        this.controller = controller;
        this.a = (Account)controller.getRecord();
        display = true;
        searchInflu();

    }
   public void searchInflu(){
    display = true;
    searchResults =[select id,Opportunity__r.Name, Opportunity__r.Approximate_Project_Value__c,Opportunity__r.Project_District__c,Opportunity__r.CreatedDate from Influencer__c where Account__r.Id=:a.id];
   
    if(searchResults.isEmpty()){
     display = false;
      ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Info,'No results found')); 
    }
   }
}