Partial_14Dec2021/force-app/main/default/objects/Influencer__c/Influencer__c.object-meta.xml
<CustomObject>
    <label>Influencer</label>
    <nameField>
        <displayFormat>INF-{0000}</displayFormat>
        <label>Influencer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Influencer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Individual Contacts</value>
        </filterItems>
        <filterItems>
            <field>Account.Party_Type__c</field>
            <operation>equals</operation>
            <value>Architect, Contractor, Plumbing Contractor, Project Manager, Purchase Manager, Site Engineer, Project Owner/Developer, Plumbing Consultant, Consultant</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Influencer</relationshipLabel>
    <relationshipName>Influencer</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Influencer_Type__c.field-meta.xml
<CustomField>
    <fullName>Influencer_Type__c</fullName>
    <label>Influencer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Plumber</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Project Owner/Developer/Builder</fullName>
            </value>
            <value>
                <fullName>Purchase Manager</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Site Engineer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Plumbing Consultant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Influencer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Influencer</relationshipLabel>
    <relationshipName>Influencer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Special Pricing Request</label>
    <nameField>
        <displayFormat>ON-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Pricing Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Order__c/fields/Order_Value__c.field-meta.xml
<CustomField>
    <fullName>Order_Value__c</fullName>
    <label>Total MRP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>20% advance with PO</fullName>
            </value>
            <value>
                <fullName>30 Days credit with PO</fullName>
            </value>
            <value>
                <fullName>90 Days credit with PO</fullName>
            </value>
            <value>
                <fullName>100% Payment against Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Project_Tracker__c/Project_Tracker__c.object-meta.xml
<CustomObject>
    <label>Project Tracker</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Project Tracker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Project_Tracker__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Tracker</relationshipLabel>
    <relationshipName>Project_Tracker</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Supply__c/Supply__c.object-meta.xml
<CustomObject>
    <label>Supply</label>
    <nameField>
        <displayFormat>Supply-{00000000}</displayFormat>
        <label>Supply Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Supply__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Supplies</relationshipLabel>
    <relationshipName>Supplies</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Supply__c/fields/ParentSupplyFlag__c.field-meta.xml
<CustomField>
    <fullName>ParentSupplyFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ParentSupplyFlag</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Supply__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Supplies</relationshipLabel>
    <relationshipName>Supplies</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/SupplyLineItem__c.object-meta.xml
<CustomObject>
    <label>SupplyLineItem</label>
    <nameField>
        <displayFormat>SupplyItem-{0000000000}</displayFormat>
        <label>SupplyLineItem Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SupplyLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SupplyLineItems</relationshipLabel>
    <relationshipName>SupplyLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/ORC_Markup__c.field-meta.xml
<CustomField>
    <fullName>ORC_Markup__c</fullName>
    <label>ORC/Markup</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/ORC_Status__c.field-meta.xml
<CustomField>
    <fullName>ORC_Status__c</fullName>
    <label>ORC Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Order Received</fullName>
            </value>
            <value>
                <fullName>Part Received</fullName>
            </value>
            <value>
                <fullName>Order Lost</fullName>
            </value>
            <value>
                <fullName>Order Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Order_Value__c.field-meta.xml
<CustomField>
    <fullName>Order_Value__c</fullName>
    <label>Supply Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/OrderLineItem__c.field-meta.xml
<CustomField>
    <fullName>OrderLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>SupplyLineItems</relationshipLabel>
    <relationshipName>SupplyLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100% advance with PO</fullName>
            </value>
            <value>
                <fullName>20% advance &amp; Balance against Delivery</fullName>
            </value>
            <value>
                <fullName>30 days after delivery</fullName>
            </value>
            <value>
                <fullName>45 days after delivery</fullName>
            </value>
            <value>
                <fullName>60 days after delivery</fullName>
            </value>
            <value>
                <fullName>90 days after delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>SupplyLineItems</relationshipLabel>
    <relationshipName>SupplyLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>SupplyLineItems</relationshipLabel>
    <relationshipName>SupplyLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Supply_Status__c.field-meta.xml
<CustomField>
    <fullName>Supply_Status__c</fullName>
    <label>Supply Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fully Received</fullName>
            </value>
            <value>
                <fullName>Part Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/SupplyDetails__c.field-meta.xml
<CustomField>
    <fullName>SupplyDetails__c</fullName>
    <label>Supply</label>
    <referenceTo>Supply__c</referenceTo>
    <relationshipLabel>SupplyLineItems</relationshipLabel>
    <relationshipName>SupplyLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/SupplyLineItem__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Boxes</fullName>
            </value>
            <value>
                <fullName>Mtrs</fullName>
            </value>
            <value>
                <fullName>No.&apos;s</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Architects_Meet__c.field-meta.xml
<CustomField>
    <fullName>Architects_Meet__c</fullName>
    <label>Architects Meets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Boarers_Meet__c.field-meta.xml
<CustomField>
    <fullName>Boarers_Meet__c</fullName>
    <label>Boarers Meets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Builders_Meet__c.field-meta.xml
<CustomField>
    <fullName>Builders_Meet__c</fullName>
    <label>Builders Meets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Column_Dealer_Meet__c.field-meta.xml
<CustomField>
    <fullName>Column_Dealer_Meet__c</fullName>
    <label>Column Dealer / Distributor Meets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Projects</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/classes/Initial_Test_Data.cls
/*******************XXX**********************************

Created By      :Mohd.Numaan Ahmed
Created Date    :24-Jan-2015
Modified Date   :
Version         :1.0
Description     :Initial Test Data for test classes

********************XXX***********************************/

/*
    0.User
    1.Account
    2.Project(Opportunity)
    3.OpportunityLineItems
    4.Product2
    5.pricebookentry
    6.Influencer
    7.Project Tracker
    8.Pricebook2

*/
@isTest
public class Initial_Test_Data {
    
    //User
    public static User createUser(String LName ,String FName,String profileName){
        
        Profile p = [SELECT Id, Name FROM Profile WHERE Name =: profileName]; 
        User userData = new User(Alias = 'standt1', 
                                  Email= FName+LName+'@TestUser.com', 
                                  EmailEncodingKey='UTF-8', 
                                  FirstName = FName,
                                  LastName = LName, 
                                  LanguageLocaleKey='en_US', 
                                  LocaleSidKey='en_AU', 
                                  ProfileId = p.Id, 
                                  TimeZoneSidKey='Australia/Sydney', 
                                  UserName= FName+LName+'@TestUser.com',
                                  EmployeeNumber = 'Test'
                                  );
        return userData; 
    }



    public static Account createAccount(String name,String recordTypeName) {
        Id recordTId  = [select id from RecordType where SobjectType = 'Account' AND Name =:recordTypeName].id;
        Account newAccount = new Account(
                                Name  = name,
                                BillingState = 'Gujarat',
                                BillingStreet = 'Abc Street',
                                BillingCity = 'Abc City',
                                BillingCountry = 'India',
                                RecordTypeId = recordTId,
                                AccountNumber = '12345'
                                );

        return newAccount;
    }
    //Project 
    public static Opportunity createNewProject(String projectName,String projType,Id accoId,String stag) {  
        //Id recordTypeId  = [select id from RecordType where SobjectType = 'Opportunity' AND DeveloperName='New_Project'].id;
        Opportunity newNewProject =  new Opportunity(
                                   
                                    Name=projectName,
                                    Project_Type__c = projType,
                                    CloseDate = date.today(),
                                    No_of_Bathrooms__c = 100,
                                    StageName = stag,
                                    Project_By__c = accoId
                                    );
        return newNewProject; 
    }

    //OpportunityLineItem 
    public static OpportunityLineItem createOppLineItem(Id oppId,String aType,Id priceb) {  
        //Id recordTypeId  = [select id from RecordType where SobjectType = 'Opportunity' AND DeveloperName='New_Project'].id;
        OpportunityLineItem oppLineItem =  new OpportunityLineItem(
                                  
                                    OpportunityId = oppId,
                                    UnitPrice = 0,
                                    APPL_Type__c = aType,
                                    PricebookEntryId = priceb,
                                    Quantity = 2,
                                    Probability_MRP__c = null,
                                    Unit__c = null,
                                    Product_Specified__c = 'Yes'
                                    
                                    );
        
        return oppLineItem; 
    }

    //OpportunityLineItem 
    public static OpportunityLineItem createOppLineItemYes(Id oppId,String aType,Id priceb) {  
        //Id recordTypeId  = [select id from RecordType where SobjectType = 'Opportunity' AND DeveloperName='New_Project'].id;
        OpportunityLineItem oppLineItem =  new OpportunityLineItem(
                                  
                                    OpportunityId = oppId,
                                    UnitPrice = 0,
                                    APPL_Type__c = aType,
                                    PricebookEntryId = priceb,
                                    Quantity = 2,
                                    Probability_MRP__c = null,
                                    Unit__c = null,
                                    Probability_Validation__c = 'Yes'
                                    
                                    );
        
        return oppLineItem; 
    }
    public static OpportunityLineItem createOppLineItemNo(Id oppId,String aType,Id priceb) {  
        //Id recordTypeId  = [select id from RecordType where SobjectType = 'Opportunity' AND DeveloperName='New_Project'].id;
        OpportunityLineItem oppLineItem =  new OpportunityLineItem(
                                  
                                    OpportunityId = oppId,
                                    UnitPrice = 0,
                                    APPL_Type__c = aType,
                                    PricebookEntryId = priceb,
                                    Remark__c = null,
                                    Quantity = 2,
                                    Probability_Validation__c = 'No'
                                    
                                    );
        
        return oppLineItem; 
    }

    //Product
    public static Product2 createProduct(String proName) {

        Product2 newPro = new Product2(

                        Name = proName,
                        IsActive=true
                        );

        return newPro;

    } 
    
    //PricebookEntry
    public static PricebookEntry createPriceBookEntry(Id price,Id prod) {

        PricebookEntry newPriceE = new PricebookEntry(

            Pricebook2Id = price,

            UnitPrice = 0.0,

            IsActive = true,

            Product2Id = prod);

 
        return newPriceE;

    }   
    //Influencer
    public static Influencer__c createInfluencer(Id prod) {

        Influencer__c newInfu = new Influencer__c(

         
                            Influencer_Type__c = 'Engineer',

                            Opportunity__c = prod

                           );

        return newInfu;

    }   
    //Influencer
    public static Influencer__c createInfluencerdetails(Id oppId,Id accid) {

        Influencer__c newInfu = new Influencer__c(

         
                            Influencer_Type__c = 'Purchase Manager',

                            Opportunity__c = oppId ,
                            Account__c = accid                      

                           );

        return newInfu;

    }   

    //Influencer
    public static Project_Tracker__c createPTracker(Id prod) {

        Project_Tracker__c newPT = new Project_Tracker__c(

         
                            Question__c = 'All Product range approved',

                            Opportunity__c = prod

                           );

        return newPT;

    }   

    //PricebookEntry
    public static Pricebook2 createPriceBook(String pricebookName) {

        Pricebook2 newPriceBook = new Pricebook2(

            Description = 'Project Pricebook',
            IsActive = true,
            Name = pricebookName
            );

        return newPriceBook;

    } 
    
      //Target
    /*public static Target__c CreateTarget(String User) {
        
         Target__c target = new Target__c(
         Is_Active__c = true,
         Architects_Meet__c = 2,
         Boarers_Meet__c = 3,
         Builders_Meet__c = 4,
         Column_Dealer_Meet__c = 5
         
         );
         return target;
    } */
    public static Order createOrder(Id accountID, Id opportunityID, Id priceBookId) {
        
        Order newOrder = new Order(
                                Status  = 'Draft',
                                AccountId = accountID,
                                OpportunityId = opportunityID,
                                EffectiveDate = Date.today(),
                                Pricebook2Id = priceBookId
                                );

        return newOrder;
    } 
    public static OrderItem createOrderItem(Id productId, Id parentOrder, Id accountId, Id PricebookEntryId) {
        
        OrderItem newOrderItem = new OrderItem(
                                Quantity  = 1,
                                Unit__c = 'Mtrs',
                                Order_Value__c = 0,
                                ServiceDate = Date.today(),
                                Distributor_Name__c = accountId,
                                Competitor_Name__c = 'Astral',
                                EndDate = Date.today(),
                                Payment_Terms__c = '30 Days credit with PO',
                                Validity_for_Price__c = Date.today(),
                                OrderId = parentOrder,
                                UnitPrice = 0.0,
                                PricebookEntryId = PricebookEntryId
                                );

        return newOrderItem;
    }
    public static Supply__c createSupply(Id parentOrder, Id oppId) {
        
        Supply__c parentSupply = new Supply__c(
                                Order__c  = parentOrder,
                                Project__c = oppId,
                                ParentSupplyFlag__c = true
                                );

        return parentSupply;
    }
    public static SupplyLineItem__c createSupplyItem(Id parentSupply, Id orderLineItem, Id productId, Id accountId) {
        
        SupplyLineItem__c supplyLineItem = new SupplyLineItem__c(
                                SupplyDetails__c = parentSupply,
                                OrderLineItem__c  = orderLineItem,
                                Quantity__c = 0.0,
                                Unit__c = 'Mtrs',
                                Order_Value__c = 123,                                
                                Product__c = productId,
                                Supply_Status__c = 'Fully Received',
                                Payment_Terms__c = '30 days after delivery',
                                Distributor_Name__c = accountId,
                                ORC_Markup__c = 'qwerty',
                                ORC_Status__c =  'Part Received'

                                );

        return supplyLineItem;
    }

      

}