Partial_14Dec2021/force-app/main/default/objects/Bi_Monthly_Batch__c/Bi_Monthly_Batch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Bi Monthly Batch</label>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Bi_Monthly_Batch__c/fields/Color_Language_Size__c.field-meta.xml
<CustomField>
    <fullName>Color_Language_Size__c</fullName>
    <label>Color/Language/Size</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Bi_Monthly_Batch__c/fields/Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Code__c</fullName>
    <label>Item Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Bi_Monthly_Batch__c/fields/Product_Discription__c.field-meta.xml
<CustomField>
    <fullName>Product_Discription__c</fullName>
    <label>Product Discription</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/inventory__c.object-meta.xml
<CustomObject>
    <description>Object created to hold the data of the inventory</description>
    <label>inventory</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>inventories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Color_Language_Size__c.field-meta.xml
<CustomField>
    <fullName>Color_Language_Size__c</fullName>
    <label>Color/Language/Size</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ENGLISH</fullName>
            </value>
            <value>
                <fullName>HINDI</fullName>
            </value>
            <value>
                <fullName>GUJARATI</fullName>
            </value>
            <value>
                <fullName>MARATI</fullName>
            </value>
            <value>
                <fullName>KANNADA</fullName>
            </value>
            <value>
                <fullName>TELUGU</fullName>
            </value>
            <value>
                <fullName>TAMIL</fullName>
            </value>
            <value>
                <fullName>RED</fullName>
            </value>
            <value>
                <fullName>VIOLET</fullName>
            </value>
            <value>
                <fullName>INDIGO</fullName>
            </value>
            <value>
                <fullName>BLUE</fullName>
            </value>
            <value>
                <fullName>GREEN</fullName>
            </value>
            <value>
                <fullName>YELLOW</fullName>
            </value>
            <value>
                <fullName>ORANGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Is_Depo_User__c.field-meta.xml
<CustomField>
    <fullName>Is_Depo_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Depo User</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/IsCSO_User__c.field-meta.xml
<CustomField>
    <fullName>IsCSO_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCSO User</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Owner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>COLUMN</fullName>
            </value>
            <value>
                <fullName>CASING</fullName>
            </value>
            <value>
                <fullName>V4</fullName>
            </value>
            <value>
                <fullName>CPVC</fullName>
            </value>
            <value>
                <fullName>AQUALIFE</fullName>
            </value>
            <value>
                <fullName>SWR</fullName>
            </value>
            <value>
                <fullName>PAN CONNECTORS</fullName>
            </value>
            <value>
                <fullName>SILENT SWR</fullName>
            </value>
            <value>
                <fullName>UNDER GROUND</fullName>
            </value>
            <value>
                <fullName>AAV</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>GI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>SILENT PLUS</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>PLUMBING</fullName>
            </value>
            <value>
                <fullName>MINI</fullName>
            </value>
            <value>
                <fullName>MEGA</fullName>
            </value>
            <value>
                <fullName>SWR_PUSHFIT</fullName>
            </value>
            <value>
                <fullName>SWR_SOLFIT</fullName>
            </value>
            <value>
                <fullName>SWR SILENT</fullName>
            </value>
            <value>
                <fullName>SWR SILENT PLUS</fullName>
            </value>
            <value>
                <fullName>UNDERGROUND</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>LEAFLETS</fullName>
            </value>
            <value>
                <fullName>HAND BILL</fullName>
            </value>
            <value>
                <fullName>STICKERS</fullName>
            </value>
            <value>
                <fullName>BANNERS</fullName>
            </value>
            <value>
                <fullName>SCROLL 3&apos;x2&apos;</fullName>
            </value>
            <value>
                <fullName>STALL TENT</fullName>
            </value>
            <value>
                <fullName>FLEX BOARD 6&apos; x 3&apos;</fullName>
            </value>
            <value>
                <fullName>FLEX BOARD 8&apos; x 4&apos;</fullName>
            </value>
            <value>
                <fullName>POP BOARDS</fullName>
            </value>
            <value>
                <fullName>TECHNICAL MANUAL</fullName>
            </value>
            <value>
                <fullName>PRICELIST - ALL INDIA</fullName>
            </value>
            <value>
                <fullName>PRICELIST - TAMILNADU</fullName>
            </value>
            <value>
                <fullName>PIPE SELECTION BOOK</fullName>
            </value>
            <value>
                <fullName>THERMOFOAM BOARD</fullName>
            </value>
            <value>
                <fullName>PRICELIST FOLDERS</fullName>
            </value>
            <value>
                <fullName>CORPORATE BROUCHER (EXCELLENCE TO BRILLANCE)</fullName>
            </value>
            <value>
                <fullName>APPLICATION FORM (CHANNEL PARTNERSHIP)</fullName>
            </value>
            <value>
                <fullName>CORPORATE  LEAFLETS</fullName>
            </value>
            <value>
                <fullName>BLUE TAPE (SHELF STICKERS)</fullName>
            </value>
            <value>
                <fullName>WHITE FOLDER</fullName>
            </value>
            <value>
                <fullName>STANDEES</fullName>
            </value>
            <value>
                <fullName>ALL PRODUCT CLUSTER_STANDEES</fullName>
            </value>
            <value>
                <fullName>MULTI USE KNIFE</fullName>
            </value>
            <value>
                <fullName>TORCHE_EVEREADY</fullName>
            </value>
            <value>
                <fullName>TORCH_NIPPO</fullName>
            </value>
            <value>
                <fullName>UMBRELLA</fullName>
            </value>
            <value>
                <fullName>ASHIRVAD KEY CHAIN -  ENGLISH</fullName>
            </value>
            <value>
                <fullName>LEATHER  KEY CHAIN</fullName>
            </value>
            <value>
                <fullName>LEATHERITE PURSE</fullName>
            </value>
            <value>
                <fullName>LUNCH BOX_TRAVEL MATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PRODUCT COLLATERALS</fullName>
            </value>
            <value>
                <fullName>GIFT ITEMS</fullName>
            </value>
            <value>
                <fullName>PACKING MATERIALS</fullName>
            </value>
            <value>
                <fullName>SAMPLES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/Inventory_Request__c.object-meta.xml
<CustomObject>
    <label>Inventory Request</label>
    <nameField>
        <displayFormat>IR-{0000}</displayFormat>
        <label>Inventory Request  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/Comments_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Comments_Remarks__c</fullName>
    <inlineHelpText>Enter the Reason</inlineHelpText>
    <label>Comments/Remarks</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/inventory_Product__c.field-meta.xml
<CustomField>
    <fullName>inventory_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>inventory_Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>inventory__c.Type__c</field>
            <operation>equals</operation>
            <value>PRODUCT COLLATERALS</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>inventory__c</referenceTo>
    <relationshipLabel>Inventory Requests (inventory_Product)</relationshipLabel>
    <relationshipName>Inventory_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/Inventory_Request_Number__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Request_Number__c</fullName>
    <label>Case Number</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Inventory Requests</relationshipLabel>
    <relationshipName>Inventory_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/inventory_Sample__c.field-meta.xml
<CustomField>
    <fullName>inventory_Sample__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>inventory_Sample</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>inventory__c.Type__c</field>
            <operation>equals</operation>
            <value>SAMPLES</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>inventory__c</referenceTo>
    <relationshipLabel>Inventory Requests (inventory_Sample)</relationshipLabel>
    <relationshipName>Inventory_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/Request_Rasied_by__c.field-meta.xml
<CustomField>
    <fullName>Request_Rasied_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request Raised by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Inventory_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/Required_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Required_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Required Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Request__c/fields/Type_of_Item__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Type of Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>inventory__c.Owner_Account__c</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <filterItems>
            <field>inventory__c.Type__c</field>
            <operation>equals</operation>
            <value>GIFT ITEMS</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>inventory__c</referenceTo>
    <relationshipLabel>Inventory Requests</relationshipLabel>
    <relationshipName>Inventory_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/Bi_Monthly_Batch.cls
/*  
  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 * File Name  : Bi_Monthly_Batch
 * Description: Batch Apex for syncing values of opening and closing stock for object 'inventory'.
 * Author     : Renjay Surendran
 * Modification Log 
 * ===================================================================== 
 * Ver   Date        Author                         Modification 
 * ---------------------------------------------------------------------
 * 1.0   10-Sept-2015   Renjay Surendran            Initial Code 
  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
*/ 
global class Bi_Monthly_Batch implements Database.Batchable<sObject>{

    //Id n='00530000003m5lD';
    //List<String> qu=new List<String> {'PRODUCT COLLATERALS','SAMPLES'};
    global String query ='select firstname,Address,depo__c,depo__r.depot_zone__c, team_lead__c, head_office__c, lastname, id from user where isactive=true';

    global  database.QueryLocator start(Database.BatchableContext BC)
    {
        // Initiate the Batch context
       return Database.getQueryLocator(query);
       //return null;      
    }
    global void execute(Database.BatchableContext BC, List<sObject> scope)
    {
       execbatch((list<user>) scope);
    }
    
    public void execbatch(list<user> userInfo1)
    {   system.debug('####'+userInfo1.size());
        set<id> userId = new set<id>();
        List<Case> caseList = new List<Case>();
        List<Inventory_Request__c> batchInv = new List<Inventory_Request__c>();
        Map<id,List<inventory__c>> invMap = new Map<id,List<inventory__c>>();
        
        List<String> qu=new List<String> {'PRODUCT COLLATERALS','SAMPLES'};
        list<inventory__c> inventList=[select ID, Name, IsCSO_User__c, Is_Depo_User__c, Color_Language_Size__c, Item_Code__c, Product__c, Product_Description__c, Type__c, Owner_Account__c from inventory__c where Is_Depo_User__c<>true AND IsCSO_User__c<>true AND Type__c IN: qu]; //AND Owner_Account__c=:n';

        
        RecordType Rt = [select Id from RecordType where Name ='Collateral Request' and SobjectType = 'case'];
        
        List<Bi_Monthly_Batch__c> batchList= [select name, Product__c, Product_Discription__c, Item_Code__c, Color_Language_Size__c, Category__c, Batch_Size__c from Bi_Monthly_Batch__c];
           
        for(inventory__c val : inventList)
        {
            userId.add(val.Owner_Account__c); 
        }  
        for(id i:userId)
        {
            List<inventory__c> inv= new List<inventory__c>();
            for(inventory__c val : inventList)
            {
                if(val.Owner_Account__c==i)
                {
                    inv.add(val);
                }
            }
            invMap.put(i,inv);
        }
        
        //system.debug('userId::'+ userId);
      //  List<user> userInfo=[select firstname,Address,depo__c, team_lead__c, head_office__c, lastname, id from user where id =: userId and isactive=true];
         List<user> userInfo = new List<user>();
        for(User users : userInfo1){
            for(Id setUser : userId){
            
            if(users.id == setUser){
            userInfo.add(users);
            break;
            }
            }
        
        }
        
        system.debug('userInfo:::'+userInfo.size());
        for(user i: userInfo)
        {
            Case cases = new Case();
            cases.subject = 'Bi-Monthly Batch Lot for User' +  i.firstname + ' ' + i.lastname;
            cases.ownerid =  i.id;
            cases.Request_Raised_By__c = i.id;
            cases.recordtypeId= Rt.id;
            cases.status = 'Auto Approved for Bi-Monthly Batch';
            cases.Origin = 'User';
            cases.Priority = 'Medium';
            cases.collateral_flows__c = 'BiMonthlyRequest';
            cases.description = 'Batch Lot to be dispatched for the user ' +  i.firstname + ' ' + i.lastname;
            Address addr = i.Address;
            if(addr != null){
            cases.Shipping_Address__c =addr.getStreet()+ ' ' + addr.getcity() + ' '  + addr.getstate()+ ' '
            +  addr.getPostalCode() +' '+ addr.getcountry();
            }
            else
            {
            cases.Shipping_Address__c ='';
            }
            cases.Depo__c=i.depo__c;
            cases.Head_Office__c=i.Head_office__c;
            cases.team_lead__c = i.team_lead__c;
            if(i.depo__c !=null){
            cases.depot_zone__c =i.depo__r.depot_zone__c;}
            caseList.add(cases);
           
            }
            
           insert caseList; 
           
           system.debug('caseList::::'+caseList.size());
            
            for(Case cases : caseList){
                 system.debug('how many times??');       
            for(inventory__c val: invMap.get(cases.ownerid))
            {              
               for(Bi_Monthly_Batch__c b: batchList)
                {               
                    if(val.Type__c==b.Category__c && val.Product__c==b.Product__c && val.Product_Description__c==b.Product_Discription__c && val.Color_Language_Size__c==b.Color_Language_Size__c && val.Item_Code__c==b.Item_Code__c)
                    {
                        Inventory_Request__c invReq = new Inventory_Request__c();
                        invReq.Inventory_Request_Number__c = cases.id;
                        invReq.Comments_Remarks__c = 'Batch Request';
                        invReq.Request_Rasied_by__c = cases.ownerid;
                        invReq.Required_Quantity__c = b.Batch_Size__c;
                        invReq.Type_of_Item__c = val.id;
                        
                        if(val.Type__c=='PRODUCT COLLATERALS')
                        {
                            invReq.inventory_Product__c = val.id;
                             batchInv.add(invReq);
                        }
                        else{
                           invReq.inventory_Sample__c = val.id;
                            batchInv.add(invReq); }
                        
                        //batchInv.add(invReq);
                    }
                }
                }
            } 
       
        system.debug('batchInv.size()::'+batchInv.size());
        insert batchInv;
        
        
         List<caseShare> caseShareList = new List<caseShare>();
         
         for(Case currentCase : caseList){
            if(currentCase.Team_Lead__c != null){
               CaseShare caseShare=new CaseShare();
               caseShare.UserOrGroupID = currentCase.Team_Lead__c;
               caseShare.CaseAccessLevel= 'Read';
               caseShare.CaseId= currentCase.Id;
               caseShare.RowCause = 'Manual';
               caseShareList.add(CaseShare);      
            }
           if(currentCase.depo__c !=null){
            CaseShare caseShare=new CaseShare();
               caseShare.UserOrGroupID = currentCase.depo__c;
               caseShare.CaseAccessLevel= 'Edit';
               caseShare.CaseId= currentCase.Id;
               caseShare.RowCause = 'Manual';
               caseShareList.add(CaseShare); 
           }
           if(currentCase.head_office__c !=null){
            CaseShare caseShare=new CaseShare();
               caseShare.UserOrGroupID = currentCase.head_office__c;
               caseShare.CaseAccessLevel= 'Edit';
               caseShare.CaseId= currentCase.Id;
               caseShare.RowCause = 'Manual';
               caseShareList.add(CaseShare); 
           }
           }
          if(caseShareList.size()!=0 && caseShareList !=null){
           insert caseShareList;}
           
           system.debug('!!!!'+caseList);
        system.debug('@@@@'+batchInv);
        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
        for(case c : caseList){
            app.setObjectId(c.id);
            app.setComments('BatchLot..'); 

            Approval.ProcessResult result = Approval.process(app);
        }
                  
    }   
    global void finish(Database.BatchableContext BC)
    {
       
    }     
    
}