Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback__c/KAM_Feedback__c.object-meta.xml
<CustomObject>
    <label>KAM Feedback</label>
    <nameField>
        <label>KAM Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KAM Feedbacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>KAM Feedbacks</relationshipLabel>
    <relationshipName>KAM_Feedbacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback__c/fields/KAM_Feedback_Master__c.field-meta.xml
<CustomField>
    <fullName>KAM_Feedback_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KAM Feedback Master</label>
    <referenceTo>KAM_Feedback_Master__c</referenceTo>
    <relationshipLabel>KAM Feedbacks</relationshipLabel>
    <relationshipName>KAM_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Feedback Given</fullName>
                <default>true</default>
                <label>Feedback Given</label>
            </value>
            <value>
                <fullName>Ringing - No Response</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback_Line_Item__c/KAM_Feedback_Line_Item__c.object-meta.xml
<CustomObject>
    <label>KAM Feedback Line Item</label>
    <nameField>
        <displayFormat>KFL-{000000}</displayFormat>
        <label>KAM Feedback Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KAM Feedback Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback_Line_Item__c/fields/KAM_Feedback__c.field-meta.xml
<CustomField>
    <fullName>KAM_Feedback__c</fullName>
    <label>KAM Feedback</label>
    <referenceTo>KAM_Feedback__c</referenceTo>
    <relationshipLabel>KAM Feedback Line Items</relationshipLabel>
    <relationshipName>KAM_Feedback_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback_Master__c/KAM_Feedback_Master__c.object-meta.xml
<CustomObject>
    <label>KAM Feedback Master</label>
    <nameField>
        <label>KAM Feedback Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KAM Feedback Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback_Master__c/fields/Applicable_State__c.field-meta.xml
<CustomField>
    <fullName>Applicable_State__c</fullName>
    <label>Applicable State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Pondicherry</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
            <value>
                <fullName>Uttaranchal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback_Master__c/fields/CheckBox__c.field-meta.xml
<CustomField>
    <fullName>CheckBox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CheckBox</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback_Master_Line_Item__c/KAM_Feedback_Master_Line_Item__c.object-meta.xml
<CustomObject>
    <label>KAM Feedback Master Line Item</label>
    <nameField>
        <displayFormat>KFM-{000000}</displayFormat>
        <label>KAM Feedback Master Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KAM Feedback Master Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback_Master_Line_Item__c/fields/Display_order__c.field-meta.xml
<CustomField>
    <fullName>Display_order__c</fullName>
    <label>Display Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback_Master_Line_Item__c/fields/KAM_Feedback_Master__c.field-meta.xml
<CustomField>
    <fullName>KAM_Feedback_Master__c</fullName>
    <label>KAM Feedback Master</label>
    <referenceTo>KAM_Feedback_Master__c</referenceTo>
    <relationshipLabel>KAM Feedback Master Line Items</relationshipLabel>
    <relationshipName>KAM_Feedback_Master_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/KAM_Feedback_Test.cls
@isTest
public class KAM_Feedback_Test {
    
    static testMethod void testKAM_feedback()
    {            
      Account ac=new Account();
      ac.Name='Bangalore TRADERS';
      ac.State__c='Karnataka';
      ac.Mobile_No_Status__c='Invalid';
      ac.Contact_Number_Mobile__c='9876543210';
      insert ac;
     
      KAM_Feedback_Master__c kfm1=new KAM_Feedback_Master__c();
      kfm1.Name='KAM Feedback Master Test ';
      kfm1.Active__c=true;
      kfm1.Applicable_State__c='Karnataka';
      kfm1.Checkbox__c = True;
      insert kfm1;       
     
      KAM_Feedback_Master_Line_Item__c kfmli1=new KAM_Feedback_Master_Line_Item__c();
      kfmli1.KAM_Feedback_Master__c=kfm1.Id;
      kfmli1.Display_Order__c=1;
      kfmli1.Answer__c='test Answer';
      kfmli1.Question__c='How is Post sales support?';
      insert kfmli1;
         
      KAM_Feedback__c kf10=new KAM_Feedback__c();
      kf10.Name='Feedback Class';
      kf10.Account__c=ac.Id;
      kf10.Status__c='Feedback Given';
      kf10.Date__c=System.Today();
      kf10.KAM_Feedback_Master__c = kfm1.id;
      insert kf10;  
      
      KAM_Feedback_Line_Item__c kfli1=new KAM_Feedback_Line_Item__c();
      kfli1.KAM_Feedback__c=kf10.Id;
      kfli1.Display_Order__c=kfmli1.Display_Order__c;
      kfli1.Answer__c=kfmli1.Answer__c;
      kfli1.Question__c=kfmli1.Question__c;
      
      insert kfli1;      
        
      PageReference pageRef = Page.KAMFeedback;
      Test.setCurrentPage(pageRef);
      pageRef.setredirect(true);
      pageRef.getParameters().put('id',ac.Id);
      Test.startTest();       
      KAM_feedback kfdb = new KAM_feedback(new ApexPages.StandardController(ac));
       
        kfdb.kf.Status__c='Feedback Given';
        kfdb.Next();
        kfdb.kf.Status__c='';
        kfdb.Next();
        kfdb.Add();
        kfdb.Saveall();
        kfdb.Cancel();
        Test.StopTest();   
    }
}