Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback__c/KAM_Feedback__c.object-meta.xml
<CustomObject>
    <label>KAM Feedback</label>
    <nameField>
        <label>KAM Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KAM Feedbacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>KAM Feedbacks</relationshipLabel>
    <relationshipName>KAM_Feedbacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback__c/fields/Call_Person_Name__c.field-meta.xml
<CustomField>
    <fullName>Call_Person_Name__c</fullName>
    <label>Call Person Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sundaresan Sadasivam</fullName>
            </value>
            <value>
                <fullName>Amarnath G K</fullName>
            </value>
            <value>
                <fullName>Vikas Gera</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback__c/fields/KAM_Feedback_Master__c.field-meta.xml
<CustomField>
    <fullName>KAM_Feedback_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KAM Feedback Master</label>
    <referenceTo>KAM_Feedback_Master__c</referenceTo>
    <relationshipLabel>KAM Feedbacks</relationshipLabel>
    <relationshipName>KAM_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>Feedback Given</fullName>
                <default>true</default>
                <label>Feedback Given</label>
            </value>
            <value>
                <fullName>Ringing - No Response</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback__c/fields/status_Remarks__c.field-meta.xml
<CustomField>
    <fullName>status_Remarks__c</fullName>
    <label>status Remarks</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback_Line_Item__c/KAM_Feedback_Line_Item__c.object-meta.xml
<CustomObject>
    <label>KAM Feedback Line Item</label>
    <nameField>
        <displayFormat>KFL-{000000}</displayFormat>
        <label>KAM Feedback Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KAM Feedback Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback_Line_Item__c/fields/KAM_Feedback__c.field-meta.xml
<CustomField>
    <fullName>KAM_Feedback__c</fullName>
    <label>KAM Feedback</label>
    <referenceTo>KAM_Feedback__c</referenceTo>
    <relationshipLabel>KAM Feedback Line Items</relationshipLabel>
    <relationshipName>KAM_Feedback_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback_Master__c/KAM_Feedback_Master__c.object-meta.xml
<CustomObject>
    <label>KAM Feedback Master</label>
    <nameField>
        <label>KAM Feedback Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KAM Feedback Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback_Master__c/fields/Applicable_State__c.field-meta.xml
<CustomField>
    <fullName>Applicable_State__c</fullName>
    <label>Applicable State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Pondicherry</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
            <value>
                <fullName>Uttaranchal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback_Master__c/fields/CheckBox__c.field-meta.xml
<CustomField>
    <fullName>CheckBox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CheckBox</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback_Master_Line_Item__c/KAM_Feedback_Master_Line_Item__c.object-meta.xml
<CustomObject>
    <label>KAM Feedback Master Line Item</label>
    <nameField>
        <displayFormat>KFM-{000000}</displayFormat>
        <label>KAM Feedback Master Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KAM Feedback Master Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback_Master_Line_Item__c/fields/Display_order__c.field-meta.xml
<CustomField>
    <fullName>Display_order__c</fullName>
    <label>Display Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/KAM_Feedback_Master_Line_Item__c/fields/KAM_Feedback_Master__c.field-meta.xml
<CustomField>
    <fullName>KAM_Feedback_Master__c</fullName>
    <label>KAM Feedback Master</label>
    <referenceTo>KAM_Feedback_Master__c</referenceTo>
    <relationshipLabel>KAM Feedback Master Line Items</relationshipLabel>
    <relationshipName>KAM_Feedback_Master_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/KAM_Feedback.cls
/********************************XXX********************************************************

Copyright © 2017 Ashirvad. All rights reserved.
Created By      : Bhargav Surapaneni
Email           : bhargav.surapaneni@ashirvad.com
Created Date    : 16-Feb-2017
Description     : Controller for KAM Feedback page  (For Key Account Managers Feedback)

**********************************XXX*******************************************************/

public class KAM_Feedback {
    
    public Id accId;
    public Account acc{get;set;}
    public Boolean showexisting{get;set;}
    public Boolean showKFM{get;set;}
    public KAM_Feedback__c Kf{get;set;}
    public List<KAM_Feedback_Master__c> kfb{get;set;} 
    public List<KAM_Feedback_Master__c> AllcheckedKFm{get;set;}   
    public List<KAM_Feedback__c> CreateKFBS{get;set;}
        
    public KAM_Feedback(ApexPages.StandardController controller){
        try
        {
            AllcheckedKFm=new List<KAM_Feedback_Master__c>();
            createKFBS = new List<KAM_Feedback__c>();
            accId = ApexPages.CurrentPage().getParameters().get('id');
            acc = [Select id,Name,State__c FROM Account WHERE id=:accId LIMIT 1];
            kfb = [SELECT id, Name, Active__c, Checkbox__c, Applicable_State__c FROM KAM_Feedback_Master__c WHERE  Applicable_State__c includes (:acc.State__c)
                    AND Active__c=True];
            kf = new KAM_Feedback__c();
            showKFM = False;
        }
        catch(Exception ex)
        {
            ApexPages.addMessages(ex);
        }
    }
    
    public PageReference Add()
    {
        try
        {
            if(kf.Status__c!='Feedback Given')
            {
                kf.Account__c = accId;
                insert kf;                
            }
        }
        catch(Exception ex2)
        {
            ApexPages.addMessages(ex2);
        }
        pageReference pr = new PageReference('/'+accId);
        pr.setRedirect(true);
        return pr;
    }
    
    public void Next()
    {
        try
        {
            List<KAM_Feedback_Master__c> temp=new List<KAM_Feedback_Master__c>();
            if(kf.Status__c=='Feedback Given'){
                for(KAM_Feedback_Master__c obj:kfb)
                {
                    if(obj.Checkbox__c==true){
                        temp.add(obj);
                    }                   
                } 
                if(temp.size()==1){
                    for(KAM_Feedback_Master__c kobj:temp){
                        showKFM = true;
                        System.debug('------>>> KFM Name'+ kobj.Name);
                        KAM_Feedback__c newKFB = new KAM_Feedback__c(Account__c=accid);
                        newKFB.Name = kobj.Name;
                        newKFB.KAM_Feedback_Master__c = kobj.id;
                        newkFB.Status__c = kf.Status__c;
                        newKFB.Call_Person_Name__c = kf.Call_Person_Name__c;
                        newKFB.status_Remarks__c = kf.status_Remarks__c;
                        newKFB.Date__c = kf.Date__c;
                        CreateKFBS.add(newKFB);
                        KAM_Feedback_Master__c checkedKFM = [Select id,Name,Active__c,Applicable_State__c,Remarks__c,Checkbox__c,
                                                            (Select id,Name,Display_order__c,Question__c,Answer__c,KAM_Feedback_Master__c
                                                            from KAM_Feedback_Master_Line_Items__r ORDER By Display_Order__c ASC)
                                                            FROM KAM_Feedback_Master__c WHERE id =:kobj.id];
                        System.Debug('@@@@@------->>>LinItemsSize'+checkedKFm.KAM_Feedback_Master_Line_Items__r.Size());
                        try{
                        AllcheckedKFm.add(checkedKFm);                
                        System.Debug('------->>>Size'+AllcheckedKFm.Size());
                        }
                        catch(exception ex3){
                          System.Debug('-the error is '+ex3.getMessage()+'at line number:'+ex3.getLineNumber());  
                        }
                    }
                    insert createKFBS;
                }
                else
                {
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Select Any 1 Questionnaire'));
                }
            }
            if(kf.status__c!='FeedBack Given')
            {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Other Than "Feedback Given" Feedback Line Items shouldnot be created so  click on ADD button  to create Feedbacks Only'));                
            }
        }
        catch(Exception ex4)
        {
            ApexPages.addMessages(ex4);             
        }
    }    
    
    public PageReference saveAll()
    {
        try
        {
            Set<Id> KFB_Ids = new Set<Id>();
            Map<Id,KAM_Feedback__c> MapKFBs = new Map<Id,KAM_Feedback__c>();
            for(KAM_Feedback__c kobj2:CreateKFBS)
            {
                KFB_Ids.add(kobj2.id);
            }
            List<KAM_Feedback__c> AllKFBs = [SELECT id,Name,KAM_Feedback_Master__c FROM KAM_Feedback__c WHERE id IN: KFB_Ids];
            if(!AllKFBs.isEmpty())
            {
                for(KAM_Feedback__c kobj3:CreateKFBS)
                {
                    MapKFBs.put(kobj3.KAM_Feedback_Master__c, kobj3);
                }
            }
            List<KAM_Feedback_Line_Item__c> kfli = new List<KAM_Feedback_Line_Item__c>();
            for(KAM_Feedback_Master__c m:AllcheckedKfm)
            {
                for(KAM_Feedback_Master_Line_Item__c e:m.KAM_Feedback_Master_Line_Items__r)
                {
                    if(MapKFBs.get(e.KAM_Feedback_Master__c)!=null)
                    {
                        KAM_Feedback_Line_Item__c kfd = new KAM_Feedback_Line_Item__c();
                        kfd.KAM_Feedback__c = MapKFBS.get(e.KAM_Feedback_Master__c).Id;
                        kfd.Question__c=e.Question__c;
                        kfd.Answer__c=e.Answer__c;
                        kfd.Display_Order__c=e.Display_Order__c;
                        kfli.add(kfd);
                        System.Debug('#######Size'+kfli);
                    }
                }
                System.Debug('123#######Size'+kfli.Size());
            }
            insert kfli;
            pageReference pf=new PageReference('/'+accid);
            pf.SetRedirect(true);
            return pf;       
        }
        catch(Exception ex5)
        {
            ApexPages.addMessages(ex5);
        }
        return null;
    }
    
    
    public PageReference cancel()
    {
        pageReference pe=new PageReference('/'+accid);
        pe.setRedirect(true);
        return pe;
    }
}