Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mega_Meets_Column__c.field-meta.xml
<CustomField>
    <fullName>Mega_Meets_Column__c</fullName>
    <formula>Mechanics_Factory_Visit__c + Mega_Mechanic_Meet__c  +  Mega_Farmers_Meet__c  +  Boarers_Meet__c + Column_DSM_Meet_Training__c + Column_Dealer_Meet__c +  Column_Distributors_Dealers_Mechanic_Fac__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mega Meets (Column)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mega_Meets_Plumbing__c.field-meta.xml
<CustomField>
    <fullName>Mega_Meets_Plumbing__c</fullName>
    <formula>Mega_Plumbers_Meet__c + Architects_Engineers_Consultants_Factory__c + Plumber_Factory_Visit__c + Engineers_Meet__c + Architects_Meet__c + Plumbing_Dealers_Factory_Visit__c + Plumbing_Dealer_Distributor_Meets__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mega Meets Plumbing (Target)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mega_Meets_Project__c.field-meta.xml
<CustomField>
    <fullName>Mega_Meets_Project__c</fullName>
    <formula>Architects_Engineers_Consultants_Actual__c +  Architects_Meet__c + Builders_Meet__c +  Engineers_Meet__c + Projects_DSM_Meet_Training__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mega Meets Project</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mini_Meets_Column__c.field-meta.xml
<CustomField>
    <fullName>Mini_Meets_Column__c</fullName>
    <formula>InShop_Mechanic_Meet__c  +  Inshop_Boarers_Meet__c +  Exhibition_Agri_Fairs_Actuval__c  + Mini_Farmers_Meet_Weightage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mini Meets (Column)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mini_Meets_Plumbing__c.field-meta.xml
<CustomField>
    <fullName>Mini_Meets_Plumbing__c</fullName>
    <formula>InSHOP_Plumber_meet__c +  Naaka_Meet__c +  Onsite_Plumber_Meet__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mini Meets Plumbing</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mini_Meets_Project__c.field-meta.xml
<CustomField>
    <fullName>Mini_Meets_Project__c</fullName>
    <formula>Onsite_Plumber_Meet__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mini Meets Project</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>CASE(MONTH(Start_Date__c),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;,
4, &quot;April&quot;,
5, &quot;May&quot;,
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;None&quot;)+&quot; &quot;+&quot;-&quot;+&quot; &quot;+TEXT(YEAR(Start_Date__c))</formula>
    <label>Month</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Column</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
            <value>
                <fullName>Branding</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/AutoRequestForMeetController.cls
/*  
  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 * File Name  : AutoRequestForMeetController
 * Description: Batch Apex for raising the auto request for BDM's on 2nd of every month
 * Author     : vasanthi K N
 * Modification Log 
 * ===================================================================== 
 * Ver       Date            Author                      Modification 
 * ---------------------------------------------------------------------
 * 1.0    28-Aug-2015       Vasanthi K N                 Initial Code 
  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
*/ 
global class AutoRequestForMeetController implements Database.Batchable<sObject>{

autoRequestBatchHelper helper = new autoRequestBatchHelper();

String currentMonth = helper.getCurrentMonth();
String variable1='Pending';
String variable2 ='Approved';
global String query ='select Mega_Meets_Column__c,Mega_Meets_Plumbing__c,Mega_Meets_Project__c, Mini_Meets_Column__c, Mini_Meets_Plumbing__c, Mini_Meets_Project__c,Approval_Status__c, ownerid, Month__c, Vertical__c from Target__c where (Approval_Status__c =: variable1 or Approval_Status__c =: variable2) and month__c =: currentMonth';

 global  database.QueryLocator start(Database.BatchableContext BC)
    {
        // Initiate the Batch context
       return Database.getQueryLocator(query);
       //return null;      
    }
    global void execute(Database.BatchableContext BC, List<Target__c> scope)
    {
       system.debug('scope::::' + scope);
       helper.executeAutoRequestForMeet(scope);
    }


 global void finish(Database.BatchableContext BC)
    {
       
    } 
}