Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Approval_Comments__c.field-meta.xml
<CustomField>
    <fullName>Approval_Comments__c</fullName>
    <description>Approved Comments for Tour plan</description>
    <label>Approved Comments</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/GenerateExpensePDFRedirectControllerTest.cls
@isTest
public class GenerateExpensePDFRedirectControllerTest {
    static testMethod void expensePdfMethod() {
        Target__c tc = new Target__c();
        tc.Approval_Comments__c = 'Approve';
        Insert tc;
        
        ApexPages.currentPage().getHeaders().put('USER-AGENT', 'Mobile');
        ApexPages.StandardController sc = new ApexPages.standardController(tc);
        GenerateExpensePDFRedirectController accPdf = new GenerateExpensePDFRedirectController(sc);
        
    /*    EmailMessage email = new EmailMessage();
        email.FromAddress = 'test@abc.org';
        email.Incoming = True;
        email.ToAddress= 'test@xyz.org';
        email.Subject = 'Test email';
        email.HtmlBody = 'Test email body';
      //  email.ParentId = tc.Id; 
        insert email;
        
        Attachment attach=new Attachment();   	
    	attach.Name='Unit Test Attachment';
    	Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
    	attach.body=bodyBlob;
        attach.parentId=tc.id;
        insert attach;
        */
        accPdf.sendGenerateExpPdf();
        GenerateExpensePDFRedirectController.codeCoverageTrick();
    }
}