Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Approval_Comments__c.field-meta.xml
<CustomField>
    <fullName>Approval_Comments__c</fullName>
    <description>Approved Comments for Tour plan</description>
    <label>Approved Comments</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/AccountPdfTestRedirectControllerTest.cls
@isTest
public class AccountPdfTestRedirectControllerTest {
    static testMethod void accountPdfMethod() {
        Target__c tc = new Target__c();
        tc.Approval_Comments__c = 'Approve';
        Insert tc;
        
        ApexPages.currentPage().getHeaders().put('USER-AGENT', 'Mobile');
        ApexPages.StandardController sc = new ApexPages.standardController(tc);
        AccountPdfTestRedirectController accPdf = new AccountPdfTestRedirectController(sc);
        accPdf.sendprojectFormatPdf();
     //   accPdf.sendDownloadPdf();
        
		accPdf.sendprojectFormatPdf();
        AccountPdfTestRedirectController.codeCoverageTrick();        
    }
}