Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Contacts_visit_Plumbers_ACHVD__c.field-meta.xml
<CustomField>
    <fullName>Contacts_visit_Plumbers_ACHVD__c</fullName>
    <formula>Contacts_visit_Plumbers_etc__c /  Contacts_visit_Target_Plumbers__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contacts visit  (Plumbers) % ACHVD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Contacts_visit_Plumbers_etc__c.field-meta.xml
<CustomField>
    <fullName>Contacts_visit_Plumbers_etc__c</fullName>
    <label>Contacts visit Actual ( Plumbers)​</label>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.Party_Type__c</field>
        <operation>notEqual</operation>
        <value>Dealer, Direct Dealer, Distributor</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.Party_Type__c</field>
        <operation>notEqual</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>AP_Site_Visit__c.Target__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Contacts_visit_Score_Plumbers__c.field-meta.xml
<CustomField>
    <fullName>Contacts_visit_Score_Plumbers__c</fullName>
    <formula>Contacts_visit_Weightage_Plumbers__c *  (Contacts_visit_Plumbers_ACHVD__c/100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contacts visit Score (Plumbers)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Contacts_visit_Target_Plumbers__c.field-meta.xml
<CustomField>
    <fullName>Contacts_visit_Target_Plumbers__c</fullName>
    <label>Contacts visit Target ( Plumbers)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Contacts_visit_Weightage_Plumbers__c.field-meta.xml
<CustomField>
    <fullName>Contacts_visit_Weightage_Plumbers__c</fullName>
    <label>Contacts visit Weightage ( Plumbers)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/ISP_Meets_Plumbing__c.field-meta.xml
<CustomField>
    <fullName>ISP_Meets_Plumbing__c</fullName>
    <formula>Naaka_Meet__c  +  Onsite_Plumber_Meet__c  +  InSHOP_Plumber_meet__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ISP Meets (Plumbing)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Key_influencers_Arch_consultant_ACHVD__c.field-meta.xml
<CustomField>
    <fullName>Key_influencers_Arch_consultant_ACHVD__c</fullName>
    <formula>Key_influencers_contact_Arch_consultant__c /  Key_influencers_Target_Arch_consultant__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Key influencers (Arch/consultant) %ACHVD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Key_influencers_contact_Arch_consultant__c.field-meta.xml
<CustomField>
    <fullName>Key_influencers_contact_Arch_consultant__c</fullName>
    <label>Key influencers Actual ( Arch/consultant</label>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.Party_Type__c</field>
        <operation>equals</operation>
        <value>Architect, Consultant, Builder, Contractor, Engineer, Plumbing Contractor, Purchase Manager, Customer, Project Manager, Project Owner/Developer, Site Engineer, Site Incharge / Supervisor</value>
    </summaryFilterItems>
    <summaryForeignKey>AP_Site_Visit__c.Target__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Key_influencers_Score_Arch_consultant__c.field-meta.xml
<CustomField>
    <fullName>Key_influencers_Score_Arch_consultant__c</fullName>
    <formula>Key_influencers_Weighta_Arch_consultant__c *  (Key_influencers_Arch_consultant_ACHVD__c/100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Key influencers Score( Arch/consultant)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Key_influencers_Target_Arch_consultant__c.field-meta.xml
<CustomField>
    <fullName>Key_influencers_Target_Arch_consultant__c</fullName>
    <label>Key influencers Target ( Arch/consultant</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Key_influencers_Weighta_Arch_consultant__c.field-meta.xml
<CustomField>
    <fullName>Key_influencers_Weighta_Arch_consultant__c</fullName>
    <label>Key influencers Weighta(Arch/consultant)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mega_Meets_ACHVD__c.field-meta.xml
<CustomField>
    <fullName>Mega_Meets_ACHVD__c</fullName>
    <formula>if( Text(Vertical__c) == &apos;Column&apos;, (Mega_Meets_Column_Actual__c  /  Mega_Meets_Column_Target__c), if(Text(Vertical__c) == &apos;Plumbing&apos;, Mega_Meets_Plumbing_Actual__c / Mega_Meets_Plumbing__c,0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mega Meets % ACHVD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mega_Meets_Plumbing__c.field-meta.xml
<CustomField>
    <fullName>Mega_Meets_Plumbing__c</fullName>
    <formula>Mega_Plumbers_Meet__c + Architects_Engineers_Consultants_Factory__c + Plumber_Factory_Visit__c + Engineers_Meet__c + Architects_Meet__c + Plumbing_Dealers_Factory_Visit__c + Plumbing_Dealer_Distributor_Meets__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mega Meets Plumbing (Target)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mega_Meets_Plumbing_Actual__c.field-meta.xml
<CustomField>
    <fullName>Mega_Meets_Plumbing_Actual__c</fullName>
    <description>Mega Plumbers Meets, Architects / Engineers / Consultants Factory Visit, 
Plumbers Factory Visit, Architects Meets, 
Engineers Meets, Plumbing Dealers Factory Visits, Plumbing Dealer / Distributor Meets</description>
    <label>Mega Meets Plumbing (Actual)</label>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Other Activities</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.Othet_Activities__c</field>
        <operation>equals</operation>
        <value>Promotional Activity</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.Promotion_Type__c</field>
        <operation>equals</operation>
        <value>Mega Plumbers Meets, Architects / Engineers / Consultants Factory Visit, Plumbers Factory Visit, Architects Meets, Engineers Meets, Plumbing Dealers Factory Visits, Plumbing Dealer / Distributor Meets, Plumbing DSM Meet/Training</value>
    </summaryFilterItems>
    <summaryForeignKey>AP_Site_Visit__c.Target__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mega_Meets_Score__c.field-meta.xml
<CustomField>
    <fullName>Mega_Meets_Score__c</fullName>
    <formula>Mega_Meets_Weightage__c  * ( Mega_Meets_ACHVD__c /100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mega Meets - Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mega_Meets_Weightage__c.field-meta.xml
<CustomField>
    <fullName>Mega_Meets_Weightage__c</fullName>
    <label>Mega Meets - Weightage</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/No_of_visits_Score_field_work__c.field-meta.xml
<CustomField>
    <fullName>No_of_visits_Score_field_work__c</fullName>
    <formula>No_of_visits_Weightage_total_visits__c * (No_of_visits_total_visits_ACHVD__c/100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No.of visits Score ( field work)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/No_of_visits_Target_total_visits__c.field-meta.xml
<CustomField>
    <fullName>No_of_visits_Target_total_visits__c</fullName>
    <formula>Head_Quarter_Daily_Calls__c +  HEAD_QUARTER_METRO_Daily_Calls__c + Head_Quarter_State_Capital_Daily_Calls__c + Out_Station_Daily_Calls__c + Ex_Station_Daily_Calls__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No.of visits Target ( total visits)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/No_of_visits_total_visits__c.field-meta.xml
<CustomField>
    <fullName>No_of_visits_total_visits__c</fullName>
    <label>No.of visits Actual ( total visits)​</label>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Visits</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.Party_Type__c</field>
        <operation>equals</operation>
        <value>Dealer</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.Dealer_visit_actual_calculation__c</field>
        <operation>notEqual</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>AP_Site_Visit__c.Target__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/No_of_visits_total_visits_ACHVD__c.field-meta.xml
<CustomField>
    <fullName>No_of_visits_total_visits_ACHVD__c</fullName>
    <formula>No_of_visits_total_visits__c / No_of_visits_Target_total_visits__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No.of visits ( total visits)​ %ACHVD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/No_of_visits_Weightage_total_visits__c.field-meta.xml
<CustomField>
    <fullName>No_of_visits_Weightage_total_visits__c</fullName>
    <label>No.of visits Weightage ( total visits)​</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Retailing_days_field_work__c.field-meta.xml
<CustomField>
    <fullName>Retailing_days_field_work__c</fullName>
    <label>Retailing days Actual ( field work)</label>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Visits</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.Retailing_Day__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>AP_Site_Visit__c.Target__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Retailing_days_field_work_ACHVD__c.field-meta.xml
<CustomField>
    <fullName>Retailing_days_field_work_ACHVD__c</fullName>
    <formula>Retailing_days_field_work__c/Retailing_days_Target_field_work__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Retailing days ( field work) %ACHVD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Retailing_days_field_work_Weightage__c.field-meta.xml
<CustomField>
    <fullName>Retailing_days_field_work_Weightage__c</fullName>
    <label>Retailing days Weightage ( field work)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Retailing_days_Score_field_work__c.field-meta.xml
<CustomField>
    <fullName>Retailing_days_Score_field_work__c</fullName>
    <formula>Retailing_days_field_work_Weightage__c * (Retailing_days_field_work_ACHVD__c/100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Retailing days Score ( field work)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Retailing_days_Target_field_work__c.field-meta.xml
<CustomField>
    <fullName>Retailing_days_Target_field_work__c</fullName>
    <formula>Head_Quarter_No_of_Days__c + HEAD_QUARTER_METRO_No_Of_Days__c + Head_Quarter_State_Capital_No_of_days__c + Ex_Station_No_of_Days__c + Out_Station_No_of_Days__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Retailing days Target ( field work)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Column</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Projects</fullName>
            </value>
            <value>
                <fullName>Branding</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/recordTypes/Column.recordType-meta.xml
<RecordType>
    <fullName>Column</fullName>
    <active>true</active>
    <label>Column</label>
</RecordType>

Partial_14Dec2021/force-app/main/default/classes/Test_APPL_SMART_KRA_REPORT_CONTROLLER.cls
@isTest(seealldata=true)
public with sharing class Test_APPL_SMART_KRA_REPORT_CONTROLLER {
    
    public static User userdata;
     public static User userdata2;
    public static Target__c target;
    
    public static void init() {
        
        userdata = Test_Intial_Data_Phase2.ColumnRH('First','Last','System Administrator');
        insert userdata ;
        target = Test_Intial_Data_Phase2.CreateTarget(userdata);
        target.Vertical__c = 'Plumbing';
        target.Start_Date__c = Date.Today().toStartOfMonth();
        Integer month = Date.Today().month();
        Integer year   = Date.Today().year();
        target.End_Date__c   = target.Start_Date__c.addDays(Date.daysInMonth(year, month)-1);
        insert target;
    userdata2=Test_Intial_Data_Phase2.ColumnRH('First1','Last1','BD');
    insert userdata2 ;
List<target__c> targetRecord=[select id ,Retailing_days_Target_field_work__c,Retailing_days_field_work_ACHVD__c,Retailing_days_field_work__c,Retailing_days_field_work_Weightage__c,Retailing_days_Score_field_work__c,No_of_visits_Target_total_visits__c,No_of_visits_total_visits__c,No_of_visits_total_visits_ACHVD__c,No_of_visits_Weightage_total_visits__c,No_of_visits_Score_field_work__c,Contacts_visit_Target_Plumbers__c,
                                            Contacts_visit_Plumbers_etc__c,Contacts_visit_Plumbers_ACHVD__c,Contacts_visit_Weightage_Plumbers__c,Contacts_visit_Score_Plumbers__c,Key_influencers_Target_Arch_consultant__c,
                                            Key_influencers_contact_Arch_consultant__c ,Key_influencers_Arch_consultant_ACHVD__c,Key_influencers_Weighta_Arch_consultant__c,Key_influencers_Score_Arch_consultant__c,
                                             Mega_Meets_Plumbing__c,Mega_Meets_Plumbing_Actual__c,Mega_Meets_ACHVD__c,Mega_Meets_Weightage__c,Mega_Meets_Score__c,
                                             ISP_Meets_Plumbing__c,Inshop_Plumber_Meets_Actual__c,Inshop_Plumber_Meet_ACHVD__c,Inshop_Plumber_Meet_Weightage__c,Inshop_Plumber_Meet_Score__c,PRIMARY_SALES_CPVC__c,Primary_Sales_CPVC_Actuals__c,Primary_Sales_CPVC_ACHVD__c,
                                              Primary_Sales_CPVC_Weightage__c,Primary_Sales_CPVC_Score__c,PRIMARY_SALES_UPVC__c,Primary_Sales_Aqua_Actuals__c,Primary_Sales_Aqua_ACHVD__c,Primary_Sales_Aqua_Weightage__c,Primary_Sales_Aqua_Score__c,
                                              PRIMARY_SALES_SWR__c,Primary_Sales_SWR_Actuals__c,Primary_Sales_SWR_ACHVD__c,Primary_Sales_SWR_Weightage__c,Primary_Sales_SWR_Score__c,   Secondary_Sales_Target__c,Secondary_Sales_Actual_In_Lacs__c,Secondary_Sales_ACHVD__c,
                                              Secondary_Sales_Weightage__c,Secondary_Sales_Score__c,Plumbing_DSM_Meet_Training_ACHVD__c,Plumbing_DSM_Meet_Training_Weightage__c  from Target__c limit 2 ];//new target__c();
      
        List<Target__c> tgtListnew=new List<Target__c>();
        for(target__c tgt: targetRecord){
        tgt.Contacts_visit_Target_Plumbers__c=10;
        tgt.OwnerId=userInfo.getUserId();
         tgt.End_Date__c   = Date.today();
         tgt.Start_Date__c   = Date.today();
            tgtListnew.add(tgt);
         
        }
        update tgtListnew;
        system.debug('+++++++++++++++%$(^%*&%&(^%&' +targetRecord.size());
    }
    public static testmethod void testone() {
        
        init();
        
        test.startTest();
        APPL_SMART_KRA_REPORT_CONTROLLER  smartkra = new APPL_SMART_KRA_REPORT_CONTROLLER();
        KRAv1 kraModified=new KRAv1();
           kraModified.target = target;
           kraModified.selectedMonth = string.valueOf(Date.today().month());
           kraModified.selectedYear  = string.valueOf(Date.today().year());
       
        smartkra.target = target;
        smartkra.selectedMonth = string.valueOf(Date.today().month());
        smartkra.selectedYear  = string.valueOf(Date.today().year());
        //system.debug([select id, Start_Date__c, End_date__c from Target__c]);
        
        smartkra.SelectSubordinates=true;
        smartkra.rertieveKRAData();
        target.Vertical__c = 'Column';
        update target;
        smartkra.rertieveKRAData();
        target.Vertical__c = 'Projects';
        target.Plumbing_DSM_Meet_Training_Weightage__c=0;
        
        update target;
        smartkra.rertieveKRAData();
        
        List<target__c> TLIST=new List<target__c>();
          kraModified.selectSubordinates=true;
        target.Vertical__c = 'Plumbing';
        update target;
        kraModified.callKRA();
        target.Vertical__c = 'Column';
        TLIST.add(target);
        update target;
        kraModified.callKRA();
        target.Vertical__c = 'Projects';
         target.Plumbing_DSM_Meet_Training_Weightage__c=0;
        kraModified.projectflag=true;
        TLIST.add(target);
        update target;
        kraModified.callKRA();
        TLIST.add(target);
        test.stopTest();
    }
}