Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/Tour_Plan1__c.object-meta.xml
<CustomObject>
    <label>Tour Plans</label>
    <nameField>
        <label>Tour Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/BD_Tour_Plans_1__c.field-meta.xml
<CustomField>
    <fullName>BD_Tour_Plans_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BD Tour Plans 1</label>
    <referenceTo>Tour_Plan1__c</referenceTo>
    <relationshipLabel>Tour Plans (BD Tour Plans 1)</relationshipLabel>
    <relationshipName>Tour_Plans3</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Location_1__c.field-meta.xml
<CustomField>
    <fullName>Location_1__c</fullName>
    <label>Location 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Architects__c.field-meta.xml
<CustomField>
    <fullName>No_of_Architects__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Architects (Planned)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Builders_Planned__c.field-meta.xml
<CustomField>
    <fullName>No_of_Builders_Planned__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No:of Builders (Planned)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Consultants__c.field-meta.xml
<CustomField>
    <fullName>No_of_Consultants__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Consultants (Planned)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Dealers__c.field-meta.xml
<CustomField>
    <fullName>No_of_Dealers__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Dealers (Planned)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Distributors__c.field-meta.xml
<CustomField>
    <fullName>No_of_Distributors__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Distributors (Planned)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Engineers__c.field-meta.xml
<CustomField>
    <fullName>No_of_Engineers__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Engineers (Planned)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Plumbing_Contractor__c.field-meta.xml
<CustomField>
    <fullName>No_of_Plumbing_Contractor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Plumbing Contractor (Planned)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Other_Contacts_if_any__c.field-meta.xml
<CustomField>
    <fullName>Other_Contacts_if_any__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Other Contacts if any (Planned)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Visit_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhatisgarh</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttaranchal</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
            <value>
                <fullName>Pondicherry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Tour_Plans_2__c.field-meta.xml
<CustomField>
    <fullName>Tour_Plans_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tour Plans 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Tour_Plan1__c.Date__c</field>
            <operation>equals</operation>
            <valueField>$Source.Date__c</valueField>
        </filterItems>
        <filterItems>
            <field>Tour_Plan1__c.CreatedBy.ManagerId</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tour_Plan1__c</referenceTo>
    <relationshipLabel>Tour Plans (Tour Plans 2)</relationshipLabel>
    <relationshipName>Tour_Plans1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Tour_Plans_3__c.field-meta.xml
<CustomField>
    <fullName>Tour_Plans_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tour Plans 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Tour_Plan1__c.Date__c</field>
            <operation>equals</operation>
            <valueField>$Source.Date__c</valueField>
        </filterItems>
        <filterItems>
            <field>Tour_Plan1__c.CreatedBy.ManagerId</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tour_Plan1__c</referenceTo>
    <relationshipLabel>Tour Plans (Tour Plans 3)</relationshipLabel>
    <relationshipName>Tour_Plans2</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Tour_Program__c.field-meta.xml
<CustomField>
    <fullName>Tour_Program__c</fullName>
    <label>Tour Program</label>
    <referenceTo>Tour_Program__c</referenceTo>
    <relationshipLabel>Tour Plans</relationshipLabel>
    <relationshipName>Tour_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/User_2__c.field-meta.xml
<CustomField>
    <fullName>User_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tour_Plans1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/User_3__c.field-meta.xml
<CustomField>
    <fullName>User_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tour_Plans2</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tour_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Visit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Head Quarter</fullName>
            </value>
            <value>
                <fullName>Ex-Outstation</fullName>
            </value>
            <value>
                <fullName>Out Station</fullName>
            </value>
            <value>
                <fullName>Leave</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/Tour_Program__c.object-meta.xml
<CustomObject>
    <label>Tour Program</label>
    <nameField>
        <label>Tour Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/BD_Tour_Plans_1__c.field-meta.xml
<CustomField>
    <fullName>BD_Tour_Plans_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BD Tour Plans 1</label>
    <referenceTo>Tour_Plan1__c</referenceTo>
    <relationshipLabel>Tour Programs</relationshipLabel>
    <relationshipName>Tour_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/DisplayTourPlansClass.cls
public with sharing class DisplayTourPlansClass {
    Public Id TourProgramId;
    Public Tour_Program__c TourProgram{get;set;}
    Public List<Tour_Plan1__c> TourPlans{get;set;}
    

    public DisplayTourPlansClass(ApexPages.StandardController controller) {
        
        TourProgramId=ApexPages.CurrentPage().getParameters().get('Id');
        TourProgram=[SELECT id,Name From Tour_Program__c WHERE id=:TourProgramId];
        TourPlans=[SELECT id,Name,Date__c,State__c,District__c,Market_Type__c,User__r.Name,User_2__r.Name,User_3__r.Name,Tour_Program__c,No_of_Architects__c,No_of_Consultants__c,No_of_Dealers__c,
                    No_of_Distributors__c,Other_Contacts_if_any__c,Tour_Plans_2__r.Other_Contacts_if_any__c,Tour_Plans_3__r.Other_Contacts_if_any__c,No_of_Builders_Planned__c,No_of_Plumbing_Contractor__c,Location__c,Location_1__c,District_1__c,User__c,No_of_Engineers__c,Visit_Type__c,Tour_Plans_2__r.Name,Tour_Plans_2__r.Date__c,Tour_Plans_2__r.State__c,Tour_Plans_2__r.District__c,Tour_Plans_2__r.Market_Type__c,Tour_Plans_2__r.Tour_Program__c,Tour_Plans_2__r.No_of_Architects__c,Tour_Plans_2__r.No_of_Consultants__c,Tour_Plans_2__r.No_of_Dealers__c,
                    Tour_Plans_2__r.No_of_Distributors__c,Tour_Plans_2__r.No_of_Builders_Planned__c,Tour_Plans_2__r.No_of_Plumbing_Contractor__c,Tour_Plans_2__r.Location__c,Tour_Plans_2__r.Location_1__c,Tour_Plans_2__r.District_1__c,Tour_Plans_2__r.User__c,Tour_Plans_2__r.No_of_Engineers__c,Tour_Plans_2__r.Visit_Type__c,Tour_Plans_3__r.Name,Tour_Plans_3__r.Date__c,Tour_Plans_3__r.State__c,Tour_Plans_3__r.District__c,Tour_Plans_3__r.Market_Type__c,Tour_Plans_3__r.Tour_Program__c,Tour_Plans_3__r.No_of_Architects__c,Tour_Plans_3__r.No_of_Consultants__c,Tour_Plans_3__r.No_of_Dealers__c,
                    Tour_Plans_3__r.No_of_Distributors__c,Tour_Plans_3__r.No_of_Builders_Planned__c,Tour_Plans_3__r.No_of_Plumbing_Contractor__c,Tour_Plans_3__r.Location__c,Tour_Plans_3__r.Location_1__c,Tour_Plans_3__r.District_1__c,Tour_Plans_3__r.User__c,Tour_Plans_3__r.No_of_Engineers__c,Tour_Plans_3__r.Visit_Type__c,BD_Tour_Plans_1__r.Name,BD_Tour_Plans_1__r.Date__c,BD_Tour_Plans_1__r.State__c,BD_Tour_Plans_1__r.District__c,BD_Tour_Plans_1__r.Market_Type__c,BD_Tour_Plans_1__r.Tour_Program__c,BD_Tour_Plans_1__r.No_of_Architects__c,BD_Tour_Plans_1__r.No_of_Consultants__c,BD_Tour_Plans_1__r.No_of_Dealers__c,
                    BD_Tour_Plans_1__r.No_of_Distributors__c,BD_Tour_Plans_1__r.Other_Contacts_if_any__c,BD_Tour_Plans_1__r.No_of_Builders_Planned__c,BD_Tour_Plans_1__r.No_of_Plumbing_Contractor__c,BD_Tour_Plans_1__r.Location__c,BD_Tour_Plans_1__r.Location_1__c,BD_Tour_Plans_1__r.District_1__c,BD_Tour_Plans_1__r.User__c,BD_Tour_Plans_1__r.No_of_Engineers__c,BD_Tour_Plans_1__r.Visit_Type__c FROM Tour_Plan1__c WHERE Tour_Program__c=:TourProgram.id Order By Date__c ASC];
    }

}