Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/LookupController.cls
/*******************************************************************
 * Custom controller for the "Custom Lookup" recipe. Executes a 
 * search based on a query string entered by a user. 
 *******************************************************************/
public with sharing class LookupController 
{
    // the query string entered by the user
    public String query {get; set;}
    
    // the matchin>g accounts
    public List<Account> accounts {get; set;}
    
    // has a search been executed?
    public Boolean doneLookup {get; set;}
    
    // constructor
    public LookupController()
    {
        doneLookup=false;
    }
    
    // executes the search
    public PageReference runQuery()
    {
        accounts  = new List<Account>();
        List<Account> searchResults= New List<Account>([SELECT Id,Name,District__c, State__c, Status__c, Party_type__c FROM Account WHERE status__c ='Existing' AND Party_Type__c = 'Distributor' and name LIKE: query+'%' limit 999]);
           
        accounts.addAll(searchResults);
        doneLookup=true;
        return null;
    }
}