Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Pincode__c/Pincode__c.object-meta.xml
<CustomObject>
    <label>Pincode</label>
    <nameField>
        <label>Pincode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pincodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Pincode__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Pincodes</relationshipLabel>
    <relationshipName>Pincodes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Pincode__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Pincodes</relationshipLabel>
    <relationshipName>Pincodes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Problem__c/Problem__c.object-meta.xml
<CustomObject>
    <label>Problem</label>
    <nameField>
        <label>Problem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Problems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Problem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Problems</relationshipLabel>
    <relationshipName>Problems</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Problem__c/fields/Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Type</label>
    <referenceTo>WorkType</referenceTo>
    <relationshipLabel>Problems</relationshipLabel>
    <relationshipName>Problems</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Territory_Contractors__c/Territory_Contractors__c.object-meta.xml
<CustomObject>
    <label>Territory Contractors</label>
    <nameField>
        <label>Territory Contractors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Contractors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Territory_Contractors__c/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Contractors</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Territory_Contractors__c/fields/SAP_Code_ship__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code_ship__c</fullName>
    <label>SAP Code(ship)</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Territory_Contractors__c/fields/SAP_Code_sold__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code_sold__c</fullName>
    <label>SAP Code(sold)</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Territory_Contractors__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Territory Contractors</relationshipLabel>
    <relationshipName>Territory_Contractors</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Town_Master__c/Town_Master__c.object-meta.xml
<CustomObject>
    <label>Town Master</label>
    <nameField>
        <label>Town Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Town Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Town_Master__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Dharmapuri</fullName>
            </value>
            <value>
                <fullName>krishnagiri</fullName>
            </value>
            <value>
                <fullName>Coimbatore</fullName>
            </value>
            <value>
                <fullName>Hosur</fullName>
            </value>
            <value>
                <fullName>Bandra(Mumbai Suburban district)</fullName>
            </value>
            <value>
                <fullName>Tirupathi</fullName>
            </value>
            <value>
                <fullName>Guntur</fullName>
            </value>
            <value>
                <fullName>Kuppam</fullName>
            </value>
            <value>
                <fullName>Erode</fullName>
            </value>
            <value>
                <fullName>Mangalore</fullName>
            </value>
            <value>
                <fullName>Bantval</fullName>
            </value>
            <value>
                <fullName>Aurangabad</fullName>
            </value>
            <value>
                <fullName>Adilabad</fullName>
                <isActive>false</isActive>
                <label>Adilabad</label>
            </value>
            <value>
                <fullName>Agra</fullName>
                <isActive>false</isActive>
                <label>Agra</label>
            </value>
            <value>
                <fullName>Ahmadabad</fullName>
                <isActive>false</isActive>
                <label>Ahmadabad</label>
            </value>
            <value>
                <fullName>Ahmadnagar</fullName>
                <isActive>false</isActive>
                <label>Ahmadnagar</label>
            </value>
            <value>
                <fullName>Aizawl</fullName>
                <isActive>false</isActive>
                <label>Aizawl</label>
            </value>
            <value>
                <fullName>Ajmer</fullName>
                <isActive>false</isActive>
                <label>Ajmer</label>
            </value>
            <value>
                <fullName>Akola</fullName>
                <isActive>false</isActive>
                <label>Akola</label>
            </value>
            <value>
                <fullName>Alappuzha</fullName>
                <isActive>false</isActive>
                <label>Alappuzha</label>
            </value>
            <value>
                <fullName>Aligarh</fullName>
                <isActive>false</isActive>
                <label>Aligarh</label>
            </value>
            <value>
                <fullName>Allahabad</fullName>
                <isActive>false</isActive>
                <label>Allahabad</label>
            </value>
            <value>
                <fullName>Almora</fullName>
                <isActive>false</isActive>
                <label>Almora</label>
            </value>
            <value>
                <fullName>Alwar</fullName>
                <isActive>false</isActive>
                <label>Alwar</label>
            </value>
            <value>
                <fullName>Ambala</fullName>
                <isActive>false</isActive>
                <label>Ambala</label>
            </value>
            <value>
                <fullName>Ambedkar Nagar</fullName>
                <isActive>false</isActive>
                <label>Ambedkar Nagar</label>
            </value>
            <value>
                <fullName>Amravati</fullName>
                <isActive>false</isActive>
                <label>Amravati</label>
            </value>
            <value>
                <fullName>Amreli</fullName>
                <isActive>false</isActive>
                <label>Amreli</label>
            </value>
            <value>
                <fullName>Amritsar</fullName>
                <isActive>false</isActive>
                <label>Amritsar</label>
            </value>
            <value>
                <fullName>Pune</fullName>
                <isActive>false</isActive>
                <label>Pune</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Town_Master__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Town Master</relationshipLabel>
    <relationshipName>Town_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Town_Master__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Town_Master__c/fields/Town_code__c.field-meta.xml
<CustomField>
    <fullName>Town_code__c</fullName>
    <label>Town code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/ProductRequestTestClass.cls
@isTest
Private class ProductRequestTestClass {
public static testMethod void testproduct(){
    Product2 p1=new Product2();
    p1.Name='Concealed valve';
    insert p1;
         OperatingHours oh = new OperatingHours();
        oh.Name = 'TestOH';
        oh.TimeZone='America/Los_Angeles';
        insert oh;
   
      ServiceTerritory s1=new ServiceTerritory();
        s1.Name='Bangalore';
        s1.IsActive=true;
        s1.OperatingHoursId=oh.id;
        insert s1;
      Town_Master__c tm=new Town_Master__c();
        tm.Name='Bangalore';
        tm.State__c='Karnataka';
        tm.District__c='Bangalore';
        tm.Service_Territory__c=s1.id;
        insert tm;
        
        Account acc1=new Account();
        acc1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Retail-Customer').getRecordTypeId();
        acc1.Name='Customer';
        acc1.Contact_Number_Mobile__c='12345678901';
        acc1.Can_you_please_give_address_retail__c='asdfghj';
        acc1.City_lookup__c=s1.id;
        acc1.State__c='Karnataka';
        acc1.Country_fsl__c='India';
        acc1.PinCode__c='123456';
        acc1.Town_Code__c='5670';
         acc1.Business_Line__c='Column';
        acc1.Products__c='CPVC';
        
        acc1.Town_Name__c=tm.id;
        insert acc1;
         
        Entitlement ent=new Entitlement();
         ent.name='Work Order Process';
         ent.AccountId=acc1.id;
         insert ent;
        
        Entitlement ent1=new Entitlement();
         ent1.name='Case Process';
         ent1.AccountId=acc1.id;
         insert ent1;
        
       
        
        ServiceTerritory s5=new ServiceTerritory();
        s5.Name='Pune';
        s5.IsActive=true;
        s5.OperatingHoursId=oh.id;
        insert s5;
        
        Product2 prod=new Product2();
        prod.Name='Concealed Valve';
        prod.IsActive=true;
        prod.Family='Concealed Valve';
        insert prod;
       
        Product2 prod1=new Product2();
        prod1.Name='Concealed Diverter';
        prod1.IsActive=true;
        prod1.Family='Diverter';
        insert prod1;
        
        WorkType work=new WorkType();
        work.Name='Concealed';
        work.DurationType='Hours';
        work.EstimatedDuration=5;
        insert work;
        
        Problem__c prob =new Problem__c();
        prob.Name='Concealed valve leakage';
        prob.Product__c=prod.Id;
        
        prob.Work_Type__c=work.id;
        insert prob;
        
         Problem__c prob1 =new Problem__c();
        prob1.Name='Concealed Diverter leakage';
        prob1.Product__c=prod1.Id;
        
        prob1.Work_Type__c=work.id;
        insert prob1;

       Contact con = new Contact(LastName ='testCon',Salutation='Mr',AccountId = acc1.Id);
       insert con;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Ashirvad Contractor Partner Community'];
        User u1=new User();
        u1.Alias='user1';
        u1.Email='test@gmail.com';
        u1.Username='test675433@gmail.com.123';
        u1.FirstName='test';
        u1.LastName='user';
        u1.ProfileId=p.id;
        u1.EmailEncodingKey='UTF-8';
        u1.LanguageLocaleKey='en_US';
        u1.LocaleSidKey='en_US';
        u1.IsActive=true;
        u1.ContactId=con.id;
        u1.TimeZoneSidKey='America/Los_Angeles';
        insert u1;
 
         ServiceResource sr=new ServiceResource();
        sr.Name='TestResource';
       // sr.ResourceType='Technician';
        sr.RelatedRecordId=u1.Id;
        sr.IsActive=true;
        insert sr;
        
          
        Territory_Contractors__c tc =new Territory_Contractors__c();
        tc.Name='Test';
        tc.Service_Territory__c=s1.Id;
        tc.Contractor__c= u1.id;
        tc.SAP_Code_ship__c='qwer';
        tc.SAP_Code_sold__c='sdf';
        insert tc;
    
    Schema.Location loc1=new Schema.Location();
    loc1.LocationType='Warehouse';
    loc1.Name='Test Warehouse';
    loc1.IsInventoryLocation=true;
    insert loc1;
    
    ProductItem pi=new ProductItem();
    pi.LocationId=loc1.id;
    pi.Product2Id=p1.id;
    pi.QuantityOnHand=20;
   insert pi;
    
    
    ProductRequest pr=new ProductRequest();
    pr.OwnerId=u1.id;
    pr.DestinationLocationId=loc1.id;
    pr.Status='Draft';
    insert pr;
    
    ProductRequestLineItem lineitem=new ProductRequestLineItem();
    lineitem.ParentId=pr.id;
    lineitem.DestinationLocationId=loc1.id;
    lineitem.Product2Id=p1.id;
    lineitem.QuantityRequested=10;
    lineitem.Status='Draft';
    insert lineitem;
    
     ProductRequest pro=new ProductRequest();
    pro.id=pr.id;
    pro.DestinationLocationId=loc1.id;
    pro.Status='Submitted';
    update pro;
    
     ProductRequest prodr=new ProductRequest();
    prodr.id=pr.id;
    prodr.DestinationLocationId=loc1.id;
    prodr.Status='Received';
    update prodr;
    
    
     ProductRequestLineItem lineitemz=new ProductRequestLineItem();
    lineitemz.ParentId=pr.id;
    lineitemz.DestinationLocationId=loc1.id;
    lineitemz.Product2Id=p1.id;
    lineitemz.QuantityRequested=10;
    lineitemz.Status='Draft';
    insert lineitemz;
    
    
    
    ProductRequest pr11=new ProductRequest();
     pr11.DestinationLocationId=loc1.id;
    pr11.Status='Draft';
    insert pr11;
    
      ProductRequest pr12=new ProductRequest();
    pr12.id=pr11.id;
         pr12.Status ='Submitted';
    update pr12;
    
     ProductRequest pr13=new ProductRequest();
    pr13.id=pr11.id;
    pr11.Status='Received';
    update pr13;
     ProductRequestLineItem lineitem1=new ProductRequestLineItem();
    lineitem1.id=lineitem.id;
   // lineitem1.ParentId=pr11.id;
    lineitem1.DestinationLocationId=loc1.id;
    lineitem1.Product2Id=p1.id;
    lineitem1.QuantityRequested=10;
    lineitem1.Quantity_Received__c=5;
    lineitem1.Status='Received';
    update lineitem1;
    
     ProductRequestLineItem lineitem11=new ProductRequestLineItem();
    lineitem11.id=lineitemz.id;
   // lineitem1.ParentId=pr11.id;
    lineitem11.DestinationLocationId=loc1.id;
    lineitem11.Product2Id=p1.id;
    lineitem11.QuantityRequested=10;
    lineitem11.Quantity_Received__c=10;
    lineitem11.Status='Received';
    update lineitem11;
    
    ProductRequest prre=new ProductRequest();
    prre.DestinationLocationId=loc1.id;
    prre.Status='Received';
    insert prre;
    
     
    ProductRequestLineItem line=new ProductRequestLineItem();
    line.ParentId=prre.id;
    line.DestinationLocationId=loc1.id;
    line.Product2Id=p1.id;
    line.QuantityRequested=10;
    line.Status='Draft';
    insert line;
    
}
}