Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/Tour_Plan1__c.object-meta.xml
<CustomObject>
    <label>Tour Plans</label>
    <nameField>
        <label>Tour Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/BD_Tour_Plans_1__c.field-meta.xml
<CustomField>
    <fullName>BD_Tour_Plans_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BD Tour Plans 1</label>
    <referenceTo>Tour_Plan1__c</referenceTo>
    <relationshipLabel>Tour Plans (BD Tour Plans 1)</relationshipLabel>
    <relationshipName>Tour_Plans3</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>JORDAN</fullName>
            </value>
            <value>
                <fullName>UNITED ARAB EMIRATES</fullName>
            </value>
            <value>
                <fullName>SAUDI ARABIA</fullName>
            </value>
            <value>
                <fullName>LIBYAN ARAB JAMAHIRIYA</fullName>
            </value>
            <value>
                <fullName>SOUTH AFRICA</fullName>
            </value>
            <value>
                <fullName>ITALY</fullName>
            </value>
            <value>
                <fullName>CYPRUS</fullName>
            </value>
            <value>
                <fullName>KUWAIT</fullName>
            </value>
            <value>
                <fullName>TURKEY</fullName>
            </value>
            <value>
                <fullName>GREECE</fullName>
            </value>
            <value>
                <fullName>OMAN</fullName>
            </value>
            <value>
                <fullName>IRAN, ISLAMIC REPUBLIC OF</fullName>
            </value>
            <value>
                <fullName>UNITED STATES</fullName>
            </value>
            <value>
                <fullName>SRI LANKA</fullName>
            </value>
            <value>
                <fullName>KENYA</fullName>
            </value>
            <value>
                <fullName>SYRIAN ARAB REPUBLIC</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>LEBANON</fullName>
            </value>
            <value>
                <fullName>SINGAPORE</fullName>
            </value>
            <value>
                <fullName>PORTUGAL</fullName>
            </value>
            <value>
                <fullName>SPAIN</fullName>
            </value>
            <value>
                <fullName>TUNISIA</fullName>
            </value>
            <value>
                <fullName>SUDAN</fullName>
            </value>
            <value>
                <fullName>COSTA RICA</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Location_1__c.field-meta.xml
<CustomField>
    <fullName>Location_1__c</fullName>
    <label>Location 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Location_2__c.field-meta.xml
<CustomField>
    <fullName>Location_2__c</fullName>
    <label>Location 2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Location_3__c.field-meta.xml
<CustomField>
    <fullName>Location_3__c</fullName>
    <label>Location 3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Architects__c.field-meta.xml
<CustomField>
    <fullName>No_of_Architects__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Architects (Planned)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Builders_Planned__c.field-meta.xml
<CustomField>
    <fullName>No_of_Builders_Planned__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No:of Builders (Planned)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Consultants__c.field-meta.xml
<CustomField>
    <fullName>No_of_Consultants__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Consultants (Planned)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Dealers__c.field-meta.xml
<CustomField>
    <fullName>No_of_Dealers__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Dealers (Planned)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Distributors__c.field-meta.xml
<CustomField>
    <fullName>No_of_Distributors__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Distributors (Planned)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Engineers__c.field-meta.xml
<CustomField>
    <fullName>No_of_Engineers__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Engineers (Planned)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Plumbing_Contractor__c.field-meta.xml
<CustomField>
    <fullName>No_of_Plumbing_Contractor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Plumbing Contractor (Planned)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Visit_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhatisgarh</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttaranchal</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
            <value>
                <fullName>Pondicherry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Tour_Plans_2__c.field-meta.xml
<CustomField>
    <fullName>Tour_Plans_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tour Plans 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Tour_Plan1__c.Date__c</field>
            <operation>equals</operation>
            <valueField>$Source.Date__c</valueField>
        </filterItems>
        <filterItems>
            <field>Tour_Plan1__c.CreatedBy.ManagerId</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tour_Plan1__c</referenceTo>
    <relationshipLabel>Tour Plans (Tour Plans 2)</relationshipLabel>
    <relationshipName>Tour_Plans1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Tour_Plans_3__c.field-meta.xml
<CustomField>
    <fullName>Tour_Plans_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tour Plans 3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Tour_Plan1__c.Date__c</field>
            <operation>equals</operation>
            <valueField>$Source.Date__c</valueField>
        </filterItems>
        <filterItems>
            <field>Tour_Plan1__c.CreatedBy.ManagerId</field>
            <operation>equals</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tour_Plan1__c</referenceTo>
    <relationshipLabel>Tour Plans (Tour Plans 3)</relationshipLabel>
    <relationshipName>Tour_Plans2</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Tour_Program__c.field-meta.xml
<CustomField>
    <fullName>Tour_Program__c</fullName>
    <label>Tour Program</label>
    <referenceTo>Tour_Program__c</referenceTo>
    <relationshipLabel>Tour Plans</relationshipLabel>
    <relationshipName>Tour_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/User_2__c.field-meta.xml
<CustomField>
    <fullName>User_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tour_Plans1</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/User_3__c.field-meta.xml
<CustomField>
    <fullName>User_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tour_Plans2</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tour_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Worked_With__c.field-meta.xml
<CustomField>
    <fullName>Worked_With__c</fullName>
    <label>Worked With</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/Tour_Program__c.object-meta.xml
<CustomObject>
    <label>Tour Program</label>
    <nameField>
        <label>Tour Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/BD_Tour_Plans_1__c.field-meta.xml
<CustomField>
    <fullName>BD_Tour_Plans_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BD Tour Plans 1</label>
    <referenceTo>Tour_Plan1__c</referenceTo>
    <relationshipLabel>Tour Programs</relationshipLabel>
    <relationshipName>Tour_Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/UpdateIncomeClass.cls
/** Company - Epeople Bespoke Consulting Private Limited.
     Description -For one Tour Program Tour plan Willbe created for 1 week i.e 7 days.For 
     all the 7 Records same page have to be edited.For that we are using this Class and Mass Edit visualforce page and added this vf Page to Tpur Plan button
     Created By  -Prabha.k 11/02/2014
     Modified By  -prabha.k 12/02/2014
**/
public with sharing class UpdateIncomeClass {
public Id opid{get;set;}
public Tour_Program__c tp{get;set;}
public Id aid {get;set;}
  List<Tour_Plan1__c> UpdateList=new List<Tour_Plan1__c>();
public UpdateIncomeClass(ApexPages.StandardController controller) 
    {
        String  opid=ApexPages.CurrentPage().getParameters().get('Id');
        tp=[SELECT Id, Name,From_Date__c,To_Date__c FROM Tour_Program__c WHERE Id = :opid]; 
        plans=[select id,name,Date__c,State__c,Country__c,District__c,Worked_With__c,BD_Tour_Plans_1__c,Tour_Plans_2__c,Tour_Plans_3__c,District_1__c,District_2__c,District_3__c,Location__c,Location_1__c,Location_2__c,Location_3__c,User__c,User_2__c,User_3__c,No_of_Architects__c,No_of_Consultants__c,No_of_Plumbing_Contractor__c,No_of_Dealers__c,No_of_Distributors__c,No_of_Engineers__c,No_of_Builders_Planned__c,Other_Contacts_If_Any__c, Visit_Type__c 
               from Tour_Plan1__c where Tour_Program__c=:tp.id ORDER BY Date__c  ASC] ;  
        
      
    }
Public void Autorun()
    {
       
     
    }
    
private List<Tour_Plan1__c > plans;
private List<Tour_Plan1__c > plans1;
public List<Tour_Plan1__c > getplans() 
  {     
      return plans;
  }
public List<Tour_Plan1__c > getplans1() 
  {          
      return plans1;
  }  
  
public void GetID(){
      
      system.debug('aid'+aid);     
  }
 
public PageReference UpdateRecords()
   {
       update plans;
       PageReference pageRef = new PageReference('/'+ ApexPages.currentPage().getParameters().get('id'));
       return pageRef;    
    
   }
}