Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/Tour_Plan1__c.object-meta.xml
<CustomObject>
    <label>Tour Plans</label>
    <nameField>
        <label>Tour Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Visit_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhatisgarh</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttaranchal</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
            <value>
                <fullName>Pondicherry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Tour_Program__c.field-meta.xml
<CustomField>
    <fullName>Tour_Program__c</fullName>
    <label>Tour Program</label>
    <referenceTo>Tour_Program__c</referenceTo>
    <relationshipLabel>Tour Plans</relationshipLabel>
    <relationshipName>Tour_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/Tour_Program__c.object-meta.xml
<CustomObject>
    <label>Tour Program</label>
    <nameField>
        <label>Tour Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/TestCreateTourplan.cls
/** Company - Epeople Bespoke Consulting Private Limited.
     Description -Test Class for SetPrimaryContact
     Created By  -Prabha.K 20/02/2014
     Modified By  -Prabha.K 21/02/2014
**/
@isTest
public class TestCreateTourplan
{
static testmethod void TestgetTour()
{
Test.StartTest();
Tour_Program__c tp1=new Tour_Program__c();

tp1.From_Date__c=Date.newInstance(2014 , 10 ,01);
tp1.To_Date__c=Date.newInstance(2014 , 10 ,15);
insert tp1;
 Tour_Plan1__c top=new Tour_Plan1__c(Name='test12', Tour_Program__c=tp1.id,Date__c=System.Today(),State__c='TamilNadu',District__c='Tirunelveli',Location__c='local');
   insert top;

Test.StopTest();
}
}