Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Districts</relationshipLabel>
    <relationshipName>Districts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/Tour_Plan1__c.object-meta.xml
<CustomObject>
    <label>Tour Plans</label>
    <nameField>
        <label>Tour Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Builders_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Builders_Meet_Actuals__c</fullName>
    <label>Builders Meet (Actuals)(not used)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Expenses_Approved__c.field-meta.xml
<CustomField>
    <fullName>Expenses_Approved__c</fullName>
    <formula>Tour_Program__r.Expenses_Approved__c =True</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expenses Approved</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Expenses_Details__c.field-meta.xml
<CustomField>
    <fullName>Expenses_Details__c</fullName>
    <label>Expenses Details</label>
    <type>TextArea</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Fare__c.field-meta.xml
<CustomField>
    <fullName>Fare__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Farmers_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Farmers_Meet_Actuals__c</fullName>
    <label>Farmers Meet (Actuals)(not used)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Food_and_Boarding__c.field-meta.xml
<CustomField>
    <fullName>Food_and_Boarding__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Food and Boarding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Jeep_Campaign_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Jeep_Campaign_Actuals__c</fullName>
    <label>Jeep Campaign (Actuals)(not used)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Location_1__c.field-meta.xml
<CustomField>
    <fullName>Location_1__c</fullName>
    <label>Location 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Lodge__c.field-meta.xml
<CustomField>
    <fullName>Lodge__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lodge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Mechanics_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Mechanics_Meet_Actuals__c</fullName>
    <label>Mechanics Meet (Actuals)(not used)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Mini_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Mini_Meet_Actuals__c</fullName>
    <label>Mini Meet (Actuals)(not used)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Mode_of_Travel__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Travel__c</fullName>
    <label>Mode of Travel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>Bike</fullName>
            </value>
            <value>
                <fullName>Bus</fullName>
            </value>
            <value>
                <fullName>Car</fullName>
            </value>
            <value>
                <fullName>Jeep</fullName>
            </value>
            <value>
                <fullName>Train</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Air Plane</fullName>
            </value>
            <value>
                <fullName>Taxi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Architects1__c.field-meta.xml
<CustomField>
    <fullName>No_of_Architects1__c</fullName>
    <label>No:of Architects (Actuals)</label>
    <summaryFilterItems>
        <field>Site_Visit__c.Party_Type__c</field>
        <operation>equals</operation>
        <value>Architect</value>
    </summaryFilterItems>
    <summaryForeignKey>Site_Visit__c.Tour_Plan1__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Consultant__c.field-meta.xml
<CustomField>
    <fullName>No_of_Consultant__c</fullName>
    <label>No:of Consultant (Actuals)</label>
    <summaryFilterItems>
        <field>Site_Visit__c.Party_Type__c</field>
        <operation>equals</operation>
        <value>Consultant</value>
    </summaryFilterItems>
    <summaryForeignKey>Site_Visit__c.Tour_Plan1__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/No_of_Dealer__c.field-meta.xml
<CustomField>
    <fullName>No_of_Dealer__c</fullName>
    <label>No:of Dealer (Actuals)</label>
    <summaryFilterItems>
        <field>Site_Visit__c.Party_Type__c</field>
        <operation>equals</operation>
        <value>Dealer</value>
    </summaryFilterItems>
    <summaryForeignKey>Site_Visit__c.Tour_Plan1__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Visit_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhatisgarh</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttaranchal</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
            <value>
                <fullName>Pondicherry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan1__c/fields/Tour_Program__c.field-meta.xml
<CustomField>
    <fullName>Tour_Program__c</fullName>
    <label>Tour Program</label>
    <referenceTo>Tour_Program__c</referenceTo>
    <relationshipLabel>Tour Plans</relationshipLabel>
    <relationshipName>Tour_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/Tour_Program__c.object-meta.xml
<CustomObject>
    <label>Tour Program</label>
    <nameField>
        <label>Tour Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tour Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/Builders_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Builders_Meet_Actuals__c</fullName>
    <label>Builders Meet (Actuals)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/Ex_Station_Visit_Days__c.field-meta.xml
<CustomField>
    <fullName>Ex_Station_Visit_Days__c</fullName>
    <label>Ex Station Visit Days</label>
    <summaryFilterItems>
        <field>Tour_Plan1__c.Visit_Type__c</field>
        <operation>equals</operation>
        <value>Ex-Outstation</value>
    </summaryFilterItems>
    <summaryForeignKey>Tour_Plan1__c.Tour_Program__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/Expenses_Approved__c.field-meta.xml
<CustomField>
    <fullName>Expenses_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expenses Approved</label>
    <type>Checkbox</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/Farmers_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Farmers_Meet_Actuals__c</fullName>
    <label>Farmers Meet (Actuals)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/H_Q_Visit_Days__c.field-meta.xml
<CustomField>
    <fullName>H_Q_Visit_Days__c</fullName>
    <label>H.Q Visit Days</label>
    <summaryFilterItems>
        <field>Tour_Plan1__c.Visit_Type__c</field>
        <operation>equals</operation>
        <value>Head Quarter</value>
    </summaryFilterItems>
    <summaryForeignKey>Tour_Plan1__c.Tour_Program__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/Jeep_Campaign_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Jeep_Campaign_Actuals__c</fullName>
    <label>Jeep Campaign (Actuals)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/Mechanics_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Mechanics_Meet_Actuals__c</fullName>
    <label>Mechanics Meet (Actuals)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/Mini_Meet_Actuals__c.field-meta.xml
<CustomField>
    <fullName>Mini_Meet_Actuals__c</fullName>
    <label>Mini Meet (Actuals)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/Out_Station_Visit_Days__c.field-meta.xml
<CustomField>
    <fullName>Out_Station_Visit_Days__c</fullName>
    <label>Out Station Visit Days</label>
    <summaryFilterItems>
        <field>Tour_Plan1__c.Visit_Type__c</field>
        <operation>equals</operation>
        <value>Out Station</value>
    </summaryFilterItems>
    <summaryForeignKey>Tour_Plan1__c.Tour_Program__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Program__c/fields/User_State__c.field-meta.xml
<CustomField>
    <fullName>User_State__c</fullName>
    <formula>Owner:User.State__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User State</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/TorProgramClass.cls
public with sharing class TorProgramClass 
{
    Public Id TPId;
    Public Integer ExStation{get;set;}
    Public Integer OutStation{get;set;}
    Public Integer HeadQuarter{get;set;}
    Public Tour_Program__c TourProgrm{get;set;}
    Public User user{get;set;}
    Public List<Tour_Plan1__c> TourPlans{get;set;}
    public TorProgramClass(ApexPages.StandardController controller) 
        {
            TPId=ApexPages.CurrentPage().getParameters().get('Id');
            TourProgrm=[SELECT id,Name,OwnerId,H_Q_Visit_Days__c,Out_Station_Visit_Days__c,Ex_Station_Visit_Days__c,From_Date__c,To_Date__c FROM Tour_Program__c WHERE id=:TPId];
            user=[SELECT id,Name,State,Head_Quarter__c,EmployeeNumber,User_State__c FROM User WHERE id=:TourProgrm.OwnerId];
            TourPlans=[SELECT id,Name,Courier__c,
                        Date__c,District__c,
                        District_1__c,Expenses_Approved__c,Expenses_Details__c,Fare__c,
                        Farmers_Meet_Actuals__c,Builders_Meet_Actuals__c,Food_and_Boarding__c,From__c,Jeep_Campaign_Actuals__c,Local_Conveyance__c,Location__c,Location_1__c,
                        Lodge__c,Market_Type__c,Mechanics_Meet_Actuals__c,Mini_Meet_Actuals__c,Miscellaneous__c,Miscellaneous_Details__c,Mode_of_Travel__c,No_of_Architects1__c,
                        No_of_Consultant__c,No_of_Dealer__c,
                        Plumber_Mechanic_Engineers_Factory_Visit__c,Plumbers_Meet_Actuals__c,Remarks__c,
                        Remarks_for_Not_meeting_the_Visit_Target__c,Shandy_Show_Actuals__c,State__c,Stationery_and_Photocopy__c,Telephone_Fax_Internet__c,To__c,
                        Total_Expenses__c,Total_Visits_Target__c,Tour_Program__c,Tour_Program_Approved__c,Tractor_Show_Actuals__c,Visit_Type__c FROM Tour_Plan1__c WHERE Tour_Program__c=:TourProgrm.id Order By Date__c ASC ];
           System.Debug('###*****@@@@@@@@@@-------->>>>>>>>'+TourPlans);             
        }
   

}