Partial_14Dec2021/force-app/main/default/objects/AWS_S3__c/AWS_S3__c.object-meta.xml
<CustomObject>
    <label>AWS S3</label>
    <nameField>
        <label>AWS S3 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AWS S3</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AWS_S3__c/fields/AccessKey__c.field-meta.xml
<CustomField>
    <fullName>AccessKey__c</fullName>
    <label>AccessKey</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AWS_S3__c/fields/BucketName__c.field-meta.xml
<CustomField>
    <fullName>BucketName__c</fullName>
    <label>BucketName</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AWS_S3__c/fields/Prefix__c.field-meta.xml
<CustomField>
    <fullName>Prefix__c</fullName>
    <label>Prefix</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AWS_S3__c/fields/SecretKey__c.field-meta.xml
<CustomField>
    <fullName>SecretKey__c</fullName>
    <label>SecretKey</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/sales_accrual__c/sales_accrual__c.object-meta.xml
<CustomObject>
    <label>Sales Accrual</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Sales Accrual Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Accrual</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/sales_accrual__c/fields/Bill_Image__c.field-meta.xml
<CustomField>
    <fullName>Bill_Image__c</fullName>
    <label>Bill Image</label>
    <type>Url</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/AWSUtility.cls
public class AWSUtility {
    @AuraEnabled
    public static String fetchBillImage(String recordId){
        sales_accrual__c sa = [select Id, Bill_Image__c from sales_accrual__c where Id =: recordId];
        String billImage = sa.Bill_Image__c;
        System.debug('Bill Image: '+ billImage);
        return billImage;
    }
    
    @AuraEnabled
    public static string getSignedURL(string file) {
        String filename = EncodingUtil.urlEncode(file, 'UTF-8');
       
        AWS_S3__c a = [select BucketName__c,AccessKey__c,SecretKey__c, Prefix__c from AWS_S3__c limit 1];
        String BucketName=a.BucketName__c;
        String AccessKey= a.AccessKey__c;
        String SecretKey= a.SecretKey__c;
        String Prefix = a.Prefix__c;
        Datetime now = DateTime.now();
        Datetime expireson = now.AddSeconds(60); // Lifespan of the link
        Long Lexpires = expireson.getTime()/1000;
        
        String stringtosign = 'GET\n\n\n'+Lexpires+'\n/'+BucketName+'/'+Prefix+'/'+BucketName+'/'+filename;
        System.debug('redirectToS3Key stringstosign: ' + stringtosign);
        
        String signingKey = EncodingUtil.base64Encode(Blob.valueOf(SecretKey));
        Blob mac = Crypto.generateMac('HMacSHA1', blob.valueof(stringtosign),blob.valueof(SecretKey)); 
        String signed= EncodingUtil.base64Encode(mac);     
        String codedsigned = EncodingUtil.urlEncode(signed,'UTF-8');
        String url = 'https://'+BucketName+'.s3.amazonaws.com/'+Prefix+'/'+BucketName+'/'+filename+'?AWSAccessKeyId='+AccessKey+
            '&Expires='+Lexpires+'&Signature='+signed;

        return url;
        
    }
}

/*
To run in anonymous window use following lines.

String file='/cloud-cube-jp/media/abc_HfeRUmG.png';
String url = AWSUtility.getSignedURL(file);
System.debug('Presigned URL: '+url);
* */