Partial_14Dec2021/force-app/main/default/objects/AWS_S3__c/AWS_S3__c.object-meta.xml
<CustomObject>
    <label>AWS S3</label>
    <nameField>
        <label>AWS S3 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AWS S3</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AWS_S3__c/fields/AccessKey__c.field-meta.xml
<CustomField>
    <fullName>AccessKey__c</fullName>
    <label>AccessKey</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AWS_S3__c/fields/BucketName__c.field-meta.xml
<CustomField>
    <fullName>BucketName__c</fullName>
    <label>BucketName</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AWS_S3__c/fields/SecretKey__c.field-meta.xml
<CustomField>
    <fullName>SecretKey__c</fullName>
    <label>SecretKey</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/sales_accrual__c/sales_accrual__c.object-meta.xml
<CustomObject>
    <label>Sales Accrual</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Sales Accrual Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Accrual</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/sales_accrual__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INITIATED</fullName>
                <default>true</default>
                <label>INITIATED</label>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>ON HOLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/sales_accrual__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Sales Accrual</relationshipLabel>
    <relationshipName>Sales_Accrual_Transaction</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TN-{000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>PROCESSED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>INITIATED</fullName>
            </value>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>ON HOLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/AWSUtilityTest.cls
/* Test class for AWSUtility */
@isTest
public class AWSUtilityTest {
    
    public static testMethod void fetchBillImageTest(){
        Transaction__c t = new Transaction__c(Status__c='PENDING');
        insert t;
        sales_accrual__c sa = new sales_accrual__c(Transaction__c=t.Id);
        insert sa;
        
        String file = AWSUtility.fetchBillImage(sa.Id);
    }
    
    public static testMethod void getSignedURLTest(){
        String BucketName='abc.com';
        String AccessKey= '12345';
        String SecretKey= '6789';
        AWS_S3__c aws = new AWS_S3__c(BucketName__c=BucketName, AccessKey__c=AccessKey,SecretKey__c=SecretKey);
        insert aws;
        
        String url = AWSUtility.getSignedURL('abc.png');
    }
}