Partial_14Dec2021/force-app/main/default/objects/Quiz_Attendee__c/Quiz_Attendee__c.object-meta.xml
<CustomObject>
    <label>Quiz Attendee</label>
    <nameField>
        <displayFormat>ATT-{00000}</displayFormat>
        <label>Quiz Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Quiz_Attendee__c/fields/Quiz_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz Attendee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quiz_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Quiz_Attendee__c/fields/Quiz_Catagory__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Catagory__c</fullName>
    <label>Quiz Catagory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture Junior</fullName>
            </value>
            <value>
                <fullName>Agriculture Senior</fullName>
            </value>
            <value>
                <fullName>Plumbing Junior</fullName>
            </value>
            <value>
                <fullName>Plumbing Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Quiz_Attendee__c/fields/Quiz_status__c.field-meta.xml
<CustomField>
    <fullName>Quiz_status__c</fullName>
    <label>Quiz status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/Quiz_validation_controller.cls
public with sharing class Quiz_validation_controller{

    //declaration and initialisation of variables used
    private final User candidate;
    List<User> listCand=new list<User>();
    public Integer MonthDay {get; set;}  
    
    //constructor
    public Quiz_validation_controller(ApexPages.StandardController controller){
        this.candidate=(User)controller.getRecord();
        MonthDay = Date.Today().Day();
    }
    
     //method to send a security token to the test taker
        
    //method to navigate to the next page and modify the candidate object to have the final time taken calculated
    public PageReference navigate(){
        
        try{
        system.debug('MonthDay:::'+ MonthDay  );
        if(MonthDay  == 04 || MonthDay == 05 || MonthDay  == 06 ){ 
        
        User loggedUserDetail = [Select Quiz_catagory__c from User where id =: UserInfo.getUserId()];
        if(loggedUserDetail.Quiz_catagory__c =='' || loggedUserDetail.Quiz_catagory__c == null){
         ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,
        'Your user profile does not fall into any of the quiz catagory. Please contact your administator'));
        return null;
        }
           autoRequestBatchHelper autoRequest = new autoRequestBatchHelper();
                
                String thisMonth = autoRequest.getCurrentMonth();
               // List<Quiz_Attendee__c> atendeeToUpsert = new List<Quiz_Attendee__c>();
                List<Quiz_Attendee__c> atendees = [select Quiz_Attendee__c, Quiz_Catagory__c, Quiz_status__c, Quiz_Month__c
                 from Quiz_Attendee__c where Quiz_Attendee__c =: UserInfo.getUserId() and Quiz_Month__c=: thisMonth]; 
                
                if(atendees.size() == 0){
                Quiz_Attendee__c atendeeDetail = new Quiz_Attendee__c();
                atendeeDetail.Quiz_Attendee__c=UserInfo.getUserId();
                atendeeDetail.Quiz_Month__c = thisMonth;
                atendeeDetail.Quiz_status__c='Started';
                atendeeDetail.Quiz_Catagory__c =loggedUserDetail.Quiz_catagory__c;
                //atendeeToUpsert.add(atendeeDetail);
                upsert atendeeDetail;
                }
                else{
                for(Quiz_Attendee__c atend : atendees){
                if(atend.Quiz_status__c=='Completed'){
              
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,
        'You have already attempted the quiz for this month. Hence you will not be able to take the Quiz again'));
        return null;
        
                }
               
                }
                }
                
                
        
             PageReference firstPage = new PageReference ('/apex/QuizQuestionPage');
                firstPage.getParameters().put('ID', userInfo.getUserId());
                firstPage.setRedirect(false);
                return firstPage;           
             }
             else{
              PageReference secondPage = new PageReference ('/apex/QuizErrorPage');
             return secondPage; 
             }
                    }
       
         catch(exception e){system.debug(e.getMessage()); return null;} 
        }
    }