Partial_14Dec2021/force-app/main/default/objects/Quiz_Attendee__c/Quiz_Attendee__c.object-meta.xml
<CustomObject>
    <label>Quiz Attendee</label>
    <nameField>
        <displayFormat>ATT-{00000}</displayFormat>
        <label>Quiz Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Quiz_Attendee__c/fields/Quiz_Attendee__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz Attendee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quiz_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Quiz_Attendee__c/fields/Quiz_Catagory__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Catagory__c</fullName>
    <label>Quiz Catagory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture Junior</fullName>
            </value>
            <value>
                <fullName>Agriculture Senior</fullName>
            </value>
            <value>
                <fullName>Plumbing Junior</fullName>
            </value>
            <value>
                <fullName>Plumbing Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Quiz_Attendee__c/fields/Quiz_status__c.field-meta.xml
<CustomField>
    <fullName>Quiz_status__c</fullName>
    <label>Quiz status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/Quiz_validation_controller_UT.cls
@isTest
public class Quiz_validation_controller_UT{
    
    static testMethod void Quizvalidationcontrollertest(){
        
        Profile profile= [Select Id from Profile where name='System Administrator' limit 1];
        User user= new User( Quiz_Catagory__c='Agriculture Junior',FirstName='Test', EmployeeNumber='1234',LastName='User', alias='abcd', email='testuser@abc.com', username='testuserXYZ@abc.com', profileId=profile.Id, TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
        insert user;
        
        
        test.startTest();
        Date MyDate = Date.newInstance(2019, 1, 30);
        System.runAs(user)
        { 
            
            ApexPages.currentPage().getParameters().put('id', user.id); 
            ApexPages.StandardController sc = new ApexPages.StandardController(new user());     
            Quiz_validation_controller cont = new Quiz_validation_controller(sc);
            cont.MonthDay=2;
            PageReference ref=cont.navigate();
        }
        test.stopTest();
    }
    
    static testMethod void Quizvalidationcontrollertest1(){
        
        Profile profile= [Select Id from Profile where name='System Administrator' limit 1];
        User user= new User( Quiz_Catagory__c='Agriculture Senior',FirstName='Test', LastName='User',EmployeeNumber='1234', alias='abcd', email='testuser@abc.com', username='testuserGHI@abc.com', profileId=profile.Id, TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
        insert user;
        
        Quiz_Attendee__c atendeeDetail = new Quiz_Attendee__c();
        atendeeDetail.Quiz_Attendee__c=user.id;
        atendeeDetail.Quiz_Month__c = 'September - 2019';
        atendeeDetail.Quiz_status__c='Completed';
        atendeeDetail.Quiz_Catagory__c ='Agriculture Senior';
        insert atendeeDetail;
        test.startTest();
        System.runAs(user)
        { 
            ApexPages.currentPage().getParameters().put('id', user.id); 
            ApexPages.StandardController sc = new ApexPages.StandardController(new user());
            Quiz_validation_controller cont = new Quiz_validation_controller(sc);
            cont.MonthDay=3;
            PageReference ref=cont.navigate();
        }
        test.stopTest();
    }
    
    static testMethod void Quizvalidationcontrollertest2(){
        
        Profile profile= [Select Id from Profile where name='System Administrator' limit 1];
        User user= new User( FirstName='Test', LastName='User', alias='abcd', email='testuser@abc.com', username='testuserPQR@abc.com',EmployeeNumber='1234', profileId=profile.Id, TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
        insert user;
        Integer MonthDay = Date.Today().Day();
        
        test.startTest();
        System.runAs(user)
        { 
            ApexPages.currentPage().getParameters().put('id', user.id); 
            ApexPages.StandardController sc = new ApexPages.StandardController(new user());
            Quiz_validation_controller cont = new Quiz_validation_controller(sc);
            cont.MonthDay=1;
            PageReference ref=cont.navigate();
        }
        test.stopTest();
    }
    
    static testMethod void Quizvalidationcontrollertest3(){
        
        Profile profile= [Select Id from Profile where name='System Administrator' limit 1];
        User user= new User( Quiz_Catagory__c='Agriculture Junior',FirstName='Test',EmployeeNumber='1234', LastName='User', alias='abcd', email='testuser@abc.com', username='testuserLMN@abc.com', profileId=profile.Id, TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
        insert user;
        Integer MonthDay = 1;
        Quiz_Attendee__c atendeeDetail = new Quiz_Attendee__c();
        atendeeDetail.Quiz_Attendee__c=user.id;
        atendeeDetail.Quiz_Month__c = 'December - 2015';
        atendeeDetail.Quiz_status__c='Completed';
        atendeeDetail.Quiz_Catagory__c ='Agriculture Junior';
        
        insert atendeeDetail;
        test.startTest();
        System.runAs(user)
        { 
            ApexPages.currentPage().getParameters().put('id', user.id); 
            ApexPages.StandardController sc = new ApexPages.StandardController(new user());
            Quiz_validation_controller cont = new Quiz_validation_controller(sc);
            
            PageReference ref=cont.navigate();
        }
        test.stopTest();
    }
    
    static testMethod void Quizvalidationcontrollertest4(){
        
        Profile profile= [Select Id from Profile where name='System Administrator' limit 1];
        User user= new User( FirstName='Test', LastName='User', alias='abcd', email='testuser@abc.com',EmployeeNumber='1234' ,username='testuserMBA@abc.com', profileId=profile.Id, TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
        insert user;
        Integer MonthDay = Date.Today().Day();
        autoRequestBatchHelper autoRequest = new autoRequestBatchHelper();
        
        String thisMonth = autoRequest.getCurrentMonth();
        Quiz_Attendee__c atendeeDetail = new Quiz_Attendee__c();
        atendeeDetail.Quiz_Attendee__c=user.id;
        atendeeDetail.Quiz_Month__c = thisMonth;
        atendeeDetail.Quiz_status__c='Started';
        atendeeDetail.Quiz_Catagory__c ='Agriculture Junior';
        
        insert atendeeDetail;
        test.startTest();
        System.runAs(user)
        { 
            ApexPages.currentPage().getParameters().put('id', user.id); 
            ApexPages.StandardController sc = new ApexPages.StandardController(new user());
            
            Quiz_validation_controller cont = new Quiz_validation_controller(sc);
            cont.MonthDay=1;
            PageReference ref=cont.navigate();
        }
        test.stopTest();
    }
}