Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/Unique_SPR__c.object-meta.xml
<CustomObject>
    <description>This object contains the unique name of each spr. Uniqueness is valid for a specific project. This record goes for approval in the new revamp structure.</description>
    <label>Unique SPR</label>
    <nameField>
        <displayFormat>UN-{000}</displayFormat>
        <label>Unique Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unique SPRs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Number_of_SPR_s__c.field-meta.xml
<CustomField>
    <fullName>Number_of_SPR_s__c</fullName>
    <description>count the number of spr under a particular record</description>
    <label>Number of SPR&apos;s</label>
    <summaryForeignKey>New_Special_Pricing_Request__c.Unique_SPR__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Unique_SPR__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Unique SPRs</relationshipLabel>
    <relationshipName>Unique_SPRs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/ItemsToApproveCustomControllerCls.cls
/*****************************************************************************************************************************************
*Created By:  Subhajit Ghosh
*company:     KVP
*Description: Display the items to be approved in the Lightning home page. It displays the Project name instead of the Unique SPR 
name. This is a quick link to go the project. 
****************************************************************************************************************************************/
public class ItemsToApproveCustomControllerCls {
public List<uniqueProjectName> uniqueProjectNameList{get;set;}
public  List<Unique_SPR__c> uniqueSprList;
public List<Id> uniqueSprId;
public List<ProcessInstanceWorkItem> ProcessInstanceWorkItemList;
public Map<Id,String> mapProjectwithID;
public Map<Id,String> mapUserNamewithID;

public ItemsToApproveCustomControllerCls(){
    
    String currentLoggedUserId=UserInfo.getUserId();// logged in user id- 
    uniqueSprId=new List<Id>();
    uniqueSprList=new List<Unique_SPR__c>();
    mapProjectwithID=new Map<Id,String>();
    mapUserNamewithID=new Map<Id,String>();
    uniqueProjectNameList=new List<uniqueProjectName>();
    uniqueSprList=[SELECT id from Unique_SPR__c WHERE Approval_Status__c=:'Pending' AND Number_of_SPR_s__c>:0];//query the pending spr's from object
    if(uniqueSprList.size() > 0){
        for(Unique_SPR__c ids : uniqueSprList){
            uniqueSprId.add(ids.id); 
        }
    }
    //to get the list of uniqueSpr that are pending 
    ProcessInstanceWorkItemList=new List<ProcessInstanceWorkItem>(); 
    ProcessInstanceWorkItemList=[SELECT ProcessInstance.TargetObjectId FROM ProcessInstanceWorkItem 
                                WHERE ProcessInstance.Status = 'Pending' AND ActorId =: currentLoggedUserId
                                AND ProcessInstance.TargetObjectId IN: uniqueSprId order by createddate desc] ;
    system.debug('ProcessInstanceWorkItemList--'+ProcessInstanceWorkItemList);
    
    if(ProcessInstanceWorkItemList.size()>0){
        uniqueSprId.clear(); 
        uniqueSprList.clear();
        
        for(ProcessInstanceWorkItem pro:ProcessInstanceWorkItemList){
            uniqueSprId.add(pro.ProcessInstance.TargetObjectId);
        }
        
        uniqueSprList=[select id,Project__c,Project__r.Name,Project__r.Owner.Name FROM Unique_SPR__c where ID IN: uniqueSprId order by createddate desc]; 
        
        for(Unique_SPR__c un : uniqueSprList){
            if(!mapProjectwithID.containsKey(un.Project__c)){
                mapProjectwithID.put(un.Project__c,un.Project__r.Name);
            } 
            if(!mapUserNamewithID.containsKey(un.Project__c)){
                mapUserNamewithID.put(un.Project__c,un.Project__r.Owner.Name);
            } 
            
        }
        
        if(mapProjectwithID.size()>0){
            for (Id ids : mapProjectwithID.keySet()){
                uniqueProjectName unInstance=new uniqueProjectName();
                unInstance.ProjectName=mapProjectwithID.get(ids);
                unInstance.recordId=ids;
                unInstance.submittedBy=mapUserNamewithID.get(ids);
                uniqueProjectNameList.add(unInstance);
            }  
            
        }
        
        
        
    }
    
    
}


public class uniqueProjectName{
    public Id recordId{get;set;}
    public String ProjectName{get;set;}
    public String submittedBy{get;set;}
}


}