Partial_14Dec2021/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Special Pricing Request</label>
    <nameField>
        <displayFormat>ON-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Pricing Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Order__c/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <label>Projects</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Special Pricing Requests</relationshipLabel>
    <relationshipName>Special_Pricing_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Projects__c/Projects__c.object-meta.xml
<CustomObject>
    <label>Projects(O)</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects(O)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/Addrowspecialpricingreq.cls
public class Addrowspecialpricingreq 
{
    public String sid{get;set;}
    public account acc{get;set;}
    public Addrowspecialpricingreq(ApexPages.StandardController controller) {
    orderList = new list<order__c>();
    sid=Apexpages.currentpage().getparameters().get('id');
    }


    public PageReference saveorder() {
     insert orderList;
     pagereference pg = new pagereference('/'+sid);
        return pg;
    }
     public PageReference cancelorder() {
   
     pagereference pf = new pagereference('/'+sid);
        return pf;
    }

    public  List<Order__c> orderList {get;set;}
    public List<Order__c> orderAddList {get;set;}
    public String ordervalue {get;set;}   
    
    public Addrowspecialpricingreq()
    {
       
    }
    public void AddRow()
    {
        orderList .add(new Order__c(projects__C=sid));
    }  
}