Partial_14Dec2021/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Special Pricing Request</label>
    <nameField>
        <displayFormat>ON-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Pricing Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order__c/fields/Order_Value__c.field-meta.xml
<CustomField>
    <fullName>Order_Value__c</fullName>
    <label>Total MRP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Order__c/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <label>Projects</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Special Pricing Requests</relationshipLabel>
    <relationshipName>Special_Pricing_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Projects__c/Projects__c.object-meta.xml
<CustomObject>
    <label>Projects(O)</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects(O)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/TestAddrowspecialpricingreq.cls
@isTest
public class TestAddrowspecialpricingreq 
{
     Static TestMethod Void Addrowspecialpricingreq()
     {
     Profile p=[SELECT Id From Profile WHERE Name='Standard User'];
         User u2 =new User( Alias = 'newUser1' ,
                            Email ='newuser123456@testorg.com',
                            EmailEncodingKey = 'UTF-8',
                            LastName = 'Testing',
                            LanguageLocaleKey='en_US',
                            LocaleSidKey='en_US', 
                            UserName='newuser_Satya@testorg.com',
                            ProfileId=p.Id,
                            TimeZoneSidKey    = 'America/Los_Angeles');

    System.runAs(u2) {
         Test.StartTest();
         //RecordType rt = [SELECT Id,Name FROM RecordType WHERE SobjectType='Account' and Name='Projects' LIMIT 1];
         Account acc = new Account();
         acc.Name= 'Test AccountAAP';
         acc.Type1__c='Commercial';
         acc.No_of_Bathrooms__c=5;
         acc.Contact_Number_Mobile__c='9898969694';
         acc.Order_Status__c='Order Loss';
         //acc.RecordTypeId= rt.Id;
         insert acc;
         
         
         Order__c oc = new Order__c();
         oc.Order_Value__c=10000;
         oc.Projects__c=acc.Id;
         insert oc;
         
        ApexPAges.StandardController scon = new ApexPages.StandardController(acc);
        Addrowspecialpricingreq  testExt = new Addrowspecialpricingreq (scon);
        PageReference pageRef = Page.Specialpricingrequestorder;
        pageRef.getParameters().put('id', String.valueOf(acc.Id));
        Test.setCurrentPage(pageRef);
        testExt.saveorder();
        testExt.cancelorder();
        testExt.AddRow();
        Test.StopTest();
       
       }
     }
     }