Partial_14Dec2021/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Special Pricing Request</label>
    <nameField>
        <displayFormat>ON-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Pricing Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Order__c/fields/Projects__c.field-meta.xml
<CustomField>
    <fullName>Projects__c</fullName>
    <label>Projects</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Special Pricing Requests</relationshipLabel>
    <relationshipName>Special_Pricing_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Projects__c/Projects__c.object-meta.xml
<CustomObject>
    <label>Projects(O)</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects(O)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/TestProjectclass.cls
@isTest
public class TestProjectclass 
{
     Static TestMethod Void TestProject()
     {
     Test.StartTest();
     Account a=new Account();
     a.Name='test Project';
     a.Contact_Number_Mobile__c = '7891234560';
     insert a;
     Order__c o=new Order__c();
     o.Projects__c=a.Id;
     insert o;
     PageReference pageRef = Page.Projectsformat;
              Test.setCurrentPage(pageRef);
              pageRef.setredirect(true);
              pageRef .getParameters().put('id',a.id);
              
            ProjectClass t= new ProjectClass (new ApexPages.StandardController(a));
     Test.StopTest();
     }
     }