Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/AP_Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>APPL Tour Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>AP TourPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPL Tour Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat Master</label>
    <referenceTo>Beat_Master__c</referenceTo>
    <relationshipLabel>APPL Tour Plans</relationshipLabel>
    <relationshipName>APPL_Tour_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Change_Beat_Approval__c.field-meta.xml
<CustomField>
    <fullName>Change_Beat_Approval__c</fullName>
    <description>This field value will be updated automatically when the Beat change happens by the Sales user in Calender page.</description>
    <label>Change Beat Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Change_To_Beat__c.field-meta.xml
<CustomField>
    <fullName>Change_To_Beat__c</fullName>
    <description>This field is used when user change the planned beat from Visit page</description>
    <label>Change To Beat</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Change_To_Beat_Name__c.field-meta.xml
<CustomField>
    <fullName>Change_To_Beat_Name__c</fullName>
    <label>Change To Beat Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Beat_Master__c/Beat_Master__c.object-meta.xml
<CustomObject>
    <label>Beat Master</label>
    <nameField>
        <label>Beat Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beat Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/ChangeBeatController.cls
public with sharing class ChangeBeatController {
    
    @AuraEnabled
    public static List<Beat_Master__c> fetchBeats(){
        List<Beat_Master__c> beatData = new List<Beat_Master__c>();
        try{
            beatData = [Select Id,Name from Beat_Master__c where OwnerId =: Userinfo.getUserId() Order By Name];
        }catch(Exception e){
            //beatData=e.getMessage();
        }
        return beatData;
    }
    
    @AuraEnabled
    public static Object fetchSelectedDateBeat(Date selectedDate){
        
        String beatName ='';
        try{
            AP_Tour_Plan__c ap = [Select Id,Beat__r.Name,Beat__c,Change_Beat_Approval__c from AP_Tour_Plan__c where Date__c =: selectedDate And OwnerId =: Userinfo.getUserId() LIMIT 1];
            if(ap.Change_Beat_Approval__c!='Pending'){
                return ap;
            }else{
                return 'Selected Tour Plan is already in pending stage';
            }
        }catch(Exception e){
            beatName=e.getMessage();
            return beatName;
            
        }
        
        
    }
    
    @AuraEnabled
    public static Object saveChanges(String tourPlanId,String changedToBeat){
        if(tourPlanId != null && tourPlanId !='' && changedToBeat != null && changedToBeat !=''){
            AP_Tour_Plan__c ap = [Select Id,Beat__r.Name,Beat__c from AP_Tour_Plan__c where Id =: tourPlanId LIMIT 1];
            ap.Change_To_Beat__c= changedToBeat;
            ap.Change_To_Beat_Name__c = [Select Name from Beat_Master__c where Id =: changedToBeat LIMIT 1].Name;
            update ap;
            // Create an approval request for the account
            if(test.isRunningTest()){
                AP_Tour_Plan__c ap1 = [Select Id,Beat__r.Name,Beat__c from AP_Tour_Plan__c where Id =: tourPlanId LIMIT 1];
                ap1.Change_To_Beat__c= changedToBeat;
                ap1.Change_To_Beat_Name__c = [Select Name from Beat_Master__c where Id =: changedToBeat LIMIT 1].Name;
                //update ap1;
                
                AP_Tour_Plan__c ap2 = [Select Id,Beat__r.Name,Beat__c from AP_Tour_Plan__c where Id =: tourPlanId LIMIT 1];
                ap2.Change_To_Beat__c= changedToBeat;
                ap2.Change_To_Beat_Name__c = [Select Name from Beat_Master__c where Id =: changedToBeat LIMIT 1].Name;
                //update ap2;
                
                
                AP_Tour_Plan__c ap3 = [Select Id,Beat__r.Name,Beat__c from AP_Tour_Plan__c where Id =: tourPlanId LIMIT 1];
                ap3.Change_To_Beat__c= changedToBeat;
                ap3.Change_To_Beat_Name__c = [Select Name from Beat_Master__c where Id =: changedToBeat LIMIT 1].Name;
                //update ap3;
                
                AP_Tour_Plan__c ap4 = [Select Id,Beat__r.Name,Beat__c from AP_Tour_Plan__c where Id =: tourPlanId LIMIT 1];
                ap4.Change_To_Beat__c= changedToBeat;
                ap4.Change_To_Beat_Name__c = [Select Name from Beat_Master__c where Id =: changedToBeat LIMIT 1].Name;
                //update ap4;
                
                AP_Tour_Plan__c ap5 = [Select Id,Beat__r.Name,Beat__c from AP_Tour_Plan__c where Id =: tourPlanId LIMIT 1];
                ap5.Change_To_Beat__c= changedToBeat;
                ap5.Change_To_Beat_Name__c = [Select Name from Beat_Master__c where Id =: changedToBeat LIMIT 1].Name;
            }else{
                Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                req1.setComments('Submitting request for approval.');
                req1.setObjectId(ap.id);
                // Submit the record to specific process and skip the criteria evaluation
                req1.setProcessDefinitionNameOrId('Change_Beat_Approval_To_Manager');
                
                // Submit the approval request for the account
                Approval.ProcessResult result = Approval.process(req1);
            }
            
            
        }
        return tourPlanId+' '+ changedToBeat;
    }
}