Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/AP_Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>APPL Tour Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>AP TourPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPL Tour Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Account_Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Contact_Number__c</fullName>
    <formula>Account__r.Contact_Number_Mobile__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Contact Number</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Planned Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Promotional_Type__c.field-meta.xml
<CustomField>
    <fullName>Promotional_Type__c</fullName>
    <label>Promotional Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Boarers Meet</fullName>
            </value>
            <value>
                <fullName>Exhibition</fullName>
            </value>
            <value>
                <fullName>Jeep Campaign</fullName>
            </value>
            <value>
                <fullName>Farmers Meet</fullName>
            </value>
            <value>
                <fullName>Tractor Show</fullName>
            </value>
            <value>
                <fullName>Shandy Show</fullName>
            </value>
            <value>
                <fullName>Mechanics Meet</fullName>
            </value>
            <value>
                <fullName>Column Dealer Meet</fullName>
            </value>
            <value>
                <fullName>Column Dealers Factory Visit</fullName>
            </value>
            <value>
                <fullName>Column Dealers Salesman Meet</fullName>
            </value>
            <value>
                <fullName>InShop Mechanic Meet</fullName>
            </value>
            <value>
                <fullName>Mechanics Factory Visit</fullName>
            </value>
            <value>
                <fullName>Onsite Plumber Meet</fullName>
            </value>
            <value>
                <fullName>Plumbing DSM Meet / Training</fullName>
            </value>
            <value>
                <fullName>Engineers Meets</fullName>
            </value>
            <value>
                <fullName>Onsite Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Naaka Meets</fullName>
            </value>
            <value>
                <fullName>Architects Meets</fullName>
            </value>
            <value>
                <fullName>Mega Plumbers Meets</fullName>
            </value>
            <value>
                <fullName>Plumbing Dealers Factory Visits</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Engineers</fullName>
            </value>
            <value>
                <fullName>Consultants Factory Visits</fullName>
            </value>
            <value>
                <fullName>Plumbing factory Visits</fullName>
            </value>
            <value>
                <fullName>Inshop Plumber Meets</fullName>
            </value>
            <value>
                <fullName>Exhibition / Construction Fairs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/SMSonTourPLANCreation.cls
public class SMSonTourPLANCreation {
    public static void smsSend(List<Ap_Tour_Plan__c> newTourPlanList){
        set<Id> uID=new set<Id>();
        for(Ap_Tour_Plan__c temp:newTourPlanList){
          uID.add(temp.CreatedById); 
        }
        List<User> usr=new List<User>();
        usr=[select id,name from user where id IN:uID];
        system.debug('user'+usr);
         Map<id,String> mUser=new Map<id,String>();
        for(User u:usr){
          mUser.put(u.id,u.name);  
        }
       system.debug('map'+mUser);
          string msgTemp= 'Dear Sir,\nWe are conducting @TourPlanName at @Place, @District on @PrmotionDate\n-@Owner\nFor More Information Contact:@number.';
        try{
        for(AP_Tour_Plan__c tourPlan:newTourPlanList){
             system.debug('entered ');
           // if(tourPlan.Promotional_Type__c!='')
            {
                  String msg= msgTemp.replace('@TourPlanName', tourPlan.Promotional_Type__c);
                          String OwnerName=string.valueOf(mUser.get(tourPlan.CreatedById)); 
                 system.debug('OwnerName '+OwnerName);
                           msg= msg.replace('@Owner',OwnerName);
                            
                            msg= msg.replace('@number',string.valueOf(tourPlan.Owner_Phone__c));
                            msg= msg.replace('@Place',string.valueOf(tourPlan.Location__c));   //tourPlan.)
                            msg= msg.replace('@District',string.valueOf(tourPlan.District__c));
                            msg= msg.replace('@PrmotionDate',string.valueOf(tourPlan.Date__c)); //format('dd/MMM/yyyy ')HH:mm:ss
                        
                            String msgEncoded= EncodingUtil.urlEncode(msg, 'UTF-8');

                            SendSMSController.sendMessage(tourPlan.Account_Contact_Number__c,msgEncoded);
                  
                            system.debug('entered the method');
                 system.debug('entered number'+tourPlan.Account_Contact_Number__c);
                  
                            //b.SMS_Sent__c = true; 
                
            } 
        }
        }
        catch(exception e){
            System.debug('The Error is '+e.getMessage()+'at Line Number'+e.getLineNumber());
        }
    }
}