Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/AP_Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>APPL Tour Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>AP TourPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPL Tour Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Change_Beat_Approval__c.field-meta.xml
<CustomField>
    <fullName>Change_Beat_Approval__c</fullName>
    <description>This field value will be updated automatically when the Beat change happens by the Sales user in Calender page.</description>
    <label>Change Beat Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>APPL Tour Plans</relationshipLabel>
    <relationshipName>AP_TourPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Visit Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Head Quarter</fullName>
            </value>
            <value>
                <fullName>Ex-Station</fullName>
            </value>
            <value>
                <fullName>Out Station</fullName>
            </value>
            <value>
                <fullName>Leave</fullName>
            </value>
            <value>
                <fullName>Holiday</fullName>
            </value>
            <value>
                <fullName>Meetings/Training/Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Beat_Master__c/Beat_Master__c.object-meta.xml
<CustomObject>
    <label>Beat Master</label>
    <nameField>
        <label>Beat Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beat Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/classes/ChangeBeatControllerTest.cls
@isTest public class ChangeBeatControllerTest {
    
    @isTest public static void test(){
        User userdata;
        userdata = Test_Intial_Data_Phase2.ColumnRH('First','Last','System Administrator');
        insert userdata ;
        Target__c target;
        target = Test_Intial_Data_Phase2.CreateTarget(userdata);
        target.Start_Date__c = Date.today();
        insert target;
        AP_Tour_Plan__c tourplan;
        tourplan  = Test_Intial_Data_Phase2.CreateTourPlan(target.Id);
        tourplan.Change_Beat_Approval__c = 'Approved';
        tourplan.Visit_Type__c = 'Ex-Station';
        tourplan.Date__c = Date.today();
        tourplan.Target__c = target.ID;
        insert tourplan;
        Beat_Master__c beat = new Beat_Master__c();
        beat.Name = 'Testt';
        insert beat;
        ChangeBeatController.fetchBeats();
        ChangeBeatController.fetchSelectedDateBeat(System.today());
        
        
        ChangeBeatController.saveChanges(tourplan.Id,beat.Id);
    }
    
}