Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/AP_Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>APPL Tour Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>AP TourPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPL Tour Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Ex_Station_Actual__c.field-meta.xml
<CustomField>
    <fullName>Ex_Station_Actual__c</fullName>
    <label>Ex-Station(Actual)</label>
    <summaryFilterItems>
        <field>AP_Expenses__c.Expens_Visit_Type__c</field>
        <operation>equals</operation>
        <value>Ex-station</value>
    </summaryFilterItems>
    <summaryForeignKey>AP_Expenses__c.TourPlan__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Head_Quarter_Actual__c.field-meta.xml
<CustomField>
    <fullName>Head_Quarter_Actual__c</fullName>
    <label>Head Quarter(Actual)</label>
    <summaryFilterItems>
        <field>AP_Expenses__c.Expens_Visit_Type__c</field>
        <operation>equals</operation>
        <value>Headquarter</value>
    </summaryFilterItems>
    <summaryForeignKey>AP_Expenses__c.TourPlan__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Head_Quarter_Metro_Actual__c.field-meta.xml
<CustomField>
    <fullName>Head_Quarter_Metro_Actual__c</fullName>
    <label>Head Quarter - Metro(Actual)</label>
    <summaryFilterItems>
        <field>AP_Expenses__c.Expens_Visit_Type__c</field>
        <operation>equals</operation>
        <value>Headquarter-Metro</value>
    </summaryFilterItems>
    <summaryForeignKey>AP_Expenses__c.TourPlan__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Head_Quarter_State_Capital_Actual__c.field-meta.xml
<CustomField>
    <fullName>Head_Quarter_State_Capital_Actual__c</fullName>
    <label>Head Quarter - State Capital(Actual)</label>
    <summaryFilterItems>
        <field>AP_Expenses__c.Expens_Visit_Type__c</field>
        <operation>equals</operation>
        <value>Headquarter-State Capital</value>
    </summaryFilterItems>
    <summaryForeignKey>AP_Expenses__c.TourPlan__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Out_Station_Actual__c.field-meta.xml
<CustomField>
    <fullName>Out_Station_Actual__c</fullName>
    <label>Out Station(Actual)</label>
    <summaryFilterItems>
        <field>AP_Expenses__c.Expens_Visit_Type__c</field>
        <operation>equals</operation>
        <value>Outstation</value>
    </summaryFilterItems>
    <summaryForeignKey>AP_Expenses__c.TourPlan__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>APPL Tour Plans</relationshipLabel>
    <relationshipName>AP_TourPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Attendance_Expense__c/Attendance_Expense__c.object-meta.xml
<CustomObject>
    <label>Attendance Expense</label>
    <nameField>
        <displayFormat>AE-{0000000}</displayFormat>
        <label>Attendance Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Attendance_Expense__c/fields/Ex_Station__c.field-meta.xml
<CustomField>
    <fullName>Ex_Station__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Ex-Station</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Attendance_Expense__c/fields/HeadQuarter__c.field-meta.xml
<CustomField>
    <fullName>HeadQuarter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>HeadQuarter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Attendance_Expense__c/fields/Headquarter_Metro__c.field-meta.xml
<CustomField>
    <fullName>Headquarter_Metro__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Headquarter-Metro</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Attendance_Expense__c/fields/Headquarter_State_Capital__c.field-meta.xml
<CustomField>
    <fullName>Headquarter_State_Capital__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Headquarter-State Capital</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Attendance_Expense__c/fields/Outstation__c.field-meta.xml
<CustomField>
    <fullName>Outstation__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Outstation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Attendance_Expense__c/fields/UserName__c.field-meta.xml
<CustomField>
    <fullName>UserName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Attendance_Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Ex_Station_Actual__c.field-meta.xml
<CustomField>
    <fullName>Ex_Station_Actual__c</fullName>
    <label>Ex-Station(Actual)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Head_Quarter_Actual__c.field-meta.xml
<CustomField>
    <fullName>Head_Quarter_Actual__c</fullName>
    <label>Head Quarter(Actual)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Head_Quarter_Metro_Actual__c.field-meta.xml
<CustomField>
    <fullName>Head_Quarter_Metro_Actual__c</fullName>
    <label>Head Quarter - Metro(Actual)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Head_Quarter_State_Capital_Actual__c.field-meta.xml
<CustomField>
    <fullName>Head_Quarter_State_Capital_Actual__c</fullName>
    <label>Head Quarter - State Capital(Actual)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Out_Station_Actual__c.field-meta.xml
<CustomField>
    <fullName>Out_Station_Actual__c</fullName>
    <label>Out Station(Actual)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Target_User__c.field-meta.xml
<CustomField>
    <fullName>Target_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/BatchAttendanceExpenseCreation.cls
global class BatchAttendanceExpenseCreation implements Database.Batchable<SObject>,Database.Stateful{
    global Date startDate,EndDate;
    
    global Map<String,List<AP_Tour_Plan__c>> MapTour; 
    
    global BatchAttendanceExpenseCreation(){
        try{
            endDate=Date.newInstance(System.today().year(),System.today().month(),25);
            startDate=endDate.addMonths(-1);
            System.debug('Start Date :'+startDate);
            System.debug('End Date :'+endDate);
            MapTour=new Map<String,List<AP_Tour_Plan__c>>();
        }catch(Exception ex){
            System.debug(ex);
            System.debug(ex.getMessage());
            System.debug(ex.getLineNumber());
        }
    }
    global Database.QueryLocator start(Database.BatchableContext bc){
        try{
            String Query='select Id,Date__c,Ex_Station_Actual__c,Target__r.Target_User__c,Head_Quarter_Actual__c,Head_Quarter_Metro_Actual__c,Head_Quarter_State_Capital_Actual__c,Out_Station_Actual__c,Target__r.Target_User__r.EmployeeNumber from AP_Tour_Plan__c where Date__c>=:startDate AND Date__c<=:endDate';
            return Database.getQueryLocator(Query);
        }catch(Exception ex){
            System.debug(ex);
            System.debug(ex.getLineNumber());
            System.debug(ex.getMessage());
        }
        return null;
    }
    global void execute(Database.BatchableContext bc,List<AP_Tour_Plan__c> tourLst){
        try{
            System.debug(tourLst);
            for(AP_Tour_Plan__c temp:tourLst){
                if(MapTour.containsKey(temp.Target__r.Target_User__c)){
                    MapTour.get(temp.Target__r.Target_User__c).add(temp);
                }else{
                    MapTour.put(temp.Target__r.Target_User__c,new List<AP_Tour_Plan__c>{temp});
                }
            }
            
        }catch(Exception ex){
            System.debug(ex);
            System.debug(ex.getMessage());
            System.debug(ex.getLineNumber());
   
        }
    }
    global void finish(Database.BatchableContext bc){
        System.debug(MapTour);
        List<String> dt1=(''+startDate).split(' ');
        List<String> dt2=(''+endDate).split(' ');
       // List<String> dt3=(''+startDate.addMonths(1)).split(' ');
       // List<String> fastforward=dt3[0].split('-');
        List<String> beforeMonth=dt1[0].split('-');
        List<String> presentMonth=dt2[0].split('-');
        
        
        List<Attendance_Expense__c> AE_lst=new LIst<Attendance_Expense__c>();
        for(String mapID:MapTour.keySet()){
            Attendance_Expense__c expense=new Attendance_Expense__c();
            expense.Date__c=System.today();
            expense.UserName__c=mapID;
             //expense.Employee_Number__c=MapTour.get(mapID)[0].Target__r.Target_User__r.EmployeeNumber;
             expense.External_Id__c=mapID+beforeMonth[1]+presentMonth[1]+endDate.year();          
            expense.Ex_Station__c=0;
            expense.HeadQuarter__c=0;
            expense.Headquarter_Metro__c=0;
            expense.Headquarter_State_Capital__c=0;
            expense.Outstation__c=0;
            for(AP_Tour_Plan__c z:MapTour.get(mapID)){
                if(z.Ex_Station_Actual__c>0){
                    expense.Ex_Station__c++;
                }
                if(z.Head_Quarter_Actual__c>0){
                    expense.HeadQuarter__c++;
                }
                if(z.Head_Quarter_Metro_Actual__c>0){
                    expense.Headquarter_Metro__c++;
                }
                if(z.Head_Quarter_State_Capital_Actual__c>0){
                    expense.Headquarter_State_Capital__c++;
                }
                if(z.Out_Station_Actual__c>0){
                    expense.Outstation__c++;
                }
            }
            AE_lst.add(expense);
        }
        if(AE_lst.size()>0){
            upsert AE_lst External_Id__c;
        }
        System.debug('Finish');
        
        try{
        /*PageReference page = new PageReference('/apex/ViewAttendanceReport');
        system.debug(page);
        page.setRedirect(true);*/
        
        AttendanceReport a = new AttendanceReport();
        system.debug(a);
        }
        catch(Exception ex){
            System.debug(ex);
            System.debug(ex.getMessage());
            System.debug(ex.getLineNumber());
        }
    }
    
}