Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/AP_Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>APPL Tour Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>AP TourPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPL Tour Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>APPL Tour Plans</relationshipLabel>
    <relationshipName>AP_TourPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/inventory__c.object-meta.xml
<CustomObject>
    <description>Object created to hold the data of the inventory</description>
    <label>inventory</label>
    <nameField>
        <label>Collateral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>inventories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Closing_Stocks__c.field-meta.xml
<CustomField>
    <fullName>Closing_Stocks__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Closing Stocks</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Color_Language_Size__c.field-meta.xml
<CustomField>
    <fullName>Color_Language_Size__c</fullName>
    <label>Color/Language/Size</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>ENGLISH</fullName>
            </value>
            <value>
                <fullName>HINDI</fullName>
            </value>
            <value>
                <fullName>GUJARATI</fullName>
            </value>
            <value>
                <fullName>MARATI</fullName>
            </value>
            <value>
                <fullName>KANNADA</fullName>
            </value>
            <value>
                <fullName>TELUGU</fullName>
            </value>
            <value>
                <fullName>TAMIL</fullName>
            </value>
            <value>
                <fullName>RED</fullName>
            </value>
            <value>
                <fullName>VIOLET</fullName>
            </value>
            <value>
                <fullName>INDIGO</fullName>
            </value>
            <value>
                <fullName>BLUE</fullName>
            </value>
            <value>
                <fullName>GREEN</fullName>
            </value>
            <value>
                <fullName>YELLOW</fullName>
            </value>
            <value>
                <fullName>ORANGE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/opening_stock__c.field-meta.xml
<CustomField>
    <fullName>opening_stock__c</fullName>
    <label>Opening Stock</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Owner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>COLUMN</fullName>
            </value>
            <value>
                <fullName>CASING</fullName>
            </value>
            <value>
                <fullName>V4</fullName>
            </value>
            <value>
                <fullName>CPVC</fullName>
            </value>
            <value>
                <fullName>AQUALIFE</fullName>
            </value>
            <value>
                <fullName>SWR</fullName>
            </value>
            <value>
                <fullName>PAN CONNECTORS</fullName>
            </value>
            <value>
                <fullName>SILENT SWR</fullName>
            </value>
            <value>
                <fullName>UNDER GROUND</fullName>
            </value>
            <value>
                <fullName>AAV</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>GI</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>SILENT PLUS</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>PLUMBING</fullName>
            </value>
            <value>
                <fullName>MINI</fullName>
            </value>
            <value>
                <fullName>MEGA</fullName>
            </value>
            <value>
                <fullName>SWR_PUSHFIT</fullName>
            </value>
            <value>
                <fullName>SWR_SOLFIT</fullName>
            </value>
            <value>
                <fullName>SWR SILENT</fullName>
            </value>
            <value>
                <fullName>SWR SILENT PLUS</fullName>
            </value>
            <value>
                <fullName>UNDERGROUND</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>LEAFLETS</fullName>
            </value>
            <value>
                <fullName>HAND BILL</fullName>
            </value>
            <value>
                <fullName>STICKERS</fullName>
            </value>
            <value>
                <fullName>BANNERS</fullName>
            </value>
            <value>
                <fullName>SCROLL 3&apos;x2&apos;</fullName>
            </value>
            <value>
                <fullName>STALL TENT</fullName>
            </value>
            <value>
                <fullName>FLEX BOARD 6&apos; x 3&apos;</fullName>
            </value>
            <value>
                <fullName>FLEX BOARD 8&apos; x 4&apos;</fullName>
            </value>
            <value>
                <fullName>POP BOARDS</fullName>
            </value>
            <value>
                <fullName>TECHNICAL MANUAL</fullName>
            </value>
            <value>
                <fullName>PRICELIST - ALL INDIA</fullName>
            </value>
            <value>
                <fullName>PRICELIST - TAMILNADU</fullName>
            </value>
            <value>
                <fullName>PIPE SELECTION BOOK</fullName>
            </value>
            <value>
                <fullName>THERMOFOAM BOARD</fullName>
            </value>
            <value>
                <fullName>PRICELIST FOLDERS</fullName>
            </value>
            <value>
                <fullName>CORPORATE BROUCHER (EXCELLENCE TO BRILLANCE)</fullName>
            </value>
            <value>
                <fullName>APPLICATION FORM (CHANNEL PARTNERSHIP)</fullName>
            </value>
            <value>
                <fullName>CORPORATE  LEAFLETS</fullName>
            </value>
            <value>
                <fullName>BLUE TAPE (SHELF STICKERS)</fullName>
            </value>
            <value>
                <fullName>WHITE FOLDER</fullName>
            </value>
            <value>
                <fullName>STANDEES</fullName>
            </value>
            <value>
                <fullName>ALL PRODUCT CLUSTER_STANDEES</fullName>
            </value>
            <value>
                <fullName>MULTI USE KNIFE</fullName>
            </value>
            <value>
                <fullName>TORCHE_EVEREADY</fullName>
            </value>
            <value>
                <fullName>TORCH_NIPPO</fullName>
            </value>
            <value>
                <fullName>UMBRELLA</fullName>
            </value>
            <value>
                <fullName>ASHIRVAD KEY CHAIN -  ENGLISH</fullName>
            </value>
            <value>
                <fullName>LEATHER  KEY CHAIN</fullName>
            </value>
            <value>
                <fullName>LEATHERITE PURSE</fullName>
            </value>
            <value>
                <fullName>LUNCH BOX_TRAVEL MATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Received_Stock__c.field-meta.xml
<CustomField>
    <fullName>Received_Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Received Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PRODUCT COLLATERALS</fullName>
            </value>
            <value>
                <fullName>GIFT ITEMS</fullName>
            </value>
            <value>
                <fullName>PACKING MATERIALS</fullName>
            </value>
            <value>
                <fullName>SAMPLES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Type_Of_Meet__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Meet__c</fullName>
    <label>Type Of Meet</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mega Meet</fullName>
            </value>
            <value>
                <fullName>Mini Meet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/inventory__c/fields/Used_Stock__c.field-meta.xml
<CustomField>
    <fullName>Used_Stock__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Used Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Gift_Request__c/Inventory_Gift_Request__c.object-meta.xml
<CustomObject>
    <label>Inventory_Gift_Request</label>
    <nameField>
        <displayFormat>IGR-{000000}</displayFormat>
        <label>InventoryGiftRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory_Gift_Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Inventory_Gift_Request__c/fields/Request_Raised_by__c.field-meta.xml
<CustomField>
    <fullName>Request_Raised_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request Raised by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Inventory_Gift_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mega_Meets_Column__c.field-meta.xml
<CustomField>
    <fullName>Mega_Meets_Column__c</fullName>
    <formula>Mechanics_Factory_Visit__c + Mega_Mechanic_Meet__c  +  Mega_Farmers_Meet__c  +  Boarers_Meet__c + Column_DSM_Meet_Training__c + Column_Dealer_Meet__c +  Column_Distributors_Dealers_Mechanic_Fac__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mega Meets (Column)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mega_Meets_Plumbing__c.field-meta.xml
<CustomField>
    <fullName>Mega_Meets_Plumbing__c</fullName>
    <formula>Mega_Plumbers_Meet__c + Architects_Engineers_Consultants_Factory__c + Plumber_Factory_Visit__c + Engineers_Meet__c + Architects_Meet__c + Plumbing_Dealers_Factory_Visit__c + Plumbing_Dealer_Distributor_Meets__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mega Meets Plumbing (Target)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mega_Meets_Project__c.field-meta.xml
<CustomField>
    <fullName>Mega_Meets_Project__c</fullName>
    <formula>Architects_Engineers_Consultants_Actual__c +  Architects_Meet__c + Builders_Meet__c +  Engineers_Meet__c + Projects_DSM_Meet_Training__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mega Meets Project</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mini_Meets_Column__c.field-meta.xml
<CustomField>
    <fullName>Mini_Meets_Column__c</fullName>
    <formula>InShop_Mechanic_Meet__c  +  Inshop_Boarers_Meet__c +  Exhibition_Agri_Fairs_Actuval__c  + Mini_Farmers_Meet_Weightage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mini Meets (Column)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mini_Meets_Plumbing__c.field-meta.xml
<CustomField>
    <fullName>Mini_Meets_Plumbing__c</fullName>
    <formula>InSHOP_Plumber_meet__c +  Naaka_Meet__c +  Onsite_Plumber_Meet__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mini Meets Plumbing</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Mini_Meets_Project__c.field-meta.xml
<CustomField>
    <fullName>Mini_Meets_Project__c</fullName>
    <formula>Onsite_Plumber_Meet__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mini Meets Project</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/autoRequestBatchHelper.cls
public class autoRequestBatchHelper{

    RecordType Rt = [select Id from RecordType where Name ='Collateral Request' and SobjectType = 'case'];

    public String getCurrentMonth(){
        String month;

        Date currentDate = Date.today();

        if(currentDate.month() == 1){
            month = 'January'  + ' '+ '-' + ' ' +  currentDate.year();
        }
        else if(currentDate.month() == 2){
            month = 'February' + ' '+ '-' + ' ' +  currentDate.year();
        }
        else if(currentDate.month() == 3){
            month = 'March'  + ' '+ '-' + ' ' +  currentDate.year();
        }
        else if(currentDate.month() == 4){
            month = 'April'  + ' '+ '-' + ' ' + currentDate.year();
        }
        else if(currentDate.month() == 5){
            month = 'May' + ' '+ '-' + ' ' +  currentDate.year();
        }
        else if(currentDate.month() == 6){
            month = 'June' + ' '+ '-' + ' ' + currentDate.year();
        }
        else if(currentDate.month() == 7){
            month = 'July' + ' '+ '-' + ' ' + currentDate.year();
        }
        else if(currentDate.month() == 8){
            month = 'August' + ' '+ '-' + ' ' + currentDate.year();
        }
        else if(currentDate.month() == 9){
            month = 'September' + ' '+ '-' + ' ' + currentDate.year();
        }
        else if(currentDate.month() == 10){
            month = 'October' + ' '+ '-' + ' ' + currentDate.year();
        }
        else if(currentDate.month() ==11){
            month = 'November' + ' '+ '-' + ' ' + currentDate.year();
        }
        else if(currentDate.month() == 12){
            month = 'December' + ' '+ '-' + ' ' + currentDate.year();
        }
   
        return month;
       

    }

    public void executeAutoRequestForMeet(List<Target__c> targets){
        
       String currentMonth=getCurrentMonth();
        List<Inventory__C> userInventories = new List<Inventory__C>();
        List<AP_Tour_Plan__c> bdmTourPlan = new List<AP_Tour_Plan__c>();
        Map<Id, Map<String,Decimal>> inventoryThresholdMap = new Map<Id, Map<String,Decimal>>();
        List<User> userInfo = new List<User>();
        List<Id> targetId = new List<Id>();
        Set<Id> bdmList = new Set<Id>();
        for(Target__c tar : targets){
            targetId.add(tar.id);
            bdmList.add(tar.ownerId);
            
        }
        system.debug('bdmList:::' + bdmList);
        userInventories = [select product__C,type_of_meet__c, name, Type__c,Product_Description__c, Color_Language_Size__c, opening_stock__c, Used_Stock__c,Received_Stock__c, Closing_Stocks__c, Owner_Account__c  from inventory__c
                           where Owner_Account__c in : bdmList and type__c ='GIFT ITEMS'];

        userInfo  = [select firstname,Address,depo__c,depo__r.depot_zone__c, team_lead__c, head_office__c, lastname,Mega_Meet_Threshold__c, Mini_Meet_Threshold__c, id from user where id =: bdmList and Gifts_Required_For_Meet__c = true and isactive=true];
        
        Map<id, List<Inventory_Gift_Request__c>> inrGiftMap = new map<id, List<Inventory_Gift_Request__c>>();
        
        List<Case> caseList = new List<Case>();
        
        inventoryThresholdMap = getGiftInventoryCount(userInfo, userInventories);
        system.debug('inventoryThresholdMap:::'+inventoryThresholdMap);
        system.debug('userInfo:::' + userInfo);
        for(User userdata : userInfo){
         Map<String, Decimal>  invThresholdData = new Map<String, Decimal>();
            Decimal megaMultiplier=0.0;
            Decimal miniMultiplier=0.0;
      
           
            for(Target__c tar : targets){
            if(tar.ownerid == userdata.id){
            Decimal MegaMeetColumn =0.0;
             Decimal MegaMeetPlumbing =0.0;
              Decimal MegaMeetProjects =0.0;
             Decimal MiniMeetColumn =0.0;
             Decimal MiniMeetPlumbing =0.0;
              Decimal MiniMeetProjects =0.0; 
             system.debug('MegaMultiplier::'+ tar.Mega_Meets_Column__c);
             system.debug('miniMultiplier:::' + tar.Mini_Meets_Column__c);
            if(tar.Mega_Meets_Column__c != null){ MegaMeetColumn = tar.Mega_Meets_Column__c; }
            if(tar.Mega_Meets_Plumbing__c != null){ MegaMeetPlumbing  = tar.Mega_Meets_Plumbing__c;}
            if(tar.Mega_Meets_Project__c != null){ MegaMeetProjects  = tar.Mega_Meets_Project__c ;}
            if(tar.Mini_Meets_Column__c != null) {MiniMeetColumn  = tar.Mini_Meets_Column__c;}
            if(tar.Mini_Meets_Plumbing__c !=null) { MiniMeetPlumbing  = tar.Mini_Meets_Plumbing__c ;}
            if(tar.Mini_Meets_Project__c != null) {MiniMeetProjects  = tar.Mini_Meets_Project__c ;}
            MegaMultiplier = MegaMeetColumn  + MegaMeetPlumbing  + MegaMeetProjects ;
            miniMultiplier = MiniMeetColumn  + MiniMeetPlumbing + MiniMeetProjects;
            }
           }
           
            invThresholdData=inventoryThresholdMap.get(userdata.id);
            
            if(invThresholdData != null && invThresholdData.size()!=0){
            system.debug('invThresholdData:::'+invThresholdData.keyset());
           
           
           List<Inventory_Gift_Request__c> inrGiftList = new List<Inventory_Gift_Request__c>();
                
            for(String meet: invThresholdData.keyset()){
               Inventory_Gift_Request__c inrGift = new Inventory_Gift_Request__c();
                if(meet == 'Mega Meet'){
                    if(megaMultiplier!=0){
                    if(invThresholdData.get(meet) <= (userdata.Mega_Meet_Threshold__c * megaMultiplier)){

                        inrGift.Request_Raised_by__c = userdata.id;
                        inrGift.Required_Quantity__c = (userdata.Mega_Meet_Threshold__c * megaMultiplier) - invThresholdData.get(meet);
                        inrGift.Type_Of_Meet__c ='Mega Meet';
                        inrGift.comments__c='Need the requested Quantity of gifts for Mega Meet';
                        inrGiftList.add(inrGift);
                        }
                    }
                }
                else if(meet == 'Mini Meet'){
                    if(miniMultiplier !=0){
                   
                    if(invThresholdData.get(meet) <= (userdata.Mini_Meet_Threshold__c* miniMultiplier )){

                        inrGift.Request_Raised_by__c = userdata.id;
                        inrGift.Required_Quantity__c = (userdata.Mini_Meet_Threshold__c * miniMultiplier ) - invThresholdData.get(meet);
                        inrGift.Type_Of_Meet__c ='Mini Meet';
                        inrGift.comments__c='Need the requested Quantity of gifts for Mini Meet';
                        inrGiftList.add(inrGift);
                        
                     }
                    }
                }
               
                
            }
            if(inrGiftList.size() != 0 && inrGiftList !=null){
                inrGiftMap.put(userdata.id,inrGiftList);             
                system.debug('inrGiftList::' + inrGiftList);
               
            }
         List<Inventory_gift_request__c> invList1= inrGiftMap.get(userdata.id);
            if(invList1 != null && invList1.size() !=0){
            Case cases = new Case();

                cases.subject = 'Supply of Mega and Mini Meet gifts for the BDM ' +  userdata.firstname + ' ' + userdata.lastname;
                cases.ownerid =  userdata.id;
                cases.Request_Raised_By__c = userdata.id;
                cases.recordtypeId= Rt.id;
                cases.status = 'Auto Approved for Mini-Mega Meet';
                cases.Origin = 'User';
                cases.Priority = 'Medium';
                cases.Check_Gifts__c = true;
                cases.collateral_flows__c = 'Requestor';
                cases.description = 'The user ' +  userdata.firstname + ' ' + userdata.lastname +' has '+ megaMultiplier + ' Mega Meet and ' + miniMultiplier + ' Mini Meet for the Month '+ currentMonth +'. As the user is falling short of the gifts, an auto request is raised to dispatch the required quantity for the meets';
                Address addr = userdata.Address;
                if(addr != null){
                    cases.Shipping_Address__c =addr.getStreet()+ ' ' + addr.getcity() + ' '  + addr.getstate()+ ' '
                    +  addr.getPostalCode() +' '+ addr.getcountry();
                }
                else{
                    cases.Shipping_Address__c ='';}
                cases.Depo__c=userdata.depo__c;
                cases.Head_Office__c=userdata.Head_office__c;
                cases.team_lead__c = userData.team_lead__c;
                cases.depot_zone__c=userdata.depo__r.depot_zone__c;
                caseList.add(cases);
        }
        }
        }
        system.debug('caseList::'+caseList.size());
        insert caseList;
        
        List<Inventory_Gift_Request__c> finalList = new List<Inventory_Gift_Request__c>();
        for(case c : caseList){
            List<Inventory_gift_request__c> invList= inrGiftMap.get(c.Request_Raised_By__c);
            system.debug('invList:::'+invList);
            for(Inventory_Gift_Request__c inreq : invList){
                inreq.Case__c = c.id;
                finalList.add(inreq);
            }

        }
       system.debug('finalList::'+finalList.size());
       
        
        insert finalList;

        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
        for(case c : caseList){
            app.setObjectId(c.id);
            app.setComments('Auto Approved..'); 

            Approval.ProcessResult result = Approval.process(app);
        }
        
        List<caseShare> caseShareList = new List<caseShare>();
        for(Case currentCase : caseList){
            if(currentCase.Team_Lead__c != null){
               CaseShare caseShare=new CaseShare();
               caseShare.UserOrGroupID = currentCase.Team_Lead__c;
               caseShare.CaseAccessLevel= 'Read';
               caseShare.CaseId= currentCase.Id;
               caseShare.RowCause = 'Manual';
               caseShareList.add(CaseShare);      
            }
           if(currentCase.depo__c !=null){
            CaseShare caseShare=new CaseShare();
               caseShare.UserOrGroupID = currentCase.depo__c;
               caseShare.CaseAccessLevel= 'Edit';
               caseShare.CaseId= currentCase.Id;
               caseShare.RowCause = 'Manual';
               caseShareList.add(CaseShare); 
           }
           if(currentCase.head_office__c !=null){
            CaseShare caseShare=new CaseShare();
               caseShare.UserOrGroupID = currentCase.head_office__c;
               caseShare.CaseAccessLevel= 'Edit';
               caseShare.CaseId= currentCase.Id;
               caseShare.RowCause = 'Manual';
               caseShareList.add(CaseShare); 
           }
           
           }
          if(caseShareList.size()!=0 && caseShareList !=null){
           insert caseShareList;}

    }


    public Map<Id, Map<String,Decimal>> getGiftInventoryCount(List<User> userInfo, List<Inventory__C> giftList){
        Map<Id, Map<String,Decimal>> returnMap = new Map<Id, Map<String,Decimal>>();
        List<Inventory__C> miniMeetList= new List<Inventory__C>();
        List<Inventory__C> megaMeetList= new List<Inventory__C>();
        Map<String, Decimal> maptoAdd = new Map<String, Decimal>();
        for(Inventory__c inv : giftList){

            if(inv.type_of_meet__c =='Mega Meet'){
                megaMeetList.add(inv);
            }
            else if (inv.type_of_meet__c =='Mini Meet'){
                miniMeetList.add(inv);
            }
        }


        for(User user : userInfo){
            maptoAdd.clear();
            Decimal megaCount = 0.0;
            Decimal miniCount =0.0;
            boolean checkMega=false;
            boolean checkMini=false;
            for(Inventory__c inv : megaMeetList){
                if(inv.Owner_Account__c == user.id){
                checkMega=true;
                    megaCount = megaCount + inv.Closing_Stocks__c;
                }  
            }
            if(checkMega){
            maptoAdd.put('Mega Meet', megaCount );
            }
            for(Inventory__c inv : miniMeetList){
                if(inv.Owner_Account__c == user.id){ 
                checkMini=true;
                    miniCount = miniCount + inv.Closing_Stocks__c;    
                }   
            }
            
                              
            if(checkMini){
            maptoAdd.put('Mini Meet', miniCount);
            
            }
            
            if(maptoAdd.size()!=0){
            
            returnMap.put(user.id, maptoAdd);
            }
         system.debug('maptoAdd:::'+maptoAdd);   
          
        }
        system.debug('returnMap:::'+ returnMap);
        return returnMap;

    }

}