Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/AP_Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>APPL Tour Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>AP TourPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPL Tour Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Non_Holiday_Non_Leave_Other_Activities__c.field-meta.xml
<CustomField>
    <fullName>Non_Holiday_Non_Leave_Other_Activities__c</fullName>
    <description>Non-Holiday/Non Leave Other Activities</description>
    <label>Non-Holiday/Non Leave Other Activities</label>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Other Activities</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.Othet_Activities__c</field>
        <operation>equals</operation>
        <value>Meeting, Promotional Activity, Training, Post Visit Order</value>
    </summaryFilterItems>
    <summaryForeignKey>AP_Site_Visit__c.AP_Tour_Plan__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Non_Holiday_Non_Leave_Visit_Activities__c.field-meta.xml
<CustomField>
    <fullName>Non_Holiday_Non_Leave_Visit_Activities__c</fullName>
    <description>Non-Holiday/Non Leave Visit Activities</description>
    <label>Non-Holiday/Non Leave Visit Activities</label>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Project Visit, Visits, brandingVist</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.Geo_Address__c</field>
        <operation>notEqual</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>AP_Site_Visit__c.AP_Tour_Plan__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Number_of_Leave_Holiday__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Leave_Holiday__c</fullName>
    <label>Number of Leave/Holiday</label>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Other Activities, brandingVist</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>AP_Site_Visit__c.Othet_Activities__c</field>
        <operation>equals</operation>
        <value>Holiday/ Market Closed, Leave</value>
    </summaryFilterItems>
    <summaryForeignKey>AP_Site_Visit__c.AP_Tour_Plan__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>APPL Tour Plans</relationshipLabel>
    <relationshipName>AP_TourPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<CustomObject>
    <label>Attendance</label>
    <nameField>
        <displayFormat>Attendance-{00000}</displayFormat>
        <label>Attendance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Attendance__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Attendance</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Attendance__c/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <formula>Employee__r.EmployeeNumber</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Id</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Attendance__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <formula>Employee__r.FirstName &amp;  Employee__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Name</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Attendance__c/fields/In_Time__c.field-meta.xml
<CustomField>
    <fullName>In_Time__c</fullName>
    <label>In Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Attendance__c/fields/Out_Time__c.field-meta.xml
<CustomField>
    <fullName>Out_Time__c</fullName>
    <label>Out Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Attendance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
                <label>P</label>
            </value>
            <value>
                <fullName>Absent</fullName>
                <label>A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Attendance__c/fields/Tour_Plan__c.field-meta.xml
<CustomField>
    <fullName>Tour_Plan__c</fullName>
    <label>Tour Plan</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Attendance__c/fields/TourPlanDate__c.field-meta.xml
<CustomField>
    <fullName>TourPlanDate__c</fullName>
    <label>TourPlanDate</label>
    <type>Date</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Target_User__c.field-meta.xml
<CustomField>
    <fullName>Target_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan__c/Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>Tour Plan(O)</label>
    <nameField>
        <displayFormat>TP-{0}</displayFormat>
        <label>Tour Plan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Plan(O)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Tour_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( Total_Visits_Target__c &gt; 0 , &apos;Tour Plan Not Completed&apos;,
IF(Total_Visits_Target__c = 0 , &apos;Tour Plan Completed&apos;, &apos;More Visits&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/BatchCreateAttendanceRecords.cls
global class BatchCreateAttendanceRecords implements Database.Batchable<SObject>, Database.Stateful {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        //first, you gather all the records you want to create a new record with
      
            Map<Id,User> mapUser=new Map<Id,User>([select id,Create_Attendance__c  from user where Create_Attendance__c=true AND isActive=true]);
            List<Id> zz=new List<Id>();
            for(Id z:mapUser.KeySet()){
                zz.add(z);
            }
       
           // set<Id> usrSet=new set<Id>();
           // String usrSet='select id,name,Create_Attendance__c from User where Create_Attendance__c=true AND isActive=true';
           //system.debug(usrSet);
            Date startDate=Date.newInstance(System.today().Year(),System.today().month(),23);
            Date endDate=startDate.addMonths(1);
            System.debug('startDate =='+startDate);
            System.debug('endDate =='+endDate);
          //  List<AP_Tour_Plan__c> tourPlanLst = [SELECT Id, Name, Date__c, Target__c,Target__r.Target_User__c,Target__r.Target_User__r.Name, Target__r.Target_User__r.EmployeeNumber, Non_Holiday_Non_Leave_Other_Activities__c, Non_Holiday_Non_Leave_Visit_Activities__c, Number_of_Leave_Holiday__c FROM AP_Tour_Plan__c where (Date__c =Today OR Date__c = Yesterday)];
            String tourPlanLst = 'SELECT Id, Name, Date__c, Target__c,Target__r.Target_User__c,Target__r.Target_User__r.Name, Target__r.Target_User__r.EmployeeNumber, Non_Holiday_Non_Leave_Other_Activities__c, Non_Holiday_Non_Leave_Visit_Activities__c, Number_of_Leave_Holiday__c FROM AP_Tour_Plan__c where (Date__c =LAST_N_DAYS:90 and Date__c<=Today) and Target__r.Target_User__r.Id in:zz';
            
        //below checks to see if the batch is being called from a test class. If the record count
        //returned by the query above is over 200, the test will fail
       /*if(Test.isRunningTest())
            query += ' limit 200'; */ 
        return Database.getQueryLocator(tourPlanLst);
    }
    
   
    
    
    global void execute(Database.BatchableContext bc, List<AP_Tour_Plan__c> tourPlanLst){
        //now we want to loop through the records from the query above and create the new records
        //and store them in a list
         Map<String,AP_Tour_Plan__c> presentMapTour=new Map<String,AP_Tour_Plan__c>();
         Map<String,AP_Tour_Plan__c> absentMapTour=new Map<String,AP_Tour_Plan__c>();
         String inTime=Label.In_Time;
         String outTime=Label.Out_Time;

         for(AP_Tour_Plan__c tour:tourPlanLst){
                 List<String> tourdate=(''+tour.Date__c).split(' ');
                 List<String> dateSplit=tourdate[0].split('-');
                 if((tour.Non_Holiday_Non_Leave_Other_Activities__c>0||tour.Non_Holiday_Non_Leave_Visit_Activities__c>0)){
                     presentMapTour.put(''+tour.Target__r.Target_User__c+dateSplit[0]+dateSplit[1]+dateSplit[2],tour);
                 }
                 if((tour.Number_of_Leave_Holiday__c>0 && tour.Non_Holiday_Non_Leave_Other_Activities__c==0 && tour.Non_Holiday_Non_Leave_Visit_Activities__c==0)||(tour.Non_Holiday_Non_Leave_Other_Activities__c==0 && tour.Non_Holiday_Non_Leave_Visit_Activities__c==0 && tour.Number_of_Leave_Holiday__c==0 )){
                     absentMapTour.put(''+tour.Target__r.Target_User__c+dateSplit[0]+dateSplit[1]+dateSplit[2],tour);
                 }
            }
            System.debug(presentMapTour);
            System.debug(absentMapTour);
            
            Map<String,Attendance__c> presentAttendance= new Map<String,Attendance__c>();
            Map<String,Attendance__c> absentAttendance= new Map<String,Attendance__c>();
            List<Attendance__c> attendanceLst = [Select id,name,Employee_Id__c,Employee_Name__c,Status__c,Tour_Plan__c,TourPlanDate__c,Employee__c from Attendance__c where  (TourPlanDate__c = LAST_N_DAYS:90 and Tourplandate__c <= Today)];
            for(Attendance__c att:attendanceLst){
                List<String> tourdate=(''+att.TourPlanDate__c).split(' ');
                List<String> dateSplit=tourdate[0].split('-');
                if(att.Status__c=='Present'){
                    presentAttendance.put(att.Employee__c+dateSplit[0]+dateSplit[1]+dateSplit[2],att);
                }else{
                    absentAttendance.put(att.Employee__c+dateSplit[0]+dateSplit[1]+dateSplit[2],att);
                }
            }
            System.debug(presentAttendance);
            System.debug(absentAttendance);
            
            
            List<Attendance__C> UpsertData=new List<Attendance__C>();
            
            for(String presTour:presentMapTour.keySet()){
                if(absentAttendance.containsKey(presTour)){
                    Attendance__C temp=absentAttendance.get(presTour);
                    temp.Status__c='Present';
                    temp.In_Time__c = inTime;
                    temp.Out_Time__c = outTime;
                    UpsertData.add(temp);
                    absentAttendance.remove(presTour);
                }else if(presentAttendance.containsKey(presTour)){
                
                    System.debug('Already Present');
                }else{
                    AP_Tour_Plan__c tempTour=presentMapTour.get(presTour);
                    Attendance__C temp=new Attendance__C ();
                    temp.Employee__c= tempTour.Target__r.Target_User__c;
                    temp.Status__c = 'Present';
                    temp.In_Time__c = inTime;
                    temp.Out_Time__c = outTime;
                    temp.TourPlanDate__c= tempTour.Date__c;
                    temp.Tour_Plan__c= tempTour.Name;                  
                    UpsertData.add(temp);
                }
            }
            
           
            
            for(String absTour:absentMapTour.keySet()){
                if(presentAttendance.containsKey(absTour)){
                    Attendance__C temp=presentAttendance.get(absTour);
                    System.debug(temp);
                    temp.Status__c='Absent';
                    temp.In_Time__c = '';
                    temp.Out_Time__c = '';
                    UpsertData.add(temp);
                    presentAttendance.remove(absTour);
                }else if(absentAttendance.containsKey(absTour)){
                
                    System.debug('Already Absent');
                }else{
                    AP_Tour_Plan__c tempTour=absentMapTour.get(absTour);
                    Attendance__C temp=new Attendance__C ();
                    temp.Employee__c= tempTour.Target__r.Target_User__c;
                    temp.Status__c = 'Absent';
                    temp.In_Time__c ='';
                    temp.Out_Time__c = '';
                    temp.TourPlanDate__c= tempTour.Date__c;
                    temp.Tour_Plan__c= tempTour.Name;
                 
                    UpsertData.add(temp);
                }
            }        
        
        //this checks to see if there are any records to insert. If there are, then it will create them
       
        if(!UpsertData.isEmpty())
            database.upsert(UpsertData,false); 
        //newrecords is the list of records you put in during the for loop. The "false" is saying,
        //if one records fails to insert, still insert the rest (All or Nothing)
    }
    
    global void finish(Database.BatchableContext bc) {}
}