Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/AP_Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>APPL Tour Plan</label>
    <nameField>
        <displayFormat>TP-{000000}</displayFormat>
        <label>AP TourPlan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>APPL Tour Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Beat__c.field-meta.xml
<CustomField>
    <fullName>Beat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beat Master</label>
    <referenceTo>Beat_Master__c</referenceTo>
    <relationshipLabel>APPL Tour Plans</relationshipLabel>
    <relationshipName>APPL_Tour_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Beat_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Beat_Frequency__c</fullName>
    <label>Beat Frequency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chandigarh</fullName>
            </value>
            <value>
                <fullName>Chhatisgarh</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jammu and Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Orissa</fullName>
            </value>
            <value>
                <fullName>Pondicherry</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/AP_Tour_Plan__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target</label>
    <referenceTo>Target__c</referenceTo>
    <relationshipLabel>APPL Tour Plans</relationshipLabel>
    <relationshipName>AP_TourPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Beat_Master__c/Beat_Master__c.object-meta.xml
<CustomObject>
    <label>Beat Master</label>
    <nameField>
        <label>Beat Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beat Master</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Beat_Master__c/fields/Beat_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Beat_Frequency__c</fullName>
    <label>Beat Frequency</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday Week1</fullName>
            </value>
            <value>
                <fullName>Monday Week2</fullName>
            </value>
            <value>
                <fullName>Monday Week3</fullName>
            </value>
            <value>
                <fullName>Monday Week4</fullName>
            </value>
            <value>
                <fullName>Tuesday Week1</fullName>
            </value>
            <value>
                <fullName>Tuesday Week2</fullName>
            </value>
            <value>
                <fullName>Tuesday Week3</fullName>
            </value>
            <value>
                <fullName>Tuesday Week4</fullName>
            </value>
            <value>
                <fullName>Wednesday Week1</fullName>
            </value>
            <value>
                <fullName>Wednesday Week2</fullName>
            </value>
            <value>
                <fullName>Wednesday Week3</fullName>
            </value>
            <value>
                <fullName>Wednesday Week4</fullName>
            </value>
            <value>
                <fullName>Thursday Week1</fullName>
            </value>
            <value>
                <fullName>Thursday Week2</fullName>
            </value>
            <value>
                <fullName>Thursday Week3</fullName>
            </value>
            <value>
                <fullName>Thursday Week4</fullName>
            </value>
            <value>
                <fullName>Friday Week1</fullName>
            </value>
            <value>
                <fullName>Friday Week2</fullName>
            </value>
            <value>
                <fullName>Friday Week3</fullName>
            </value>
            <value>
                <fullName>Friday Week4</fullName>
            </value>
            <value>
                <fullName>Saturday Week1</fullName>
            </value>
            <value>
                <fullName>Saturday Week2</fullName>
            </value>
            <value>
                <fullName>Saturday Week3</fullName>
            </value>
            <value>
                <fullName>Saturday Week4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>Indian state list</description>
    <label>State</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/Target__c.object-meta.xml
<CustomObject>
    <label>APPL Target</label>
    <nameField>
        <displayFormat>TGT-{YYYY}{MM}-{0000}</displayFormat>
        <label>Target Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Submitted</fullName>
                <default>true</default>
                <label>Not Submitted</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Partial_14Dec2021/force-app/main/default/objects/Target__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>CASE(MONTH(Start_Date__c),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;,
4, &quot;April&quot;,
5, &quot;May&quot;,
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;None&quot;)+&quot; &quot;+&quot;-&quot;+&quot; &quot;+TEXT(YEAR(Start_Date__c))</formula>
    <label>Month</label>
    <type>Text</type>
</CustomField>

Partial_14Dec2021/force-app/main/default/classes/Batch_AutoTourPlanCreation.cls
/*
**Please run this batch always with frequency as 1.
*/
global class Batch_AutoTourPlanCreation implements Database.Batchable <SObject>,Database.Stateful {
    public Boolean beatFreqChangeFlag;
    public Set<Id> whereCondition = new Set<Id>();
    public String batchMonthStr = '';
    public Map<Date,AP_Tour_Plan__c> dateTourPlanMap = new Map<Date,AP_Tour_Plan__c>();
    //Constructor to get dynamic query parameters
    public Batch_AutoTourPlanCreation(Set<Id> targetIdSet,String monthStr){
        whereCondition = targetIdSet;
        batchMonthStr = monthStr;
    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        DateTime dt = Datetime.now().AddMonths(1);
        String nextMonth = dt.format('MMMM');
        String year = String.valueOf(dt.Year());
        beatFreqChangeFlag = false;
        String query = '';
        if(whereCondition == null)
            query = 'SELECT Id,Name,Start_Date__c,End_Date__c,OwnerId,Approval_Status__c FROM Target__c WHERE Approval_Status__c IN (\'Not Submitted\',\'Pending\') AND Month__c = \''+nextMonth+' - '+year+'\'';
        else
            query = 'SELECT Id,Name,Start_Date__c,End_Date__c,OwnerId,Approval_Status__c FROM Target__c WHERE ID IN:whereCondition';
        if(batchMonthStr != '')
            query += ' AND State__c=\''+batchMonthStr+'\'';
        System.debug(query);
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext bc,List<Target__c> targetList) {
        if(targetList[0].Approval_Status__c != null && (targetList[0].Approval_Status__c == 'Pending' || targetList[0].Approval_Status__c == 'Not Submitted')){
            List<AP_Tour_Plan__c> tourPlanList = new List<AP_Tour_Plan__c>(); 
            List<Beat_Master__c> beatMasterLst = new List<Beat_Master__c>();
            dateTourPlanMap = new Map<Date,AP_Tour_Plan__c>();
            Map<String,Integer> dayMap = new Map<String,Integer>();
            Map<Integer,Integer> dayWeekMap = new Map<Integer,Integer>();
            List<String> beatFreqList;
            Integer dayinMonth = Date.daysInMonth(targetList[0].Start_Date__c.year(),targetList[0].Start_Date__c.month());
            beatMasterLst = [SELECT Id,Beat_Frequency__c FROM Beat_Master__c WHERE Beat_Frequency__c != null AND OwnerId = :targetList[0].OwnerId];
            for(Integer i = 1; i <= 7; i++){
                Date tempDate = Date.newInstance(targetList[0].Start_Date__c.year(),targetList[0].Start_Date__c.month(),i);
                Datetime tempDateTime = (DateTime)tempDate;
                dayMap.put(tempDateTime.format('EEEE'),i);
                dayWeekMap.put(i,getWeekOfMonth(tempDate));
            }
            for(Beat_Master__c beatMasterObj : beatMasterLst){
                beatFreqList = new List<String>();
                beatFreqList.addAll(beatMasterObj.Beat_Frequency__c.split(';'));
                for(String beatFreqObj : beatFreqList){
                    tourPlanList.add(getTourPlan(targetList[0],beatMasterObj,beatFreqObj,dayMap));
                }
            }
            //planning for 5th week
            for(Integer dayNumber: dayWeekMap.keySet()){
                if(dayWeekMap.get(dayNumber) == 1 && dayNumber + 28 <= dayinMonth){
                    if(dateTourPlanMap.get(Date.newInstance(targetList[0].Start_Date__c.year(),targetList[0].Start_Date__c.month(),dayNumber+14)) != null){
                        AP_Tour_Plan__c tourPlanObj = dateTourPlanMap.get(Date.newInstance(targetList[0].Start_Date__c.year(),targetList[0].Start_Date__c.month(),dayNumber+14)).clone();
                        tourPlanObj.Date__c = tourPlanObj.Date__c.addDays(14);
                        Datetime tempDateTime = (DateTime)tourPlanObj.Date__c;
                        tourPlanObj.Beat_Frequency__c = tempDateTime.format('EEEE') +' Week5';
                        tourPlanList.add(tourPlanObj);
                    }
                }
            }
            if(tourPlanList.size() > 0){
                INSERT tourPlanList;
                if(!beatFreqChangeFlag){
                    if(targetList[0].Approval_Status__c != 'Pending'){
                        targetList[0].Approval_Status__c = 'Pending';
                        UPDATE targetList[0];   
                    }
                    approvalSubmission(targetList[0].Id);
                }
            }
        }
    }
    global void finish(Database.BatchableContext bc){}
    //Prepare tor plan object for insertion
    public AP_Tour_Plan__c getTourPlan(Target__c targetObj,Beat_Master__c beatMasterObj,String beatFreqObj,Map<String,Integer> dayMap){
        AP_Tour_Plan__c tourPlanObj =  new AP_Tour_Plan__c();                                 
        tourPlanObj.Target__c = targetObj.Id;
        tourPlanObj.OwnerId = targetObj.OwnerId;
        tourPlanObj.Beat__c = beatMasterObj.Id;
        tourPlanObj.Beat_Frequency__c = beatFreqObj;
        tourPlanObj.Date__c = getBeatDate(beatFreqObj,targetObj.Start_Date__c,dayMap);
        dateTourPlanMap.put(tourPlanObj.Date__c,tourPlanObj);
        RETURN tourPlanObj;
    }
    public Date getBeatDate(String beatFreqObj,Date startDate,Map<String,Integer> dayMap){
        String freqDay = beatFreqObj.split(' ')[0];
        Date beatDate_1 = Date.newInstance(startDate.year(),startDate.month(),dayMap.get(freqDay));
        Date beatDate_2 = beatDate_1.addDays(7*(Integer.valueOf(beatFreqObj.substring(beatFreqObj.length()-1))-1));
        RETURN beatDate_2;
    }
    //SUbmission for approval
    public void approvalSubmission(Id targetId) {
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Please approve my Tour Plan.');
        req1.setObjectId(targetId);
        try {
            Approval.ProcessResult result = Approval.process(req1);
        }catch(Exception e) {
            system.debug(e.getMessage());
        }
    }
    //get week count from date
    public Integer getWeekOfMonth( Date todaysDate){
        Date currentDate = todaysDate;
        Integer weekCount = 0;
        Integer startWeekResidue = 0;
        Integer endWeekResidue = 0;
        Date dt = currentDate.toStartOfMonth().addDays(-1);
        Date dtFirstWeekend = dt.toStartOfWeek().addDays(6);
        startWeekResidue = dt.daysBetween(dtFirstWeekend);
        Date dtLastWeekend = currentDate.toStartOfWeek().addDays(-1);
        endWeekResidue = dtLastWeekend.daysBetween(currentDate);
        weekCount = (currentDate.day() - (startWeekResidue + endWeekResidue))/7;
        weekCount += (startWeekResidue > 0 ? 1:0)+(endWeekResidue > 0 ? 1:0);
        RETURN weekCount;
    }
}